### ISSUE TITLE
Is that possible to filter some items by parsing a function which will return a promise.

### ISSUE THREAD

**Issue by ljxok2001** [dfahlander/Dexie.js#1000]
Hey, guys. 

Is that possible to filter some items with a filter function which will return a promise. in case resolve(true), the  item matches the rule of filter.

Here is my raw code:

```javascript
let list = [];
index.openCursor(range).onsuccess = async (e) => {
    let cursor = e.target.result;
    if (cursor) {
        let result = condition(cursor.value);
        if (result instanceof Promise) {
            result = await result;
        }
        if (result) {
            list.push(cursor.value);
        }
        cursor.continue();
    }
}
```

I hope to do things like below:

```javascript
db.friends.where({age: 30}).filter(async function(item) {
    let result =  condition(item);
    if (result instanceof Promise) {
        result = await result;
   }
   return result;
})
```

Hope for your reply. Thanks very much.

**Comment by dfahlander** [comment]
It's not possible to do exactly that with Dexie's filter(). However, you would get better performance by using toArray() and filter the result afterwards. When you are using Dexie's filter() the framework will have to use IDBCursor, which is quite slow as it requires an async event callback for every item. If you use toArray() and filter it manually, the framework will be able to use IDBIndex.getAll() which will only require a single callback and is way faster.

So I would suggest something like the following instead:

```js
const friends = await db.friends.where({age: 30}).toArray();
const conditionExecution = await Promise.all(friends => friends.map(async item => ({
  item,
  included: await condition(item),
})));
const filteredFriends = conditionExecution.filter(({item, included}) => included).map(({item}) => item);
```

**Comment by ljxok2001** [comment]
Hi David, thanks a lot, I got it, I'll try it as you show me. haha.
