### ISSUE TITLE
The __dbnames can`t be created when i use pwa in my project

### ISSUE THREAD

**Issue by MatrixAge** [dfahlander/Dexie.js#1001]
here is the website: [online case](https://matrixage.github.io/testool/)

the pwa tech i use:
- offline-plugin (webpack-plugin)

how i get __dbnames:
```js
export const Service_getAllGroups = async (): Promise<Array<string>> => {
      if (await Dexie.exists('__dbnames')) {
		const db = new Dexie('__dbnames')

		await db.open()
		await db.table('dbnames').toArray()

		return await Dexie.getDatabaseNames()
	} else {
		return []
	}
}
```

when the code has deployed to the gh-pages,the __debnames can`t be established,then the code will not run as well.

I`m a new user of Dexie,i try to find out the reason of why this case happened,but i get nothing about that.

**Comment by dfahlander** [comment]
Let me kindly ask you to put the question [at stackoverflow](http://stackoverflow.com/questions/ask?tags=dexie) instead unless you believe this is a bug.

**Comment by MatrixAge** [comment]
i got by created a new db that loging dbnames，and it works

**Comment by dfahlander** [comment]
Thanks. Closing this issue then.
