### ISSUE TITLE
Tables indexes not updating when versions are declared in reverse order

### ISSUE THREAD

**Issue by Thomas-Defossez** [dfahlander/Dexie.js#1002]
Hello, first of all I wanted to say thank you for dexie.js which is a very useful and practical tool ! 

I'm using dexie.js 2.0.4 in my app, and for performance reasons I want to update the indexes of one of my tables. 

If I run the following code :

```
const db: dexie = new dexie('mydb');
db.version(1).stores({
  friends: '++id,name,age',
  pets: '++id,name,kind',
});
```

The table is created with the right indexes, and the version is 10.

Now if I run the following code and refresh my browser :

```
const db: dexie = new dexie('mydb');
db.version(2).stores({
  friends: '++id,name,city',
  pets: '++id,name,kind',
});
db.version(1).stores({
  friends: '++id,name,age',
  pets: '++id,name,kind',
});
```

The version updates to 20, however the index of **friends** have not been updated and are still name and age.

If I go back to version 10, and then run the following code :
```
const db: dexie = new dexie('mydb');
db.version(1).stores({
  friends: '++id,name,age',
  pets: '++id,name,kind',
});
db.version(2).stores({
  friends: '++id,name,city',
  pets: '++id,name,kind',
});
```

The indexes are correctly updated as well as the version number.

**Comment by dfahlander** [comment]
I think this is a duplicate of #919. It has been solved in 3.x.

**Comment by Thomas-Defossez** [comment]
Thanks for your reply. This indeed looks like a duplicate of #919. I'll wait for the release of 3.x, in the meantime I can declare the versions in ascending order to update my indexes.
