### ISSUE TITLE
Querying a non-existent index returns generic errors messages

### ISSUE THREAD

**Issue by tp** [dfahlander/Dexie.js#101]
Querying an index which is defined in the current version but does not exist in the browser (like I see in #100) returns this generic error:

```
DOMException [NotFoundError: "The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened."
code: 8
nsresult: 0x80660003
location: http://localhost:1236/assets/vendor.js:60587]
```

On the other hand, using a non-defined index one gets this more detailed error:

```
Error: KeyPath xxx on object store cityIndex is not indexed
```

**Comment by dfahlander** [comment]
This happens when the actual version is not in sync with the version schema specified in the call to db.version().stores(). Specifically, that can happen after opening the database with duplicate index names as in Issue #100.
