### ISSUE TITLE
Automatic upgrade

### ISSUE THREAD

**Issue by mihaiav** [dfahlander/Dexie.js#1011]
I'm not sure if I read the docs correctly but it looks like dixie could manage the schema updates/upgrades along with the indexes automatically based on the queries received. Why it doesn't do that by default? Is there a plugin that does just that?  

 
**Change Tracking**

_With Dexie it’s possible to control and monitor each database change. No matter which method is being used for data manipulation, Dexie may tell whether a CREATE, UPDATE or DELETE is about to happen and offer the hook callbacks to manipulate the change if requested. It is also possible to hook into READ operations; to provide a proxy function that will be called whenever an object has been read from database and is about to be delivered to caller._

https://dexie.org/docs/Tutorial/Design#database-versioning

**Comment by dfahlander** [comment]
Dexie does not find out the indexes needed. They have to be explicitely declared as described in the link you provided. However, it will automatically figure out which indexes to add/remove between versions but it is still based on the indexes in the last version declared, not from the queries made to it. The text you citate is from the next chapter about [Change Tracking](https://dexie.org/docs/Tutorial/Design#change-tracking) and is not about indexes or upgrades but about how to inject code based on data manipulation.

I hope this clarifies it a bit.
