### ISSUE TITLE
Missing Typescript shims in dexie-export-import package

### ISSUE THREAD

**Issue by lonk** [dfahlander/Dexie.js#1012]
Hi there !

I'm using the exportDB method in my project, and it works like a charm !
The only issue I have is that the shims are missing for the addon: they are there in the Dexie package, but not in the addon.
Is it planned to add it someday ?

Here's an attached image of how both directories look
![Capture d’écran de 2020-04-06 20-47-11](https://user-images.githubusercontent.com/2729398/78594141-0aa84600-7848-11ea-8085-1117a7ac08f1.png)

Thank you for your work !

**Comment by dfahlander** [comment]
Thanks for reporting this. It seems the d.ts files was not included with the last release. I've now re-released a version 1.0.0-rc.2 after rebuilding and rerunning npm publish on the addon.

**Comment by lonk** [comment]
I'm checking it tomorrow ! Thanks you !

**Comment by lonk** [comment]
The file is now there, thanks for your reactivity
