### ISSUE TITLE
Call for feedback on 3.0.0-rc releases!

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#1016]
I am about to release version 3.0 as a stable version but would like some feedback on the release candidate before I do.

```
Question!

Are you a Dexie user that has installed Dexie 3.0.0-rc.x?

Please give a thumbs up or a comment on your experience with upgrading from 2.x!
```

**If you've upgraded to 3.0 already and find it working equally well or better, please do a thumbs up on this issue!**

**If you've tried to upgrade but had to downgrade again for some reason, please leave a note here.**

**Comment by wuxiaobin1995** [comment]
hi, how i can use the latest version(v3.0.0) in npm? just like this: `npm install dexie@3.0.0 -S ` ?

**Comment by oxycoder** [comment]
Look like v3 is missing typescript define for syncable and observable plugin.

**Comment by adamJLev** [comment]
Great work man! 
Seems to be working well so far for my project 👍 
(`3.0.0-rc.7`) 
You can see it all in action on https://www.nextup.co/

**Comment by mierak** [comment]
I just upgraded from v2 to v3 rc7 and had to do zero changes to my code with fairly extensive usage of Dexie! 

Using typescript and had zero issues with typings aswel.

**Comment by dpogue** [comment]
Been using the 3.0.0-rc versions for well over a year now, aside from the bug with rc6 with unique primary keys, it's been great!

**Comment by dfahlander** [comment]
Thanks! The addons are released separately, so I will go ahead and release dexie 3.0.0 now, and look into the typings of the addons separately.

**Comment by Trontor** [comment]
Hi @dfahlander, have you had any time to look into the dexie-observable typings?

**Comment by dfahlander** [comment]
@Trontor I'm working on dexie-observable and dexie-syncable typings in #1048 for dexie@3. Closing this issue now to be followed up there.
