### ISSUE TITLE
Select where key not present

### ISSUE THREAD

**Issue by einicher** [dfahlander/Dexie.js#1019]
Hello,

I added a parent key later in the project and need to select all objects now, that do not have a parent key or where it is zero. How do i do that? This gives no results:

```
db.pages.where('parent').anyOf([0, undefined, null])
```

**Comment by dfahlander** [comment]
IndexedDB indexes will not handle undefined or null. So if you have objects where parent is null or undefined, the only way to find them would be to enumerate all objects and filter them out manually.

The only cure in your case is making sure that parent is always set to an indexable value, such as the number 0, an empty string, -Infinity, Infinity, an empty array etc (see [Indexable Types](https://dexie.org/docs/Indexable-Type)).

**Comment by einicher** [comment]
Ok, thank you.
