### ISSUE TITLE
Passing an empty array to anyOf throws exception

### ISSUE THREAD

**Issue by iconexperience** [dfahlander/Dexie.js#102]
table.where('id').anyOf([])

throws

    TypeError: keyRangeGenerator is not a function
    at WriteableCollection.Collection (https://rawgit.com/dfahlander/Dexie.js/master/dist/latest/Dexie.js:1556:28)

https://jsfiddle.net/fadsod17/

**Comment by dfahlander** [comment]
Thanks a lot for the fiddle! Will add it as a unit test and fix it hopefully this weekend.

**Comment by dfahlander** [comment]
Added a unit test to reproduce issue #102. However, the test passes
src/Dexie.js but not the minified version of latest stable. Need to
investigate whether this is a minification bug or something that has
been solved in another issue.

**Comment by dfahlander** [comment]
Good news, the issue only exists in 1.0.3 but was fixed by Anders Rune Jenssen in the following commit: d265be6a0dd5e4222ff8d51131828e1bd3bedbb2.
