### ISSUE TITLE
dexie-export-import DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by AlinC123** [dfahlander/Dexie.js#1022]
In `webpack.config.js` I have [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) :

```javascript
module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        use: ["source-map-loader"],
        enforce: "pre"
      }
    ]
  }
};
```

package.json:
```json
"scripts": {
    "dev": "webpack-dev-server"
  }
```

I start the server `npm run dev`.

In console log I have only this error from all the packages I'm using:

`
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/dexie-export-import/dist/dexie-export-import.mjs.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
`

**Comment by dfahlander** [comment]
Seems to be a webpack config issue. At least I have the map file at `node_modules/dexie-export-import/dist/dexie-export-import.mjs.map` after doing `npm install dexie-export-import`.

**Comment by AlinC123** [comment]
Yes, looks like the problem was with my webpack config. I had commented out `// devtool: 'eval-cheap-module-source-map'` for a while, then I when I needed to debug and enabled it back the error disapeared.
