### ISSUE TITLE
Can I use it together with the native API at the same time?

### ISSUE THREAD

**Issue by wuxiaobin1995** [dfahlander/Dexie.js#1024]
For example, I use Dexie.js to create a database；and I use the native API to add something.
thanks!

**Comment by dfahlander** [comment]
Yes, you can do that. Either by retrieving the instance of IDBDatabase from the [backendDB()](https://dexie.org/docs/Dexie/Dexie.backendDB()) call, or by opening another connection natively. Just keep in mind that dexie [multiplies the version number by 10](https://github.com/dfahlander/Dexie.js/issues/59).  See also [this page](https://dexie.org/docs/Tutorial/Migrating-existing-DB-to-Dexie) how to switch from/to dexie.

**Comment by jeffRTC** [comment]
@dfahlander 

Sorry for bumping this issue. Indeed, a neat wrapper, but I need to override this behavior since I don't target IE browser. 

Can you point me the code line where exactly you multiply by 10 so that I can omit it in my personal fork?

**Comment by dfahlander** [comment]
Search for verno and .version . Somewhere it's doing a divide by 10 and another place a multiply by 10 (with Math.round to preserve integer type)
