### ISSUE TITLE
Duplicate database copies in Safari 

### ISSUE THREAD

**Issue by stephent** [dfahlander/Dexie.js#1027]
This may well be a Safari issue, rather than something in Dexie, but I thought I'd post in case anyone has seen this and knows of any workarounds.

The same issue is reported for idb: https://github.com/jakearchibald/idb/issues/72

After loading my app, I'm seeing three duplicate copies of the database:

![Screenshot_2020-04-23_at_12_09_32](https://user-images.githubusercontent.com/898090/80134045-628ac080-855b-11ea-9d1f-b63a76ea14ae.png)

The code to define the version and open the db is as follows:

```
import Dexie from 'dexie';
import log from 'loglevel';
// Create your instance
export const locationsDB = new Dexie("locations"); 

// Define locations schema
locationsDB.version(1).stores({
    saved: "&uuid, useruuid, title, requiresSync, favourite, folder"
});

locationsDB.version(2).stores({
  saved: "&uuid, useruuid, title, requiresSync, favourite, folder",
  deleted: "&uuid, useruuid, deletedAt"
});

// Open the database
if (!locationsDB.isOpen()) {
  locationsDB.open().catch(function (e) {
    log.error("Dexie open failed: " + e);
 });
};
```

Nothing apparently controversial there and it all works as expected in Chrome, Firefox etc. with no duplicate DB copies.

Environment details: Safari 13.1, macOS 10.14.6
Libraries: React 16.13.1, Dexie 2.0.4

Appreciate any insights!

**Comment by dfahlander** [comment]
I haven't seen this issue before but seems to be a Safari related issue. Maybe just an issue with Safari's IDB browser, as jakearchibald sais in the other issue, and not nescessarily an IDB issue. Need to do a full repro of it to make sure it has any data-corruption / data-loss effect.

**Comment by sachinrekhi** [comment]
I'm seeing the exact same duplicate IndexedDB issue with Safari 13.1.1 on Mac 10.15.5. My guess though is that it's an issue with Safari's IDB browser, because when I make a change to a key, that change is reflected in both versions of the databases shown in the browser, suggesting they are actually the same underlying data, not in-fact two separate databases.

**Comment by stephent** [comment]
Agreed - almost certainly not Dexie related, and probably not IDB's problem either. I continue to see the triplicate copies in Safari, but no data issues in the actual store that I can detect. I'll close this.

**Comment by SANTOSHKVNSP** [comment]
@sachinrekhi @stephent I am using an Angular app. What I see is that whenever in safari I navigate to a route that initializes google maps, duplicate copy of the database is getting created.
