### ISSUE TITLE
TransactionInactiveError outside of a transaction

### ISSUE THREAD

**Issue by andrewgordstewart** [dfahlander/Dexie.js#1029]
I'm hitting things like the following when calling `someTable.get(key)` without explicitly creating a transaction.

```
dexie.mjs:1261 Unhandled rejection: TransactionInactiveError: Transaction has already completed or failed
    at Transaction$$1.../../node_modules/dexie/dist/dexie.mjs.Transaction._promise (http://localhost:3055/bundle.js:14543:30)
    at Table$$1.../../node_modules/dexie/dist/dexie.mjs.Table._trans (http://localhost:3055/bundle.js:13248:27)
    at Table$$1.../../node_modules/dexie/dist/dexie.mjs.Table.get (http://localhost:3055/bundle.js:13261:21)
    at Backend.<anonymous> (http://localhost:3055/bundle.js:261586:57)
    at Generator.next (<anonymous>)
    at http://localhost:3055/bundle.js:261372:71
    at executePromiseTask (http://localhost:3055/bundle.js:12767:9)
    at new DexiePromise (http://localhost:3055/bundle.js:12585:5)
From previous: 
    at DexiePromise.then (http://localhost:3055/bundle.js:12595:22)
    at Table$$1.../../node_modules/dexie/dist/dexie.mjs.Table.get (http://localhost:3055/bundle.js:13264:12)
```

By debugging, I've found that `PSD.trans` is defined when `someTable._trans` is executed [here](https://github.com/dfahlander/Dexie.js/blob/8028732f0d86dcbde319bb07d21ff4da20ecf841/src/classes/table/table.ts#L40), even though I do appear to be calling `someTable.get` from within a transaction zone. This transaction was created from a parallel, explicit call to `myDexieDB.transaction(...)`.

It seems that something like this is happening:
1. the explicit transaction (tx1) starts
2. `someTable.get(key)` is called
3. `someTable._trans` creates a sub-transaction tx2 of tx1
4. The explicit transaction tx1 commits
5. tx2 tries to commit, sees that its parent is committed, and throws `TransactionInactiveError`.

I'm wondering if I am accidentally keeping the PSD scope open after tx1 commits somehow. If that's the case, do you have any advice on how to debug this? I've added a listener for the `complete` event for tx1, and the listener fires about 200ms _before_ `someTable.get` is called.

I'm able to reproduce it pretty reliably in a local environment, but I was unable to create a minimal example reproducing it.

**Comment by andrewgordstewart** [comment]
(This is with `"dexie": "^3.0.0-rc.7"`)

**Comment by dfahlander** [comment]
Hi! All operations in dexie execute within the transaction of the calling function, if any.  If you for example write your own generic events/hooks, and call them from within a transaction, the implementation of the events will also run in the same transaction. This can be avoided using [Dexie.ignoreTransaction()](https://dexie.org/docs/Dexie/Dexie.ignoreTransaction()). Could this be the case? If not, please share some code that preferably reproduces this, or else paste parts of your existing code - the functions involved in executing transaction and the callers of the someTable.get(key).

**Comment by andrewgordstewart** [comment]
Thanks for the quick response!

> Hi! All operations in dexie execute within the transaction of the calling function, if any. If you for example write your own generic events/hooks, and call them from within a transaction, the implementation of the events will also run in the same transaction. This can be avoided using [Dexie.ignoreTransaction()](https://dexie.org/docs/Dexie/Dexie.ignoreTransaction()). Could this be the case? 

I don't think we're directly doing anything like this, but it's possible that one of the libraries we're using is (I'm thinking either rxjs or xstate could be the culprit). But it still seems suspicious that the offending transaction seemed to complete.


> If not, please share some code that preferably reproduces this, or else paste parts of your existing code - the functions involved in executing transaction and the callers of the someTable.get(key).

I've created a [branch](https://github.com/statechannels/monorepo/tree/ags/nested-transactions-issue) in our repo where I'm able to reproduce it. It's a bit much, but I'll try to point out what's happening.

For context, in our integration test we have two chromium browsers (controlled by puppeteer) running a webtorrent client. Each browser is running a "state channel wallet" inside an iframe. Within that iframe, I observed this sequence of events in "browser 1" from [this log file](https://21389-209829093-gh.circle-artifacts.com/0/tmp/seed-download.pino.log)

1. [This function](https://github.com/statechannels/monorepo/blob/ags/nested-transactions-issue/packages/xstate-wallet/src/store/store.ts#L383-L406) is called, which creates an explicit transaction [here](https://github.com/statechannels/monorepo/blob/ags/nested-transactions-issue/packages/xstate-wallet/src/store/dexie-backend.ts#L190-L196). 

```
[1588034807382] INFO  (xstate-wallet): Starting transaction 13
    context: "transactions"
    stores: [
      "channels",
      "privateKeys"
    ]
    logMessage: "SignAndAdd"
    browserId: 1
```

2. Then, [this function](https://github.com/statechannels/monorepo/blob/ags/nested-transactions-issue/packages/xstate-wallet/src/store/store.ts#L511-L518) is called. This should not be in the same PSD scope as the "transaction 13" above, since `reserveFunds` is called in [only one place](https://github.com/statechannels/monorepo/blob/ags/nested-transactions-issue/packages/xstate-wallet/src/workflows/create-and-fund.ts#L101-L114), and seems to be independent of the `signAndAddState` function, which is called [here](https://github.com/statechannels/monorepo/blob/ags/nested-transactions-issue/packages/xstate-wallet/src/workflows/support-state.ts#L54).
```
[1588034807404] INFO  (xstate-wallet):
    context: "transactions"
    currentTransaction: {
      "storeNames": [
        "channels",
        "privateKeys"
      ]
    }
    browserId: 1
```

What's going on here, is these promises are "invoked services" of [this state machine](https://xstate.js.org/viz/?gist=e973ea444fb1e26145869ec6fe567eb7). The machine  transitions from `'preFundSetup'` to `virtual` when the `signAndAddState` promise resolves. At that point, (2) happens, and then the `reserveFunds` promise is "invoked".

If I make `reserveFunds` run as a top-level transaction (with mode`rw!'`) then I run into a different, similar issue (the scenario that I described in the original description, where dexie throws a `TransactionInactiveError`).

I'm wondering if the xstate machinery is messing with the Dexie promises or PSD. I'd like to reproduce it in a simpler example that's easier to grok without understanding our whole codebase 😛

**Comment by andrewgordstewart** [comment]
I think I've figured out what's going on -- will post a reproduction soon.

**Comment by andrewgordstewart** [comment]
I think it boils down to something like this:
```
require('fake-indexeddb/auto');
const Dexie = require('dexie');

const fooEmitter = new EventEmitter()

const db = new Dexie('foo');
db.version(1).stores({
  foo: '',
  bar: ''
})

fooEmitter.on('NewFoo', foo => {
  console.log("New foo");
  addBar(foo).catch(error => {
    // SubTransactionError: Table bar not included in parent transaction.
    console.error(error);
  })
})

const addBar =  bar => db.transaction('rw', 'bar', () => {
  console.log("Adding bar " + bar)
  db.bar.set(bar, bar)
})

const addFoos = () => db.transaction('rw', 'foo', () => {
  [0,1,2].map(i => {
    console.log("Adding foo "+ i);
    db.foo.put(i, i);
    console.log("Added foo " + i);
    fooEmitter.emit('NewFoo', i);
  });
})

addFoos().then(() => console.log("Foos added"));
```

In my old mental model, the `addBar` callback does not happen in the "transaction scope" of the `addFoos` transaction.

This was obfuscated by xstate, since it registers internal callbacks to internal events which then get executed within the transaction scope. Making [this change](https://github.com/statechannels/monorepo/pull/1590/commits/1ff676453a2d39d1369676e000bee2ac15b495a4) completely fixed the dexie errors!

The [relevant dexie documentation](https://dexie.org/docs/Dexie/Dexie.transaction()) says:
>If you call another function, it will also be executing in the current transaction zone:

When I think about how event emitters work, it's perfectly clear that whatever callbacks are registered with `fooEmitter.on('NewFoo', cb)` get called when `fooEmitter.emit('NewFoo', i)` is called, so they do indeed happen within the `addFoos` transaction scope.

Given how common event emitters are, maybe it makes sense to add a warning to the [transaction scope](https://dexie.org/docs/Dexie/Dexie.transaction()#transaction-scope) documentation? I'm happy to make a PR.

**Comment by dfahlander** [comment]
Indeed this is something that needs to be brought up in the docs. I would be grateful for any help with clarifying this in the docs!
