### ISSUE TITLE
Timeframe on next npm release? Loader detection causing problems in 1.0.4.

### ISSUE THREAD

**Issue by axefrog** [dfahlander/Dexie.js#103]
The current distribution (1.0.4) fails after being bundled with jspm due to incorrect module loader detection. I've made a quick fix in my local copy of the package, but obviously that will get overwritten on any package reload. The loader detection actually appears to be fixed in trunk, but is not present in dist, so I suspect I'm just waiting on the next release. What's the timeframe on that?

**Comment by dfahlander** [comment]
Next release contains lots of important fixes and will be out within a week from now.

**Comment by axefrog** [comment]
Excellent news! I shall wait with bated breath.
