### ISSUE TITLE
AggregateError in src/helpers/promise.js

### ISSUE THREAD

**Issue by nicolashenry** [dfahlander/Dexie.js#1037]
It seems that a global error class named `AggregateError` is used in [src/helpers/promise.js file](https://github.com/dfahlander/Dexie.js/blob/master/src/helpers/promise.js#L332). My CI rules are reporting it as an error since it does not seems to be a native error and it does not seems to be declared in Dexie.

Why Dexie is needing this error class ?

Thanks! :)

**Comment by dfahlander** [comment]
It's part of the ecmascript [Promise.any() proposal](https://tc39.es/proposal-promise-any/#sec-aggregate-error-constructor) and is in stage 3. We only support it to be future compliant with Promise. Is it a linting rule that fails in your CI or something else? What you think should be done to take away the error? Would checking if typeof AggregateError === "undefined" before throwing do it?

**Comment by nicolashenry** [comment]
It is a kind of manual linting rule that operate on our final bundle to check that all used global references are actually existing. Taking it from global object would be enough to fix it, I created a PR : https://github.com/dfahlander/Dexie.js/pull/1038

**Comment by nicolashenry** [comment]
I changed my mind on this, I will ignore AggregateError references and maybe add a shim for it on my project. Sorry for the noise.
