### ISSUE TITLE
Table named 'schema' not working in Dexie 3.

### ISSUE THREAD

**Issue by jefbarn** [dfahlander/Dexie.js#1039]
Hello,
Trying to update my application to Dexie 3 and noticed that it doesn't seem to support a table named 'schema'. Easy workaround was to rename the table, but might want investigate or list it in the breaking changes.
The error was along the lines of 
"cannot set property schema of [object object] which has only a getter"

**Comment by dfahlander** [comment]
Ok. Does it help if you access it through ’db.table('schema')’ instead of just ’db.schema’?

**Comment by jefbarn** [comment]
A little more investigation this morning...

The full stack trace is:
ERROR Error: Uncaught (in promise): TypeError: Cannot set property schema of [object Object] which has only a getter
TypeError: Cannot set property schema of [object Object] which has only a getter
    at new Transaction$$1 (dexie.mjs:2723)
    at LocalDbService.Dexie._createTransaction (dexie.mjs:4053)
    at tempTransaction (dexie.mjs:1278)
    at Table$$1.push../node_modules/dexie/dist/dexie.mjs.Table._trans (dexie.mjs:1343)
    at Table$$1.push../node_modules/dexie/dist/dexie.mjs.Table.put (dexie.mjs:1504)

This is after a table.put() operation in my code.
I get a reference to the table via the db.table('schema') method.
So my code looks something like this:
let table = db.table('schema')
...time passes...
table.put({ data })
error

**Comment by dfahlander** [comment]
Ok, thanks! Looks like a bug. I'll see if it can be easily fixed.
