### ISSUE TITLE
Bower is not picking up the two digit version tags, v1.1 is not available.

### ISSUE THREAD

**Issue by glade-at-gigwell** [dfahlander/Dexie.js#104]
It appears bower is not picking up the two digit tags that have been published, neither v1.0 and v1.1 are available there.  Can you release a new three digit version so bower can pick it up?  

Also, I think its a best practice to version the bower.json file when publishing.  Its quite confusing to review bower_components/ and inspect a bower.json and find it missing the version. 

Thanks for the great work.

**Comment by dfahlander** [comment]
Thanks! I'll fix asap.

**Comment by dfahlander** [comment]
Fixed

**Comment by glade-at-gigwell** [comment]
Thanks much!
