### ISSUE TITLE
Question: Sort Order of Virtual Index 

### ISSUE THREAD

**Issue by samratarmas** [dfahlander/Dexie.js#1045]
Hello David, super excited about the Dexie 3.0 improvements and features! I have a very quick question about virtual indexes. Bellow are two queries:

**Example setup:**

`const db = new Dexie('dbname');`
`db.version(1).stores({
    people: 'id, [firstName+lastName]' 
});`

**Query One:**  uses the compound index to filter by "firstname" and sort by "lastname"

`db.people.where('[firstName+lastName]').between(["foo", Dexie.minKey], ["foo", Dexie.maxKey]).toArray()`

**Query Two:**  uses a virtual index on the compound key to filter by "firstname"

`db.people.where('firstName').equals("foo").toArray()`

Now, will the result of Query Two **always** be sorted by the the other half of the compound key? (ie. "lastname"). If that is not the behavihor then is using Query One the best way to approach the problem of simple filtering and sorting without loading the entire collection into memory?

Regards

**Comment by dfahlander** [comment]
Hi! I'm happy to hear that. Either Query One or Query Two will sort by lastName. So, yes, there is a difference in sort order between real and virtual index, as a real "plain" index will sort by primary key as the secondary sort order, while if the virtual index is used, the secondary property will be used as the secondary sort order. Now, that is an effect that was not the main purpose of the feature, but should probably be highlighted in docs. 

However, the VirtualIndex middleware will prefer "plain" indexes before compound ones, so the sort order would be different if a plain "firstName" index exists - in that case, you would have to use Query One explicitely to select the compound index.

[JSitor sample with only compound index](https://jsitor.com/VT5fF4FTb)

[JSitor sample if plain index is added](https://jsitor.com/d9kfgKES6)

As you can see, if a plain index exists, it will be chosen before the compound index unless using Query One.

**Comment by samratarmas** [comment]
> Now, that is an effect that was not the main purpose of the feature, but should probably be highlighted in docs.

It is indeed a very desirable side effect

Thanks a lot for your detailed response!
