### ISSUE TITLE
Dexie Syncable with Dexie 3.0.0

### ISSUE THREAD

**Issue by oliverhowden** [dfahlander/Dexie.js#1048]
Am i correct to assume the current version of Dexie syncable will not work with Dexie 3.0.0? 
I get a lot of namespace errors, and import errors such as
`cannot augment module 'Dexie' with value exports because it resolves to a non-module entity.`

**Comment by dfahlander** [comment]
Hi! They are runtime compatible but there might be typing issues.

**Comment by oliverhowden** [comment]
Okay. Thank you very much

**Comment by oliverhowden** [comment]
Hello, Sorry for re-opening this one. Do you have any suggestions for fixing the typing issues for this? Although the package is working, we're unable to run any build pipelines due to the typing issues.

Thank you

**Comment by dfahlander** [comment]
Any contribution of the typings are welcome. If someone could provide me with a PR with the changes needed in [Dexie.Syncable.d.ts](https://github.com/dfahlander/Dexie.js/blob/master/addons/Dexie.Syncable/src/Dexie.Syncable.d.ts) and [api.d.ts](https://github.com/dfahlander/Dexie.js/blob/master/addons/Dexie.Syncable/api.d.ts), I can release a new version of the addon.

**Comment by dfahlander** [comment]
I'm working on this now

**Comment by oliverhowden** [comment]
Awesome. Thank you very much

**Comment by dfahlander** [comment]
I've published new versions of dexie-observable and dexie-syncable on npm that should be type-wise compatible with Dexie 3.0. Any feedback on these would be much apprechiated:

```
npm i dexie-observable@next dexie-syncable@next
```

**Comment by dfahlander** [comment]
Anyone who have tested the addons?

```
npm i dexie-observable@next dexie-syncable@next
```
