### ISSUE TITLE
Distinguishing between create/update hooks in DBCore/Dexie 3.0

### ISSUE THREAD

**Issue by oliverhowden** [dfahlander/Dexie.js#1049]
We're in the process of migrating our hooks from the old API to the DBCore method. Currently running into issues in matching our hooks with the previous process of `table.hook('creating')` vs `table.hook('updating')`. 
I understand there's a `type` parameter, though is there a better way to correctly identify an update vs a creation event? As `put` can be used for both... 

On a side note, very impressed with 3.0 so far. Thanks a lot

**Comment by dfahlander** [comment]
Unfortunately, DBCore maps more to the native IndexedDB interface and does not detect whether a put operation will result in an add or update. The solution is to resolve the effective keys from the put operation (you can find code that does this in dexie source, hooks-middleware.ts) and calls the lower layer with a getMany request for those keys. After that you can know which ones will result in creation or an update.

**Comment by dfahlander** [comment]
Explaining hooks-middleware: Look in the inner function addPutOrDelete() where it:
1. calls getEffectiveKeys() (which is a tiny function you can copy)
2. calls getExistingValues() (also a tiny function that calls getMany())
3. Compares the existing values with the requests that are going to be made, to find out where updates or creates is going to happen.

**Comment by dfahlander** [comment]
I also want to make clear that the hook API:s are not being deprecated, so if you are happy with them, you do not have to migrate. I might move hooks-middleware.ts out from the main module at some point into an addon (version 4 maybe), but no plans to stop maintaining it.

**Comment by oliverhowden** [comment]
Awesome. Thanks for that. 
We're in dire need of async hooks, so moving to DBCore is a welcomed option. Just hitting a few pain points. It does an nice addition in a future update to replicate this behaviour, or at least provide a sample solution to obtain the same results as the hook API. 
Thanks a lot for the help, I may be back with a few more questions. 
Cheers

**Comment by oliverhowden** [comment]
Currently having a few issues around using hooks and Dexie syncable. The error that is occurring is:
`Unhandled rejection: TransactionInactiveError: Transaction has already completed or failed`

Basically, if we use syncable to return our server results, and a fairly vanilla sync protocol implementation from the examples,
```
db.use({
			stack: 'dbcore', // The only stack supported so far.
			name: 'myMiddleware', // Optional name of your middleware
			create(downlevelDatabase) {
				// Return your own implementation of DBCore:
				return {
					// Copy default implementation.
					...downlevelDatabase,
					// Override table method
					table(tableName) {
						// Call default table method
						const downlevelTable = downlevelDatabase.table(tableName);
						// Derive your own table from it:
						return {
							// Copy default table implementation:
							...downlevelTable,
							// Override the mutate method:
							mutate: async req => {
								const myRequest = { ...req }
								// call downlevel mutate:
								return downlevelTable.mutate(myRequest).then(async res => {                
										//Check to ensure its our correct table here before running async hooks
										await new Dexie.Promise(resolve =>
											setTimeout(resolve, 1000)
										);
									// Do things after mutate
									const myResponse = { ...res };
									// Then return your response:
									return myResponse;
								});
							},
						};
					},
				};
			},
		});
```

Dexie waits to return the promise, though it appears the transaction is finalised before before all are complete - as operations continue to be applied from the data being synced before the transaction is complete.

My understanding of the issue is that syncable is not waiting for all dbCore operations/hooks to fire before resolving the transaction.

Is there anything obvious that I'm doing wrong that would cause this to happen in Dexie 3.0?

Thank you very much!

**Comment by dfahlander** [comment]
The following part of your code:

```ts
await new Dexie.Promise(resolve =>
  setTimeout(resolve, 1000)
);
```
...will make the IDB transaction commit. This is about how IndexedDB transaction works, as they commit when there is no operation on the transaction.
