### ISSUE TITLE
WhereClause.above() / IDBKeyRange.lowerBound() + Binary Keys

### ISSUE THREAD

**Issue by diegocr** [dfahlander/Dexie.js#1051]
Hello,

I would like to retrieve data in paging mode using binary keys, but it does not seem to work properly since i am always getting the same rows, so wondering if binary keys are supported there or otherwise i am doing something wrong (?)

Here's some sample code:

```js

self.db[table].orderBy(keyPath)
    .limit(limit)
    .toArray()
    .then(function _(r) {
        if (r.length) {
            var last = r[r.length - 1][keyPath]; // <-- this is an ArrayBuffer

            /* ... do stuff ... */

            // if (r.length >= limit) {
                self.db[table].where(keyPath)
                    .above(last)
                    .limit(limit).toArray().then(_).catch(reject);
                return;
            // }
        }
        resolve();
    })
    .catch(reject);
```

Any help will be greatly appreciated, thanks in advance!

**Comment by diegocr** [comment]
Anyone? :-/

**Comment by dfahlander** [comment]
Binary keys are supported in range queries the same way as strings or numbers. Some old browsers does not support them though - IE, Non-chromium Edge and older Safari versions.

**Comment by diegocr** [comment]
Thanks for the reply, i am using latest Chrome so it is correct speculating there may be an issue in `WhereClause`, or do you have some other clue?

**Comment by dfahlander** [comment]
The code you provided is not enough to understand what you are trying to do or what is going wrong. Please create a repro in jsitor.com or similar, that verifies the issue.

**Comment by diegocr** [comment]
My sample code is adapted from the [paging approach noted in the docs](https://dexie.org/docs/Collection/Collection.offset()#a-better-paging-approach-using-a-unique-property), i do suspect the issue may actually come from the fact the data stored into indexedDB is encrypted using AES CBC, will try to make a complete repro case whenever i have a chance...thanks anyway.

**Comment by diegocr** [comment]
Disregard, while trying to make that repro found the issue... the decryption step does mutates the original data (aka, `last`), so it becomes no longer usable for `WhereClause.above()` ... this is so embarrassing, sorry for bothering 😅

**Comment by dfahlander** [comment]
No probs! Happy you found it!
