### ISSUE TITLE
Entering a hook's transaction

### ISSUE THREAD

**Issue by ChicagoSchooler** [dfahlander/Dexie.js#106]
Thank you for this great library!

I'm trying to use hooks as foreign keys, such as a cascading delete, but I'm having a little trouble figuring out how to enter a hook's transaction.

Would you mind providing a brief example?

Thanks in advance!

**Comment by dfahlander** [comment]
Thanks :)

Don't know exactly what you're after but the transaction is provided as parameter to the hook subscriber 

https://github.com/dfahlander/Dexie.js/wiki/Table.hook('deleting')

What's missing so far in the api is fully asynchronic hooks. Hope to fix that in next major version.

**Comment by ChicagoSchooler** [comment]
I probably don't understand the full data model.

Please let me explain: I have as an example two tables, tableA and tableB.  Inside tableB is idA which should only include values from the auto-incremented primary key of tableA, called id.

I'd like to create the equivalent of a CASCADE DELETE on tableB such that when a record is deleted from tableA, any record in tableB with idA equal to the primary key of the just deleted record is also deleted, all within a single transaction.

To accomplish this, do I simply need to write something like:

```javascript
sampleDB.tableA.hook('deleting', function(id, tableArecord, transaction) {
	this.onsuccess = function(){
		sampleDB.tableB.where('idA').equals(id).delete()
	}
})
```

Or do I need to somehow append this operation to the current transaction, or do I need to wrap that in a new transaction?

Thank you for your support!

**Comment by dfahlander** [comment]
For CRUD hooks you need to use the provided transaction instead of db. It's s low level api. Just replace sampleDB with transactions and its rock solid.

**Comment by ChicagoSchooler** [comment]
That's great!

Just to confirm, this is correct?

```javascript
sampleDB.tableA.hook('deleting', function(id, tableArecord, transaction) {
    this.onsuccess = function(){
        transaction.tableB.where('idA').equals(id).delete()
    }
})
```

This is an amazing library!  Thank you!

**Comment by dfahlander** [comment]
:+1:

**Comment by ChicagoSchooler** [comment]
Incredible!

**Comment by Rocker2102** [comment]
> That's great!
> 
> Just to confirm, this is correct?
> 
> sampleDB.tableA.hook('deleting', function(id, tableArecord, transaction) {
>     this.onsuccess = function(){
>         transaction.tableB.where('idA').equals(id).delete()
>     }
> })
> This is an amazing library! Thank you!

`Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.`

```ts
export default function registerUsersHook(db: AppDatabase) {
  db.users.hook("deleting", function (id, _obj, transaction) {
    this.onsuccess = async () => {
      const dbTransaction = transaction as Transaction & AppDatabase;

      console.log(dbTransaction);

      try {
        dbTransaction.accounts.where({ userId: id }).delete();

        dbTransaction.budgets.where({ userId: id }).delete();

        dbTransaction.categories.where({ userId: id }).delete();
      } catch (error) {
        throw error;
      }
    };
  });
}
```

The log:
```js
Transaction2 {db: AppDatabase, mode: 'readwrite', storeNames: Array(1), schema: {…}, chromeTransactionDurability: undefined, …}
active: false
chromeTransactionDurability: undefined
db: AppDatabase {_middlewares: {…}, verno: 1, _options: {…}, _deps: {…}, _dbSchema: {…}, …}
idbtrans: IDBTransaction {_cache: null, mutatedParts: {…}, objectStoreNames: DOMStringList, mode: 'readwrite', durability: 'default', …}
mode: "readwrite"
on: ƒ (eventName, subscriber)
parent: null
schema: {users: {…}, categories: {…}, accounts: {…}, cards: {…}, transactions: {…}, …}
storeNames: ['users']
_blockedFuncs: []
_completion

.....
```

The `stores` property only includes the current table, i.e., which triggered the hook. How can i include all the tables by default for all hooks?
