### ISSUE TITLE
Dexie 3.0.0 + Syncable 1.0.0-beta-7 halts during initialisation randomly

### ISSUE THREAD

**Issue by oliverhowden** [dfahlander/Dexie.js#1066]
Using the simplest possible test for dexie syncable registerSyncProtocol the following snippet will successfully run ~95% of the time. 
Sometimes it will run 100 times in a row, though randomly (and then sometimes 20 times in a row) the `console.log('connecting');` will fail to hit. About 25 seconds later, the log will run and the protocol registration will continue. 

```
const url = 'localhost';
Dexie.Syncable.registerSyncProtocol('websocketsync', {
	sync: (
		context,
		url,
		options,
		baseRevision,
		syncedRevision,
		changes,
		partial,
		applyRemoteChanges,
		onChangesAccepted,
		onSuccess,
		onError
	) => {
		console.log('connecting');
		const ws = new WebSocket(url);
		ws.onopen = event => {
			console.log('websocket open');
		};
	},
}

**Comment by oliverhowden** [comment]
The issue appears to arise from creating a new database with the same name as one that previously was created, without calling `Dexie.delete()` in-between.

It causes `db._localSyncNode.isMaster` to be false and fail to connect sporadically. 
Fixed by ensuring the previous database is deleted in-between.

**Comment by hellorashid** [comment]
hey @oogghh can you share how/where you deleted in between? 

Running into this same issue now. Client will connect sometimes and then when I refresh page, it will sometimes not connect, until I refresh 10-20 times, and then will start connecting again.
