### ISSUE TITLE
mapToClass not applied to bulkGet results

### ISSUE THREAD

**Issue by medmunds** [dfahlander/Dexie.js#1079]
Table.mapToClass is not applied to the results of Table.bulkGet. (Using Dexie 3.0.1)

Example: https://codesandbox.io/s/dexie-maptoclass-bulkget-test-7x15x?file=/src/index.ts

I think the underlying issue is that [mapToClass relies on the readHook](https://github.com/dfahlander/Dexie.js/blob/v3.0.1/src/classes/table/table.ts#L248-L267), and that hook is run in [get](https://github.com/dfahlander/Dexie.js/blob/v3.0.1/src/classes/table/table.ts#L80) but not in [bulkGet](https://github.com/dfahlander/Dexie.js/blob/v3.0.1/src/classes/table/table.ts#L363-L370).

It's not entirely clear from the [mapToClass docs](https://dexie.org/docs/Table/Table.mapToClass()) whether this is expected, but it seems odd. (Especially since it looks like all the other bulk operations *do* run their corresponding CRUD hooks via the hooksMiddleware.)

**Comment by dfahlander** [comment]
Thanks for the report and the fix :)

**Comment by medmunds** [comment]
My pleasure. Thanks for Dexie!
