### ISSUE TITLE
very slow for add large data

### ISSUE THREAD

**Issue by ngocquynh85** [dfahlander/Dexie.js#1083]
It take so long time to see data after add large row. How can I speed-up it. 
for example:
var db = new Dexie("MyFriendDB");
db.version(1).stores({
	friends: '++id,name'
});

//
// Query Database
//
for (var tmp=1; tmp<=200000; tmp++){ 
  db.friends.add({name:"test", age:123}); 
}

![Annotation 2020-07-21 231554](https://user-images.githubusercontent.com/8684770/88079613-2aba0600-cba8-11ea-84d5-b6bd49e79ecb.jpg)

**Comment by dfahlander** [comment]
Try [bulkAdd](https://dexie.org/docs/Table/Table.bulkAdd()). But if you are adding 200,000 records, depending on how large objects you are adding, you may be better of splitting them into chunks of, for example 1000 records, and calling bulkAdd 200 times.

**Comment by ngocquynh85** [comment]
yess, I used bulkPut. It better now. Thank you.
