### ISSUE TITLE
Dataerror when trying to write large json array property

### ISSUE THREAD

**Issue by anushi1210** [dfahlander/Dexie.js#1087]
Hi,
Seeking help here, it would be much appreciated.
I've created a new issue because in the other one that i found no one was responding to the comment i added, maybe because it was a closed issue. 
I'm trying to write a json with a property which is a large array of objects (screen below) and this was working fine for the last 2 years in Android but last week it started to throw an "Dataerror: Failed to write blobs" to a lot of android users, maybe after some update of the Android Webview.
![monge_bug_results](https://user-images.githubusercontent.com/48827544/88370781-03735c80-cd93-11ea-8a8a-019d18f69b2b.png)

In my case i have this cordova app which writes some data through Dexie as a first sync. This is only one of the tables, i have other ones with much more results but this is the only one which have a complex property. As i sad the app worked fine the last 2 years with this workflow. This is the code which writes the json to my db:

```js
db.open().then(function () {
                   db.transaction('rw', db[objStoreName], function () {
                            db[objStoreName].clear().then(function () {
                                db[objStoreName].bulkAdd(res);
                            })
                    }).then(function () {
                        console.log("Transaction completed: database modification for " + objStoreName + " finished.");
                    }).catch(function (err) {
                        //***********This is where the error is catched, on end of transaction
                        console.error(err.stack || err);
                    });
                }).catch(function (err) {
                    console.error(err.stack || err);
                });
```

I tried different things as workarounds, i tried to:
1) catch the error on bulkAdd, but no error is thrown, instead it says it writes correctly but on end of transaction it throws the error.
2) use add() in loop, same error happens.
3) write array with chunks of 500, same problem.
4) JSON.stringify the array property, same error.

This is a screen of the error:
![monge_bug_error_mex](https://user-images.githubusercontent.com/48827544/88372263-d4121f00-cd95-11ea-8450-2c0d2e02f117.png)

I understand this is most probably a browser-related problem and not a Dexie issue, but i need to find a solution or even a temporary workaround to make it work as fast as i can so the users can use the app. My other option is to restructure the json as a plain table but it will cost me much more development time in terms of refactoring.
So if anyone have a workaround or a solution for this it would be much appreciated .

Thanks,
AN

**Comment by anushi1210** [comment]
Found a solution in: https://github.com/dfahlander/Dexie.js/issues/970#issuecomment-668459468
Thanks,
AN

**Comment by steveetm** [comment]
I found another strange thing: The actual leveldb database size is about 1.1GB while I am storing 20-30MB of data. I am 100% sure this is not a bug in dexie, but totally clueless where and how should I report this. AFAIK if any indexeddb record is larger than 64KB it will be stored as blob in indexeddb, so the error makes a bit more sense, as it comes from the internal database itself. But among those 1.1GB of blobs I found a _lot_ of duplicates, while there is definitely no bug in code, this is working fine in chrome/safari, I can reproduce it only in android webview atm.

**Comment by dfahlander** [comment]
@steveetm To me, is sound familiar that the physical database can contain much more data than the actual data in many database implementations, as a db engine may choose to store changed rows as new additions and mark the old versions as deleted instead of actually changing data or deleting old things. It can wait until next cleanup phase that may be periodic or may me on demand when there is low disk space.

**Comment by steveetm** [comment]
While this absolutely makes sense, two things aren't really ok:
- Writing 17megs increases leveldb by 64-200MB, whatever the underlying storage format is, this is _not_ ok.
- The write actually fails with data error, but the leveldb _never_ shrinks. I let it run for a day, opened indexeddb, write different tables, deleted records from different tables, all works fine, but every leveldb blob remains there. As soon as I try to write that 17MB again 200MB of blob created and data error thrown. As we automatically retry failed transaction x times every startup of the app can occupy 1GB of data, which is visible under application details. Still trying to put together of a minimal repro as something somewhere is definitely broken :( Already using a single, top-level transaction, still no luck. Also made sure that _nothing_ else is running when this write kicks in but have the same results.
