### ISSUE TITLE
Wiki edit request to describe Promise/IndexedDB incompatibility on the Transaction page

### ISSUE THREAD

**Issue by ChicagoSchooler** [dfahlander/Dexie.js#109]
I spent a day on this one wondering why my hook was leaving the transaction.

I stumbled upon the warning in the Promise page.  The Transaction page seems to conflict with that.

If you like and give me permission I can add it, but it will be some time since I'm currently in the weeds.

**Comment by dfahlander** [comment]
Please do! Thanks for discovering! Wiki should be able to edit for anyone.

**Comment by ChicagoSchooler** [comment]
Great.

Thanks again for this incredible library!  It has completely transformed my app.

**Comment by dfahlander** [comment]
Nice to hear!  :+1:

**Comment by ChicagoSchooler** [comment]
Done.
