### ISSUE TITLE
Non-inbound compound primary key

### ISSUE THREAD

**Issue by mychrisbi** [dfahlander/Dexie.js#1091]
Hello!
Is there a way to create a non-inbound compound primary key? I want to do something like this:

Object to save:
`{
   a:1,
   b:2
}`

Primary key: 
`{key1: "abc", key2:"efg"}`

I don't want to put those objects together and save the keys as inbound compound primary key, because I already have the typescript types in place and don't necessarily want to modify them. 

Thank you in advance!

**Comment by dfahlander** [comment]
yes you can use an array as key and add objects with using the key [key1,key2]

**Comment by mychrisbi** [comment]
Thank you very much, it is working now!
