### ISSUE TITLE
upgrade is not called after deleting and re-creating the db

### ISSUE THREAD

**Issue by fishbone1** [dfahlander/Dexie.js#1096]
Browser: Chrome 86.0.4221.0 (Official Build) canary (64-Bit)
Dexie 3.0.2

Problem:
The upgrade function is not called after DB deletion, although the DB schema is created newly and correctly. The `upgradeneeded` event works correctly with native IndexedDB (see code below). Everything works fine if the DB is not deleted: If I increase version from 2 to 3 below and reload browser tab, the upgrade function will be called.

**Reproduction:**
* Open application in browser
* Delete database in dev tools
* Add new table in source code (to check if DB is upgraded at all)
* Reload browser tab (f5)

**Result:**
* Devtools show DB version 20 (2 * 10)
* DB even has new table created between deletion and reload
* Upgrade method wasn't called after reloading the browser tab

**Expected result:**

Upgrade method to be called after reloading browser tab.

**Code:**

```typescript
import Dexie from "dexie";
import {Customer} from "./models/customer.model";

type AppDexieDb = Dexie & {
  customers: Dexie.Table<Customer, number>,
};

export class DbService {

  private static INITIAL_CUSTOMERS = [
      {name: 'test'},
      // ...
  ];

  private db: AppDexieDb;

  constructor() {
    // THIS WORKS
    /*
    const request = window.indexedDB.open('myapp', 3);
    request.onupgradeneeded = event => {
      // shows 0, 3
      console.log(`IDB onupgradeneeded oldVersion: ${event.oldVersion}, newVersion: ${event.newVersion}`);
    };
    request.onsuccess = () => {
      console.log('IDB onsuccess')
    };
    return;
    */

    this.db = <AppDexieDb>new Dexie('myapp');

    this.db.version(1);
    this.db.version(2).stores({
      customers: '++id',
      checkifupgrades5: 'id',
    }).upgrade(tx => {
      alert('Upgrade to version 2');
      return tx.table('customers').bulkAdd(DbService.INITIAL_CUSTOMERS);
    });
    this.db.customers.mapToClass(Customer);
    this.db.customers.toArray().then(() => {
      console.log('Dexie: Retrieve customers');
    });
  }
}
```

**Comment by dfahlander** [comment]
This is intentional and described in detail in [database-versioning](https://dexie.org/docs/Tutorial/Design#database-versioning). Since there is no old version to migrate from, no upgrader should run. There's a numbered list under *Description of the open / upgrade sequence* that describes the sequence that happens when Dexie opens a database. If you need to populate database, use [populate](https://dexie.org/docs/Dexie/Dexie.on.populate) event.

**Comment by fishbone1** [comment]
Seems that I missed that part. But I guess `populate` doesn't really fit my needs. Let's say I introduce a new table `countries` at version 5 and I have to populate countries. This is a very common case in many applications. Then users upgrading from lower versions won't have country data, as their database isn't new. What is your suggestion in this case? Should I define a function `populateCountries()` and call it from both, `upgrade()` and `.on('populate', ...)`?

**Comment by dfahlander** [comment]
Think of upgraders as temporary code that you will eventually remove when all your users are migrated. Populate on the other hand describes what data should be in the DB according to the current schema. The strict way would be to declare a versioned function populateCountries5() and call it from the upgrader of version 5 + from the populate event. If you add countries, add them to populateCountries6() and call it from version 6 upgrader but call both from populate event.

Another approach is to use the [ready](https://dexie.org/docs/Dexie/Dexie.on.ready) event similar to how it's done in [this sample](https://dexie.org/docs/Dexie/Dexie.on.populate#ajax-populate-sample). Other database-facing code will be pause until the promise returned by Dexie.on.ready completes.
