### ISSUE TITLE
Schema modifications, using the documented approach, do not work

### ISSUE THREAD

**Issue by wkhatch** [dfahlander/Dexie.js#1104]
In any production react build, when I modify the schema using the documented strategy, things fail miserably in the deployed app such that we have to instruct every single user on how to clear their db, etc. This is a problem that keeps resurfacing. It works fine in local dev, but not in production.

**Comment by dfahlander** [comment]
Can you give me an example of how you update your schema? Are you using version 2 or 3 of Dexie?

**Comment by wkhatch** [comment]
Hello, using 2.0.4 of Dexie. Here's the latest migration, (borrowing that term from the rails community), which works fine in local development, but then fails spectacularly in production:

```
db.version(7)
  .stores({
    conditionRuleGroups: 'item_id, parent_group_id, condition_id, name',
    conditions: 'item_id, condition_name, trigger_id',
    condition_rules: 'item_id, parent_group_id, condition_id, device_id',
    condition_triggers: 'item_id, service_call_id, device_command_id, trigger_type, publish_path',
    integrations: 'item_id, name, active',
    trigger_actions: 'item_id, trigger_id, trigger_output_id, trigger_event_id',
    trigger_inputs: 'item_id, name, trigger_type, category, enabled',
    trigger_outputs: 'item_id, name, action_type, category, enabled, integration_id',
    triggered_events: 'item_id, trigger_action_id, status',
    triggers: 'item_id, name, trigger_type'
  })
  .upgrade(tx => {
    return tx.table('devices').modify(device => {
      delete device.datatimestamp;
    });
  });
```

**Comment by dfahlander** [comment]
Did you do as described in the docs [Migrate Data](https://dexie.org/docs/Tutorial/Understanding-the-basics#migrate-data)  and keep the old version declarations in the code?

**Comment by dfahlander** [comment]
Also, I see you are using a non-existing method Table.modify(). You need to do:

```js
tx.table('devices').toCollection().modify(device => {
  delete device.datatimestamp;
});
```

The reason it works in local db is probably because you dont have an earlier version installed so the upgrader with faulty code won't run. I'd recommend everyone to test the upgrading:
1. Navigate a fresh browser to an older version of your app. You can probably build it from a historical git commit.
2. Let the same browser visit your latest version.

If possible, test all your upgrades in browser-hosted unit test - one unit test for each released version.

```

**Comment by wkhatch** [comment]
Yes, all previous versions are preserved in database.js 

Bill Hatch

**Comment by dfahlander** [comment]
Ok good. I hope you didn't miss my next comment also about what is wrong in your upgrade code.

**Comment by wkhatch** [comment]
> Ok good. I hope you didn't miss my next comment also about what is wrong in your upgrade code.

I'm sorry, I actually did not see the second comment at first. That explanation makes complete sense, and we've updated that statement to:

```
db.version(7)
  .stores({
    conditionRuleGroups: 'item_id, parent_group_id, condition_id, name',
    conditions: 'item_id, condition_name, trigger_id',
    condition_rules: 'item_id, parent_group_id, condition_id, device_id',
    condition_triggers: 'item_id, service_call_id, device_command_id, trigger_type, publish_path',
    integrations: 'item_id, name, active',
    trigger_actions: 'item_id, trigger_id, trigger_output_id, trigger_event_id',
    trigger_inputs: 'item_id, name, trigger_type, category, enabled',
    trigger_outputs: 'item_id, name, action_type, category, enabled, integration_id',
    triggered_events: 'item_id, trigger_action_id, status',
    triggers: 'item_id, name, trigger_type'
  })
  .upgrade(tx => {
    return tx
      .table('devices')
      .toCollection()
      .modify(device => {
        delete device.datatimestamp;
      });
  });
```

Thank you so much!!

**Comment by kendallroth** [comment]
Please note that some documentation still references `.table().modify()`, which may be causing this (I ran into it just recently as well).

[Example docs](https://dexie.org/docs/API-Reference#upgrade)

**Comment by dfahlander** [comment]
> Please note that some documentation still references `.table().modify()`, which may be causing this (I ran into it just recently as well).
> 
> [Example docs](https://dexie.org/docs/API-Reference#upgrade)

Thanks! I've update the docs! As of dexie@4 Table.update() can be used in this place ( a bit shorter than table.toCollection().modify().

**Comment by kendallroth** [comment]
Oh wow, did not expect that turnaround 🤣! Regarding `Table.update()` though, that requires updating with _known_ keys, correct? While `table.toCollection().modify()` uses a function to allow reassigning existing values (not possible via `Table.update()`), correct?

For example, how could `table.update()` handle the following?

```ts
.table("recording").toCollection().modify((r) => {
  r.fileKey = r.fileName;
  delete r.fileName;
});
```

**Comment by dfahlander** [comment]
Historically Table.update() did as you describe and that's why there are many examples but as of dexie 4, it's also allowed to pass a callback to Table.update() .
