### ISSUE TITLE
bulkAdd & bulkPut typing: accept a `readonly` array

### ISSUE THREAD

**Issue by wh1t3cAt1k** [dfahlander/Dexie.js#1105]
We follow immutability practices in our codebase, but because of the current typings, `bulkAdd` and `bulkPut` do not accept a `readonly TEntity[]`, only `TEntity[]`.

If I understand it correctly, the typing could be safely relaxed to allow both the readonly and non-readonly versions of the array.

This would be a small change and would avoid a type assertion in the consuming code.

Thank you!

**Comment by dfahlander** [comment]
Yes, it's true we could add the readonly attribute into bulkAdd and bulkPut and I thing we should. PR's would be welcome. First change table.d.ts under src/public/types. Then go ahead and change the implementations as TSC will start complaining. It might require a change all the way into DBCoreAddRequest and DBCorePutRequest interfaces but that is ok. DBCore does not alter given arrays in the mutate method. The request objects itself may be extended with the optional key property but the values array will be readonly in practice.
