### ISSUE TITLE
Possible to use DbCore middlewares to override store spec parsing?

### ISSUE THREAD

**Issue by carsonfarmer** [dfahlander/Dexie.js#1109]
I'd like to do something similar to Dexie.Observable using the new middleware framework. One thing I like about Dexie.Observable is that it supports the alternative `$$` UUID specification. Additionally, it automatically adds a few extra tables to the DB. Right now, it does this by overriding the `_parseStoresSpec` method. Is there a way to do this via the middleware framework? I tried something similar to the https://github.com/dfahlander/Dexie.js/blob/master/src/dbcore/virtual-index-middleware.ts (to modify the schema property), but it seems this happens _after_ parsing the key values, so it is too late to "strip" the $$ prefix. Additionally, it doesn't seem possible to _add_ keys to the `DBCoreIndex` interface at runtime, which is another thing that Dexie.Observable was doing. This last item is less important to me though.

As an aside, for these types of "questions" is there a better place to ask than using a GitHub issue?

**Comment by dfahlander** [comment]
Thanks for the interesting question! I gladly take these types of questions here as Github issues. DBCore currently only intercept runtime when database is opened, so you would need to do the schema changes similar to how they were done in Dexie.Observable - by overriding _parseStoresSpec. One way is to create an addon that does these things along with calling db.use(yourMiddleware). Will not deprecate the possibility to override _parseStoresSpec. I suppose you could add keys in the form of a schema specification there, that will affect the DBCoreIndexes you will see from the middleware.

**Comment by carsonfarmer** [comment]
Ok, awesome, this sounds like the right path forward then!

**Comment by carsonfarmer** [comment]
Oh actually, it looks like additional keys in the schema spec aren't going to be available in the middleware because they are hardcoded here: https://github.com/dfahlander/Dexie.js/blob/master/src/dbcore/dbcore-indexeddb.ts#L61. Does that seem correct?

**Comment by dfahlander** [comment]
They are parsed from what's in the native IndexedDB schema after it has been opened. And that in turn will be affected by the indexes defined in ’version(x).stores({....})’ part which has run earlier. DBCore is initiated after all the code that takes part in the db.open() procedure and can read from the opened database.

**Comment by carsonfarmer** [comment]
Ok, I still don't seem to be able to access custom keys for a schema specification defined in _parseStoresSpec in the middleware, but this is not a _requirement_ for what I'm working on, so closing this as "answered"! Thanks again.
