### ISSUE TITLE
Intercepting transactions in DBCore middleware

### ISSUE THREAD

**Issue by carsonfarmer** [dfahlander/Dexie.js#1111]
I am trying to intercept all transactions going through DBCore using something like:

```typescript
// middleware.ts
export function createMyMiddleware(dbCore: DBCore): DBCore {
  return {
    ...dbCore,
    transaction(req: DBCoreTransactionRequest): DBCoreTransaction {
      // Modify the transaction request here?
      console.log("transaction called")
      return dbCore.transaction(req);
    },
  };
}

export const myMiddleware: Middleware<DBCore> = {
  stack: "dbcore",
  name: "MyMiddleware",
  create: createMyMiddleware,
};
```

And then something like:

```typescript
// index.ts
const db = new Dexie("databaseName");
db.use(myMiddleware);

db.version(1).stores({
  friends: "++id,name,shoeSize,address.city",
  other: "++id",
});

await db.open();

await db.table("friends").put({
  name: "Earthling",
  shoeSize: 10,
  address: {
    city: "Earth",
  },
});

await db.transaction("readwrite", ["friends"], async (tx) => {
  const friends = tx.table("friends");
  const friend = await friends.get({ name: "Earthling" });
  ++friend.shoeSize;
  await friends.put(friend);
  await db.transaction("readwrite", friends, async (tx) => {
    const id = await friends.add({
      name: "Martian",
      shoeSize: 6,
      address: {
        city: "Mars",
      },
    });
    const friend = await friends.get(id);
    friend.name = "Replaced";
    await friends.put(friend);
    await friends.delete(id);
  });
});
```

But no matter what I do, the modified transaction code is never run. I would like to modify the transaction to include additional (hidden) tables, or to piggyback on the existing transaction in some way. I've also played with doing this in the table's `modify` middleware, which does run when I expect it to, but I don't appear to be able to accomplish what I need there. The documentation for DBCore (https://dexie.org/docs/DBCore/DBCore) states that it "... covers more use cases, such as when a transaction is created..." which is pretty much exactly what I need/want. Any help intercepting transactions would be greatly appreciated!

Also, apologies for another DBCore question! 

P.S. I am able to provide a self-contained example if that would help, though I suspect this is just something pretty simple I'm missing.

**Comment by dfahlander** [comment]
Transactions in dexie seems still be using IDB directly and can be overridden the "old" way, through overriding [db._createTransaction()](https://github.com/dfahlander/Dexie.js/blob/master/src/public/types/dexie.d.ts#L26). I'm glad you are entering a new path here to detect incorrect docs. But it must be a bit frustrating to debug these things. Apologize for that.

db._createTransaction has been used by dexie-observable for quite a time and should cover your use case anyhow. The method is overridable the same way as _parseStoresSpec.

**Comment by carsonfarmer** [comment]
Not a problem, thanks for the help here!
