### ISSUE TITLE
Dexie module does not have named export

### ISSUE THREAD

**Issue by nicolashenry** [dfahlander/Dexie.js#1127]
Hello,

The Dexie typescript definition file indicates that Dexie is exported as the default export __and__ as 'Dexie' named export but the real javascript module only expose it as the default export.

So this:
```ts
import { Dexie } from 'Dexie';
```
causes this error while bundling:
```
export 'Dexie' was not found in 'dexie'
```
but typescript is not complaining.

**Comment by dfahlander** [comment]
Ok. I thought I did it in [dexie-static-props.ts](https://github.com/dfahlander/Dexie.js/blob/c9187ae60c0d7a424f85bab3af179fbbc9901c8e/src/classes/dexie/dexie-static-props.ts#L223-L228) but I understand now that it only works for the umd version.

**Comment by dfahlander** [comment]
If we'd `export {Dexie}` together with `export default Dexie` in index.ts we create problems for rollup to generate the UMD version. For UMD outputs, rollup handles the case when only a default export is used so it is similar to `module.exports = Dexie`. Having a mixed export would require the UMD to let the final exported module become {Dexie: Dexie, default: Dexie}, which works bad for UMD exports.

I think it's fixable if we separate the UMD and ES builds a bit (different module entries and different rollup configs).
Working on it.
