### ISSUE TITLE
How to customize UUID generator

### ISSUE THREAD

**Issue by hucsmn** [dfahlander/Dexie.js#1128]
I am investigating on mocking a conventional backend project in browser using indexedDB, with some sort of data synchronization functionalities. Dexie.js seems to be an awesome choice for me to work on. Queries in Dexie.js is really concise.

I have noticed that `Dexie.Observable` addon supports generate UUIDv4 for primary keys. However my original backend project is based on MyBatis Plus, which uses a variant of snowflake UUID primary key generator (w/o hyphens) by default.

As mentioned in [a comment in 2015](https://github.com/dfahlander/Dexie.js/issues/136#issuecomment-142207833), people could customize `createUUID` simply by replacing it. But it seems not work now.

Also, I have found that [the creating hook](https://github.com/dfahlander/Dexie.js/blob/bf3a6fc7fb7666767050f2914d313486287a6fdd/addons/Dexie.Observable/src/hooks/creating.js#L11) of `Dexie.Observable` would directly invoke its default `createUUID` other than invoking the exposed `Dexie.Observable.createUUID`.

Is there any way to customize the UUID generator of `Dexie.Observable`, or any method to custom uuid primary key generate in indexedDB.

**Comment by dlech** [comment]
This seems like a bug. Maybe we should keep the issue open?

**Comment by dfahlander** [comment]
The PR #1527 is released in dexie-observable@[4.0.0-beta.13](https://www.npmjs.com/package/dexie-observable/v/4.0.0-beta.13).
