### ISSUE TITLE
Can't define class when table with composite key

### ISSUE THREAD

**Issue by jsobus-neurosys** [dfahlander/Dexie.js#113]
I try to define class on table with composite key and get this error:

Error: Assertion failed
    at assert (Dexie.js:2769)
    at setByKeyPath (Dexie.js:2820)
    at WriteableTable.extend.mapToClass (Dexie.js:974)
    at WriteableTable.extend.defineClass (Dexie.js:1013)
    at getUserProgressTable (userProgressService.js:33)
    at getUserProgressForCourse (userProgressService.js:66)
    at app.js:20
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$get.Scope.$eval (angular.js:14466)

My table definition:
'userProgress': '[CourseId+UserId], CourseId, UserId'

My define class:
var UserProgressObject = table.defineClass({
                    UserId: Number,
                    CourseId: Number,
                    FinishDate: String,
                    DueDate: String,
                    ContentsProgress: []
                });

**Comment by jsobus-neurosys** [comment]
My define class show all columns in that table of course.

**Comment by jsobus-neurosys** [comment]
Line 2820: assert(typeof value !== 'string' && 'length' in value);
Fail because value is "" and can't get 'length' in value.

**Comment by dfahlander** [comment]
Thanks! Please try with src/Dexie.js from github repo to verify it's fixed.

**Comment by jsobus-neurosys** [comment]
Yeah it's better now, I debugged key assertion there (now line 2909) but after key definition next iteration have value = undefined. I think this is becuse of my ContentsProgress wchich is other array. I tried to change this and now I have: 

            function ContentProgress() {
                                return {
                    Attempts: Number,
                    ContentId: Number,
                    Score: Number,
                    IsCompleted: Boolean
                };
            };

var UserProgressObject = table.defineClass({
                    UserId: Number,
                    CourseId: Number,
                    FinishDate: Object,
                    DueDate: Object,
                    ContentsProgress: [ContentProgress]
                });
but error still occurs:

TypeError: Cannot use 'in' operator to search for 'length' in undefined
    at setByKeyPath (Dexie.js:2909)
    at delByKeyPath (Dexie.js:2932)
    at WriteableTable.mapToClass (Dexie.js:977)
    at WriteableTable.defineClass (Dexie.js:1015)
    at getUserProgressTable (userProgressService.js:28)
    at getUserProgressForCourse (userProgressService.js:65)
    at app.js:20
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$eval (angular.js:14466)

**Comment by jsobus-neurosys** [comment]
Just to clarify i debugged assertion (line 2909) i see the first 2 iterations create key but after that (3rd iteration) have var value undefined.

**Comment by dfahlander** [comment]
Aha, it's an issue with delByKeyPath() on array keyPaths. I fix. Thnkx!

**Comment by dfahlander** [comment]
Please re-test

**Comment by jsobus-neurosys** [comment]
You got it ;) Now everything works great! So close this isse. I have another question. Is it possible to extend objects in array of main table object - like in my ContentsProgress: [ContentProgress] so ContentProgress object have it own prototype functions? As i cheked now i can make ContentsProgress: [] and it's still the same. I ask because if i create my ContentProgress like this: 
                function ContentProgress() {
                return {
                    Attempts: Number,
                    ContentId: Number,
                    Score: Number,
                    IsCompleted: Boolean,
                    SumSum: function()
                    {
                            return this.Attempts + this.Score;
                    }
                };
            };
After i get main object (UserProgressObject) from table, object ContentsProgress is the array of Objects not my defined class so I am not able to use my SumSum function.. I know i can create related table and map to class then and get it by some key but i would like to use it as document i don't need relations. I think this is JavaScript limitation but tell me how to do it if i am wrong :)

**Comment by dfahlander** [comment]
I see what you mean. No, it's not possible today with Dexie, but I understand the use of it.

Note though that defineClass() and mapToClass() does never call your constructor, it just fixes the prototype chain for the objects.

Internally this is implemented by subscribing to [Table.hook('reading')](https://github.com/dfahlander/Dexie.js/wiki/Table.hook('reading')) and fix the prototype chain for the main object.
 
What I would do if implementing this, would be to also fix the prototype chains for Function-members declared in defineClass. Think it would be easy to implement this, but defineClass() would have to store some more meta data to be read from the [Table.hook('reading')](https://github.com/dfahlander/Dexie.js/wiki/Table.hook('reading')) subscriber.

If this would be implemented, you would though have to declare your ContentProgress class like this instead:

```js
function ContentProgress() {
    // Optionally set local properties into this by reading from constructor arguments.
}
ContentProgress.prototype.SumSum = function () {
    return this.Attempts + this.Score;
}
```

It's the preferred way of defining javascript classes. It's also how ES6- and Typescript classes generate when transpiled to ES5.

**Comment by jsobus-neurosys** [comment]
Yeah i tried with prototype also and i use this way of class implementing for my main table objects ;) Because, as you said, Typescript make it this way also. I think this will be great feature for Dexie because no additional mapper/extending will be needed. I'm looking forward for this feature but for the moment thanks for this library.

**Comment by dfahlander** [comment]
The only thing that prevents me from extending the defineClass() method, is that I like mapToClass() more than defineClass() for the simple reason that mapToClass() adapts to existing ways of defining classes but defineClass() invents its own way a quite non-stanard way, which makes it hard to use with ES6 or typescript for example. It solves part of the things that typescript solves.

It would be best to have your desired functionality without the dependence on defineClass() and instead in some way make it also work with mapToClass().

So there are questions to answer before digging into it, I believe.

Sorry for thinking out loud here but maybe I could implement it experimentally and then complement later with a solution for mapToClass() as well that works also with Typescript and ES6... Maybe I'll have a quick look at it...
