### ISSUE TITLE
Upgrade Not Running in Test Environment

### ISSUE THREAD

**Issue by cwbuecheler** [dfahlander/Dexie.js#1134]
Hiya, I'm running into a strange issue that I don't really understand. I have some test code where I'm creating a Dexie instance, like this:

```
const db = new Dexie('MyDb');
db.version(1).stores({
  TableOne: 'id',
  TableTwo: 'id',
});
```

And then, a line later:

```
db.version(2).stores({
  TableOne: 'id',
  TableTwo: 'id',
}).upgrade((tx) => {
  console.log('upgrade');
  return tx.table('TableOne').toCollection().modify((session) => {
    const newSession = { ...session };
    session = newSession;
  });
});
```

(I've anonymized my table names and stripped some stuff from the `tx.table` code above which is why it looks like it's just returning the same object).

I know you don't need to keep the old DB init anymore with Dexie 3+ (I'm on the latest release) but I actually need it in this situation because I'm specifically testing to catch a data error that might get thrown if someone changes a model but forgets to write an upgrade for the change.

The problem is that the upgrade method doesn't seem to run. For one thing, the `console.log` doesn't actually happen, and for another, the changes to my session variable don't seem to happen.

This is using `fake-indexeddb` and running in a test environment (Jest, Node 14.12.0), so it's very possible this is not strictly a Dexie issue, but I feel like I'm missing something obvious and would appreciate any help.

**Comment by dfahlander** [comment]
To trigger the upgrade, database must be created at version 1 first. Then you close it and add version to and reopen it.

So, to test upgrades you need to mimic the state of a real user:

```js
let db = new Dexie('MyDb');
db.version(1).stores({
  TableOne: 'id',
  TableTwo: 'id',
});
db.open().then(async()=>{
  // At this point you might insert some data if you want to test the upgrader with real data.

  // Now mimic a real user scenario: page is closed:
  db.close();

  // ...page is opened and this time your app has a new version on the DB:
  db = new Dexie('MyDb');
  db.version(1).stores({
    TableOne: 'id',
    TableTwo: 'id',
  });
  db.version(2).stores({
    TableOne: 'id',
    TableTwo: 'id',
  }).upgrade((tx) => {
    console.log('upgrade');
    return tx.table('TableOne').toCollection().modify((session) => {
      const newSession = { ...session };
      session = newSession;
    });
  });
  await db.open(); // db.open() is what triggers the upgrader.
});
``

**Comment by cwbuecheler** [comment]
@dfahlander - thanks so much! I'll give this a shot tomorrow. If you want to close out the comment, no prob, otherwise I'll do it after I've got things up and running.
