### ISSUE TITLE
Compound Index/Key declaration with Typescript

### ISSUE THREAD

**Issue by tvvignesh** [dfahlander/Dexie.js#1142]
Hi. I am trying to get compound index working with Typescript using Dexie. 

I was able to get it working with a string key like this:

`myTable: Dexie.Table<myClass, string>;` 

**But this throws an error for me in Chrome:**

`myTable: Dexie.Table<myClass, myCompoundIndexInterface>;` 

I have defined an interface to define my keys like this:

```ts
interface myCompoundIndexInterface {
   key1: string;
   key2: string;
}
```

And it throws me an error in chrome saying:

```
Unhandled rejection: DataError: Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key.
 DataError: Failed to execute 'bound' on 'IDBKeyRange': The parameter is not a valid key.
```

also tried defining a class like this instead of an interface which lead to the same error:

```ts
export class myCompoundIndexClass {
  key1: string;
  key2: string;

  constructor(key1: string, key2: string) {
    this.key1= key1;
    this.key2 = key2;
  }
}
```

and this lead to the same error. Was not able to find any docs on how to declare compound index keys using typescript interfaces or classes.

I am using store something like this:

```ts
this.version(1).stores({
     myTable: '[key1+key2],[index1+index2]',
});
```

Any help appreciated.
CC: @dfahlander

**Comment by tvvignesh** [comment]
Oops. This occurred cause my key was undefined. Sorry. Closing this.

**Comment by dfahlander** [comment]
No problems! Glad you found it.
