### ISSUE TITLE
bulkPut with {allKeys: true} - order of returned keys?

### ISSUE THREAD

**Issue by MarMun** [dfahlander/Dexie.js#1143]
If I add via `bulkPut`, the returned keys array is in same order as the objects to put (e.g. key on index 1 was assigned to object at index 1)

Is this intended, can I rely on this?

I asked because while for `bulkGet` it's stated ([source](https://dexie.org/docs/Table/Table.bulkGet()#remarks)):

> The resulting array will always have the same length as the given array of keys. Every position in given key array will correspond to the same position in the resulting array.

It is not stated for `bulkPut` ([source](https://dexie.org/docs/Table/Table.bulkPut()#return-value)):

> If options argument is provided in second or third argument with {allKeys: true}, the return value is a promise resulting with an array of resulting primary keys. The resulting array will have the same length as given array of objects to put.

I'm missing a `Every position in given object array will correspond to the same position in the resulting key array` for `bulkPut`

**Comment by dfahlander** [comment]
Yes, they will be in the same position, just like it is with bulkGet().
