### ISSUE TITLE
[unreleased] Dexie.Observable: TypeScript compile-time errors - missing properties

### ISSUE THREAD

**Issue by jayaddison** [dfahlander/Dexie.js#1144]
In the unreleased `Dexie` head commit 1f2cad1eee7166d1a0c4b3cb9ac13120a3b2131b , TypeScript compilation of a module that constructs a `Dexie` database after importing `Dexie.Observable` fails with the following `tsc` error:

```
        TS2322: Type '{ (db: Dexie): void; createUUID: () => string; on: ObservableEventSet; localStorageImpl: { setItem(key: string, value: string): void; getItem(key: string): string; removeItem(key: string): void; }; _onStorage: (event: StorageEvent) => void; }' is not assignable to type '(db: Dexie) => void'.
    Types of parameters 'db' and 'db' are incompatible.
      Type 'Dexie' is missing the following properties from type 'Dexie': observable, _localSyncNode, _changes, _syncNodes, _intercomm
```

A repro TypeScript module to reproduce this is:

```typescript
import Dexie from 'dexie';
import observable from 'dexie-observable';

class Database extends Dexie {
    constructor() {
      super('dbname', {addons: [observable]});
    }
}
```

Naive assessment: it seems as if the [extended properties](https://github.com/dfahlander/Dexie.js/blob/1f2cad1eee7166d1a0c4b3cb9ac13120a3b2131b/addons/Dexie.Observable/src/Dexie.Observable.d.ts#L52-L54) from the `Dexie.Observable` addon are not present on the `Dexie` type when the compiler performs type-checking.

Note: the `addons: [observable]` option is provided to the super constructor because otherwise the `on` and `subscribe` functions do not appear to be added to the resulting database class.

Commit 3f364f3ea85e063026b20b6e0e7b95191e82331e seems to be the first version of the `Dexie.Observable` addon where this problem occurs.

**Comment by dfahlander** [comment]
Ok. Thanks for the feedback. I will investigate.

**Comment by dfahlander** [comment]
I tried to reproduce it using 
```
npm i dexie@next dexie-observable@next
```
Get no typescript error there. But when downgrading dexie-observable to dexie-observable@latest I get many tsc errors.

Which version of dexie-observable did you test with? If you didn't try dexie-observable@next, it could be the reason it doesn't work.

**Comment by jayaddison** [comment]
Thanks for taking a look.  This was using a git checkout of Dexie + Dexie.Observable @ https://github.com/dfahlander/Dexie.js/commit/1f2cad1eee7166d1a0c4b3cb9ac13120a3b2131b.

I ran `npm run-script build` to compile `dist` files for each of them, and then refer to those via file paths in `package.json` -- I'll try to package an example up in a repro repository soon.

**Comment by jayaddison** [comment]
Repro for this is available in https://github.com/jayaddison/dexie-1144-repro (with instruction steps in the README).

**Comment by jayaddison** [comment]
I'm unable to reproduce this using `dexie@3.0.3-rc.2`, `dexie-observable@3.0.0-beta.10`.
