### ISSUE TITLE
Can't increase version of db schema - UpgradeError Not yet support for changing primary key

### ISSUE THREAD

**Issue by dmingazov** [dfahlander/Dexie.js#1148]
Hi,
Can't figure our what I'm doing wrong here.
To reproduce I use sample project from here: samples/react

import Dexie from 'dexie';
import 'dexie-observable';

const db = new Dexie('ReactSampleDB');
db.version(1).stores({ todos: '$$uuid' });

//After deployment (which is Ok), I increase version by adding this:

db.version(2).stores({ tasks: '$$uuid' });

And after page reload I'm getting this exception
Unhandled Rejection (OpenFailedError): UpgradeError Not yet support for changing primary key

**Comment by dmingazov** [comment]
Seems like that issue had similar symptoms
https://github.com/dfahlander/Dexie.js/pull/959#issuecomment-590973310

**Comment by dfahlander** [comment]
Thanks for reporting this. It's fixed and will be released in 3.0.3-rc.3.
