### ISSUE TITLE
cand understand order of code running

### ISSUE THREAD

**Issue by boynet** [dfahlander/Dexie.js#115]
just cant understand it, take this simple code:
````
db.games.put({vs: vs, score: score,why:why}).then (function(){
        db.scoreVS.where('vs').equals(vs).toArray(function(a) {
            return a;
        }).then(function (a) {
                console.log('1');
                db.scoreVS.put(a[0]).then(function(){
                    console.log('2');
                });
        });
        db.close();
    });
````
I excepeted to see in console:
````
1
2
````

while I see the reverse:
````
2
1
````

whats the right way of making a table with counter inside it and to increase the counters in some situations? right now I do where to get the counter value increase it and do a put with the new data. but its not working as the put working first and than the increasment

**Comment by dfahlander** [comment]
Sounds strange. I've no time to debug that right now, but one obvious issue with your code is that you close the database before everything is done. Move db.close() to after console.log('2').
