### ISSUE TITLE
Efficiently read almost million records by index

### ISSUE THREAD

**Issue by raj1127** [dfahlander/Dexie.js#1150]
How to efficiently read almost million records stored in IndexedDB using Dexie by given index.
I am using below and it is taking forever to return records

this.ddb.version(1).stores({
                elements: '[Element.DatasetId+Element.Id], Element.NodePath, Element.Label'
            });

this.ddb.elements.where('Element.NodePath').anyOf(nodePathArray)   //nodePathArray contains array of strings to be searched in IndexedDB. Almost 3000 elements in it to be searched.

**Comment by dfahlander** [comment]
* Avoid anyOf() when querying millions of rows as it needs to use IDBCursor which is slow. Prefer use the plain index operators equals, above, below, between and startsWith.
* Prefer toArray() over each()

Your query would get better performance using something like the following:

```js
Promise.all(
  nodePathArray.map(nodePath =>
    this.ddb.elements.where('Element.NodePath').equals(nodePath).toArray()));
```

**Comment by raj1127** [comment]
Thanks your code seems to be working way faster now. But it is now returning everything in Arrays (each item) under one big array. How to return one single array with objects (elements) from indexed db only (with index matching give index)? Thanks again.


![image](https://user-images.githubusercontent.com/11743082/96654003-e7cf1200-12ff-11eb-94b7-192704d2e31e.png)

**Comment by dfahlander** [comment]
Use [flat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) on the result to get it into a single array.

**Comment by raj1127** [comment]
Thanks David for help. Working good now. Thanks again.
