### ISSUE TITLE
Export loadUntilWeGotEnoughData or JsonStream

### ISSUE THREAD

**Issue by fishbone1** [dfahlander/Dexie.js#1163]
Can you please export `loadUntilWeGotEnoughData()` and/or `JsonStream()` in your npm module?

Background:
We delete our database before importing the file. But before importing, we need to know if the backup file is valid.
Your method `loadUntilWeGotEnoughData()` uses JsonStream to fetch the relevant JSON part which allows you to check if the file is valid, but the deletion must occur between this validation and the import itself.

We want to go even further and implement a "dry run" which imports the data into a temporary db. If this is successfull we can delete the actual db and start the actual import.

To achieve this, we wrote a method which is almost identical to `importDB`. The only difference is, that it uses the temporary db name:

```ts
export async function dryRunImportDB(exportedData: Blob | JsonStream<DexieExportJsonStructure>, options?: StaticImportOptions): Promise<Dexie> {
  options = options || {}; // All booleans defaults to false.
  options.acceptNameDiff = true; // DRY RUN
  const CHUNK_SIZE = options!.chunkSizeBytes || (DEFAULT_KILOBYTES_PER_CHUNK * 1024);
  const stream = await loadUntilWeGotEnoughData(exportedData, CHUNK_SIZE); // CANNOT IMPORT THIS METHOD
  const dbExport = stream.result.data!;
  const db = new Dexie(dbExport.databaseName + '_dryrun'); // DRY RUN
  db.version(dbExport.databaseVersion).stores(extractDbSchema(dbExport));
  await importInto(db, stream, options);
  return db;
}
```
But this doesn't work, because we cannot `import` `loadUntilWeGotEnoughData()` in line 5.

The temporary dry-run db doesn't exist before running the import. The key thing here is this line:
```ts
  db.version(dbExport.databaseVersion).stores(extractDbSchema(dbExport));
```
It initializes the object stores. This is only possible, because `loadUntilWeGotEnoughData()` has the necessary information.

Exporting `extractDbSchema()` would be helpful as well, but it's very simple and can be implemeted on our own.

We tries to implement `loadUntilWeGotEnoughData()` but it creates a `JsonStream` which is also not exported. Only its type information is exported. Exporting `JsonStream` would be very useful, because it allows to write your own backup file validation logic.

**Comment by fishbone1** [comment]
For anyone who is interested, here is the workaround for my Angular-project, but it should work with other typescript projects as well:

1. Copy the ts-source files of the _dexie-export-import_ addon from [Github](https://github.com/dfahlander/Dexie.js/tree/master/addons/dexie-export-import/src) to my project directory `src/lib/dexie-export-import/src`

2. Add dependencies required by the addon to my package.json:
* `"clarinet": "dfahlander/clarinet"`
* `"typeson": "^5.8.2"`
* `"typeson-registry": "^1.0.0-alpha.21"`

3. Clarinet loads module `stream` dynamically if it exists. It detects module existence by wrapping the `require()` call with a try...catch block. This is not supported by Angular as all `require`s are already resolved at compile time. We use the [same workaround](https://github.com/dfahlander/Dexie.js/issues/829) Dexie uses and provide a dummy module in `src/lib/fake-stream/stream.js`:

```js
module.exports = {Stream: function(){}};
```

We need to add its path to tsconfig.json (typescript-config), so typescript will resolve the module path for `require('stream')` correctly:

```
"paths": {
  "stream": ["src/lib/fake-stream/stream"] 
}
```

**Comment by dfahlander** [comment]
Hi! I think you're right that what's missing is the possibility to peak an import file somehow and get the "header data" without the whole content.

See the suggested PR #1166

**Comment by fishbone1** [comment]
Looks good, but still has the problem that you cannot handle file issues on your own. I added a suggestion in the PR how to fix that.

**Comment by dfahlander** [comment]
The latest version on npm now has PR #1166 in it with your latest suggestion.
The [docs](https://dexie.org/docs/ExportImport/dexie-export-import) is also updated.
