### ISSUE TITLE
Version number of Indexed DB database displaying incorrectly when checking in Chrome Dev Tools

### ISSUE THREAD

**Issue by prichakraborty09** [dfahlander/Dexie.js#1174]
Using dexie.js with angular 8-
I have an indexed Db created something like this at present -
this.version(1).stores({
          PersonData: '++id,name',
          EmployerData: '++id,employername'
})
The db totally has 10 object stores as of now. Now when I check in Chrome under Dev Tools, the Version Number for the DB shows as 10(which should be 1) and Object stores shows 10(which is correct). 

To give more background, earlier I was creating the Db something like this -
this.version(1).stores({
          PersonData: '++id,name'
})
this.version(2).stores({
          EmployerData: '++id,employername'
})
.......... till this.version(10).stores({
         SalaryData : '++id,salary'
})

I realised my mistake on reading the Dexie documentation clearly and corrected it to be like how I have it now.
Is there a way that I could change the version number to reflect correctly as 1? Also, is the incorrect version number related to the fact that I didn't create the DB correctly initially. 

As I am new to Dexie and Indexed DB, any help will be really appreciated. Thanks in advance.

**Comment by dfahlander** [comment]
Dexie [multiplies version number with 10](https://dexie.org/docs/Dexie/Dexie.version()). The version number doesn't really matter as long as you increment it for your upcoming versions.

If you haven't published your app yet, you can always delete the database using "applications" tab in devtools and use version 1 again in the source code. If you've published your app you probably need to accept the version number that is out there. See [Database Versioning](https://dexie.org/docs/Tutorial/Design#database-versioning).

**Comment by prichakraborty09** [comment]
Thank you, David for your quick response. As I have already published the application, I guess I have to make do with it.
