### ISSUE TITLE
The compatibility of dexie in IE9 and ie10

### ISSUE THREAD

**Issue by YangQingRui** [dfahlander/Dexie.js#1178]
![image](https://user-images.githubusercontent.com/23182326/100170629-10e75180-2f01-11eb-90ae-e22e40e908d6.png)
Hello, author
As shown in the figure__ proto__ Attribute has compatibility problem in IE9 and ie10. Can you change it to Object.getPrototypeOf (xx)

**Comment by dfahlander** [comment]
Is someone using IE9-10? Anyway, Object.getPrototypeOf() is more standard and it's an easy fix. Thanks for reporting!
