### ISSUE TITLE
Issue with new indexeddbshim.js and dexie

### ISSUE THREAD

**Issue by isaacbdawson** [dfahlander/Dexie.js#118]
The most obvious thing is they changed the case from IndexedDBShim.js to indexeddbshim.js.
Which means any previous auto fetch stuff is not going to work (I believe it is auto pulled if not found in some of your samples).

More importantly for me it just seems to not work with Dexie.
I get the "make sure to included indexedDB polyfill" error.

I had not updated indexeddbshim since March and it seems from just a cursory look they drastically altered it.

It is also almost twice as big (76kb -> 129kb).

**Comment by dfahlander** [comment]
Thanks a lot.

I've actually noticed this before and updated the unit test framework to pull the correct URL but missed out one of the sample pages that also preloads the polyfill if needed.

Notice that Dexie.js in itself will never auto-fetch this polyfill though. It is up to the lib user to prefetch it.

**Comment by isaacbdawson** [comment]
So the prefetch was not my issue, I just wanted to make note of it, which may have been confusing.
The issue is I am loading the new indexeddbshim.js (not auto fetch) before Dexie and Dexie is acting like it is not there giving me the "make sure to include indexeddb polyfill" error.
