### ISSUE TITLE
DBCore middlewares not working as expected

### ISSUE THREAD

**Issue by LFFATE** [dfahlander/Dexie.js#1180]
> DBCore is a middleware-approach for Dexie that is superior to the hooks API
https://dexie.org/docs/Dexie/Dexie.use()#example

I can't use hooks API because of async functions to be applied for dexie results

DBCore has several middlewares: get, getMany, query... So I think I can use it instead of reading hook. 
But I can't make these middlewares works. 
For example, collection.toArray someway prevents these middlewares from firing:

```
const categories = await Database.categories.filter(...).toArray()
const products = await Database.products.where('id').anyOf(productsIds).toArray()
```
No one of this middlewares works. 

But this works well:
```
Database.products.get(key) // will fire DBCoreTable.get 
Database.products.get({ slug: key }) // will fire DBCoreTable.query 
```

Is it known issue? Or may be I'm doing wrong? Should I make a repro? 

General purpose is map dexie results to class factory function, which is async 

```
"dexie": "^3.0.3",
"fake-indexeddb": "^3.1.2",
"jest": "^26.6.3",
```

**Comment by dfahlander** [comment]
To catch all read-queries you must implement all functons in the [DBCoreTable interface](https://dexie.org/docs/DBCore/DBCoreTable) except mutate:

   get(req: [IDBCoreGetRequest](https://dexie.org/docs/DBCore/DBCoreGetRequest)),
   getMany(req: [DBCoreGetManyRequest](https://dexie.org/docs/DBCore/DBCoreGetManyRequest)),
   query(req: [DBCoreQueryRequest](https://dexie.org/docs/DBCore/DBCoreQueryRequest)),
   openCursor(req: [DBCoreOpenCursorRequest](https://dexie.org/docs/DBCore/DBCoreOpenCursorRequest)),
   count(req: [DBCoreCountRequest](https://dexie.org/docs/DBCore/DBCoreCountRequest))

openCursor() returns a [DBCoreCursor](https://dexie.org/docs/DBCore/DBCoreCursor).
You can create a proxy cursor from your overridden openCursor() as is being done in [virtual-index-middleware.ts](https://github.com/dfahlander/Dexie.js/blob/master/src/dbcore/virtual-index-middleware.ts#L131-L165). Notice some things here:

1. The async result of openCursor() will be null if no items were found. So your middleware must also return null if so.
2. All methods in the cursor are bound so it is safe to return a prototype-derived instance of the cursor and override properties and methods using Object.create().

If your aim is to map value results you would only need to override get, getMany, query and openCursor. As your mapping function is async, your proxy cursor may need to resolve the initial value prior to resolving the promise, as the getter of value is not async. It will also need to override start() to prefetch value using your async mapper:

```js
const myDBCoreTable = {
  ...table,
  get: req => table.get(req).then(myAsyncMapper),

  getMany: req => table.getMany(req)
    .then(res => Promise.all(res.map(myAsyncMapper))),

  query: req => table.query(req).then(res => {
    const result = Promise.all(res.result.map(myAsyncMapper));
    return { result };
  }),

  openCursor: req => table.openCursor(req)
    .then(cursor => {
      if (!cursor) return cursor; // cursor is null
      return myAsyncMapper(cursor.value).then(value => {
        return Object.create(cursor, {
          value: {
            get: () => value
          },
          start (onNext) {
            return cursor.start(onNativeNext => {
              myAsyncMapper(cursor.value)
                .then(val => {
                  value = val;
                  onNext(val);
                }).catch(error => cursor.fail(error));
            });
          }
        }
      });
    }
  });
}
```
I've just dry-coded this so it may contain syntax errors or bugs, but please try it and tell me if this works for you. I will need to update the docs with such a sample and it would be nice to have one that has been tested so your feedback is valuable!

**Comment by dfahlander** [comment]
Note: I've updated the code snippet since first reply. Still dry-coded so please verify.

**Comment by LFFATE** [comment]
@dfahlander great! All tests are passed now. Thank you. It was not obvious for me to use a custom cursor, and at query I had wrong implementation, so your example was really helpful. Tested also at browser and there is no problems at this moment

**Comment by dfahlander** [comment]
Ok great! Can I use my code snippet as it is in the docs or was it anything that you had to write differently?

**Comment by LFFATE** [comment]
Yes, but I combined your example with the one from docs. From here https://dexie.org/docs/Dexie/Dexie.use()#example
So I don't think it may cause any problems.

**Comment by LFFATE** [comment]
@dfahlander Hi again! Found a problem with IDBCursorWithValue
Here is a fast repro https://codesandbox.io/s/mystifying-sun-xwjhi?file=/src/App.js

Jest and fake-indexeddb doesn't show this error, so I missed it last time

I think there is problem with cloning IDBCursor, maybe types of `cursor.start` doesn't met. I'm trying to find out.

**Comment by LFFATE** [comment]
I see two options: 

add key property to new cursor (copy from original cursor):
```
      key: {
        value: cursor.value,
      },
```
so it will be:
```
function createCursor(cursor) {
  return myAsyncMapper(cursor.value).then((value) => {
    return Object.create(cursor, {
      value: {
        get: () => value,
      },
      key: {
        value: cursor.value,
      },
      start: {
        value: (onNext) => cursor.start(() =>
          myAsyncMapper(cursor.value).then((val) => {
            value = val;
            onNext();
          }).catch((error) => {
            cursor.fail(error);
          })
        )
      },
    });
  });
}
```

or copy all data from original cursor:
```
function createCursor(cursor) {
  const newCursorData = myAsyncMapper(cursor.value).then((value) => {
    return Object.create(cursor, {
      value: {
        get: () => value,
      },
      start: {
        value: (onNext) => cursor.start(() =>
          myAsyncMapper(cursor.value).then((val) => {
            value = val;
            onNext();
          }).catch((error) => {
            cursor.fail(error);
          })
        )
      },
    });
  });

  return Object.assign(cursor, newCursorData)
}
```

**Comment by dfahlander** [comment]
In my [comment on november 29](#issuecomment-735304268) i missed to define the `key` and `primaryKey` properties. They are needed to apply the correct this-pointer for the cursor. I just now updated that comment to correct this.

It's not very obvious nor documented (will fix that), but the methods on the cursor like start(), stop(), continue(), continuePrimaryKey() etc are already bound on the lowest-level implementation of the cursor, while the readonly properties key, primaryKey and value are not.

It's not possible to clone the cursor as it is mutable object so the simplest way of creating a proxy cursor is still by using Object.create() and override props and methods accordingly. Just keep in mind that the three readonly properties `key`, `primaryKey` and `value`, will always have to be overridden.

**Comment by LFFATE** [comment]
Hello again!
I found a new problem due to my app has grown. 
So just for readers may be helpful:

The error: 
`Unhandled rejection: TransactionInactiveError: Failed to execute 'continue' on 'IDBCursor': The transaction is not active.`

So it looks like `onNext();` calls after transaction is closed. I think it is not critical when a promise not takes so long time. Therefore the best way I found to handle it - is use `Dexie.waitFor` (https://dexie.org/docs/Dexie/Dexie.waitFor()) 

My quick code: 
```TS
async function createCursor(cursor: DBCoreCursor, tableName: string, hooks: DatabaseHooks): Promise<DBCoreCursor> {

  const hookFunction = <T = any>(data: T) => hooks.transform(tableName, data)
  let cursorValue = await Dexie.waitFor(hookFunction(cursor.value))

  return Object.create(cursor, {
    value: {
      get: () => cursorValue,
    },
    key: { get: () => cursor.key },
    primaryKey: { get: () => cursor.primaryKey },
    start: {
      value: (onNext: () => void) => {

        return cursor.start(async () => {
          try {
            const localCursorValue = await Dexie.waitFor(hookFunction(cursor.value))
            cursorValue = localCursorValue
            onNext()
          } catch(error) {
            console.log('Fails here')
            cursor.fail(error)
          }
        })
      },
    },
  })
}
```

May be I should also rewrite all `hookFunction` calls (inside toArray, get, getMany and etc.), but It still works as is
