### ISSUE TITLE
dexie + indexeddbshim + safari issue

### ISSUE THREAD

**Issue by isaacbdawson** [dfahlander/Dexie.js#119]
So I am using the latest dexie and indexeddbshim with safari and it appears indexeddbshim is creating websql databases instead of indexeddb, but to my understanding that should be ok?

The tables do get created (I can see them in web inspector).

However on the dexie add I get "undefined is not an object (evaluating 'types[getType(key)].encode') followed by "[object SQLError]".

I am unclear as to whether this is a dexie issue or an indexeddbshim issue.

**Comment by dfahlander** [comment]
Please provide a code snippet that fails. Preferably one that is easy to run, such as a jsfiddle, full html page or similar.

**Comment by isaacbdawson** [comment]
Figured it out.
Happens when an indexed field is null.
So if in your db.version.stores you have a table with ++id,name,city,state and the data to add a record has the city as null, you get that error.

**Comment by dfahlander** [comment]
Ok, that's something that should not fail with indexedDB, so it's an issue the indexedDbShim.
Thanks for sharing.

**Comment by isaacbdawson** [comment]
Just an FYI, it has been reported to the indexeddbshim guys and after reviewing they have opened an issue to look at fixing it.
