### ISSUE TITLE
How can i get modifications in DBCorePutRequest which exist in updating hook ? 

### ISSUE THREAD

**Issue by zta7** [dfahlander/Dexie.js#1190]

**Comment by dfahlander** [comment]
You need to compute them by first calling next DBCoreTable.getMany({trans, keys}) to inspect what is currently on the given keys. You could have a look at how the CRUD hooks middleware does it in [hooks-middleware.ts](https://github.com/dfahlander/Dexie.js/blob/master/src/hooks/hooks-middleware.ts).

DBCore API is a bit more verbose than the CRUD hooks but you also gain more control operations and you are able to things that is not possible using the hooks.

Note however that the hooks will continue to be maintained so if you're fine with them, keep using them. In a future major release, the hooks middleware may be moved into a helper library, but my promise is to keep it maintained no matter if they are put in a helper library or in the core library.
