### ISSUE TITLE
Update with array as value adds number objects

### ISSUE THREAD

**Issue by Christilut** [dfahlander/Dexie.js#1195]
I might be completely missing something but this is odd behavior to me:
```
const field = 'authors'

  await db.books.update(id, {
     [field]: [{ foo: 'bar' }, { foo2: 'bar2'} ]
   })
```

This ends up with `authors.0` and `authors.1` but it should just be an array.
What's going on here?

**Comment by dfahlander** [comment]
Tried to reproduce in https://jsitor.com/DGNaFfv5S but it seems to behave as it should.

```js
const db = new Dexie("bubbu");
db.version(1).stores({
  books: 'id'
});

Promise.resolve().then(async ()=>{
  await db.books.put({id: 1});
  console.log (JSON.stringify(await db.books.get(1)));
  const field = 'authors'
  await db.books.update(1, {
    [field]: [{ foo: 'bar' }, { foo2: 'bar2' }]
  });
  console.log(JSON.stringify(await db.books.get(1)));
}).catch(console.error);
```

Output:
```
{"id":1}
{"id":1,"authors":[{"foo":"bar"},{"foo2":"bar2"}]}
```

**Comment by Christilut** [comment]
Thanks for confirming that's not it. I figured out it came from the updating hook: https://jsitor.com/32Nht9kOY

The modifications are saved to the cache as `authors.0` etc. It is saved to the database like normal arrays so a cache clear fixes it.
Is this normal in the modifications object though?

**Comment by dfahlander** [comment]
Ok! The array is somehow interpreted as an object. I will investigate this. There was a similar issue and PR recently #1130. I also notice that the behavior between using dexie 2.x and 3.x.
