### ISSUE TITLE
Dexie 3.1 liveQuery of Entire Table

### ISSUE THREAD

**Issue by cliftonlabrum** [dfahlander/Dexie.js#1198]
I have been using dexie-observable to watch any change to an entire table (based only on the table name) like this:
```
db.on('changes', changes => {
  for(let change of changes){
    console.log(change.table+' just changed!')
  }
})
```
Is something like that possible with `liveQuery` in version 3.1? If not, please consider this a feature request. 🙂 

Thanks!

**Comment by dfahlander** [comment]
Currently in Dexie 3.1.0-alpha.5, you can listen to txcommitted event:

```js
Dexie.on('txcommitted', changes => {
  for(let part of Object.keys(changes)) {
    console.log(part + ' just changed!');
  }
});
```
Output:
```
idb://myDatabase/myTable/myIndex just changed
```

The API is not stable though - the event might be renamed, but this is how you can do it in latest alpha version:
```
Dexie.on('txcommitted', changes => {
  for(let part of Object.keys(changes)) {
    console.log(part.split('/')[3] + ' just changed!');
  }
});
```
New output:
```
myTable just changed
```

**Comment by cliftonlabrum** [comment]
Excellent, thank you!

**Comment by cliftonlabrum** [comment]
@dfahlander By the way, I think you can enable **Discussions** on repositories now. That might be a good alternative to opening an issue for questions like this. 🙂

**Comment by dfahlander** [comment]
I'm ok with using issues as questions. It's become a good knowledge base
that serve many with questions already answered. Know to little about
Discussions so far but maybe they could be something also.

Den tors 17 dec. 2020 19:22Clifton Labrum <notifications@github.com> skrev:
