### ISSUE TITLE
New tables added to Indexed db using dexie not getting reflected

### ISSUE THREAD

**Issue by prichakraborty09** [dfahlander/Dexie.js#1199]
Hi, 
As of last week I had created tables in my Indexed db like this -
this.version(1).stores({
          Person1Data: '++id,personName'
         Person2Data: '++id,personName'
         Person3Data: '++id,personName'
        });
This was the same that was released to the QA instance last week and so then the QA Indexed db instance for me had these 3 tables which is correct.

As of yesterday I modified my Indexed db like this -
this.version(1).stores({
          Person1Data: '++id,personName'
         Person2Data: '++id,personName'
         Person3Data: '++id,personName',
        Person4Data: '++id,personName',
        Person5Data: '++id,personName',
        });
After that this was released to QA again yesterday and when I checked, the QA Indexed db instance still had 3 tables instead of 5 tables. Thinking that it was a cache issue, I cleared my cache and then when I logged in to QA instance, the Indexed db started showing 5 tables.

However, two other people from my team tried to fix the same issue in QA by clearing cache but for them there were still 3 tables, instead of 5 tables. For one person, clearing the %temp data%  solved the issue and for the other deleting the indexed database and then going to QA instance again(database got created newly with 5 tables) solved the issue and they both were finally able to see the 5 tables.

Now, coming to my actual question - 
I am unable to join the dots between these solutions and find the actual cause of the issue. Is it because of cache that the two new tables weren't getting created or we cannot add new tables to a database version that has been released(deleting the database and allowing the database to create again adds the new tables though).

It will be really helpful if someone can provide me some direction so that if there is any issue in my code or my concept, I can rectify it. Thank you in advance.

**Comment by rianonehub** [comment]
Hi @prichakraborty09 

I think you must increment your db version number, it will update the your db schema automatically.

please see this doc for further info
https://dexie.org/docs/Tutorial/Design#database-versioning

**Comment by prichakraborty09** [comment]
Thank you @rianonehub. I went through the documentation, so what's clear to me is that one cannot add tables to an existing version if it has been published. If we do need to add tables to an existing version, we would have to delete the indexed db and allow it to re-create again.
