### ISSUE TITLE
Mention how Dexie.js can be used on Node.js

### ISSUE THREAD

**Issue by rauschma** [dfahlander/Dexie.js#12]
It’s probably not as frequent a use case as running it on browsers, but it would be nice if Dexie.js was truly cross-platform.

**Comment by langri-sha** [comment]
I'm sorry for being the necromancer :skull:, but has anyone had any luck finding something compatible which Dexie.js can use to run in Node.js?

In case anyone is also trying to shim support, I would recommend that you review your use of Dexie.js' advanced schema features.

**Comment by dfahlander** [comment]
Just for the record,  current npm release (1.3.3) has an error when trying to run in node (self is undefined) which is fixed for next release.
