### ISSUE TITLE
Problem with matching words with german umlauts using WhereClause.anyOfIgnoreCase()

### ISSUE THREAD

**Issue by Rick978** [dfahlander/Dexie.js#1203]
Hello, 

if using anyOfIgnoreCase() to match a word with german umlauts like "ä", the matching does not work.

Init of Dexie:
`var db = new Dexie('questions');
db.version(1).stores({
  lastIndex: '[category+date+part], date, category, part',
});`

The following test data were added to Dexie.add({..}):
`{
        "lastIndex": 0,
        "lastIndexAction": "2020-12-23T19:12:09.615Z",
        "category": "schießen und schießstätten",
        "date": "2018-07-13",
        "part": 0
    },`

If I try to match with _schießstätten_ it doesnt match.
`await db.lastIndex
      .where('category')
      .anyOfIgnoreCase("schießstätten")
      .modify((lastIndex) => lastIndex.lastIndex = 20);`
If I try to match with _schießen_ it does match great and the value of lastIndex changed successfull to 20.
`await db.lastIndex
      .where('category')
      .anyOfIgnoreCase("schießen")
      .modify((lastIndex) => lastIndex.lastIndex = 20);`

Ressource: https://dexie.org/docs/WhereClause/WhereClause.anyOfIgnoreCase()

I´am using the latest Dexie 3.0.3. Thanks for your help!

**Comment by dfahlander** [comment]
The case-ignore operators does only support case insensitivity of english letters a-z/A-Z. I've updated the docs just now to make this clearer. Another alternative to case insensitive search is to double-store these strings in lowercase and index the toLocaleLowerCase() version only and use the plain anyOf() operator with searchString.toLocaleLowerCase(). That's an alternate way to accomplish case insensitive search in IndexedDB. The downside is more storage size, but there are other upsides with it except for local case comparision, also more performant read queries.

**Comment by Rick978** [comment]
Thanks a lot for your answer and updating of docs. 
I´am just a beginner in web development, but i enjoy your Dexie.js very much! Thanks a lot for this great libary!!!

Best wishes 
Rick
