### ISSUE TITLE
Problem storing data on column with name "description"

### ISSUE THREAD

**Issue by lucasmoyano** [dfahlander/Dexie.js#1206]
Hi everyone,

I found this issue today. When I try to store data on a column "description", it doesn't work. But if I use any other column name it work's correctly (ex: "descriptionx"):
```
var database = new Dexie("webapp");
database.version(3).stores({
  "appointment": "id,firstname,lastname,phone,email,start,end,description"
});
database.open();
database["appointment"].put({
                        id: "123",
                        firstname: "lucas",
                        lastname: "moy",
                        description: "descripcion",
                        phone: "234234234",
                        email: "test@gmail.com",
                        start: moment().format('YYYY-MM-DD'),
                        end: moment().format('YYYY-MM-DD')
                    });
```

I really like Dexie. Good job guys 👍

**Comment by dfahlander** [comment]
This really surprise me since there's no such built in limitation. Please put your repro into a codesandbox or jsfiddle or similar and paste it's link into this issue. If you're still able to reproduce the issue, i will easily find what it could be.

**Comment by lucasmoyano** [comment]
Sorry David, it was my mistake. It works fine, I'll be more careful before reporting a bug. Have a nice day.
