### ISSUE TITLE
404 - https://dexie.org/docs/Observable/Transaction

### ISSUE THREAD

**Issue by MarMun** [dfahlander/Dexie.js#1219]
`https://dexie.org/docs/Observable/Transaction`
Gives me a 404 'Page not found' error.

I try to navigate to it from
`https://dexie.org/docs/Observable/Dexie.Observable.DatabaseChange`

> (Optional) Source of the modification. If the ´source´ property of the **Transaction** object ...

(I'm coding a electron multi window app and love that 'Dexie.Observable' exists. Last thing I need to implement is the transaction `source` property so an instance doesn't react to db changes made by itself...)

**Comment by dfahlander** [comment]
I've updated the docs of [DatabaseChange](https://dexie.org/docs/Observable/Dexie.Observable.DatabaseChange) to link correctly. However, the ´source´ property of the transaction is added by Dexie.Observable and is not documented on the link being referred to.

**Comment by MarMun** [comment]
Thx a lot for your help! I close this issue as the link is fixed.

The `source` property in all DatabaseChanges is always `null` for me. I open a new issue if can't figure this out on my own...
