### ISSUE TITLE
Webpack throws an error saying define cannot be used indirect

### ISSUE THREAD

**Issue by filipmares** [dfahlander/Dexie.js#122]
Dexie can't be references properly when building with webpack.

This issue was discussed here:
https://github.com/webpack/webpack/issues/138#issuecomment-105724313

**Comment by aaron-schmidt** [comment]
Can you provide what version of webpack and what version of Dexie you are using? Have you tried using the latest beta version of webpack?

**Comment by filipmares** [comment]
I'm using 
webpack: 1.0.11
dexie: 1.1.0

I haven't tried the beta.

**Comment by tonytamps** [comment]
@filipmares I commented on a workaround I used here:
https://github.com/webpack/webpack/issues/138#issuecomment-136567503

**Comment by filipmares** [comment]
@tonytamps thanks! ended up sound the same thing eventually.
