### ISSUE TITLE
add index Compound and MultiEntry

### ISSUE THREAD

**Issue by felek000** [dfahlander/Dexie.js#1221]
Hello I want to create indexes like so:
```
const fileSchema = {
  files:
    "id,category,status,statusLocal,[category+status+statusLocal],[status+statusLocal],*groups",
};
db.version(process.env.DB_VERSION).stores({
  ...fileSchema,
.....
});

saving data example
{
category: 1
descryption: undefined
fileType: "jpg"
groups: [5,10]
hash: "e336d229d86c87eeed2b838de8ddba20"
ico: ArrayBuffer(46457) {}
icoMimeType: "image/jpeg"
id: 33
mimeType: "image/jpeg"
publicationDate: "2020-11-19"
publicationDateTimeStamp: "2020-11-19"
status: 2
statusLocal: "new"
title: "test"
titleSanitized: "test "
updatedAt: "2021-01-12"
updatedAtTimeStamp: 1610435160
url: "url"
}
await db.files.put(dataToSave, id);
```

I see in db view proper Compound  however in MultiEntry i can see only one always. Screenshot
![image](https://user-images.githubusercontent.com/4018838/106871243-53cc5f00-66d2-11eb-8a9a-bf9a940b6b93.png)

Is my impleentation is wrong or just mix Compound  and MultiEntry is not possible ?

**Comment by dfahlander** [comment]
No it's totally ok to mix different kind of indices in same Table / ObjectStore as you are doing. What's not possible is to have a multiEntry index as a part of a compound index which is not the case here.

What you are seeing the the screenshot is that entities with ID 2,3,5,7,8 and 9 have `1` in their groups array. They might have several others as well but you'd only see them if you scroll down to those corresponding keys and look in the Primary Key column you'll see a repeated primary key there.

**Comment by felek000** [comment]
Thanks for answer.
Now I want to crate filter and for now i have like so:

```
  return await db.files
    .where(where)
    .anyOf(anyOf)
    .and(_filterGroups)
    .and(_searchByTitle)
    .toArray();
```


anyOf and where i result of function depends on selected elements:

```
  const where = function _getWhereClosure(filters) {
    const { category } = filters;
    if (category === "all") {
      return "[status+statusLocal]";
    } else if (typeof category === "number") {
      return "[category+status+statusLocal]";
    }
  }

  const anyOf = function _getAnyOfClosure(filters) {
    const { category, statusLocal } = filters;
    if (category === "all") {
      switch (statusLocal.value) {
        case "all":
          return [
            [statusAPI, statusLocalNew],
            [statusAPI, statusLocalOld],
          ];
        case "new":
          return [[statusAPI, "new"]];
      }
    } else if (typeof category === "number") {
      switch (statusLocal.value) {
        case "all":
          return [
            [category, statusAPI, statusLocalNew],
            [category, statusAPI, statusLocalOld],
          ];
        case "new":
          return [[category, statusAPI, "new"]];
      }
    }
  }
//example result
//files = await db.files.where("[status+statusLocal]").anyOf([
  //   [2, "old"],
  //   [2, "new"],
  // ]);
```
and since i cant have next where i narrow down elements by and add `and` where i search for by group and then by title.
Is it possible to mix also group in this  where part. Group is array of ids example [1,5,7,9]. And after that do full text search on results ?

**Comment by dfahlander** [comment]
No, and it would over-use the indexes. Use an index that would narrow the results the most. Filter the rest "manually" using .and()/.filter() etc.

**Comment by felek000** [comment]
OK so i leave as it is. Thank You.
