### ISSUE TITLE
LiveQuery Issues when using with .put or .bulkPut

### ISSUE THREAD

**Issue by yulolimum** [dfahlander/Dexie.js#1225]
Hello! First of all, awesome lib and implementation. 

I have looked through most GH issues and documentation but couldn't find a related report.

### Problem:
I have been using `useLiveQuery` and in some places `liveQuery` in my React project and have been noticing that sometimes the observed data does not get returned in the subscriber. I have been tracking this by logging the `liveQuery()`'s  `subscribe()`'s `nextValue` (in the  first arg callback). I have narrowed it down to: when a an operation is performed using the `.put` or `.bulkPut` on a table that is being observed, it completely breaks with very weird inconsistencies. 

I have cloned the `useLiveQuery` CodeSandbox and updated the `.add` to a `.put`: https://codesandbox.io/s/nifty-rhodes-yj8om?file=/src/components/AddFriend.tsx:225-253

### Observations:
- Data actually get's added to IndexedDB. This is inline with the documentation:
 > Adds new or replaces existing object in the object store.
 
 - The `liveQuery` with the `.count()` method works as expected. The count increases reliably. 
 
 - The `liveQuery` for retrieving friends of a certain age fails. This is inconsistent at best but mostly does not update the dataset.

- Forcing a "resubscribe" by updating `useLiveQuery`'s dependencies (`maxAge` in this case), retrieves the correct data. This is as expected as per the `useLiveQuery`'s implementation. 

- When observing a table without a `WhereClause` (e.g. `db.friends.toArray()`) - this works as expected. Any "puts" are reflected in the `liveQuery`.

### Questions:
- Should `.put` and `.bulkPut` affect the `liveQuery`?

**Comment by dfahlander** [comment]
Thanks a lot for the repro. I'll look into this asap. Yes, put/bulkPut  must work the same as any other mutating operation and be reflected correctly.

**Comment by dfahlander** [comment]
Final solution was [this commit](https://github.com/dfahlander/Dexie.js/commit/19d2546e019904839ce356e7b245898a56c7bf60 ) and not [this one](https://github.com/dfahlander/Dexie.js/commit/cd12140bf58802c902e1ea803dfc4ef0da81c19c).

**Comment by dfahlander** [comment]
This fork of your sandbox with an update of dexie to the newly released 3.1.0-alpha.7: https://codesandbox.io/s/hardcore-shtern-gc8xn confirms the fix.

**Comment by yulolimum** [comment]
Hello, @dfahlander!

Thanks a lot for the quick turn-around - you're awesome!

I updated the dependencies on my project and the issue seems to persist. Initially, I thought it might be something else (not related to Dexie), but then I decided to create a barebones reproduction. You can see it here: https://codesandbox.io/s/recursing-http-hnugs?file=/src/App.tsx

I also created a screen-recording describing the issue in the sandbox if you'd like to take a look: https://cln.sh/ooLrl8

But here's a Too Long Didn't Watch :) :

- When observing the entire table (e.g. `db.colors.toArray()` or `db.colors.toCollection().sortBy("name")`) - works as expected with any operation.

- When observing using a `WhereClause` and bulk adding/putting `<= 49` items - works as expected.

- When observing using a `WhereClause` add adding/putting `>=50` items - nothing is reflected in the `liveQuery` result.

- When observing using a `WhereClause` and first adding/putting  `<= 49` items then adding any number of items - works as expected.

I also was able to confirm the  "magic number" `50` on my project. Limiting data to `49` items does the trick. 

Note, I didn't test `.bulkDelete` but it seems to me that this issue only happens with data that's "to be added".

**Comment by dfahlander** [comment]
Oh, I see, thanks a lot. Need to complement my unit test with >=50 bulk operations as it goes into another code path to trigger a more generic update. I'll look into it asap

**Comment by dfahlander** [comment]
Thanks for taking your time to do the recording and the repro 💯 

I found the reason for the baviour (See https://github.com/dfahlander/Dexie.js/commit/02f89778b14e01148c91ce1c310311d751855bc3) and there's now a new alpha release with the fix.

Here's your repro with 3.1.0-alpha.8: https://codesandbox.io/s/ancient-dawn-pp7lu

**Comment by yulolimum** [comment]
@dfahlander This is great! I just confirmed this fix on my project with a `.pulkPut` of ~5000 items with 6 indexed keys. 

👍🏻 

I'm just curious though. Why was the number at which the bug occurred `50`? I read through the explanation for the fix but I still don't understand why that's the threshold.. Is it some kind of an optimization built into IndexedDB itself? Or `Observable`? No need to reply if busy, i'm just trying to educate myself.

**Comment by dfahlander** [comment]
No it's a threshold I'm using to not slow down large bulk operations. 50 is an arbritary number but it doesn't really make sense to "strain at a gnat and swallow a camel" the more number of bulk operations that goes into a mutation. The effect of this alternate strategy for >= 50 operations is that any query to the same table will re-execute instead of going through all the operations and computing the exact ranges on each index that would be affected. The chance is that after that large bulk operation, most of the outstanding queries on same table will be affected anyway. And the worst case scenario is just some unnescessary extra read queries compared to an always-on slowing down of large bulk inserts. A common use case is some kind of initial sync where you download a large dataset and do bulkAdd / bulkPut with it. That use case will still be as fast as before with this strategy and the outstanding queries will work, even though they might all re-execute once the write-transaction completes.

**Comment by yulolimum** [comment]
Thank you for the explanation - what a great answer! The example with multiple queries inside the hook actually helps me optimize further since I have multiple liveQueries for different data.  One last followup:

Does a `transaction` (as described in the docs) optimize the liveQuery in anyway? Take this scenario:

- API request to get 1st batch of data - bulkPut happens
- API request to get 2nd batch of data - bulkPut happens
- I take the diff of old data and new data and delete old items - bulkDelete happens
- All of this happens in immediate succession.

So, 3 operations from my perspective as a Dexie user which in effect causes the liveQuery to emit 5 results (this includes the initial 2 results - blank array and first data set pre-operations described above). 

If I were to wrap the bulk operations in a `transaction`, would the liveQuery emit only 3 times? Or is a `transaction` essentially just a mechanism to prevent all operations if one fails?

**Comment by dfahlander** [comment]
Yes, liveQueries will only re-execute after committed transactions, so if you do all in a single transaction, you will get notified fewer times. What could complicate it would be if that would require you to keep a lot of data in memory as you cannot wait for a fetch to complete within an indexedDB transaction so you would have to download all first and then to the transaction from data in memory. Depending on the dataset size this could be a problem on small devices. If so, you could also keep a react state while you are downloading data to prevent the liveQueries from being executed until all data is downloaded. You could even split the bulks into chunks in several separate transactions to save RAM during the download phase.

**Comment by yulolimum** [comment]
Thanks a lot for your help. This clarifies a lot of things for me. I'm working with operations on datasets of ~3000 items per table. So any bit of optimization helps and `transactions` seems like the correct direction. RAM isn't going to be an issue, more of a inevitable consequence. I'm rebuilding my project from holding large datasets in Mobx-State-Tree (also relies on Observables) which holds **everything** in memory by default - just the move towards IndexedDB sped up my app 10x.

**Comment by Jala015** [comment]
Just to keep here to help others with similar problems:
I had a similar issue with .put and apparently it was related to using 0 as an unique id value

**Comment by Semanual** [comment]
Just happened with me too this problem with using 0 as id, but with .update
If this is an API limitation it should be documented at [useLiveQuery page](https://dexie.org/docs/dexie-react-hooks/useLiveQuery()), don't you agree? @dfahlander

**Comment by dfahlander** [comment]
> Just to keep here to help others with similar problems: I had a similar issue with .put and apparently it was related to using 0 as an unique id value

> Just happened with me too this problem with using 0 as id, but with .update If this is an API limitation it should be documented at [useLiveQuery page](https://dexie.org/docs/dexie-react-hooks/useLiveQuery()), don't you agree? @dfahlander

Please file a new ticket. I'll be locking down this one.
