### ISSUE TITLE
Storage of blobs fails on iOS 14.5 beta

### ISSUE THREAD

**Issue by danielwestendorf** [dfahlander/Dexie.js#1227]
As a precaution I always test my app on the iOS betas to get ahead of any bugs. I've discovered a problem with persisting records with `Blob` attributes on a **physical** device running iOS 14.5 (18E5140k).

I've been able to reproduce this test script: https://gist.github.com/danielwestendorf/86de79fc5e11853883ccae22e543234a

I get the error: 
> Ooops: UnknownError: Error preparing Blob/File data to be stored in object store
 UnknownError: Error preparing Blob/File data to be stored in object store

![image](https://user-images.githubusercontent.com/44478/107438302-8240a480-6aed-11eb-92d2-ced059f48b45.png)

![image](https://user-images.githubusercontent.com/44478/107438447-b61bca00-6aed-11eb-9978-967759279d0e.png)

I've also reproduced the same action without Dexie using the IndexedDB APIs without any errors, leading me to believe this is a problem with Dexie.

I am not able to reproduce the problem on iOS 14.4, in desktop Safari, or Safari Technology Preview. To make things even more difficult, I'm not able to reproduce this error in an iOS simulator running the 14.5 beta. Persistence of data without `blob` attributes works fine.

This may just be a problem with the beta, or it may be a larger underlying problem. How can I debug further?

**Comment by danielwestendorf** [comment]
Additionally, since this business critical for my app, I'd be happy to sponsor help debugging or a fix for this.

**Comment by dfahlander** [comment]
That message text seems not to come from Dexie but from the Safari (webkit) browser. It seems LocalForage had been having the same issue and there's a bug tracked in webkit for it:

https://bugs.webkit.org/show_bug.cgi?id=188438

https://github.com/localForage/localForage/issues/834

**Comment by danielwestendorf** [comment]
I've left a comment on the webkit bug.

**Comment by danielwestendorf** [comment]
This is resolved with iOS 14.5 Beta 2 (18E5154f)
