### ISSUE TITLE
Dexie is unable to save the object that was Proxy by Vue3

### ISSUE THREAD

**Issue by akirarika** [dfahlander/Dexie.js#1237]
Demo see: https://codepen.io/akirarika/pen/GRNOPKb

When saving the data in Vue3 directly, dexie will throw an exception.

After formatting the data in Vue3 with `JSON.parse(JSON.stringify(...))`, it can be saved normally.

I don't know if this is a bug, but allow me to thank you for creating this great library!

**Comment by dfahlander** [comment]
this.user is a Proxy in vue and IndexedDB doesnt support saving proxies due to the spec of structured cloning.

**Comment by mcshaz** [comment]
Just to add for anyone who stumbles across here - you can also keep a reference to the original object wrapped by the proxy and save that (it will be updated - it is simply wrapped in the proxy):
```javascript
const id = 3
const db = new MyDexieDb()
const underlyingEntity = db.tableFoo.get(id)
if (!underlyingEntity) ...redirect etc...
const reactiveEntity = reactive(underlyingEntity)
const save = () => db.tableFoo.put(underlyingEntity)
```

**Comment by akshayitzme** [comment]
Just mentioning another way to fix this, 

you can use `toRaw` function exported by `vue` to convert a Proxy Object to its original form

```js
import { toRaw } from "vue";
//
await db.table(table).bulkPut(toRaw(data));
```

Reference: [toRaw](https://vuejs.org/api/reactivity-advanced.html#toraw)
