### ISSUE TITLE
stores multi table throw error Index must have a name and cannot be an empty string

### ISSUE THREAD

**Issue by lianghx-319** [dfahlander/Dexie.js#1238]
![image](https://user-images.githubusercontent.com/27187946/109258440-40299980-7835-11eb-8ec3-3474472e5c16.png)

I don't why this stores throw error

![image](https://user-images.githubusercontent.com/27187946/109258578-7d8e2700-7835-11eb-8efa-98aa33281aeb.png)

**Comment by dfahlander** [comment]
Very strange. The message should only happen if you have double comma characters in the stores spec. Could you try do a repro in https://codesandbox.io, codepen or similar?

**Comment by lianghx-319** [comment]
> Very strange. The message should only happen if you have double comma characters in the stores spec. Could you try do a repro in https://codesandbox.io, codepen or similar?

ok, I will try to make a demo today

**Comment by lianghx-319** [comment]
> Very strange. The message should only happen if you have double comma characters in the stores spec. Could you try do a repro in https://codesandbox.io, codepen or similar?

here the [codesandbox link](https://codesandbox.io/s/runtime-shadow-8dxfh?file=/src/index.ts)

**Comment by lianghx-319** [comment]
I found `id, timestamp, JSON,` last `,` cause error.

**Comment by dfahlander** [comment]
Aha now i see it ;)
