### ISSUE TITLE
Import/Export as independent package

### ISSUE THREAD

**Issue by brettz9** [dfahlander/Dexie.js#1239]
Hi David,

Hope you've been doing well!

Was just looking for a package to handle importing/exporting, and was wondering what you thought of extracting (or getting extracted) your import/export add-on into its own package (independent of Dexie though usable with it)?

Also probably nice to use `databases()` to be able to build an array of database exports and for restoration.

Also, off topic, but was wondering if you were ok with using `pnpm` over `yarn` on `typeson` and `typeson-registry` (would be nice for me to be able to save some more HD space).

**Comment by dfahlander** [comment]
Hi! I'm fine, thanks! How you too are! I'm ok if you want to extract code from dexie-export-import into a new standalone library. Thanks for asking!

pnpm was new to me. Seems to be s good thing. Please go ahead and use it. I might try it out too at some of my projects.

**Comment by brettz9** [comment]
Cool, thanks... Just fielding the possibility for now, but can let you know if I get something going.

As far as pnpm, I just might mention that if you have some very complex projects doing some funky things (like say iterating over the dependency tree to find license types), the different shape of `node_modules` tree that pnpm builds might not work in such cases. But for the many projects without such unusual tools, it works very, very nicely, and without issue, and I feel like I'm getting an upgraded laptop out of the deal! In any case, it's usually easy enough to try and see if one's tests still pass.
