### ISSUE TITLE
Firefox error: An IndexedDB transaction that was not yet complete

### ISSUE THREAD

**Issue by jefft0** [dfahlander/Dexie.js#124]
To reproduce: 
1. In the latest Firefox (version 40.0, running on OS X 10.9.5), open a JavaScript console.
2. Open this Dexie sample: https://rawgit.com/dfahlander/Dexie.js/master/samples/codeproject-article/DexieAlgorithmsSamples.html
3. Refresh the page.

Expected: No error.

Actual: The JavaScript console prints:
An IndexedDB transaction that was not yet complete has been aborted due to page navigation.

Comments: I'm also getting this transaction not complete error in my code, but I wanted to show it using your sample code.

**Comment by jefft0** [comment]
... The error also shows in Firefox 40.0 in Ubuntu 14.04 and Windows 8.1. The error does not show in Chrome. (It appears that the transaction completes in Chrome.)

**Comment by dfahlander** [comment]
Bug is issued at Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1147942
Will be fixed in version 41.

**Comment by jefft0** [comment]
Appreciate the quick reply. I'll watch for version 41.
