### ISSUE TITLE
useLiveQuery with multi-entry index

### ISSUE THREAD

**Issue by dusty-phillips** [dfahlander/Dexie.js#1240]
I think this is a bug, but it may be user error. useLiveQuery doesn't seem to update the query when I `add` a new item to the collection.

As a repro, I [forked the live query sandbox](https://codesandbox.io/s/hidden-cherry-9gmir) and changed the `age` to a multi-entry index (basically, I made age store a history of the birthdays instead of the current age).

If you load that sandbox and set the max age to 100, then add a person with an age of 21, the person will not show up in the friends list until you edit the max age to reboot the query.

If this isn't a bug, is there another way I can tell the live query to update when I add a value?

**Comment by dfahlander** [comment]
Thanks! It might well be a bug as I believe the code assumes indexed props are by value and records the array property instead of each entry when notifying changes. Must treat differently for multiEntry in observabilityMiddleware.

**Comment by dusty-phillips** [comment]
Wow, that was fast! Thanks for the fix.

Off topic, but I wanted to also say I'm super excited for dexie-cloud. :-)

**Comment by dfahlander** [comment]
I'm glad it was pretty straight forward to fix. Hope to release the fix on npm this weekend. Had the idea to get a refactoring done with that release but seems it has to wait for the next one. Glad to hear you're excited for Dexie Cloud. I'm also looking forward to releasing it.
Cheers!/D

**Comment by dfahlander** [comment]
This fix is in dexie@3.1.0-alpha.9.
