### ISSUE TITLE
Can't properly require with require.js

### ISSUE THREAD

**Issue by YuriSolovyov** [dfahlander/Dexie.js#125]
With config like:
```javascript
requirejs.config({
    paths: {
        Dexie: 'static/js/dexie.min'
    }
});
```
and then in code:
```javascript
define(['Dexie'], function(Dexie) {
// Dexie is undefined
});
```
Dexie is not published.

But patching amd-style publishing from:
```javascript
[self || window, function (name, value) { define(name, function () { return value; }); }] :
```
to
```javascript
[self || window, function (name, value) { define(function () { return value; }); }] :
```

seem to make it work.

**Comment by dfahlander** [comment]
Ok, thanks. If you create a pull request, I'll fix it. Having a baby right now so it may take some time until I'm back in full force. But I could probably handle a pull request. Kind regards,  David
