### ISSUE TITLE
[Question]: Modify Array of Objects

### ISSUE THREAD

**Issue by arjayisidro** [dfahlander/Dexie.js#1258]
Hi All,

I am new to dexie and I am having trouble to update one of my records in table.
Lets say I have this array of Objects `{
  profiles: [
    {
      id: '123456',
    },
    {
      id: '654321',
    }
  ]
}` how can i wrap this to `db.where(id).modify()`

Appreciate the help!

**Comment by dfahlander** [comment]
Please explain

**Comment by arjayisidro** [comment]
But it seems like i found a solution, I query base on index id and from modify function it will return the list of datas where I use es6 find to match the corresponding id. Will close it now. Thanks!
