### ISSUE TITLE
dexie-export-import issue

### ISSUE THREAD

**Issue by vikrend** [dfahlander/Dexie.js#1262]
I installed:
```sh
npm i --save dexie@next dexie-export-import
```
    "dexie": "^3.1.0-alpha.9",
    "dexie-export-import": "^1.0.0",

Imported:
```typescript
import Dexie from "dexie";
import "dexie-export-import";
```
But when trying to export db:
```typescript
class DBClass extends Dexie {
  friends: Dexie.Table<IFriendsTable, number>;

  constructor() {
    super("dbName");

    this.version(1).stores({
      friends: "id",
    });

    this.friends = this.table("friends");

    // fill some data
  }

}

const db = new DBClass();
const blob = (async () => db.export())();
```
I get typescript error:

    (TypeError): db.export is not a function

Created with create-react-app with typescript template.

What am I doing wrong?

**Comment by vikrend** [comment]
Gotta sleep more :)
I re-read documentation page and with `exportDB(db)` it works. Typescript complains about missing `export, import` properties on Dexie instance though.

**Comment by xp4u1** [comment]
Have you now found a way to use the export? I get the same error in TypeScript:

```
Type 'SomeDatabaseName' is missing the following properties from type 'Dexie': export, import
```

**Comment by vikrend** [comment]
@dfahlander Steps to reproduce:

1. npm i create-react-app
2. create-react-app dexie-test --template typescript
3. cd dexie-test
4. npm i --save dexie@next dexie-export-import
5. paste somewhere in App.tsx: `exportDB(new Dexie('dbName'));`
6. try to `npm run build` - it fails

**Comment by dfahlander** [comment]
Thanks! I reproduced it and it turns out the problem was that the dexie dependency need to be expressed as a peerDepencency in order to not tie dexie-export-import to a certain version.
I've published a new version of dexie-export-import where the deps should be corrected. I verified that this fixed the problem for me at least.
The new version also have your PR #1343 in it.

**Comment by sharafee** [comment]
You tell a story here for an hour. A project that can be implemented and we can see for ourselves will not be arranged
