### ISSUE TITLE
Possible to retrieve compound index, instead of whole table?

### ISSUE THREAD

**Issue by Sjoerd82** [dfahlander/Dexie.js#1267]
I have this table:

`fruit: '&fruit_id, [fruit_id+fruit_code]',`

Suppose it was a large table with lots of data on fruits, but in a scenario I only need to have all the ID's + the fruit's code.
Could I get only these two attributes somehow? Of course, I could do a fruit.toArray(), and only keep the two attributes I'm interested in, but that feels wasteful.

Ideally, I'd just get the whole compound index. Either all at once, or, if it's very very large table, via an each method perhaps.

Any thoughts?

**Comment by dfahlander** [comment]
Yes, you can use:

```js
await db.fruits.orderBy('[fruit_id+fruit_code]').keys();
```
It will return an array of the indexed keys (which is an array of [fruit, fruit_code]).

**Comment by Sjoerd82** [comment]
That works perfectly!
