### ISSUE TITLE
liveQuery not update when table become empty

### ISSUE THREAD

**Issue by chrisDupuis** [dfahlander/Dexie.js#1279]
liveQuery not update when table become empty.
do a liveQuery for a table with:  () => { return this.table.toArray(); }

Update the table add one element, => liveQuery call,
remove the element, => liveQuery not call !

**Comment by dfahlander** [comment]
Can you supply a repro? If you want to get create an easy repro, maybe fork [this one](https://codesandbox.io/embed/empty-sky-lnv0q?file=/src/components/FriendList.tsx&codemirror=1) for a start and try make it reproduce this error.

**Comment by chrisDupuis** [comment]
Ok, my fault.
Thanks.

**Comment by dfahlander** [comment]
How do you mean? Was it not a real bug?

**Comment by chrisDupuis** [comment]
No it 's working on Dexie, it s not a bug.
My code was filtering empty result.
When I try to reproduce with codesandbox, I go back to my code and found the problem.

**Comment by dfahlander** [comment]
Perfect! Thanks for explaining.
