### ISSUE TITLE
Missing Index Error When the Index Isn't Missing - 3.1.0 Alpha 9

### ISSUE THREAD

**Issue by cliftonlabrum** [dfahlander/Dexie.js#1285]
I'm using Dexie `3.1.0-alpha.9` and am getting a missing index error:
```
KeyPath [workspace+project+completed+section+trashed+archived] on object store tasks is not indexed
```
...but I'm staring right at it (my other tables and indices are hidden, and I added line breaks for readability).
```
import 'dexie-observable'
import Dexie, { liveQuery } from 'dexie'

let db = new Dexie('Avid')

db.version(1).stores({
  tasks: '
    recordName, 
    name, 
    notesPlain, 
    [workspace+project+completed+section+trashed+archived], //<-- Right Here
    [workspace+project+completed+trashed+archived], 
    [workspace+project+completed+section+trashed+archived+phase], 
    [workspace+assignee+completed+trashed+archived], 
    [workspace+assignee+completed+section+trashed+archived], 
    [archived+trashed], 
    trashed, 
    order
  '
})
```
<img width="888" alt="indexError" src="https://user-images.githubusercontent.com/2513753/115628716-e504a800-a2b5-11eb-801b-7fb1751c95a3.png">

I figured it was just a typo, but I can't seen anything wrong and all my other indices work fine. 

Any ideas? Is there a way to dig deeper into why this isn't working?

**Comment by dfahlander** [comment]
Try incrementing version from 1 to 2.

**Comment by cliftonlabrum** [comment]
I deleted the database and re-initialized and it started working. I swear I had tried that multiple times, but it finally took. Thanks!
