### ISSUE TITLE
Incorrect type signature for Version.upgrade

### ISSUE THREAD

**Issue by genezys** [dfahlander/Dexie.js#1286]
As a public interface, `Version` has the following signature for `upgrade`:
https://github.com/dfahlander/Dexie.js/blob/master/src/public/types/version.d.ts#L5
```
upgrade(fn: (trans: Transaction) => void): Version;
```

As a class and in the documentation, it has the following signature:
https://github.com/dfahlander/Dexie.js/blob/master/src/classes/version/version.ts#L63
```
upgrade(upgradeFunction: (trans: Transaction) => PromiseLike<any> | void): Version
```

The difference in the argument type prevents from returning the promise when using the upgrade function and can lead to bad usage.

**Comment by dfahlander** [comment]
Thanks for finding! PR welcome!
