### ISSUE TITLE
How can I do a like query on multiple fields in Dexie.js?

### ISSUE THREAD

**Issue by jigneshchudasama** [dfahlander/Dexie.js#1291]
I wanted to perform a `%like%` query like SQL on the dexie data on multiple fields/index, is it possible?

**Comment by dfahlander** [comment]
See #146

**Comment by jigneshchudasama** [comment]
@dfahlander I want to perform a fuzzy search on multiple keys and the search term can't be constant

**Comment by dfahlander** [comment]
I see. There are two options for utilizing index for fuzzy search: trigrams or full text. Both can be implemented using multiEntry index. At the moment I haven't seen any trigram addon for Dexie but there are examples on how to implement fulltext search. See #281.

**Comment by jigneshchudasama** [comment]
Fulltext search is also not meeting the requirements :/

for e.g. Name is `alexander dezousa`, if user searchs for 'alex` or `ale de` or `a sa`, it should show the result. This is currently not happening with the fulltext search approach.

Can you please help me out? @dfahlander

**Comment by dfahlander** [comment]
It would be nice if there was a trigram addon for dexie and it would defenitely be possible to implement. The principles can be read about [here](https://scoutapm.com/blog/how-to-make-text-searches-in-postgresql-faster-with-trigram-similarity). A middleware could maintain a multiEntry indexed array property based on the strings to include.

What you need it to write a function `computeTrigrams()` that given a string, generates an array of trigrams. Then on every put or add, you also compute the trigrams and put into the array (may be done in a middleware but it's not required if your application or if you have a data layer responsible for it).

Then, when searching, you would search in the trigram index.

The implementation could be something like the following. It is totally dry coded and you need to provide the computeTrigrams() function yourself. You must also fix bugs in this code as it is totally dry coded and may not take into account all the details. 

```js
const db = new Dexie("trigramSample");
db.version(1).stores({
  products: '++id, *trigrams'
});

// Example on how to search.
function findProductsLike (substring) {
  return db.products
    .where('trigrams')
    .anyOf(computeTrigrams(substring)) // utilize index
    .filter(product => product.title.includes(substring)) // narrow search
    .toArray();
}

// Middleware:
db.use({
  stack: "dbcore",
  name: "TrigramMaintainer",
  create: (db) => ({
    ...db,
    table (tableName) {
      const table = db.table(tableName);
      if (!table.schema.indexes.some(idx => idx.multiEntry && idx.name === "trigrams")) {
        return table;
      }
      return {
        ...table,
        mutate (req) {
          if (req.type !== "put" && req.type !== "add") return table.mutate(req);
          const valuesWithTrigrams = req.values.map(obj => {
            const trigramSet = new Set();

            // Include all string properties (you might want to adjust this)
            for (const [prop, val] of Object.entries(obj)) {
              if (typeof val === "string") {
                const trigrams = computeTrigrams(val);
                for (const trigram of trigrams) {
                  trigramSet.add(trigram);
                }
              }
            }
            
            return {
              ...obj,
              trigrams: [...trigramSet]
            }
          }); 
          return table.mutate({...req, values: valuesWithTrigrams});
        }
      };
    })
  });
});
db.items.where('trigrams').anyOf(computeTrigrams(searchText)).filter(res => res.content
```

**Comment by jigneshchudasama** [comment]
Still it's not working as expected :(

**Comment by dfahlander** [comment]
I have to leave it here. As I said, the code was something to explain the principle. I have no time to dive into this right now. Sorry.

**Comment by jigneshchudasama** [comment]
@dfahlander I have somehow managed to get this working but still, the slowness issue is there. Any suggestions for improving the same?
