### ISSUE TITLE
Regression: webOS 2 (2015) schema not correctly initialized

### ISSUE THREAD

**Issue by frankvdb7** [dfahlander/Dexie.js#1303]
Hello,

We currently encountered a bug while upgrading Dexie 2.0.4 to 3.0.3. It seems that the schema in the db core is not correctly initialized while loading the database. The schema is undefined and every function called with Dexie will result in unhandled rejections. An important detail is that the schema will only be undefined if there is an **existing** database (created with either native IndexedDB or Dexie). Dexie will try to open it and will fail on creating a transaction with multiple stores. Creating a **new** database and querying it works just for that session.

The webOS 2 screen has a Safari webkit engine build in, so it behaves like a version of the Safari browser from 2014/2015. 
User agent: `Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/538.2 (KHTML, like Gecko) Large Screen WebAppManager Safari/538.2`

Steps to reproduce:
1. Create a database with Dexie (or use an existing one):
`var db = new Dexie("test");`
`db.version(1).stores({
FileInfo: "",
Settings: ""
});`
`db.FileInfo.put("test.txt", { Path: "test.txt" });`
2. Open the database again (or restart the application)
3. The schema on the db core object is undefined and all queries with Dexie will result in unhandled rejections.

I can't really provide a JSFiddle and reproduce it that way, but maybe Browserstack can run some tests on an old Safari 2014/2015 version. 

The bug probably has something to do with some of the Safari fixes/bugs in the past that no longer work with current Dexie.

With best regards,
Frank

**Comment by dfahlander** [comment]
Thanks for the report. Dexie doesn't that old versions of Safari anymore and there is no plan to reintroduce workarounds for Safari 8 or 9. There are a lot of other issues with the IndexedDB support in those versions that we cannot workaround.

**Comment by frankvdb7** [comment]
Thanks for your reaction. It was a long shot considering we had a lot of issues and edge cases on that device as well. We were already considering dropping support for webOS 2, so now we have even more reason to do so.

Dexie is an awesome library and we'll continue to use version 2.0.4 for now.

Thanks!
