### ISSUE TITLE
Issue with array filter method

### ISSUE THREAD

**Issue by cpgb85** [dfahlander/Dexie.js#1306]
I have an array of user answers, and i need to determin if one of their answers is still in the question list.  I've used both lodash and the vanilla javascript filter method. 

`_.filter(answers, async answer=>(await db.questions.where('key').equals(answer.key).first())!=undefined)`

No matter what i do, it returns all 5 answers as if they are still in the database. But there is only 4 in the database.  Is there an issue with this?

**Comment by dfahlander** [comment]
_.fillter() and Array.filter takes a callback returning a boolean but your callback returns a Promise.

**Comment by cpgb85** [comment]
> _.fillter() and Array.filter takes a callback returning a boolean but your callback returns a Promise.

No, it's not returning a promise. I'm using async await which should use the value and not the promise. I'm starting to feel this is a bug in not only this library but in browsers in general. Doesn't behave as expected.

**Comment by dfahlander** [comment]
async functions return promises

**Comment by cpgb85** [comment]
Every time i've used async await, the promise resolves and results in the value.  It doesn't return a promise after it's done.  It's not behaving as intended.

**Comment by dfahlander** [comment]
There are good resources on the net to read more about how async keyword works. For example [this](https://javascript.info/async-await#summary) link. Please read it to understand that you can't use an async function as an argument to Array.filter(). The code wouldn't compile if it was typescript.

But I could also give you a hint on how to solve your actual problem:

```js
const matchingQuestions = await Promise.all(
  answers.map(answer => db.questions.get({key: answer.key})
);
const result = matchingQuestions.filter(q => q !== undefined);
```

**Comment by cpgb85** [comment]
This doesn't change the fact that i've used async and await inside of callbacks before.  Oh well.

**Comment by dheimoz** [comment]
Hello @cpgb85 , sorry for stumbling in your conversation. Kindly remember that Dexie is Open Source Software. @dfahlander was very kind to point you in the right direction. You should at least thank him.
It is good to not know anything, is not good to be disrespectful.
Cheers.

**Comment by cpgb85** [comment]
> Hello @cpgb85 , sorry for stumbling in your conversation. Kindly remember that Dexie is Open Source Software. @dfahlander was very kind to point you in the right direction. You should at least thank him.
> It is good to not know anything, is not good to be disrespectful.
> Cheers.

There was no disrespect.  Apologies if there was some taken.

**Comment by dheimoz** [comment]
@cpgb85 all right then. Have the solution presented by @dfahlander helped you?
