### ISSUE TITLE
Feature request: .stores function should allow ++id being at anywhere in the string

### ISSUE THREAD

**Issue by datdinhquoc** [dfahlander/Dexie.js#1307]
Creating stores currently this way is not working:
```
var db = new Dexie("mydb");
db.version(1).stores({
    "tests":"name,++id,url"
});
```

Error:
![image](https://user-images.githubusercontent.com/40449395/119233237-3ffa1b00-bb52-11eb-8ad0-f57b9b0bdef1.png)

But this is working:
```
var db = new Dexie("mydb");
db.version(1).stores({
    "tests":"++id,name,url"
});
```

I guess it's more flexible to have `++id` being at anywhere in the index string.
Should the feature be that way?

**Comment by dfahlander** [comment]
Unfortunately this library is limited by the IndexedDB API which only allows serials on primary keys.

**Comment by datdinhquoc** [comment]
> Unfortunately this library is limited by the IndexedDB API which only allows serials on primary keys.

I still don't get it why "name,++id,url" is different from "++id,name,url"

**Comment by dfahlander** [comment]
Dexie interprets the first index as the primary key. We will not change that.

**Comment by datdinhquoc** [comment]
> Dexie interprets the first index as the primary key. We will not change that.

Oh no, but that's not flexible

**Comment by dfahlander** [comment]
so how about primary keys not autoincremented? how to guess which one is primary? and how about inbound keys? and what gain would it be to just go for ++ when that is not required for being a primary key?? Please read indexeddb documentation to understand this in full first.

**Comment by datdinhquoc** [comment]
> so how about primary keys not autoincremented? how to guess which one is primary? and how about inbound keys? and what gain would it be to just go for ++ when that is not required for being a primary key?? Please read indexeddb documentation to understand this in full first.

understood, tks
