### ISSUE TITLE
How to do? Can multiple queries return the latest value?

### ISSUE THREAD

**Issue by baobao12356** [dfahlander/Dexie.js#1322]
How to do? Can multiple queries return the latest value?

**Comment by dfahlander** [comment]
Please elaborate the question more - it is not very clear what you are asking for. Then, I see you opened three issues in a row here with these kind of questions. Have you read the docs or do you expect us to work for free for you? Please do not span us with issues here. I advice you to follow our recommendations and put the questions on [stackoverflow](https://stackoverflow.com/questions/ask?tags=dexie)
