### ISSUE TITLE
Before each query is initiated, how can I delete the previous query and ensure that only the current query is initiated? And the value of the latest query returned this time

### ISSUE THREAD

**Issue by baobao12356** [dfahlander/Dexie.js#1323]
Before each query is initiated, how can I delete the previous query and ensure that only the current query is initiated? And the value of the latest query returned this time

**Comment by dfahlander** [comment]
Please elaborate the question more - it is not very clear what you are asking for. Then, I see you opened three issues in a row here with these kind of questions. Have you read the docs or do you expect us to work for free for you? Please do not span us with issues here. I advice you to follow our recommendations and put the questions on [stackoverflow](https://stackoverflow.com/questions/ask?tags=dexie)

Hint: When you put your questions on stackoverflow, show an example code snippet of what you want to do.
