### ISSUE TITLE
Database version differs. Current database is in version 9 but export is 8

### ISSUE THREAD

**Issue by Christilut** [dfahlander/Dexie.js#1337]
What is the recommended way to handle this in the dexie-export-import addon?

Is it possible to run all upgrade transactions on the data during import?
Or should I delete the database, run the upgrades until version 8 and then upgrade to 9 after the import is complete?

**Comment by dfahlander** [comment]
If you import something that was exported from an earlier version: Delete the database (await db.delete()). Then import a db that will be on the same version as when it was exported:

```js
const tempDb = await importDB(blob, [options]);
```

Then, close this tempDb and open your declared DB (with upgrades declared on it).

```js
await db.open();
```

This will make sure the required upgraders are run on the imported data.

**Comment by Christilut** [comment]
Perfect, thanks. The temporary database was the missing link for me.
