### ISSUE TITLE
Cloud: Invalid OTP on switch tab

### ISSUE THREAD

**Issue by dusty-phillips** [dfahlander/Dexie.js#1344]
Congratulations on releasing Dexie-cloud! I rushed out to install the beta and everything's gone smoothly so far. I had one hiccup in getting my dependencies up-to-date in package.json, but that's on me.

I accessed my site and bam! It asked me for my e-mail and then OTP. I switched tabs to check my e-mail, and when I switched back, the dev server had crashed with "Unhandled Rejection (Error): Invalid OTP".

The Unhandled Rejection is not unexpected since everything is beta and you probably haven't hooked up this path yet. 

But I figured the "crash on tab switch" was worth reporting. It's likely the prompt was cancelled because of the tab switch, as not enough time had passed to cause a timeout.

---
Browser: Safari 14.1.1
Dexie-cloud-addon: 1.0.0-beta.2
Dexie: 3.2.0-beta.1
dexie-react-hooks: 1.0.7

**Comment by dfahlander** [comment]
Ok, thanks! All feedback is very welcome. The OTP dialog is currently using a simple synchronous prompt() (which is a very temporary solution and will be replaced).

**Comment by dusty-phillips** [comment]
This is now working with the JS popup instead of prompt in alpha-7.
