### ISSUE TITLE
Cloud: Status 403 on Login

### ISSUE THREAD

**Issue by maor700** [dfahlander/Dexie.js#1348]
Hi, I'm getting:
`Unhandled Rejection (Error): Status 403 from https://z9o23kbgd.dexie.cloud/token` exception on login.

using your ToDoApp demo.

I'm actually getting sometimes 500 also but let solve this first of all.

her is my code: 

db.ts : 

import Dexie, { DexieOptions, Table } from 'dexie';
import dexieCloud, { DexieCloudTable } from 'dexie-cloud-addon';
import { DexieCloudOptions } from 'dexie-cloud-addon/dist/types/DexieCloudOptions';
import { populate } from './populate';
import { TodoItem } from './TodoItem';
import { TodoList } from './TodoList';

export class TodoDB extends Dexie {
  todoLists!: DexieCloudTable<TodoList>;
  todoItems!: DexieCloudTable<TodoItem>;

  constructor() {
    super('TodoDBCloud', { addons: [dexieCloud] });
    this.version(10).stores({
      todoLists: '@id',
      todoItems: '@id, todoListId'
    });
    // Connect to cloud
    this.cloud.configure({
      databaseUrl: process.env.REACT_APP_DBURL!,
      tryUseServiceWorker: true,
      requireAuth: false
    });
  }
}

export const db = new TodoDB();

console.log(db);

db.on('populate', populate);

export async function resetDatabase() {
  await db.delete();
  window.location.reload();
  /*return db.transaction('rw', db.todoLists, db.todoItems, async () => {
    await db.todoItems
      .filter((tdi) => !tdi.realmId || tdi.realmId === db.cloud.currentUserId)
      .delete();
    await db.todoLists
      .filter((tdl) => !tdl.realmId || tdl.realmId === db.cloud.currentUserId)
      .delete();
    await populate();
  });*/
}

NavBar login part:
<Button
            onClick={() =>
              db.cloud.login({ grant_type: 'demo', userId: 'foo@demo.local' })
            }
          >
            Login
          </Button>

.env.local:
REACT_APP_DBURL=https://zxynuo31v.dexie.cloud

dexie-cloud.key

{
  "https://zmea50om9.dexie.cloud": {
    "clientId": "f04ovpq3e4p3i0da",
    "clientSecret": "FH8hxPAbTAbop9jpQgkgrPD7Z74lqbcGjRaSpwz0QKY="
  },
  "https://zq9bn4me0.dexie.cloud": {
    "clientId": "x6q78jvjtlir2fq1",
    "clientSecret": "KXfHSkE9wmdFwG8oOHcWdrxSnXCiOkhCb/qPLk9rka8="
  },
  "https://z9o23kbgd.dexie.cloud": {
    "clientId": "qlznxzsyl96jszje",
    "clientSecret": "pXJAEWTU/L3SpNnZ0QVT9J9Zcw6bx5DYK5PwVSLvYlU="
  },
  "https://zxynuo31v.dexie.cloud": {
    "clientId": "rofz8cdc22rkojid",
    "clientSecret": "yNA+fLZyNoGEJhGpRFtlXS23dqMmkpoBCTWWGCOrKto="
  }
}

**Comment by maor700** [comment]
ok, solved. my misunderstanding about how the Auth modes.

**Comment by dfahlander** [comment]
I'm working on improving login interaction. The todolist sample will also be extended with option to login arbritary user (with OTP) or select between demo users.

Expect improvements to come the coming weeks along with a blog post and more docs.
