### ISSUE TITLE
startsWithAnyOf  Ignore Case

### ISSUE THREAD

**Issue by rtm7777** [dfahlander/Dexie.js#135]
Hi David!

Can I make query, something like `startsWithAnyOfIgnoreCase(['a', 'b', 'c'])` ?

Thanks!

**Comment by rtm7777** [comment]
Also, is it possible to create method: `containsIgnoreCase` ?

**Comment by dfahlander** [comment]
Neither of these methods exists in current version.

startsWithAnyOfIgnoreCase() would be possible to do by utilizing the or() method:

```js
db.friends.where('name').startsWithIgnoreCase('a')
    .or('name').startsWithIgnoreCase('b')
    .or('name').startsWithIgnoreCase('c');
```

A generic method that does this could be implemented the same way as startsWithAnyOf() is implemented in the latest source.

Regarding the next one, containsIgnoreCase, it is a little trickier. A normal index cannot be utilized for substring search, only prefix or exact search. There is a sample on how to build a full-text search capability on top of Dexie in [samples/full-text-search/FullTextSearch.js](https://github.com/dfahlander/Dexie.js/blob/master/samples/full-text-search/FullTextSearch.js), but that requires some additional "manual" indexing, as you can see in that source code.

**Comment by rtm7777** [comment]
About first question, I asking it because I want to search in two indexes with arbitrary count of search params, something like:

```db.friends.where('firstName').startsWithAnyOfIgnoreCase([array]).or('lastName').startsWithAnyOfIgnoreCase([the_same_array])```

maybe you know better way to do it )

Thanks again!

**Comment by dfahlander** [comment]
Here's an idea of how to do it (without having tested the code):

```js

// Algorithm:
function startsWithAnyOfIgnoreCase(table, index, prefixes) {
    if (!prefixes || prefixes.length === 0) throw "must supply at least one prefix";
    return prefixes.reduce(function(collection, prefix) {
        return collection ?
            collection.or(index).startsWithIgnoreCase(prefix) :
            table.where(index).startsWithIgnoreCase(prefix);
    }, null);
}

// Usage:
// Search of all friends whose names starts with "a", "b" or "c" case insensitive:
//
startsWithAnyOfIgnoreCase(db.friends, "name", ["a","b","c"]).toArray(function (result) {
    console.log(JSON.stringify(result));
});

```

If it works, we could add it as a standard WhereClause method.

**Comment by dfahlander** [comment]
Ok. Changed sample according to your updated question:

```js

// Adjust the first algorithm to accept either table or collection:
function startsWithAnyOfIgnoreCase(tableOrCollection, index, prefixes) {
    if (!prefixes || prefixes.length === 0) throw "must supply at least one prefix";
    return prefixes.reduce(function(collection, prefix) {
        return collection ?
            collection.or(index).startsWithIgnoreCase(prefix) :
            (tableOrCollection.where ? tableOrCollection.where(index) :
                tableOrCollection.or(index)).startsWithIgnoreCase(prefix);
    }, null);
}

// Higher algorithm to search multiple indices:
function searchMultiple (tableOrCollection, indices, prefixes) {
    return indices.reduce(function (collection, index) {
        return collection ?
            startsWithAnyOfIgnoreCase(collection, index, prefixes) :
            startsWithAnyOfIgnoreCase(tableOrCollection, index, prefixes);
    }, null);
}

// Usage:
// Search of all friends whose first- or last names starts with "a", "b" or "c" case insensitive:
//
searchMultiple (db.friends, ["firstName", "lastName"], ["a","b","c"]).toArray(function (result) {
    console.log(JSON.stringify(result));
});
```

No guaruantee that this works, but please try if it does ;)

**Comment by rtm7777** [comment]
It does! :+1: 

Thank you for helping, good luck!

**Comment by krisak** [comment]
This post is gold. It should be linked in wiki.

I have question how would i get to search like this
`searchMultiple (db.friends, ["title","tags"], value)
When database is
{ title: 'mytitle', tags: ['tag1', 'tag2', 'tag3'] }
`

I need to get tags dynamicaly somehow because there might be none or there might be 5.

THANKS
