### ISSUE TITLE
[site] The site option "Email me when Dexie Cloud is available" is broken

### ISSUE THREAD

**Issue by silvioprog** [dfahlander/Dexie.js#1357]
It seems the option "[Email me when Dexie Cloud is available](https://dexie.org/cloud)" is not working. When we put our email and click to be notified, the status "Please wait..." freezes for a long time, and any email confirmation is sent to the user, as shown in the picture below:

![image](https://user-images.githubusercontent.com/1456829/124930574-d46fee00-dfd7-11eb-9873-cbfde2391719.png)

**Comment by dfahlander** [comment]
Thanks! It must have been non-functional ever since I released https://dexie.cloud more than a week ago and deleted dexie-cloud-stub. I will fix asap!

**Comment by dfahlander** [comment]
Now it's working again.

**Comment by silvioprog** [comment]
Thanks for the quick answer! BTW the [dexie.cloud](https://dexie.cloud) is returning "```Cannot GET /```". 😕

![image](https://user-images.githubusercontent.com/1456829/124934817-747b4680-dfdb-11eb-929c-ed9f96239f75.png)

**Comment by dfahlander** [comment]
Thanks, yes I know. I will redirect it to dexie.org/cloud/
