### ISSUE TITLE
Cannot use primaryKeys to pass into bulkDelete in Angular 11

### ISSUE THREAD

**Issue by mtruong09** [dfahlander/Dexie.js#1364]
I am writing a generic function in Angular 11 to delete records based on a where clause. However, I am unable to pass the results of a .where(where).primaryKeys() to a bulkDelete:

![image](https://user-images.githubusercontent.com/3227839/125301594-21660400-e2f9-11eb-82b7-8e600ed0ce59.png)

![image](https://user-images.githubusercontent.com/3227839/125301670-32167a00-e2f9-11eb-9b20-fc9d3a10c237.png)

Based on the [docs](https://dexie.org/docs/Table/Table.bulkDelete()), it seems like I should be able to use the primary keys array as the parameter for the bulk delete?

Currently working around it by setting keys to any[] which seems to work in Chrome.

**Comment by dfahlander** [comment]
This is a typing issue. PR welcome.
