### ISSUE TITLE
Dexie-cloud: Updates to arrays don't sync reliably

### ISSUE THREAD

**Issue by dusty-phillips** [dfahlander/Dexie.js#1366]
If I store an object, as opposed to a primitive in a column, Dexie-cloud isn't syncing it reliably. Took me a while to narrow this down since I'm storing objects in almost all my columns, so it seemed like Dexie-cloud was just completely unreliable! But I noticed some actions were more likely to succeed than others:

If I create a new object, the creation (almost) always propagates to my other browsers.
If I delete an object, the deletion (almost) always propagates.
If I change a string name, the update (almost) always propagates.
But if I change a field that has a JS object stored as its value, it does not propagate. I can see the outgoing message in the verbose output on the console, but the change never shows up in "Applying server changes" on the other end.

**Comment by dusty-phillips** [comment]
I've been trying to identify this better and I realized it's actually updates to fields that I have defined as slatejs `Descendant[]` that are reliably failing to sync (other things sometimes fail, but these fields always fail).

I have the following store defined in my database:

```typescript
        outlineItems: '@id, stableid, draftid, level, *tags',
```

And it is modelled by this Typescript model:

```typescript
export interface OutlineItem {
  id: string
  stableid: string
  draftid: string
  title: Descendant[]
  summary: Descendant[]
  order: number
  level: 'Chapter' | 'Scene'
  tags: string[]
}
```

Specifically when I change the `title` or the `summary` in my code, the update fails to propagate.

The "Descendent" type is an interface representing an arbitrary tree of objects (See https://docs.slatejs.org/api/nodes). It stores in the database as something like `[{children: [{text: "something"}]}`.

So my initial assumption (as reported) was that cloud was not properly syncing objects. However, now that I look at it, the thing that is not being synced is actually an array of objects.

**Comment by dfahlander** [comment]
I see! Thanks a lot for the bug report. I will look into it next week.

**Comment by dusty-phillips** [comment]
I did a quick test and determined that if I put the array inside an object it works fine:

```javascript
export interface OutlineItem {
  id: string
  stableid: string
  draftid: string
  title: Descendant[] // <-------- This doesn't sync
  summary: Descendant[] // <------- nor this
  order: number
  level: 'Chapter' | 'Scene'
  tags: string[]
  alsoTitle?: { nodes: Descendant[] } // <-------- but this works
}
```

**Comment by dusty-phillips** [comment]
Wanted to see what the status on this one is. I've been holding off on further cloud testing, but if this is going to be a while, I might try the work around of moving all the arrays into objects.

**Comment by dfahlander** [comment]
Thanks for the reminder! Don't move your arrays into objects, this is a simple issue. Sorry for letting it take long. Without promising too much, I'm aiming for an update on Friday with this issue solved.

**Comment by dfahlander** [comment]
I could reproduce it and find the issue. The fix is just recently deployed to dexie cloud. It was a server-side issue so you won't need to update the addon. If you'll be able to verify the fix, please give me a comment and close the issue.

**Comment by dusty-phillips** [comment]
Working well. Thanks so much. This is the first time I've seen the app actually syncing.

**Comment by dusty-phillips** [comment]
Although, I noticed that they synced data isn't updating "live" like it does for normal nodes (using the react live query hooks), so there may be a client side bug as well.

**Comment by dfahlander** [comment]
I am aware of a few bugs related to realtime sync:

* websocket channel detects the existence of changes but service worker sometimes come into a state where it doesn't react on the `sync` event (a limitation in the browser it seems - that if an SW has failed a few times, browser stops waking it up for additional sync events for a while). The result of this is that the app won't do any sync request - not even at startup - for a while - will heal itself after some 30 minutes. This bug is resolved in a working branch, that also sends the sync notification as a message.

The new version will also contain an optimized realtime sync where the websocket channel delivers the changes itself instead of just triggering a resync.

I haven't seen any bug in local liveQuery propagation though - only that the data itself sometimes not reach the client. If you have any more details of how your bug manifests itself, please explain and if you'd have some code or repro that would be even better.

Cheers,
David

**Comment by dusty-phillips** [comment]
I’ll try! It hasn’t been consistent, so there isn’t an obvious repro, but I’ll narrow it down eventually.

**Comment by dfahlander** [comment]
Dexie Cloud was updated earlier this week together with a new version of dexie-cloud-addon. Unfortunaly there is still one missing piece to get full sync consistency at the server when two clients sync simultanously. However, a lot has been improved with the current release - especially regarding optimization of sync. A new update with full consistency is now being worked on and will hopefully be out within a 2 week period. The flaw in the current verison is only when two or more clients sync simultanously, some changes are not being propagated back to its clients.

**Comment by dusty-phillips** [comment]
Haven’t seen any issues recently; I’m comfortable closing.
