### ISSUE TITLE
Must use import to load ES Module: path/to/project-root/node_modules/dexie/dist/modern/dexie.mjs

### ISSUE THREAD

**Issue by neilnahid** [dfahlander/Dexie.js#1369]
I'm currently using nextjs 11 + typescript and I followed this example: https://github.com/dfahlander/dexie-todo-list
and then I encountered this error
![image](https://user-images.githubusercontent.com/25801890/126962487-f89fa1f1-82cb-4c5b-a616-7db93e615182.png)

I'm trying to run dexie in the  browser.

**Comment by neilnahid** [comment]
I've resolved this by using the next-transpile-modules plugin

```js
// eslint-disable-next-line
const withDexie = require('next-transpile-modules')(['dexie']);
module.exports = withDexie({
// your other config here...
})
```

**Comment by michaelwooley** [comment]
Thank you @neilnahid . This also turned out to be the fix for a different-but-evidently-related error that I was seeing:

> TypeError: class constructors must be invoked with 'new'

![image](https://user-images.githubusercontent.com/8423171/145137187-146c2f71-77bf-43a3-9387-fa348fcf4074.png)

**Comment by jayaddison** [comment]
Hrm.  This same issue appears for [this import statement](https://github.com/openculinary/frontend/blob/54ad4c7c25d6b867bd30d290df6d53059a9e021f/src/app/database.ts#L1) when attempting to upgrade to Dexie@3.2.0.

Based on the example in the README here, that should work, I think.  I'm a bit reluctant to add `next-transpile-modules` as a dependency without understanding a bit more about the cause.

@neilnahid @dfahlander don't suppose you can add any more clues / input?  I've tried a few tweaks to the import code mentioned, and can experiment a bit more to help track this down.

**Comment by dfahlander** [comment]
The issue is reported in #1439. Dexie 3.2.0 cannot be required but could be so in previous versions. A new version 3.2.1-beta.2 is just recently published with an extended "exports" field in package.json that hopefully resolves this.

**Comment by jayaddison** [comment]
Thanks @dfahlander - and confirmed that 3.2.1-beta.2 solves the issue (I'll echo that in #1439 as well).

**Comment by argarner** [comment]
Adding `moduleNameMapper` to my `jest.config.js` resolved this issue for me with `@swc/jest`

```
    transform: {
        '^.+\\.(t|j)s?$': '@swc/jest',
    },
    transformIgnorePatterns: [],
    testEnvironment: 'jsdom',
    testPathIgnorePatterns: ['/node_modules/'],
    setupFiles: ['fake-indexeddb/auto'],
    moduleNameMapper: {
        '^dexie$': '<rootDir>/node_modules/dexie',
    },
```
