### ISSUE TITLE
how to use startsWithAnyOf with composite indexes?

### ISSUE THREAD

**Issue by branlok** [dfahlander/Dexie.js#1372]
I'm trying to build a search for items by names in my app.
items contains id of which project it belongs to and the name of the item.

```js

//sample item
itemId: {
itemId,
projectId: 001,
name: "pizza"
}

//want to do something like this
await db.items.where("[projectId+name]").startsWithIgnoreCase(["001", "pizza"]).toArray(r => console.log(r))
//returns the pizza item
```

**Comment by dfahlander** [comment]
Some operators operates on string indexes only (startsWith, startsWithAnyOf, startsWithIgnoreCase, equalsIgnoreCase, etc). As such, they cannot be used on composite indexes as those are arrays - not strings.

Instead, you could do the following:

1. Store 'name' in lowercase so you don't need the ignoreCase-operators to search for them (this is generally more efficient anyway).
2. Change the query to:
  ```ts
  await db.items.where({
    projectId: "001",
    name: "pizza"
  }).toArray();
  ```

This query will automatically utilize your composite index '[projectId+pizza]'.

If you then need to search for multiple words (as the title of this issue suggests), do:

```ts
const projectId = "001";
const searchWords = ["pizza", "pAsta", "saLLad"];

const searchResults = await Promise.all(
  searchWords.map((searchWord) =>
    db.items.where({
      projectId,
      name: searchWord
    }).toArray()
  )
);

const flattenedResults = searchResults.flat();

```

**Comment by branlok** [comment]
very clear, thank you so much! I suppose if I ever need to scale up the search logic, I would need to tie it to something like lunr search? (saw this in a seperate issue #785)
