### ISSUE TITLE
Get all column names of a table

### ISSUE THREAD

**Issue by MinKyawNyunt** [dfahlander/Dexie.js#1375]
How to get only column names (without value) of a table?

**Comment by dfahlander** [comment]
There are no column names in IndexedDB except for the primary key and each additional index. Non-indexed properties are not declared in the schema.

To enumerate tables, primary keys and indexes, you can do something like this:

```ts
const db = new Dexie('dbName');
db.open().then(async db => {
  for (const table of db.tables) {
    console.log("Table", table.name);
    console.log("  Primary Key:", table.schema.primKey);
    console.log("  Indexes:", table.schema.indexes);
  }
});
```

**Comment by MinKyawNyunt** [comment]
Thanks
