### ISSUE TITLE
Cannot read property subscribe of undefined

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#1376]
A customer has encountered a problem on dexie-cloud-addon. An exception is thrown: Uncaught TypeError: Cannor read property 'subscribe' of undefined.

    at dbOnClosed (dexie-cloud-addon.js:2884)
    at dexieCloud (dexie-cloud-addon.js:5844)
    ...

And the code on dexie-cloud-addon.js:2882 is as below.

<img width="407" alt="bf5979a5-44ca-4567-b037-1ca0ebdd4b78" src="https://user-images.githubusercontent.com/6791329/128885409-21ba0b21-86cd-4bbf-91cd-2f848181ae02.png">

the `db.on.close` is undefined.

**Comment by dfahlander** [comment]
Reason must be that the newest version of dexie isnt installed. Must install dexie@next to work with dexie-cloud-addon.

**Comment by rayzhao99** [comment]
Yes, it works now. Thanks!
