### ISSUE TITLE
OpenFailedError: when using dexie-obeservable

### ISSUE THREAD

**Issue by Hubertformin** [dfahlander/Dexie.js#1385]
I have an electron app with implementation of my own sync protocol with MongoDB. When I try to open my app without an internet connection (no connection to the server socket). Dexie throws OpenFailedError, but If my app opens, and dexie connect's to my server socket, it works just fine. 

How do I make Dexie open without connection to the server socket?

My code

![Screen Shot 2021-09-04 at 5 45 01 PM](https://user-images.githubusercontent.com/25336761/132102283-a57c6b7e-954a-4980-9838-f9d00cf152f7.png)

![Screen Shot 2021-09-04 at 5 45 13 PM](https://user-images.githubusercontent.com/25336761/132102300-58ada019-5d0d-4d1f-abee-bf877dffb06c.png)

<img width="455" alt="Screen Shot 2021-09-04 at 5 35 22 PM" src="https://user-images.githubusercontent.com/25336761/132102303-f58b7694-2815-4698-b6f3-34adb61111ad.png">

**Comment by Hubertformin** [comment]
I found the solution.

**Comment by cpgb85** [comment]
> I found the solution.

Don't share or anything.

**Comment by dheimoz** [comment]
hey @Hubertformin would you mind sharing your solution? That is the best way to help Open Source Projects to thrive.
Thanks.
