### ISSUE TITLE
Bower doesn't seem to find version 1.2

### ISSUE THREAD

**Issue by AnimaLupi** [dfahlander/Dexie.js#139]
Hello,

hope this is isn't just an issue on my side, if it is my apologies in advance.

It seems bower isn't picking version 1.2 both if I specify "latest" or "1.2" in bower.json.

In the former case, I get:

> bower ENORESTARGET  No tag found that was able to satisfy 1.2
> 
> Additional error details:
> Available versions: 1.1.0, 1.0.4, 1.0.3, 1.0.2, 1.0.1

Thank you,

Andrea

**Comment by dfahlander** [comment]
Could be an issue with my versioning ("1.2"). I just updated the version name to "v1.2.0". Please check if it works better now.

Regards,
David

**Comment by AnimaLupi** [comment]
Now it's working, thank you David!

Have a nice weekend,

Andrea
