### ISSUE TITLE
Safari 14 fix breaks fake-indexeddb (heads up)

### ISSUE THREAD

**Issue by dusty-phillips** [dfahlander/Dexie.js#1397]
I was testing some stuff with fakeindexeddb and found it crashed with the new 3.2.0 release candidate. The problem isn't in Dexie, but I'd recommend not releasing the 3.2.0 final until https://github.com/jakearchibald/safari-14-idb-fix/pull/10 merges!

**Comment by dusty-phillips** [comment]
Or possibly not: https://github.com/jakearchibald/safari-14-idb-fix/pull/9 🤦

**Comment by dfahlander** [comment]
Thanks 🙏 I will need to update the devdep before building then

**Comment by dusty-phillips** [comment]
Upstream doesn’t want to merge PR, so the navigator check will need to be moved up to dexie.

**Comment by dfahlander** [comment]
I released 3.2.0-rc.2 now with avoiding the fix if typeof navigator === 'undefined'. If you have a chance to test it, please let me know.

**Comment by dusty-phillips** [comment]
Yep, working now. 👍
