### ISSUE TITLE
Error when using put() on tables with compound primary keys

### ISSUE THREAD

**Issue by gabrielbitencourt** [dfahlander/Dexie.js#1399]
I have the following implementation of a data table with a compound primary key

```ts
import Dexie, { Table } from 'dexie';

interface IData
{
    masterId: number;
    dataId: string;
    date: Date;
    file: Blob;
}

class DataService extends Dexie
{
    data: Table<IData>;
    constructor()
    {
        super('datadb');
        this.version(1).stores({
            'data': '[masterId+dataId],dataId'
        });
        this.data = this.table('data');
    }

    upsert(data: IData)
    {
        return this.data.put(data);
    }
}
```

But when I try to call the ```upsert()``` function it always returns the following error:

![Captura de tela 2021-09-30 192145](https://user-images.githubusercontent.com/8468139/135546381-7c8a5729-4819-4b8e-bfbb-9dd0c721949b.png)

Am I doing something wrong or could this be an issue with the browser implementation?

**Comment by dfahlander** [comment]
All properties that are parts of the primary key needs to be set and needs to be an [indexable type](https://dexie.org/docs/Indexable-Type)

**Comment by gabrielbitencourt** [comment]
In this case they are, the index is an array of a number and a string, and both are being set when I call the ```upsert()```

**Comment by dfahlander** [comment]
Have you added a breakpoint in your upsert method and verified that given object really have that? Make sure that the properties can't be getters on the prototype - they need to exist as own enumerable props.

**Comment by gabrielbitencourt** [comment]
Ok, that was it. One of the properties from the index was undefined. Thanks for the help!
