### ISSUE TITLE
Error when creating a db with dashes in key name

### ISSUE THREAD

**Issue by florianbepunkt** [dfahlander/Dexie.js#1401]
When creating a table I get errors if my keys contain a dash (-) in their name. While this works...

```ts
    this.version(1).stores({
      orders: 'orderid',
    });
```

...the following fails...

```ts
    this.version(1).stores({
      orders: 'order-id',
    });
```

I couldn't find this in the documentation. Is this a bug or by design?

**Comment by dfahlander** [comment]
It might be a limitation in the indexeddb spec of what characters are allowed in key paths. Dexie does not put any limitations.

**Comment by florianbepunkt** [comment]
@dfahlander Thank you for your time. Indeed, from the key path spec (https://www.w3.org/TR/IndexedDB/#key-path-construct, my highlighting):

> A key path is a string or list of strings that defines how to extract a key from a value. A valid key path is one of:
> 
> - An empty string.
> - An identifier, which is a string **matching the IdentifierName production from the ECMAScript Language Specification** [ECMA-262].
> - A string consisting of two or more identifiers separated by periods (U+002E FULL STOP).
> - A non-empty list containing only strings conforming to the above requirements.

`order-id` from my example above is not a valid identifier (see https://mothereff.in/js-variables for example)

The error I received was not very descriptive and I removed the dash by pure chance, otherwise I would have not found out.
