### ISSUE TITLE
Problems with regular expression in filter()?

### ISSUE THREAD

**Issue by Sjoerd82** [dfahlander/Dexie.js#1405]
I noticed that some of the rows did not return when applying a filter...

I'm applying a filter to a table/collection with a regular expression against a product name
Everything works when applying a function to the filter that uses a literal regular expression.
But, not all rows are returned when using a RegExp variable (either object or literal) instead.

I have not been able to find the pattern yet why some rows are returned while others are not. It also changes when ordering by different indexes.

```
        const matcher1 = new RegExp("Com", "gi");
        const matcher2 = /Com/gi
        const filter = function(r) {
            //return ( (matcher1.test(r['product_name']) ))      // NOK
            //return matcher2.test(r['product_name'])            // NOK
            return /Com/gi.test(r['product_name'])               // OK
        }
        const d = await db.products
              //.orderBy('product_id')
                .filter(r => {return filter(r)})
                .toArray()

        console.log('TEST 1', matcher1.test('Compass')) // true
        console.log('TEST 2', matcher2.test('Compass')) // true
```
When using one of the matchers in the example above a product named "Compass" is not returned with the search string "Com", it will be returned with variations of that.

Could this be a bug, or is my code flawed somewhere?

**Comment by dfahlander** [comment]
Hi! Dexie simply calls your filter function with the data. This is outside dexie's scope on how a dynamic RegEx works compared to a compiled one. You need to debug it. Try your filters on a plain JS array and you will experience the same things.

```js
const products = await db.products.toArray();
const d = products.filter(r => { return filter(r); });
```
