### ISSUE TITLE
[bug][question] - wrapping native promise by ```DexiePromise``` leads to errors

### ISSUE THREAD

**Issue by rkovalyov** [dfahlander/Dexie.js#1415]
Hi, I haven't investigated deeply, but if I try to use another library with own Promise wrapper together it leads to errors;
Have you faced with this issue ? 

```js
TypeError: Method Promise.prototype.then called on incompatible receiver #<KeycloakPromise>
Unhandled rejection: Error: [object Object]
From previous: 
    at DexiePromise.then ....
```

**Comment by dfahlander** [comment]
It could be if the alternate promise polyfill is loaded after dexie is included and then replaces window.Promise with it. Try if the error goes away by including the promise polyfill before including dexie.

**Comment by dfahlander** [comment]
If this error occur, check that there aren't multiple versions of dexie running in your app:

```
npm ls dexie
```
Verify that the same version of dexie is used across the dependency tree. 3rd part libraries that depend on dexie shall list it in peerDependencies and not in dependencies to avoid this.
