### ISSUE TITLE
Transaction atomicity with simultaneous db operations in Tabs/iframes 

### ISSUE THREAD

**Issue by maor700** [dfahlander/Dexie.js#1425]
I want to use dexie to manage app state cross iframes on same domain.
The question is,  in case of two iframes/tabs makes concurrent indexeddb operations, 
 will the transaction make a valid rollback  in case of error?

**Comment by dfahlander** [comment]
Yes, the transactions in IndexedDB are fully ACID compliant. Two concurrent readwrite-transactions will try to lock the same table so that only one will execute at a time though.
