### ISSUE TITLE
Sync Dexie with SQL source database direct or indirect

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [dfahlander/Dexie.js#143]
Hello Dexie team,

We want to use your solution in our App build where it must serve a search and find over 50.000 documents (with a modest amount of elements). But the source of the data is in a companies SQL database.
Can you advise how we can sync the local database with the source in a practical way? (direct or indirect SQL <-> NOSQL <-> Dexie)

Kind regards,
Mario

**Comment by dfahlander** [comment]
I personally do sync about 50,000 documents between sqlserver tables and IndexedDB in my app. Also quite small docs, around 0,25-2kb each. I created the addons Dexie.Syncable and Dexie.Observable for this purpose. It works pretty well for me wheth though their still beta. Dexie.Syncable is a bidirectional sync framework that makes apps work offline and resync once online again but you'd need to implement a sync provider (client side) and a server backend that is capable of tracking changes and optionally aurhorization handling as well if your data isn't public. 

What I've done in my app,  is :
* A set of SQL tables in a sqlserver instance in Microsoft Azure. Each table has a tenant-id column for access control. 
* An oplog/changes table at backend where I record each write operation together with a tenant id for access controlling the changes.
* a rest interface for syncing with authorization where each user can belong to 1..N tenants.
* A client side implementation of the [ISyncProtocol](https://github.com/dfahlander/Dexie.js/wiki/Dexie.Syncable.ISyncProtocol)

There are sample dummy implementations of the ISyncProtocol in this repo to look at.

Just keep in mind this is beta and that the Dexie.Syncable addon may change in future. If you are concerned about that, you could implement syncing directly on Dexie using the Dexie CRUD hooks which are stable. But that requires a little more work to get things right.

**Comment by MarioVanDenEijnde** [comment]
Hello David,

I did not study below approach in detail yet but question: if we want to release our app and when the app will be installed we need to get the 50.000 documents "synced" to the mobile app. I suppose this will be quite time consuming. What would be the best approach we can choose?

Kind regards,
Mario

On 10 okt. 2015, at 12:17, "David Fahlander" <notifications@github.com<mailto:notifications@github.com>> wrote:


I personally do sync about 50,000 documents between sqlserver tables and IndexedDB in my app. Also quite small docs, around 0,25-2kb each. I created the addons Dexie.Syncable and Dexie.Observable for this purpose. It works pretty well for me wheth though their still beta. Dexie.Syncable is a bidirectional sync framework that makes apps work offline and resync once online again but you'd need to implement a sync provider (client side) and a server backend that is capable of tracking changes and optionally aurhorization handling as well if your data isn't public.

What I've done in my app, is :

  *   A set of SQL tables in a sqlserver instance in Microsoft Azure. Each table has a tenant-id column for access control.
  *   An oplog/changes table at backend where I record each write operation together with a tenant id for access controlling the changes.
  *   a rest interface for syncing with authorization where each user can belong to 1..N tenants.
  *   A client side implementation of the ISyncProtocol<https://github.com/dfahlander/Dexie.js/wiki/Dexie.Syncable.ISyncProtocol>

There are sample dummy implementations of the ISyncProtocol in this repo to look at.

Just keep in mind this is beta and that the Dexie.Syncable addon may change in future. If you are concerned about that, you could implement syncing directly on Dexie using the Dexie CRUD hooks which are stable. But that requires a little more work to get things right.

**Comment by dfahlander** [comment]
Best thing is to show a progress bar or similar during sync. The syncable api currently lack such progress event but that's something I also need to implement.

**Comment by MarioVanDenEijnde** [comment]
Hello David,

In our app we can include a json file with which we could populate the database at first install.
And after the first install fall back on the live sync updates.
Would that be an option? What do you think.

Kind regards,
Mario

On 14 okt. 2015, at 21:03, "David Fahlander" <notifications@github.com<mailto:notifications@github.com>> wrote:


Best thing is to show a progress bar or similar during sync. The syncable api currently lack such progress event but that's something I also need to implement.

**Comment by dfahlander** [comment]
Could gain some speed by not tracking the changes locally on initial sync, I.e handling it manually without the addons enabled, yes.
