### ISSUE TITLE
Is it possible use multiple where in chain? eg. `db.where({}).where({}).first()`

### ISSUE THREAD

**Issue by axetroy** [dfahlander/Dexie.js#1438]
This seems not works

```js
        return this.db.table.where({
                accountId: getAccountId()
            })
            .where('localPath')
            .equalsIgnoreCase(filepath)
            .last()
```

**Comment by dfahlander** [comment]
No it's not possible. Chained where-conditions, mongo-like queries and combination of where() and orderBy() is planned for dexie 4.0 but it's still in its early stage it may not be able to use index to execute the query. Today you can only do queries that can utilize an index. Combinations of fields can be combined that way using a [compound index](https://dexie.org/docs/Compound-Index). However, in current version you can achieve the same by combining where(), fitlter() and sortBy().

```js
return this.db.table
  .where('localPath')
  .equalsIgnoreCase(filepath)
  .filter(x => x.accountId === getAccountId())
  .last();
```
In this specific case, it could also solve more efficient by indexing a lowercase version of localPath

```js
this.db.version(2).stores({
  table: 'id, [accountId+localPathLower]
}).upgrade(tx => {
  // A migration that stores a lowercase version of localPath:
  return tx.table.update(x => x.localPathLower = x.localPath.toLowerCase());
});
```
Then make sure to keep also storing the localPathLower when creating new objects. Either in your app code, or by writing a [middleware](https://dexie.org/docs/Dexie/Dexie.use()#example) that enforces it.

To query:

```js
await db.table.where({
  accountId: getAccountId(),
  localPathLower: filepath.toLowerCase()
}).last();
```

**Comment by axetroy** [comment]
Thank you for your patient answer, it is very helpful to me, looking forward to the new version
