### ISSUE TITLE
indexedDBShim and Dexie

### ISSUE THREAD

**Issue by isuda** [dfahlander/Dexie.js#148]
Dexie prefers to use the indexedDBShim if it is loaded, even if native indexedDB is available (and not buggy). 
The default probably should be to use native indexedDB if available, falling back to indexedDBShim. Or, only use the shim if it is actually shimming. 

This is especially important in cases going forward where WebSQL is not available, but IndexedDB is (WKWebView on iOS9 for example). If the shim were to be included there, everything would break.

This would be a huge breaking change if implemented though, as it would break existing apps using WebSQL when indexedDB is available, which is a huge problem.

The change is fairly simple: https://github.com/AyogoHealth/Dexie.js/commit/b5f7965c422257aeffeffe2f0c2f272490578b06

Just wanted to get your thoughts on this.

**Comment by dfahlander** [comment]
The reason is that the safari idb implementation is so bad that it was desired to make it possible to use the shim instead. Still it's up to the user to include it or not.

**Comment by isuda** [comment]
I guess my use case is that I want to use the shim's default behaviour, which is to use the shim if needed.

Dexie however, will force use the shim if its loaded, instead of just defaulting to the shim's behaviour.
I can understand forcing use of the shim to maintain consistency across all browsers though, but I also don't want to have to conditionally load the shim at runtime either.

**Comment by dfahlander** [comment]
I see. Possible to solve like this as well after having loaded the shim and also dexie:
```js
if (dontWantShim) {
    Dexie.dependencies.indexedDB = indexedDB;
    Dexie.dependencies.IDBKeyRange = IDBKeyRange;
    Dexie.dependencies.IDBTransaction = IDBTransaction;
}
```
It would be nice to solve this more elegant though, but Apple makes the world a little bit complex as discussed in #110 (!), and as a non-apple user I'm not the one to solve and test this in the best way.

**Comment by dfahlander** [comment]
In Dexie v1.3.5-beta.2, you can provide indexedDB and IDBKeyRange arguments as options in the Dexie constructor:

```js
var db = new Dexie('dbname', {indexedDB: window.indexedDB, IDBKeyRange: window.IDBKeyRange});
```
