### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by zuidemasanne** [dfahlander/Dexie.js#150]
Hi i'm making a app where i can see labels and articles. I now see:
- kitchen
  - knive
  - fork

but i want:
- kitchen
  - knive
  - fork
- living room
  - chair
  - table
all the information is into the database

this is my code:

        <script>
            var db = new Dexie("zusa_app");
            db.version(1).stores({
                labels: 'name, status',
				artikelen : 'name, label_id, status'
				
            });
			
            db.open();

			function populateSomeData() {
				db.labels.where('status').equals(0).toArray().then(function(labels) {
					// For each label, resolve its articles:
					Dexie.Promise.all (labels.map(function (label) {
						return db.artikelen.where('label_id').anyOf(label.name).toArray();
					})).then(function(labelArticles) {
						for (var i=0; i<labels.length; ++i) {
							//console.log(labels.length);
							var label = labels[i],
							artikelen = labelArticles[i];
							
							log (label.name);
							var name = (artikelen.map(function(a){return a.name ;}).join(','));
							var array = name.split(",");
							console.log(array);
							
							var arrayLength = array.length;
							console.log(arrayLength);
							for (var i = 0; i < artikelen.length; i++) {
							    //alert(name[i]);
							    var artikelen= document.getElementById("log");
								var div = document.createElement("div");
							    var t = document.createTextNode(array[i]);
							    li.appendChild(t);
							    artikelen.appendChild("div");
							}
						}
					});
				});
			}

			function log(txt) {
				var div = document.createElement('div');
				div.className = "label";
				div.textContent = txt.toString();
				document.getElementById('log').appendChild(div);
				
			}
			
			

			 function runSamples() {
				populateSomeData()
			}
			
            
        </script>
        
        <style>
			.label{color:red;}
		</style>
    </head>
    <body onload="runSamples();">

        <div id="log"></div>

    </body>
</html>
[code]

**Comment by dfahlander** [comment]
I am sorry but I have not time to go through your code. Need to close this. Sorry!
