### ISSUE TITLE
Each time I want to add a contact into database, it's need me to open the database,

### ISSUE THREAD

**Issue by lygstate** [dfahlander/Dexie.js#151]
Is that possible that I only need to open the database in one shot and then I don't need to open it anymore?

**Comment by dfahlander** [comment]
Yes of course. You open it once on a page life time. You should reuse the db instance where needed in your app. If you write module based code, you should write a module that creates, configures and exports the db instance to use in your other modules. If you write plain script tags, you should leave db as a global var to use where needed.

**Comment by lygstate** [comment]
@dfahlander  Sorry for the unclear to clarify the problem, I am not talking about the reuse the db instance, I am talking about each time when I trying to add data into indexedDB by Dexie,
I have to calling the Dexie.open function before I calling to the Table.add 
function, is there anyway to avoid the duplicated calling to the Dexie.open function?

**Comment by dfahlander** [comment]
No, you should never call db.open() more than once in the instance life time. Have you looked at any of [these samples](https://github.com/dfahlander/Dexie.js/wiki/Samples)? Watch the TODO-list sample for example.

**Comment by lygstate** [comment]
@dfahlander I am using the ES6's generator along with co to writing down the code
And because of that, once I open the database and then calling to the .add method of Table, it's would be blocked, I've seeing the TODO demo, the put function is only called by one time.

**Comment by dfahlander** [comment]
What is co?
What framework are you using in order to utilize ES6 generator? Do you mean that you are using Dexie.Yield addon?

I really need some more info in order to help you.

**Comment by lygstate** [comment]
@dfahlander  I found the reason is because we delete the database. so after the delete, the database is closed.

**Comment by dfahlander** [comment]
Ok, great you found it! :)
