### ISSUE TITLE
Errors are now thrown when in each callback

### ISSUE THREAD

**Issue by ibc** [dfahlander/Dexie.js#154]
Example:

```js
db.messages.where('id').equals('abcd').each(function(message) {
  throw new Error('BUMP');
});
```

Nothing happens, no error is thrown at all.

Is this the expected behavior? I've read about [Promise.on.error](https://github.com/dfahlander/Dexie.js/wiki/Promise.on.error) but honestly I don't want to handle *any* error within a single callback **out** of the scope in which it happened.

Is there some option to let errors within given callbacks explode and produce a normal exception?

**Comment by dfahlander** [comment]
This is a generic behavior of Promise based APIs. You can catch error using the catch() method of the Promise returned by each().

```js
db.messages.where('id').equals('abcd').each(function(message) {
  throw new Error('BUMP');
}).catch (function (err) {
  console.error (err);
});
```

**Comment by ibc** [comment]
Thanks. Actually I did not realize that `each()` returns a Promise.
