### ISSUE TITLE
How to use two where(index) clauses?

### ISSUE THREAD

**Issue by ibc** [dfahlander/Dexie.js#155]
This fails:

```js
db.messages.where('chatId').equals(chatId).where('msgId').equals(data.msgId)

=> db.messages.where(...).equals(...).where is not a function
```

It's obvious since `where()` returns a `WhereClause`.

I hope I don't need to use `filter()` method since that is done in JS.

Thanks a lot.

**Comment by dfahlander** [comment]
If you need to filter this without .and() method, you need to index using a compound index. This will not work in IE/Edge or Safari though.
```js
var db = new Dexie('thedb');
db.version(1).stores({
    messages: 'id, chatId, msgId, [chatId+msgId]'
});
db.open();
db.messages.where('[chatId+msgId]').equals([chatId,msgId]).toArray().then(messages => {
    console.log(JSON.stringify(messages));
});

```

See [https://github.com/dfahlander/Dexie.js/wiki/Version.stores()](https://github.com/dfahlander/Dexie.js/wiki/Version.stores())

**Comment by ibc** [comment]
Clear. Thanks a lot.
