### ISSUE TITLE
 Error: Dexie specification of currently installed DB version is missing (again)

### ISSUE THREAD

**Issue by ibc** [dfahlander/Dexie.js#156]
I've checked #16 but could not find any solution in there.

Basically I've changed some table definition (`stores`) and cleared browser data for my domain (currently localhost). Then when running again my app `db.load()` fails with:

```
 Error: Dexie specification of currently installed DB version is missing
```

I've also tried to change `db.version(2)` but nothing changes.

I'm 100% lost. Do I miss something?

Thanks a lot.

**Comment by ibc** [comment]
NOTE: I've cleared browser domain data and restarted the browser (Chrome) and now it works.

I'm a bit afraid of some users of the app will suffer the same issue when they load the new version of the website...

**Comment by dfahlander** [comment]
Whenever you add a store or index to your schema, you must do that in another version, but keep the old version schema as long as there are users out there with the old version installed.

So basically, you would need to define both version(1) and version(2). This is explained in [Design#database-versioning](https://github.com/dfahlander/Dexie.js/wiki/Design#database-versioning).

To sum it up:

* Changes to schemas should be new versions of the schema, don't change the existing one.
* Keep all schema versions that have been published (that may exist out there...)

**Comment by ibc** [comment]
Clear, thanks a lot!
