### ISSUE TITLE
How is table.put() supposed to work?

### ISSUE THREAD

**Issue by ibc** [dfahlander/Dexie.js#157]
According to the [doc](https://github.com/dfahlander/Dexie.js/wiki/WriteableTable.put()):

```js
table.put(item, [key])
```

Let's say I've a "settings" table defined via `db.stores({ settings: 'key' });` in which I want that the `key` field is the primary (and hence unique) key, and `value` holds custom data.

Now I want to store `key: 'name',  value: 'alice'`, so I do:

```js
db.settings.put({ key: 'name', value: 'alice' });
```

The problem is that by calling the same code many times I end with many entries with same key "name".

Then I try:

```js
db.settings.put({ value: 'alice' }, 'name');
```

And get an error:

```
error inserting/updating setting [key:qwe, error:DOMException: Failed to execute 'put' on 'IDBObjectStore': The object store uses in-line keys and the key parameter was provided.(…)]
```

I must be missing something obvious...

**Comment by ibc** [comment]
Forget me. The first code above does work and overrides the existing entry. Something estrange happened in my IndexedDB viewer in Chrome in which I saw both entries at the same time...

**Comment by dfahlander** [comment]
put() will add or replace existing item in store.
If store uses in-line keys (as in your case), you cannot use the second optional parameter - key must be provided in given object.

Are you sure you get multiple instances of { key: 'name', value: 'alice' } ? That should not happen if store is defined as having "key" being the primary key. Please verify again that this is the case.

In case you want not to use in-line keys, you should omit "key" from stores specification (use empty string or prefix other indexes with a comma). In that case you must always provide the key parameter to put().

The API mimics the underlying [IDBObjectStore.put() method](http://www.w3.org/TR/IndexedDB/#idl-def-IDBObjectStore).

**Comment by ibc** [comment]
Thanks, I confirm it works fine. It is just that, as explained in my second comment, at some points I saw two entries in the Chrome Dev Tool IndexedDB viewer (but I do not trust it because it is never properly refreshed...).
