### ISSUE TITLE
SecurityError when storage is disabled

### ISSUE THREAD

**Issue by joaofernandes** [dfahlander/Dexie.js#158]
If a user disables cache (privacy settings > prevent all sites to set data), Dexie throws this error

Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

Line         

localStorage: ((typeof chrome !== "undefined" && chrome !== null ? chrome.storage : void 0) != null ? null : global.localStorage)

**Comment by dfahlander** [comment]
Thanks. localStorage we should then do a try/catch around localStorage because we don't really need it. It is only used for making [Dexie.getDatabaseNames()](https://github.com/dfahlander/Dexie.js/wiki/Dexie.getDatabaseNames()). Ill look into it later.

**Comment by joaofernandes** [comment]
Thanks!

**Comment by tdelmas** [comment]
Any update on that issue ?

**Comment by dfahlander** [comment]
No. Thanks for reminder

**Comment by dfahlander** [comment]
I hope the last checkin helps. However, if you forbid the browser from storing any any data locally, indexedDB would also be disabled, so expect another error, I suppose.

**Comment by tdelmas** [comment]
If I remember correctly, it happens in Safari in private mode (not sure if database is disabled too). But I think the lib can fail more gracefully than dying during initialization ;)

**Comment by dfahlander** [comment]
So true ;)

**Comment by dfahlander** [comment]
Solved in #1.3.4
