### ISSUE TITLE
Not working on Firefox OS Emulator 2.0

### ISSUE THREAD

**Issue by achintverma** [dfahlander/Dexie.js#159]
Hello, I've setup the Dexie on my Firefox mobile app project. It works fine when I open the app in Browser (Chrome and Firefox) but doesn't work (doesn't show anything in Storage section) when I run it in Firefox OS as an app. 

App has privileged permissions so that shouldn't be issue. Any ideas??

**Comment by dfahlander** [comment]
Could you debug the app and see if any exception occur (try F12 and check the debugger to stop on caught exceptions)

**Comment by achintverma** [comment]
Hello, Thanks for reply. I checked with debugger, there's no error.

**Comment by achintverma** [comment]
Hello, I figured our that the issue was with the Firefox OS simulator. It was not showing me the records on the Storage tab but the data was there. I wrote get query and it pulled back added data.
