### ISSUE TITLE
dexie database gets deleted in chrome with cookies deletion

### ISSUE THREAD

**Issue by nidhipurnapatre** [dfahlander/Dexie.js#160]
Dear sir,
When I create dexie database in firefox, even if I deletes cookies or clears cache, it remains in predefined folder but In chrome it gets deleted with cleanup cache. Is any other settings are needed?

**Comment by dfahlander** [comment]
The IndexedDB API do not provide any flag whether to survive a cleanup of cache/cookies. The two browsers behave differently in this matter.
