### ISSUE TITLE
Multiple sorts

### ISSUE THREAD

**Issue by nidhipurnapatre** [dfahlander/Dexie.js#161]
Hi!
I want to multiple sort criteria on multiple columns 
e.g.
.reverse().sortBy("ColA")
.sortBy("ColB"), 

but as sortBy is not returning collection it is not straight forward.

Please suggest.
My current query is
       table.where('colA').equalsIgnoreCase(specialty).and(
          function (x) {
              if (search == null)
                  return true;
              else
                  return x.Value.toLowerCase().search(search) >= 0;
          })
          .reverse().sortBy("Priority")
         // .sortBy("Value")
           .then(function (dbdata) {
                // ...
          }

where .sortBy("Value") has error naturally.

Thanks in advance.

**Comment by dfahlander** [comment]
sortBy("Priority") is only sugar for:
```js
toArray(a => a.sort((a,b) => a.Priority < b.Priority ? -1 : a.Priority > b.Priority ? 1 : 0);
```
So you could do:
```js
toArray(a => a.sort((a,b) => a.Priority < b.Priority ? -1 : a.Priority > b.Priority ? 1 :
    a.Value < b.Value ? -1 : a.Value > b.Value ? 1 : 0);
```
Sorry for using the ES6 arrow syntax, but I find it easier to read. Hope you get how to write it in ES5.

**Comment by yogesh021** [comment]
@dfahlander Your solution will return an array, what if I want table ?

**Comment by dfahlander** [comment]
@yogesh021 Not possible to get a Table or Collection instance that is ordered on anything else than a single or compound index. There will probably be a new version that will allow this in the future but not in <= 3.1.0.

**Comment by yogesh021** [comment]
compounded index is not supported on Internet Explorer, non-chromium Edge and Safari < v10, is there any way around for sorting or ordering with multiple columns and using methods like offset, reverse etc with the returned value ????

**Comment by dfahlander** [comment]
> compounded index is not supported on Internet Explorer, non-chromium Edge and Safari < v10, is there any way around for sorting or ordering with multiple columns and using methods like offset, reverse etc with the returned value ????

I'm not sure the limitations of Internet Explorer and old Edge browsers will be a problem in 2021. They represent less than 1% of browsers out there. If you still need an answer, you can still pick one index for sorting and use a JS filter to filter and utilize the index for sorting only.

See updated docs for this here: https://dexie.org/docs/Collection/Collection.offset()#a-better-paging-approach
