### ISSUE TITLE
Update a subfield

### ISSUE THREAD

**Issue by ibc** [dfahlander/Dexie.js#162]
Let's have a DB entry with `id: 100` and this content:

```js
{
    body:
    {
        color: 'red',
        background: 'green'
    }
}
```

and I want to replace the `background` subfield to `blue`. Can I do something like this?:

```js
db.foos.update(100, { body.background: 'blue' })
```

If not, is there an alternative without having to retrieve all the `body` content and modify it before doing the `update()`?

**Comment by dfahlander** [comment]
```js
db.foos.update(100, { 'body.background': 'blue' });
```

**Comment by ibc** [comment]
Great. Is that also valid for `modify()`?

**Comment by ibc** [comment]
Sorry, tested, and yes, valid :)
