### ISSUE TITLE
How do you get ALL records from a table

### ISSUE THREAD

**Issue by xavibonell** [dfahlander/Dexie.js#164]
It might seem silly, but I can't find it anywhere, the documentation always assumes that you want to retrieve a certain value matching a key, but what if I want all the records from a table (which I think is a pretty common case), I should be able to use something like Table.get(*) or just Table.get().
I appreciate any help. Thanks!

**Comment by dfahlander** [comment]
```js
db.table.toArray()
```
or
```js
db.table.each(callbackFn);
```

**Comment by xavibonell** [comment]
Yes I found it in the documentation a little bit afterwards, what a shame it was right there. Thank you for your support!!

**Comment by veenitchauhan** [comment]
but this only returns a promise what if I need to return the array itself?

**Comment by dfahlander** [comment]
@veenitchauhan This is the nature of asynchronic APIs. Have a look at [this tutorial](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises) that guides you about how to use promises.
