### ISSUE TITLE
Need Help: Writing multiple where conditions or where with orderBy

### ISSUE THREAD

**Issue by achintverma** [dfahlander/Dexie.js#167]
Hello, Thank you for your prompt reply on my previous question regarding Firefox OS IDE. That's resolved and things are working great. 

Today I stumbled on an issue: I have a table called perms which stores following fields

` 'appname', 'permission','timestamp' `

Now I want to query something like: 
`where 'appname'='Facebook' and 'permission'='geolocation' get unique 'permissions'`

I read the documentation carefully and see that `whereClause` can be applied only on a `Table` and when that function runs, it returns a 'Collection' so we can't run 2 where statements in 1 go. 

Same with the `orderBy` method, that it can run only on `Table` so I can't use `where` and `orderby` together. 

Any suggestions or pointers will be of huge help. I think if there was a method like `toTable` to convert from Collection to Table, I could run multiple where for a table.

**Comment by dfahlander** [comment]
Use a compound index on appname+permission.

Schema :
```js
db.version(1).stores ({
    apps: "id,appname,permission,[appname+permission]"
});
```
Query 
```js
db.apps
    .where ("[appname+permission]")
    .equals(["Facebook", "geolocation"])
   . toArray()
```
Note: I'm aware of the needs for orderBy on Collection and multiple where clauses. Reason that it's not allowed is that they would give the false impression that the db could perform these queries in an optimized way, which is not the case if ordering on another index than querying, or trying to btree search multiple indices.

**Comment by dfahlander** [comment]
Fault. It is actually possible to define the order of a result using Dexie or plain indexedDB. Use compound index for ordering.

Sample in SQL

```sql
SELECT * FROM perms WHERE appname='Facebook' AND permission='geolocation' ORDERBY timestamp;
```

Would translate to the following Dexie code:
```js
// Schema
db.version(X).stores({
    perms: ',[appname+permission+timestamp]'
});

// Query
db.perms
    .where('[appname+permission+timestamp]')
    .between(['Facebook', 'geolocation', -Infinity], ['Facebook', 'geolocation', '\uffff']);
```

The *order by* is achieved by the third part of the compound index. Instead of *equals()* method, I use *between()*. Using `-Infinity` as lower bound ad `'\uffff'` as upper is a way to get the entire span of values no matter type. If we'de used Infinity instead of '\uffff' the query would just be compatible with numbers but not with Dates or strings. This way it is compatible with any type.

**Comment by achintverma** [comment]
Thanks @dfahlander

**Comment by fulltic** [comment]
Hi!! Can you help me, please. It's possible 

 db.customers.where("[surname+doc]").
                    startsWithIgnoreCase(["example_surname", "example_doc"]).
                    each(function (customer) {
                        customers.arrayResult[customer.id] = customer;
                    })
            );

The error is "String expected.", with "equals" is ok, but with "startsWithIgnoreCase" It is not possible to receive an array.

Thank you very much!!

**Comment by dfahlander** [comment]
IgnoreCase only possible with simple indexes unfortunately :(

You might consider maintaining a lowercase version of surname in another property and use a compound index with that property + doc.
