### ISSUE TITLE
Multiple AND & OR query

### ISSUE THREAD

**Issue by saskomateski** [dfahlander/Dexie.js#168]
This is my table definition:

    db.version(1).stores({      
                ...
                discountlist: '++id,[ClientCodeType+ItemCodeType],[ItemCodeType+ItemCode],[ItemCodeType+ItemCode+DLItemSubGroupID]',
                 ...
            });

and this is the query:

    var discount = db.discountlist
                            .orderBy('[ClientCodeType+ItemCodeType]')                            
                            .and((disc: IDiscountlist) => {
                                return disc.MatrixType == matrixType
                                    && (new Date(disc.fromDate) < wDate
                                        && new Date(disc.toDate) > wDate)
                                    && (
                                        (disc.ItemCodeType == '3' && disc.ItemCode == item.ItemGroupId && disc.DLItemSubGroupID == item.ItemSubGroupId)
                                        || (disc.ItemCodeType == '2' && disc.ItemCode == item.ItemId)
                                        || (disc.ItemCodeType == '1' && disc.ItemCode == item.ItemGroupId)
                                        || (disc.ItemCodeType == '0' && disc.ItemCode ==    '*')                                                        
                                    )
                                    && ((   disc.ClientCodeType == '3' && disc.ClientCode == clientId && disc.ClientObjectId == objectId)
                                        || (disc.ClientCodeType == '2' && disc.ClientCode == clientId && disc.ClientObjectId == '--')
                                        || (disc.ClientCodeType == '1' && disc.ClientCode == discountGroupId)
                                        || (disc.ClientCodeType == '0' && disc.ClientCode == '*'))
                            })
                            .reverse()
                            .first();

Is there a way to rewrite this so to get a better performance (better usage of defined indexes or defining missing indexes)?
                            ;

**Comment by dfahlander** [comment]
A general approach is to decide upon an index that will limit the search as much as possible so that the extracted data in the where-clause filters out the most and the and() filter complements this.

Don't exactly know how ClientCodeType and ItemCodeType helps out here or how your data table may grow. But generically time-stamps are good to index because you can utilize the btree capability of indexedDB by filtering on fromDate or toDate.

You want to find an item who's fromDate-toDate will overlap with the provided wDate, plus other criterias. If items are spread over time, you should probably index either fromDate or toDate and do: 
```ts
db.discountlist.where('fromDate').below(wDate.getTime())
    .and(yourCriteriaFilterFn)
    .reverse() // Will start iterating on the highest date closes to wDate
    .first()
```

**Comment by saskomateski** [comment]
Would you say that the following wil be a more performant query (since it'll use two indexes that will considerably limit the search): 

    var discount = db.discountlist.
                            where('[ItemCodeType+ItemCode+DLItemSubGroupID]').equals(['3', item.ItemGroupId, item.ItemSubGroupId])                            
                            .or('[ItemCodeType+ItemCode]').equals(['2', item.ItemId])
                            .or('[ItemCodeType+ItemCode]').equals(['1', item.ItemGroupId])
                            .or('[ItemCodeType+ItemCode]').equals(['0', '*'])
                            .and((disc: IDiscountlist) => {
                                return disc.MatrixType == matrixType
                                    && (new Date(disc.fromDate) < wDate
                                        && new Date(disc.toDate) > wDate)
                                    && ((   disc.ClientCodeType == '3' && disc.ClientCode == clientId && disc.ClientObjectId == objectId)
                                        || (disc.ClientCodeType == '2' && disc.ClientCode == clientId && disc.ClientObjectId == '--')
                                        || (disc.ClientCodeType == '1' && disc.ClientCode == discountGroupId)
                                        || (disc.ClientCodeType == '0' && disc.ClientCode == '*'))
                            })
                            .toArray() ;

Only that right now with the limited knowledge I have of IndexedDB (and Dexie.js) I'm not sure if both queries have the same meaning.

**Comment by dfahlander** [comment]
To decide which index to use, one must know what the data looks like. For example, if 90% of the rows in a table would have ItemCodeType=0 and ItemCode="*", this query would not be good, but if EACH of the or-expressions filters out 90% of the data, it would be ok.

The query you provided will in parallell launch 4 indexedDB queries (one for each or() expression).

At the end of the day, you would want an index that performs well no matter how large the table would grow. If the table is small enough and always will be, you could be fine by just doing db.table.filter(customFilterFn), but if your table may grow a lot over time, use a time stamp index to filter out the results and you know that old entries wont slow down the future queries.

**Comment by saskomateski** [comment]
OK, we'll have to analyze our data and queries having in mind the guidelines you gave us, and after some testing come to a near optimal solution.

Thanks for the quick and thorough answers, and also for the great library.
