### ISSUE TITLE
Request blocked when trying to delete all databases

### ISSUE THREAD

**Issue by andersekdahl** [dfahlander/Dexie.js#17]
First off, thanks for this great library!

I have a use case where I (for dev purposes) want to have a button to delete all databases. Thanks to `Dexie.getDatabaseNames()` I can get all names, and I can call `Dexie.delete()`, but all I get are promises that never resolves/rejects because I have open connections to these databases around my application.

Since Dexie returns all instances, would it be possible to have some internal tracking of all open connections to allow this to work? Something like a `Dexie.deleteAllDatabases()` which would first iterate over all open connections, close them and then delete them?

**Comment by bennyn** [comment]
I tried listening to `versionchange` but it looks like Dexie v1.4.2 replaced that with the `blocked` listener behvaiour which will receive a `IDBVersionChangeEvent`, am I right?

**Comment by dfahlander** [comment]
No, 'blocked' and 'versionchange' are separate events. Dexie 1.4 has a default versionchange listener that closes itself. This means that you no longer have to worry about forgetting to close your database in case another page wants to upgrade or delete it. It wont block anymore and you dont need this workaround.

Flow:
1. Page A creates a new Dexie instance and calls db.open();
2. Page B holds already another connection to the same database but older version, so it receives 'versionchange' event. Default implementation will close page B's database.
3. If page B overrides default implementation and does NOT close database upon 'versionchange' event, the 'blocked' event will fire on Page A.
