### ISSUE TITLE
combined index where equal on one part and sorted on the other

### ISSUE THREAD

**Issue by urpro-bas** [dfahlander/Dexie.js#171]
I have some kind of a logging table in Dexie and every entry in those logs is identified by a logId and a logdate. I would like to find the first date and last date for a given logId. I guess this could be optimized by indexes, but I don't know how to do it in Dexie. I have been trying to create a combined index and only pass the logId to the WhereClause.equals, but that does not seems to work, is there any other solution?

**Comment by dfahlander** [comment]
You would need to use a compound index. The built-in ordering will always be on the same index that you query in the where-clause. How to utilize this in a query is not obvious but you can do a between()-query and between the lowest and highest possible dates:

```js
// schema
var db = new Dexie("logdb");
db.version(1).stores({
    log: 'id,[logId+logDate]'
});

var MIN_DATE = new Date(1970, 1, 1),
    MAX_DATE = new Date(3000, 1, 1);

function getMostRecentLogEntry(logId) {
    return db.log
        .where('[logId+logDate]')
        .between([logId, MIN_DATE], [logId], MAX_DATE)
        .last();
}

function getOldestLogEntry (logId) {
    return db.log
        .where('[logId+logDate]')
        .between([logId, MIN_DATE], [logId], MAX_DATE)
        .first();
}

```

**Comment by dfahlander** [comment]
In case you store dates as plain Numbers:

```js
return db.log
        .where('[logId+logDate]')
        .between([logId, -Infinity], [logId], Infinity)
        .last();
```

**Comment by dfahlander** [comment]
Noticed you actually only needed the last date on a particular logId. You could get that even more optimal:

```js

db.log
    .where('[logId+logDate]')
    .between([logId, -Infinity], [logId, Infinity])
    .lastKey()
    .then(function (logIdAndDate) {
        return logIdAndDate[1]; // return just date
    });
```

**Comment by dfahlander** [comment]
Notice that compound indexes for doesnt work on IE, Edge or Safari. In that case you can build your compound index manually by concatenating logId+date into a property and index that property.

**Comment by urpro-bas** [comment]
thanks, this was what i was looking for.

i am currently only using opera (so chromium), it's just some tool for myself for now so no need for advanced crossbrowser support.

btw I had index called dateTime, but this did not seem to work on a combined index, but it did seem to work as a single index.

**Comment by dfahlander** [comment]
The index names are case sensitive. But no restriction on property names. Just make sure to declare and use the index as exactly "[logId+dateTime]" without any space character. Good luck with your tool.
