### ISSUE TITLE
Announcement of a breaking change

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#177]
Hi!

src/Dexie.js will soon be ES6 based and a build step will be required to produce the distributed ES5 version of this library. The automated build step will hopefully result in a more frequent release prodecudure.

In summary:

* Users of the npm package will continue using dexie as normally.
* es6 based libraries will be able to import the esnext based module.
* If you include Dexie.js in a script tag, you will have to include dist/dexie.js rather than dist/latest/Dexie.js or src/Dexie.js.
* Manual require-configs that points to src/Dexie.js must be changed to dist/dexie.js.
* Manual require-configs that points to dist/latest/Dexie.js must be changed to dist/dexie.js.
* Addons will be published as own npm packages with nomenclauture "dexie-something".

The change will take place during the coming month or so. To preview these changes, checkout the **es6 branch**. I'm still working on converting the addons.

Any thoughts? Will it break too much?

**Comment by TakahiRoyte** [comment]
I believe the changes are on the right track:)
I'm using npm so there will be no problem, and for those of ppl who don't, it only takes little time to change their configs.

**Comment by busticated** [comment]
if I use npm but still prefer to ship es5 to end-users (client-side), am I going to need to run babel?

**Comment by dfahlander** [comment]
No, dist directory will still contain the transpiled es5 version, named 'dexie.js'.

https://github.com/dfahlander/Dexie.js/tree/es6/dist.

**Comment by busticated** [comment]
:+1: thanks!

**Comment by dfahlander** [comment]
Everything finished in es6 branch now. Just had some merge problems that I'm gonna look at on monday.

Will not have dist checked in at all. So the download link for dexie.js will not be on github but looking to link to npmcdn.com for download instead. That way npm / npmcdn will be the only place were dist files will be put. Probably the way it should be done.

Dexie v1.3 will be released next week, soon after the merge from es6 branch. There will be quite a lot news since 1.2 that I will summarize in a release notes. Some of the news will be:

* new WhereClause methods
* built-in support for using yield as async in transaction blocks.
* ES6 package
* Better typescript support.

**Comment by dfahlander** [comment]
ES6 branch merged into master. All tests pass. Ran with my own product and seems to work well. Releasing soon. Made a release script that actually checks in dist files, tags the release, npm publish and then reverts adding the dist files. Reason for this dance is to continue supporting bower, which demands to have dist files checked in.

Addons will have their own npm packages but Dexie.Yield.js will be a built-in feature instead of an addon.

The wiki is updated to reflect the changes but not yet committed.
