### ISSUE TITLE
Is it possible to lock the DB and add a pending action queue?

### ISSUE THREAD

**Issue by secondl1ght** [dfahlander/Dexie.js#1784]
I have a use-case that has potential to cause bugs and I would like to know if there is a way to handle this natively with Dexie. 

The flow would be as follows:

- there is a table in Dexie with a unique primary key and inside that table one of the fields is an Array
- in order to add a new record to the Array you first need to `get` the row by it's primary key to read the current data, then add the new record to the Array, and then `update` the row with the new field which has a new length of + 1.
- this flow can happen either by direct user action or by a message coming in from a websocket in the background
- there can be multiple `get`/`update` functions running at the same time and can resolve at different times due to depending on an external API
- this means that unless the `update` is completed for Function A before Function B runs its `get` then the `update` from Function A will be overwritten and lost when Function B updates the DB without knowledge of the other newly added record
- and this can happen with any X number of Functions overwriting eachothers updates unless they are completed in the right order

So my question is, is there a way to lock the DB and setup a pending queue of edits with Dexie? So that you can ensure the updates happen in the right order and no data is lost when running multiple `get`/`update` Functions at the same time. These Functions depend on external APIs and can lead to race conditions.

I am thinking this problem is not unique to my application so there may be a way to handle these cases.

Thank you

**Comment by dfahlander** [comment]
You'd need to get and update the object within a transaction. However, make sure not to query the external API within that transaction. Instead query API first, then do the transaction with a get and a put.

**Comment by secondl1ght** [comment]
Thanks for the response, is there an example of how to properly implement something like this? My specific use-case would be to use Dexie as a local client-side DB for a chat messenger application. 

So a there could be messages being sent/received at the same time that need to be added to the DB. When sending a message there will also be multiple `status` states that will need to be updated on the message record in the DB in real time like `failed` or `success`. 

So there could be several database read/writes happening all within the same time period if a conversation is happening quickly.

I looked at the Transaction documentation but it wasn't exactly clear to me how that can be used to implement the desired behaviour of not having DB conflicts. Will switching every DB action to a transaction fix this problem even if the actions are happening from many different scopes within the application?

Is this the right page to read to try and understand how Transactions solve this? https://dexie.org/docs/Dexie/Dexie.transaction()

**Comment by dfahlander** [comment]
Yes, IndexedDB transactions are [ACID](https://en.wikipedia.org/wiki/ACID) and solves exactly this,

**Please read the docs! There are plenty of samples: https://dexie.org/docs/API-Reference#transaction**

*Think of a transaction as a lock where you lock the given tables so that any other piece of code trying to lock the same tables would block before entering it.*

**Comment by dfahlander** [comment]
You can read about database transactions in general: https://en.wikipedia.org/wiki/Database_transaction

**Comment by secondl1ght** [comment]
Thanks I will read all of these docs! It sounds great, one last question for now is: you mentioned to use a `get` and `put` but is it also OK to use a transaction with `get` and `update`? Update makes more sense for this I think because I am only updating one of the column values in the table and not the entire row.

> You'd need to get and update the object within a transaction. However, make sure not to query the external API within that transaction. Instead query API first, then do the transaction with a get and a put.

**Comment by dfahlander** [comment]
> Thanks I will read all of these docs! It sounds great, one last question for now is: you mentioned to use a `get` and `put` but is it also OK to use a transaction with `get` and `update`? Update makes more sense for this I think because I am only updating one of the column values in the table and not the entire row.
> 
> > You'd need to get and update the object within a transaction. However, make sure not to query the external API within that transaction. Instead query API first, then do the transaction with a get and a put.

Absolutely, update is also ok - it's just that update will internally do get and put because IndexedDB doesn't have update natively, so if you do a get anyway, it's easier to just manipulate the object as you like and then put the result back. Update would imply another get after your get.

**Comment by secondl1ght** [comment]
Great thanks for the tip, looking forward to implementing these transactions!
