### ISSUE TITLE
DOM Blocking/Locking

### ISSUE THREAD

**Issue by tolian49** [dfahlander/Dexie.js#180]
I was trying to put in place a status bar during a long operation that inserts records to the DB. The idea is that prior to each add I would update the x of y value which could easily be a progress bar then too. However I'm noticing that the HTML wont update until after all of the transactions are done. I'm not clear on exactly what's  blocking the DOM from updating. I note that I can log the value to the console and watch it tick up as it goes. 

Any ideas are very helpful, I notice that this does prevent things from occurring on the page as well other than the loading that I was trying to accomplish. It's minor, but a load of 10 seconds can be noticeable as the recordset grows >10,000 rows.

Here's some code as an example of how that would work via an ajax call where dbW is my dexie instantiated database:

function getInventory(){

        if(gettingInventory == 1) return;
	gettingInventory=1;
	dbW.inventory.clear().then( function(){
        return new Dexie.Promise(function (resolve, reject) {
			$.ajax('/Transactions/sync/getInventory.cfm', {
				type: 'get',
				dataType: "json",
				error: function (xhr, textStatus) {
					reject(textStatus);
					gettingInventory=0;
				},
				success: function (data) {
					// Resolving Promise will launch then() below.
					//alert(data);
					resolve(data);
				}
			});
		}).then(function (data) {
			return dbW.transaction('rw', dbW.inventory, function () {
				data=queryToObject(data);
				var invLoadCount=0
				data.forEach(function (item) {
					invLoadCount++;
					$('#invLoadStatus').text(invLoadCount + ' of ' + data.length);
					console.log(invLoadCount + ' of ' + data.length)
					dbW.inventory.add(item);
				});
			});
		}).then(function () {
			console.log ("GetInventory Sync committed");
			dbW.inventory.count(function(val){$('#inventoryCount').html(val)});
			gettingInventory=0;
			$('#inventoryTime').html(curTime())
		});

	});
}

**Comment by dfahlander** [comment]
As blogged about by @nolanlawson, this is an issue in some browsers but not others (http://nolanlawson.com/2015/09/29/indexeddb-websql-localstorage-what-blocks-the-dom/). Can be worked around by using indexedDB from a WebWorker.

**Comment by tolian49** [comment]
I'm unsure about how to integrate the syncs with a web worker exactly but will look into it more. Generally I have the sync functions updating a few dom elements and my understanding is that the web worker based functions then cant access the dom, just the indexeddb...

**Comment by dfahlander** [comment]
You will need to communicate from the WebWorker to the Dom through postMessage ()

**Comment by nolanlawson** [comment]
@tolian49 These days I recommend using IndexedDB inside of a WebWorker 100% of the time because of this issue. Dexie, in my tests, works perfectly inside of a WW. :)

Web Workers are dead easy to work with; here's an example: http://bl.ocks.org/nolanlawson/28eebac3b91feeeabc6e

**Comment by tolian49** [comment]
Thanks for the info! I've had success with setting it up as a worker
process and youre right it doesnt lock now. Many thanks.
