### ISSUE TITLE
bulk actions : delete & put

### ISSUE THREAD

**Issue by t8g** [dfahlander/Dexie.js#184]
I found & used bulkAdd with great success.
https://github.com/dfahlander/Dexie.js/blob/master/src/Dexie.js#L1033

Is there any plan to add bulkPut and bulkDelete as well?

Thanks,
Thomas

**Comment by dfahlander** [comment]
Would be good to have, I suppose. Bulk delete could be done today via db.table.where(':id').anyOf(idsToDelete).delete().

Also thinking of a bulkChanges() method or what it would be called as well, that could take an array of [DatabaseChange](https://github.com/dfahlander/Dexie.js/wiki/Dexie.Observable.DatabaseChange) with a mix of put/add/deletes.
