### ISSUE TITLE
1.3.1 TypeScript example doesn't work with Browserify

### ISSUE THREAD

**Issue by dpogue** [dfahlander/Dexie.js#186]
The TypeScript code is set up assuming ES6 modules with a default export are used, but in practice dexie.js does not use a default export.

Trying to subclass Dexie then fails:

```typescript
import Dexie from 'dexie';

class MyDB extends Dexie {
  // ...
}
```

Generates the following JS:
```javascript
var dexie_1 = require('dexie');

var MyDB = (function(_super) {
  __extends(this, _super);
  // ...
})(dexie_1.default);
```

When running in Browserify, `dexie_1.default` is undefined, leading to an error when the `__extends` helper tries to inherit the prototype.

**Comment by dfahlander** [comment]
Dexie does default export in its source version at src/Dexie.js and in dist/dexie.es6.js. The UMD module may not do this correctly though. In the typescript sample in samples/typescript in the github repo, I use a setup with tsc + babel (leaving es6 module format) + rollup that works fine. Haven't tested the setup with tsc + babel + browserify, but I suppose that combo is common.

Any suggestion on how to fix it? :)

**Comment by dfahlander** [comment]
Seems tsc behaves differently when targeting es5.

https://github.com/Microsoft/TypeScript/issues/5285

I've updated the README.md to clarify that you need to target es6 for the sample to work.

**Comment by dfahlander** [comment]
Ok, so now I've found a workaround that makes dexie.d.ts work both when tsc is targeting es5 and es6. SImply setting Dexie.default = Dexie makes it work in both cases and does not interfere with anything else.

**Comment by dpogue** [comment]
It's working now. Thanks!
