### ISSUE TITLE
Dexie with Angular 2

### ISSUE THREAD

**Issue by EliseoAzpeitiai** [dfahlander/Dexie.js#187]
I am creating a project with angular 2 and Gulp but wen trying to use Dexie I have the following problem :

> GET http://localhost:5000/dexie 404 (Not Found)f
> deps.js:47711 Error: XHR error (404 Not Found) loading http://localhost:5000/dexie(…)

Declaration:
import Dexie from 'dexie';
...
export class Context extends Dexie {
    constructor() {
			super("database")
    }

**Comment by dfahlander** [comment]
Are you using requirejs? If so, did you miss to locate dexie in the require.config? The location differs from Dexie v1.2. In v1.3, the location should be

require.config({
    paths: {
        "dexie": "node_modules/dexie/dist/latest/dexie.min"
    }
});

or if you want to fetch it over the net:

require.config({
    paths: {
        "dexie": "https://npmcdn.com/dexie@1.3.1/dist/dexie.min.js"
    }
});

**Comment by dfahlander** [comment]
My bad requirejs config. Should be:

```js
require.config({
    paths: {
        "dexie": "node_modules/dexie/dist/latest/dexie" // Won't work with 'dexie.min'
    }
});
```
or if you want to fetch it over the net:
```js
require.config({
    paths: {
        "dexie": "https://npmcdn.com/dexie@1.3.1/dist/dexie"
    }
});
```

**Comment by EliseoAzpeitiai** [comment]
I don't use requireJs. I use Gulp 
```

var config = {
    scriptsPath: "./wwwroot/scripts/",
    cssPath: "./wwwroot/css/",
    depsFiles: [
            "./node_modules/systemjs/dist/system.src.js",
            "./node_modules/es6-shim/es6-shim.js",
            "./node_modules/dexie/dist/dexie.min.js",
            "./node_modules/rxjs/bundles/Rx.js",
            "./node_modules/angular2/bundles/angular2.dev.js",
            "./node_modules/angular2/bundles/http.js",
            "./node_modules/angular2/bundles/router.js",
            "./node_modules/angular2/bundles/angular2-polyfills.js"
    ],
    cssFiles: [
            "./node_modules/bootstrap/dist/css/bootstrap.min.css"
    ]
};

// Bundle js files
gulp.task('bundle:js', function () {
    return gulp.src(config.depsFiles)
      .pipe(concat("deps.js"))
      .pipe(gulp.dest(config.scriptsPath))
      .pipe(rename("deps.min.js"))
      .pipe(uglify())
      .pipe(gulp.dest(config.scriptsPath));
});

```
The other modules are differents with dexie. For example rxjs is include in deps.js:
```
System.register("rxjs/util/noop", [], true, function(require, exports, module) {
  var global = System.global,
      __define = global.define;
  global.define = undefined;
  function noop() {}
  exports.noop = noop;
  global.define = __define;
  return module.exports;
});
```
but dexie don't use Sytem.register

**Comment by dfahlander** [comment]
Have you tried with the version I just released today (v1.3.2)? Solved issues that affected projects using typescript/requirejs and typescript/browserify. I also added support for systemjs by adding a jspm element to package.json.

Please give :+1:  or :-1:  if it solves the issue or not. If not, I'll try diving into it as well.

**Comment by dfahlander** [comment]
To clarify, Dexie should now adapt better to ES6 based build systems by providing both jsnext:main and jspm.main attributes in package.json. There are lots of stacks out there to support, but I'll try my best to fix it.

**Comment by EliseoAzpeitiai** [comment]
:-1: Not work

**Comment by EliseoAzpeitiai** [comment]
If I change the dexie/dist/dexie.js by
```
System.register("dexie", [], true, function(require, exports, module) {
  var global = System.global,
      __define = global.define;
  global.define = undefined;
(function (global, factory) {
....
```
this work fine.

**Comment by dfahlander** [comment]
Thanks!

I think you can configure Systemjs to handle other module formats. Dexie currently supports AMD, CommonJS and ES6. dist/dexie.js supports AMD,COmmonJS and plain script includes. dist/dexie.es6.js is in ES6 format.

You'll probably stumble on a couple of other modules as well with the same problem. If I'm not mistaken, you can make your system.js be capable of loading other formats, have a look at https://github.com/ModuleLoader/es6-module-loader. Also, check out http://jspm.io which seems to be promising.

Cheers,
David
