### ISSUE TITLE
Dexie, typescript. requirejs

### ISSUE THREAD

**Issue by JeffB1** [dfahlander/Dexie.js#188]
Am really struggling to get this combination to work. In your document you have the following

> `import Dexie from 'dexie';`
> 
> Assuming you have moduleResolution: "node" in your tsconfig, this will work out-of-the-box. If you use requirejs, you'll have to configure your require locations.

So I have a require config set up like this:

```
require.config({

    baseUrl: '/',

    paths: {
        //main libraries
        jquery: 'scripts/jquery-2.2.1',
        dexie: 'node_modules/dexie/dist/dexie.min'
    },

    shim: {
        jquery: {
            exports: '$'
        }
    }
}); 
```
Now if I do something like this to kick off the application:
```
require(['jquery','dexie'], function ($) {
    $(document).ready(() => {
        alert('Started');        
    });
});

```
it starts ok which indicates to me that requirejs is set up ok. Indeed, if I change the path in the require.config, it errors out showing the path is wrong. So this part seem ok to me.

However, I can't import Dexie properly to use it in my own typescript modules.

```
/// <reference path="../../../Scripts/typings/dexie/dexie.d.ts" />
import Dexie = require('dexie');

```
The 'dexie' in the require statement is not found.

`import Dexie from 'dexie';
`
Doesn't work either :-( 

Any ideas? I have spent so much time on this. Am pulling my hair out...

**Comment by dfahlander** [comment]
Typings of version 1.3 is bundled in dexie's npm package (or bower package if using bower) under dist/dexie.d.ts. Try reference that file. Since package.json can include the typings property, tsd and Defenitely typed is no more needed for Dexie.

Hope that solves the issue!

In the typescript sample under samples in the gihub repository, there are no typings required, but that one uses node as module resolver.

**Comment by dfahlander** [comment]
I've pull-requested DefinitelyTyped with the latest version of the typings now. It's a little of a pain having to do that so I thought I could just skip that step. For now, the files are updated at both places.

Did the changed version of d.ts solve your issue?

**Comment by JeffB1** [comment]
No its not. At it's most basic I have this in my ts file:
```

/// <reference path="../../../node_modules/dexie/dist/dexie.d.ts" />
export class POSDatabase extends Dexie {}
```

Visual Studio is not showing an error with the reference path so I would assume it is correct. But the extends Dexie part is showing Dexie as an error - Cannot find name 'Dexie' .

**Comment by dfahlander** [comment]
You still need to import Dexie using the es6 module format:

import Dexie from 'dexie';

You must be using a new tsc version (I tested with typescript version 1.8.7).

Have you tested the [typescript](https://github.com/dfahlander/Dexie.js/tree/master/samples/typescript) sample? It uses tsc --> es6 and then babel it to es5.

There's also #186 that I recently fixed (but not yet released) but that one does not complain when compiling - only runtime.

**Comment by JeffB1** [comment]
I installed TypeScript Tools for Microsoft Visual Studio 2013 1.8.5.0 which as far as I can tell is the latest version (https://github.com/Microsoft/TypeScript/releases). However, when I run 'tsc -v' I get 1.0.3.0. It can't be that old though because there would be plenty of other stuff that wouldn't work, I would have thought.

I haven't tested typescript sample because I'm using requirejs which that example doesn't use. However, I see in that issue #186 that you say you it has to be es6. My project is set up to compile to es5 :-( So is it possible that is where the issue lays? I changed to es6 and did a full rebuild of the solution and it still doesn't seem to want to compile.

**Comment by dfahlander** [comment]
I've been struggeling with this case entire morning, trying to make requirejs work with Dexie and typescript... Keep you updated.

**Comment by dfahlander** [comment]
Ok, so I got it working at last. It was suffering from the same issue as #186 as well as that require.js did not like configuring the dexie.min file. Had to change require.config to:

```js
require.config({
        dexie: 'node_modules/dexie/dist/dexie' // Don't use dexie.min
    }
});
```

Added a sample for this under samples/typescript-simple. Please check it out. If you still have problems, please reopen this issue.

**Comment by dfahlander** [comment]
Note that you need dexie v1.3.2 to get it working.

**Comment by JeffB1** [comment]
Thanks for your assistance to date. I'm really looking forward to getting to a point where I can use dexie!

I can now get this compiled and when I run it, it has created a database. So technically it appears to be working.

However, in VS2013 it still doesn't seemed to have picked up the dexie.d.ts properly. It shows all references to dexie as an error (with the red squiggly line). However, I can build it and it does work ok. I am pointing to the dexie.d.ts file from the node_modules folder so I assume it is the latest one. If I remove the reference path, the same issue occurs.

Previously I would get two error messages for each issue. One was a standard error and the other was a Build message. I don't get the Build error anymore but I still get the standard error. Hopefully attached image will show what I mean more clearly.


[cid:image002.png@01D17AB6.E5691240]
