### ISSUE TITLE
Erratic behavior of between

### ISSUE THREAD

**Issue by qoregexp** [dfahlander/Dexie.js#190]
I have data which is basically a matrix and I want to read portions of rows.  I do the following:

var grid = [];
$(function() {
	x1 = 10;
	x2 = 110;
	db.chart.where("[patno+row+col]").between([1, 1, x1], [1, 1, x2], true, true).each(function(cell) {
		grid.push(cell.sym);
		console.log(cell);
	}).then(function() {
		console.log("range " + x1 + "-" + x2 + " found " + grid.length);
	});
});

[patno+row+col] is the primary key.  This doesn't work (i.e. each returns nothing) when a power of 10 is part of the range, unless the lower bound is a power of 10 (including 10**0).
Examples:
x1-x2
1-100 works
99-110 doesn't work
70-100 doesn't work
1-99 works
2-100 doesn't work
10-100 works
20-100 doesn't work
20-30 works
100-110 works
250-350 works
95-130 doesn't work
101-110 works
11-100 doesn't work
1-101 works 
2-101 doesn't work
10-110 works
2-15 doesn't work
10-15 works

However, 0-2 does retrieve the 2 columns that exist (1 and 2; there is no column 0).  All the other referenced columns are populated.

I can get the data reliably by doing individual gets but I thought between would be more efficient.  Is that true?

**Comment by dfahlander** [comment]
Sounds nasty. Could you post a snippet from a to b that reproduces the error? (Declare db, schema and populate the db and then reproduce the error?)

**Comment by qoregexp** [comment]
Here you go:
[test.txt](https://github.com/dfahlander/Dexie.js/files/166000/test.txt)
Both test.js and test.html are in that one file.  The console outputs: range 91-130 found 0

**Comment by dfahlander** [comment]
Thanks. I converted the code to a unit test and corrected all the use of global vars and it results as expected. It finds 40 cells from the query:

```js
asyncTest("Erratic behavior of between #190", ()=>{
	db.transaction("rw", db.chart, function() {
		for (var r=1; r<=20; r++) {
			for (var c=1; c<=150; c++) {
				db.chart.add({patno: 1,
							  row: r,
							  col: c,
							  sym: 1});
			}
		}
	}).then(function () {
        var grid = [],
		    x1 = 91,
		    x2 = 130;
		return db.chart.where("[patno+row+col]").between([1, 1, x1], [1, 1, x2], true, true).each(cell => {
			grid.push(cell.sym);
		}).then(function() {
            equal(grid.length, 40, "Should find 40 cells");
			//console.log("range " + x1 + "-" + x2 + " found " + grid.length);
		});
	}).catch(e => {
        ok(false, "Error: " + e + " (Will fail in IE and Edge due to lack of compound primary keys)");
    }).finally(start);
});
```
If you want to run it outside qunit, remove the call to asyncTest, equal, and start and uncomment the console.log part and you'll see that it outputs 40.

I've tested with Chrome and Firefox. Note that it wouldn't work in IE or Edge beacause they lack support for compound indices and primary keys.

**Comment by qoregexp** [comment]
Sorry for the false alarm.  Unfortunately it still doesn't work for me (standalone; I don't know how to run your test) and I can't see what is wrong.  I am testing in Chrome and Firefox.  My code after the db is open is the same as yours, I think:

`$(function() {
	var grid = [],
	x1 = 91,
	x2 = 130;
	return db.chart.where("[patno+row+col]").between([1, 1, x1], [1, 1, x2], true, true).each(cell => {
		grid.push(cell.sym);
	}).then(function() {
		console.log("range " + x1 + "-" + x2 + " found " + grid.length);
	});
});
`
What is the issue with global variables? (I can see that you wouldn't want them in a unit test, but is there another problem?)  Also, I don't understand the notation you used.  What is returned from return db.chart...?  I guess cell => { } is shorthand for a function call but I've never seen that before.  Is it specific to Dexie?  I haven't run into either of these things in the documentation.  Sorry if these are naive questions.

Also, is "between" going to perform significantly better than individual gets?  I'm wondering if it's worth continuing to struggle with this. 

Thanks for your help and for this wonderful library.  I may be struggling but it's nothing compared to what I would be going through without Dexie.

**Comment by oising** [comment]
@qoregexp He's using typescript or ES6 - javascript vnext (possibly node 5.x), that's why you see the "arrow functions" - sometimes referred to as lambdas in languages like c#.

**Comment by dfahlander** [comment]
Don't know whether it was due to the global vars or not that your sample doesnt work. I've generally avoid using vars without declaring them because otherwise bad things typically happen (which could be the case here).

The arrow functions are indeed ES6 but you can already use them with Edge, Chrome, Opera and Firefox (dont know about safari) so they're tempting to start using.

Good question why I return the promise. It's a way you can chain promises to prohibit the typical "christmas tree" look of the code. Read more about them in the following articles:

* http://www.html5rocks.com/en/tutorials/es6/promises/
* http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

Here's a snippet that you could use with no dependencies what so ever except Dexie. It's your code after I rewrote it. Please test it and see if it solves the problem.

```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://npmcdn.com/dexie@1.3.2/dist/dexie.js"></script>
    <script>
        function log(txt) {
            document.getElementById('log').value += txt + "\n";
        }
    </script>
</head>
<body>
    <textarea id="log" style="width:100%;height:1000px;"></textarea>
    <script>
        // Declare DB
        var db = new Dexie("test");
        db.version(1).stores({
	        chart: '[patno+row+col], patno',
        });

        // Delete previous DB if any (for multiple runs to work)
        log("Deleting database...");
        Dexie.delete("test").then(() => {
            var cells = [];
            for (var r = 1; r <= 20; r++) {
                for (var c = 1; c <= 150; c++) {
                    cells.push({
                        patno: 1,
                        row: r,
                        col: c,
                        sym: 1
                    });
                }
            }

            log("Populating data..");
            return db.chart.bulkAdd(cells);

        }).then(() => {

            log("Querying...");
            var grid = [],
                x1 = 91,
                x2 = 130;

            return db.chart
                .where("[patno+row+col]").between([1, 1, x1], [1, 1, x2], true, true)
                .each(cell => {
                    grid.push(cell.sym);
                }).then(() => {
                    log("range " + x1 + "-" + x2 + " found " + grid.length);
                });

        }).then(() => {
            log("Done.");
        }).catch(e => {
            log("Error: " + e + " (Will fail in IE and Edge due to lack of compound primary keys)");
        });

    </script>

</body>
</html>
```
[dexie-issue190.html.txt](https://github.com/dfahlander/Dexie.js/files/168774/dexie-issue190.html.txt)

**Comment by dfahlander** [comment]
As pointed out in [this article](http://www.html5rocks.com/en/tutorials/es6/promises/) by @nolanlawson, promises can be tricky to fully understand. So if your app targets only late versions of chrome/opera/firefox/edge, you can consume promises easier with the use of Dexie.spawn() and yield. See the attached and run-ready HTML page of your sample that uses yield instead. Just rename it to html and open it in your browser. When you look at the code you'll notice that it looks like if the Dexie API was synchronous.

[dexie-issue190-with-yield.html.txt](https://github.com/dfahlander/Dexie.js/files/168829/dexie-issue190-with-yield.html.txt)


```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://npmcdn.com/dexie@1.3.2/dist/dexie.js"></script>
    <script>
        function log(txt) {
            document.getElementById('log').value += txt + "\n";
        }
    </script>
</head>
<body>
    <textarea id="log" style="width:100%;height:1000px;"></textarea>
    <script>
        "use strict";

        // Declare DB
        var db = new Dexie("test");
        db.version(1).stores({
	        chart: '[patno+row+col], patno',
        });

        // Spawn a generator function to consume promises with yield instead...
        Dexie.spawn(function*() {
            // Delete previous DB if any (for multiple runs to work)
            log("Deleting database...");
            yield Dexie.delete("test");
            
            // Setup cells in a large array to bulkAdd later
            var cells = [];
            for (var r = 1; r <= 20; r++) {
                for (var c = 1; c <= 150; c++) {
                    cells.push({
                        patno: 1,
                        row: r,
                        col: c,
                        sym: 1
                    });
                }
            }

            log("Populating data..");
            yield db.chart.bulkAdd(cells);
            
            log("Querying...");
            var x1 = 91,
                x2 = 130;

            var count = yield db.chart
                .where("[patno+row+col]").between([1, 1, x1], [1, 1, x2], true, true)
                .count();
            
            log("range " +x1 + "-" + x2 + " found " + count);
            
        }).catch(e => {
            log("Error: " +e);
        });

    </script>
</body>
</html>
```

**Comment by qoregexp** [comment]
Just saw all these new comments.  Thanks @oising and @dfahlander for the information, explanations, and examples.  I will digest it and do more testing and get back to you.  Much appreciated.

**Comment by qoregexp** [comment]
I replaced the reference to my copy of dexie.min.js with https://npmcdn.com/dexie@1.3.2/dist/dexie.min.js and made no other changes and it started working.  I'm sorry it didn't occur to me there might be a newer version.  I think I had 1.2.

**Comment by dfahlander** [comment]
Aha, that explains it. When you say it, I recall there was a sorting bug when array keys were used. Thanks for sharing!
