### ISSUE TITLE
dexie-syncable won't install over npm/jspm due to incorrect dependency

### ISSUE THREAD

**Issue by oising** [dfahlander/Dexie.js#193]
```
PS> jspm install npm:dexie-syncable
     Looking up npm:dexie-syncable
     Updating registry cache...
     Looking up npm:dexie
     Looking up npm:dexie-observable

err  Installing npm:dexie-syncable@0.1.3, no version match for npm:dexie-observable@~0.8.0

warn Installation changes not saved.
PS> jspm inspect npm:dexie-observable

     Installed versions of npm:dexie-observable

       dexie-observable 0.1.3 (^0.1.3)

PS> jspm inspect npm:dexie

     Installed versions of npm:dexie

       dexie 1.3.3 (^1.3.3)
```

Not sure what the ~0.8.0 is all about since observable is 0.1.3?

**Comment by dfahlander** [comment]
Ok. In package.json, i've specified the range ">=0.1.0 <0.9.0" for dexie-observable, which would try the latest version between 0.1.0 but below 0.9.0. Don't understand why jspm interprts that as 0.8.0. Probably need to use a simpler range.

There's also another issue with JSPM and the addons I need to fix in package.json. Will fix asap.

**Comment by dfahlander** [comment]
So, try reinstall the addons (both of versions 0.1.4 now).
* Simplified dependency semver
* Added "format": "esm" in package.json's jspm element.

**Comment by oising** [comment]
Thanks! I'll check now...
