### ISSUE TITLE
Allow Dexie to use alternate Promise implementations

### ISSUE THREAD

**Issue by Burstaholic** [dfahlander/Dexie.js#20]
Our project uses Bluebird, and it would be quite nice to use its functionality with Dexie.

Would you be amenable to something like this at https://github.com/dfahlander/Dexie.js/blob/master/src/Dexie.js#L2156:

```
 var Promise = Promise || (function () { }
```

This would automatically work with anything that provides Promise.

**Comment by ohjames** [comment]
The solution to the problem/feature of promise implementations scheduling there `then` call to the next tick (via setTimeout etc.) is to use the promise constructor and create the transaction inside of it's callback. We wrote something similar to dexie.js with this technique and it works well, allowing us to use any promise implementation the API user needs.

**Comment by dfahlander** [comment]
@ohjames That is not true if you want to support Firefox and IE and keep transaction between promises. The following code would break the transaction:

```js
transaction.get('foo').then(foo => {
    foo.counter++;
    return transaction.put(foo);
});
```
Already in the **then** callback, the transaction will be lost.
