### ISSUE TITLE
IEDeleteObjectStoreBug still present on Windows Edge Browser

### ISSUE THREAD

**Issue by larswolter** [dfahlander/Dexie.js#205]
The Delete bug seems still to be present on windows 10 browsers (at least Edge/13 on windows phone 10). i needed to adjust the bug detection function in dexie.js to:
```javascript
function hasIEDeleteObjectStoreBug() {
            // Assume bug is present in IE10 and IE11 but dont expect it in next version of IE (IE12)
            return navigator.userAgent.indexOf("Trident") >= 0 || 
              navigator.userAgent.indexOf("MSIE") >= 0 ||
              navigator.userAgent.indexOf("Edge") >= 0;
        }
```

**Comment by dfahlander** [comment]
Ok, I've updated the code in the [develop](https://github.com/dfahlander/Dexie.js/tree/develop) branch. Will be part of next release 1.3.5.

**Comment by dfahlander** [comment]
Part of 1.3.6-beta.1.
