### ISSUE TITLE
Q: Reset auto-increment to 0 && Only insert if combination of two values doesn´t exist

### ISSUE THREAD

**Issue by Pandiora** [dfahlander/Dexie.js#211]
I was wondering how I can reset an auto-incrementing primary-key to 0? It looks like clearing the table doesn´t help. The only workaround I have so far would be to delete the database and import the data again.

The second problem is, that I can´t find a method for checking the combination of multiple values before inserting. Currently I´m checking the database if an entry exists like: `db.xy.where('a').equals('b').and('c').equals('d').first()` and then checking if the value is undefined. This isn´t performant when I´m inserting ~10k entrys and sometimes kills my browser. (chrome) Thanks for your time.

**Comment by dfahlander** [comment]
There's no api in indexedDB to access the counter. You must recreate the table, add you suggested. 

Don't know if I understand your 2nd question. and() method doesn't work that way. Have a look at compound indices - they preform better but are not supported on ie/edge/safari. Also, if you're just checking for existance, use count () instead of first ().

Another better approach would be to do all the 10K checks in advance. You could use anyOf() instead of equals. Then when you've got ask the results, start doing the insert

**Comment by Pandiora** [comment]
Thanks for your answer. I´m solving my first problem with my datagrid and by checking for existing id´s. Another problem with browser-crashes are solved by using web-workers, like you already mentioned here: https://github.com/dfahlander/Dexie.js/issues/180


Now to my second question. To give you a more specific example about what I want to achieve:

Database
users | uuid: 123456
documents | uuid: 123456, did: 3344

I´m checking a service for those "did" for every "uuid" regularly with AJAX and returning all "did". So if I check the service again I´m getting "did: 3344" for "uuid: 123456". I don´t want this data to be inserted again.

I looked into it (compound-indices) and found this example (the Explanation on the Wiki isn´t enough to get an idea): https://github.com/dfahlander/idb-iegap/blob/master/test/tests-common.js

I´m not sure of how to use the compound-indices correctly. Based on your example I would write it like this:

db = new Dexie('Database');
db.version(1).stores({
  documents: '[did+uuid]'
});
db.documents.where('[uuid+did]').anyOf(['123456','3344']).count(function(document){});

Now I discovered you added BulkAdd recently and it works perfectly after I modified the array of "did" similiar to the database. To bad there isn´t a mechanism to not add elements if they already exist based on the compound-indices without writing extra code like when you set up multiple indices in sql. I´m thinking about to use db.documents.each() to just remove complete indices from the array with those "did" (including the "uuid") that already exist in database and then execute BulkAdd with the left over elements in the array.

If you know a better approach please let me know. =)

**Comment by Pandiora** [comment]
Okay, I´m retrieving the data, put every object in the array 'arr' and then calling a function which checks for existing entrys and then executing bulkAdd like this:

```
arr = [{uuid: '123', did: '3344'},{uuid: '123', did: '3345'}]

db.users.each(function(data){
  for(var i = 0; i<arr.length; i++){
    if((arr[i]['uuid'] == data['uuid']) && (arr[i]['did'] == data['did'])){
      arr.splice(i,1); // removes the object from array
    }
  }
}).then(function(){
  if(arr.length > 0){
    db.users_games.bulkAdd(arr).then(function(lastKey) {
        console.log("Done. All appids were inserted.");
    }).catch(Dexie.BulkError, function(err){
      console.log(err);
    });
  }
});
```

**Comment by dfahlander** [comment]
There is a beatiful and performant solution to this.

* Assume you're targeting Chrome, FF and Opera (supports compound indexes an primary keys). BONUS: They also support generator functions and yield, which simplifies the promise chain much (see code).

```js
db = new Dexie('Database');
db.version(1).stores({
  users: 'uuid',
  documents: '[uuid+did]'
});
```
Assuming *arr* is the array of documents to add only if they don't already exist
```js
var arr = [{uuid: '123', did: '3344'},{uuid: '123', did: '3345'}]; // from your sample

db.transaction('rw', db.documents, function* () {
  var existingKeys = yield db.documents
    .where('[uuid+did]')
    .anyOf(arr.map(doc => [x.uuid, x.did])) // Only find docs that matches uuid AND did
    .keys(); // Get just primaryKeys ([uuid, did])

  // Remove already added docs:
  arr = arr.filter(doc => existingKeys.indexOf([doc.uuid, doc.did]) === -1);

  yield db.documents.bulkAdd(arr);

  console.log("Done. All " + arr.length + " documents were inserted.");

}).catch (function (err) {
  console.error (err);
});

```

**Comment by Pandiora** [comment]
@dfahlander Thank you, your example works perfectly out of the box.

To give you some feedback I´m adding the results of my last test with Chrome´s Task-Manager:

| Example | RAM-Usage | CPU-Usage | Datasets | Colums |
|------------:| ---------------:| ---------------:| ------------:| ---------:|
Mine | 500 MB | 5-10% | 9986 | 4
Yours |1 GB | 10-15% |  9986 | 4

If you´re interested in optimization I could do further testing to add more information, like how long one run needs. Currently I´m happy it works as expected and when I´m terminating the webworker on ".finally". This code is used in a chrome-extension btw and I´m only focusing chrome and firefox.

**Comment by dfahlander** [comment]
Nice to hear. I hope my Sample is not the one labeled "Yours"? ;) Seems to preform worse than "Mine".

**Comment by Pandiora** [comment]
Phew, this tooks me some time. ^^ Here you can test it by yourself: https://jsfiddle.net/Pandiora/s2vkp5ru/

I don´t know why, but when my console isn´t open, the datasets getting inserted to fast (or not?). However, this way I tested the behaviour and sometimes your solution needs two times longer.

Now my results are:
667 MB 19.07s

**Comment by dfahlander** [comment]
Nice performance fiddle :+1: 

I see why it's not that performant. It would be good if server data included few entries and local database was large.

There's a third very simple alternative that performs almost as your sample (but your is still a little faster). If the compound index is marked as "unique", you could just brute force call

```js
db.documents.bulkAdd(arr).catch(Dexie.BulkError, e => log ("Num dups: " + e.failures.length));
```

It requires to prefix the index with "&" :
```js
db.version(1).stores({
  documents: "++id,&[uuid+did],username,created"
});
```

Here's an updated fiddle: https://jsfiddle.net/dfahlander/s2vkp5ru/55/. As said, your sample still the fastest.

**Comment by dfahlander** [comment]
Note; you need to delete DB for it to run.

**Comment by Pandiora** [comment]
So this is an **unique compound index** and that was exactly what I was searching for. Is there any chance to optimize the bulkAdd? Currently I´m searching the user-Table for uuid´s, then executing the AJAX-Calls, one for every user (most users return 50-60 did, 1 user 1500 did) and then calling a second function like spl() in the fiddle. The problem here is, that your bulkAdd-Example will try to insert all records everytime and it will need ~20s then everytime.

On the plus side, I wouldn´t need a second function and just wrap the bulkAdd inside the AJAX-Call after the for-loop which extracts the did. In the end the inserting takes the most time and in my eyes only this part could be optimized.

**Comment by Pandiora** [comment]
I searched a lil bit on how to insert the data faster. This [stackoverflow-answer](http://stackoverflow.com/questions/25914265/indexeddb-slow-when-inserting) points to a much faster solution using native indexedDB-Function [fiddle](http://jsfiddle.net/Pandiora/a5p6mL6m/17/) needs under 1s. I´m trying to add this to my fiddle.

**Comment by dfahlander** [comment]
BulkAdd() already does optimize by not listening to onsuccess except for the last add() operation.  I doubt it could be optimized more... But you've proved me wrong earlier... :)

**Comment by Pandiora** [comment]
Okay, like in my example I could easily filter already existing records by splicing the array. I added the Native IDB-Example to my fiddle and it is really fast: [jsFiddle](https://jsfiddle.net/Pandiora/s2vkp5ru/)

**Comment by dfahlander** [comment]
I don't see any bigger differencies between splice, Just BulkAdd and Native IDB, except in your table above (Time needed). Are you sure this is not just because the native sample incorrectly logs the last operation only, while the others log the entire flow?

**Comment by Pandiora** [comment]
Yep, I´m sure. Like I wrote somewhere before, the results are different if my browser-console isn´t open. I tested it again Open Console > Reload page > Delete Database > Run Native IDB-Function > 1.72s. No errors thrown.

**Comment by dfahlander** [comment]
I don't want to act as in denial, just trying to understand why in [your fiddle](https://jsfiddle.net/Pandiora/s2vkp5ru/) concludes with time time taken for only the time between the last cursor callback and the finish operation. Should'nt the conclusion comprise the entire operation from db open until transaction committed?

```js
    var startTime; // Not set here

    trans.oncomplete = function () {
      log('Finished adding '+arr.length+' documents');
      log('Processing took '+((performance.now() - startTime)/1000)+' s');
      db.close();
    }

   ...
   store.openCursor().onsuccess = function(event) {

      startTime = performance.now(); // updated in each iteration instead
```

**Comment by Pandiora** [comment]
I remove startTime and moved startCursor to the top now:

```
function nat(db, arr){
  var startCursor = performance.now();
  var openRequest = indexedDB.open("idb");
  ...
```

Same result. :/

**Comment by dfahlander** [comment]
It was a big difference. When I compare your splice (using dexie) with native, I get:
Splice: Results between 0.35 - 0.4 seconds
Native. Results between 0.33 - 0.39 seconds.

**Comment by Pandiora** [comment]
*facepalm* Okay, your right. The problem is, I always had my browser-console open and if so it took much longer like you can see in the tables I posted. Damn, that was stupid. So you´re right, Splice/Native are the fastest. 

**Latest run**
Native: 0.93
Splice: 0.98
Map/Filter: 1.25
BulkAdd: 1.46

**Comment by Pandiora** [comment]
Just want to report back, I´m using just bulkAdd from now. It is much less code and the whole processing needs a long time (AJAX-Requests before adding everything to IDB) - half of a second doesn´t matter anymore.

Do you think we have to investigate, the problem with longer runtimes when console is open, further?

**Comment by dfahlander** [comment]
Thanks for reporting back. No I think that has something with the debugger to do.

Just thought about that with downloading all docs every time. Do you control the serve? Maybe you don't. But if so you could optimize the ajax request by sending a list of already added ID's to server so it knowns if it really needs to send you all the documents?

For example:
```js

Dexie.spawn(function*(){
   var docIds = yield db.documents.toCollection().keys();
   var docIdsJoined = docIds.map(d => d.join(',')).join(';');
   var serverRes = yield jQuery.ajax("http://xyz/download-items?aleady-have=" + docIdsJoined, {
                            type: 'get', dataType: 'json'});
   yield db.documents.bulkAdd(serverRes.data);
}).catch(e => console.error(e));

```

**Comment by dfahlander** [comment]
Or if you have a timestamp on each doc that is always updated on server when a doc is added or updated:

```js
Dexie.spawn(function*(){
   var lastTs = yield db.documents.orderBy('timestamp').last();
   var serverRes = yield jQuery.ajax("http://xyz/download-items?timestamp=" + lastTs, {
                            type: 'get', dataType: 'json'});
   yield db.documents.bulkPut(serverRes.data);
}).catch(e => console.error(e));
```

The you also have support for updating earlier docs from server and sync back?

**Comment by dfahlander** [comment]
Oops, updated last response from .last() to .lastKey().

**Comment by Pandiora** [comment]
Hm, I can´t find out why it is so slow with an open console, but I will have a look at your code when I have more time. Also and this isn´t against you, if you use Vanilla IDB-commands this problem doesn't occur and thats why I'm asking if we have to investigate this further.

To bad I can't control the server. I could only give you an example what I really want to achieve and maybe it's more understandable for you. I'm having several Steam-Accounts and every account has some games in it. There's a Steam-API where you can get the "owned games" of every Steam-Account. The problem here is, I have to be 100% sure a certain account owns a specific game and the other problem is, you can only get the "Owned Games" of one account via API. So for every account you have to make 1 AJAX-Request and this way I can't cut it down to your example. On the other hand, this step is only needed if I add new games via product-keys or steam-gifts.
