### ISSUE TITLE
Table.get() returns promise with undefined argument in Chrome [Android]

### ISSUE THREAD

**Issue by Welfordian** [dfahlander/Dexie.js#212]
When performing `db.messages.get("messages").then(function(data){ console.log(data); });` in Chrome on Android 5.1, the console shows `undefined` or in some cases `null`.

Tested on Chrome 49.0.2623.91 on Android 5.1.1

**Comment by dfahlander** [comment]
Table.get() will return a successful Promise also when item is not found. It's not an error. The value will then be undefined.

https://github.com/dfahlander/Dexie.js/wiki/Table.get()

When is null returned? Can you give us some code that reproduces that?

**Comment by Welfordian** [comment]
I'm not sure why this would be the case only on mobile. When running the above code on Chrome in the desktop I get back my desired value. Even when inspecting IndexedDB in my mobile browser I can see that the item does exist.

**Comment by dfahlander** [comment]
Haven't heard that chrome on android should behave differently, except that it may act unpredictable when having low physical hard drive space. If you could create a [jsfiddle](https://jsfiddle.net) that reproduce the error, it could be reported to the chrome team. Maybe hard to reproduce if it is due to low disk space though. Could it be the case?

**Comment by Welfordian** [comment]
Looks like it's happening in my jsFiddle on Chrome Desktop also.

https://jsfiddle.net/cg0ygwt3/

**Comment by dfahlander** [comment]
Your primary key is ++id, which is a number. You try to get an object with a string key "messages". Why? Are you trying to get all messages? Do 

```js
db.messages.toArray()
```

**Comment by andreyluiz** [comment]
I got the same problem on Electron. Like @dfahlander said above, you need to be careful when passing the ID to pass a number. In my case, I had a parameter coming from a `react-router`. And by default, it is a string, so I had to convert it to a number for this to work properly.

```
const { id } = useParams();

const getFile = async () => {
  const file = await db.files.get(Number.parseInt(id));
}
```

**Comment by philliskiragu** [comment]
> I got the same problem on Electron. Like @dfahlander said above, you need to be careful when passing the ID to pass a number. In my case, I had a parameter coming from a `react-router`. And by default, it is a string, so I had to convert it to a number for this to work properly.
> 
> ```js
> const { id } = useParams();
> 
> const getFile = async () => {
>   const file = await db.files.get(Number.parseInt(id));
> }
> ```

This saved me a headache. The same goes when getting the value from `vue-router` / `nuxt`
