### ISSUE TITLE
No TypeScript definitions for Observable / Syncable

### ISSUE THREAD

**Issue by oising** [dfahlander/Dexie.js#213]
I tried to generate .d.ts files with the compiler after feeding it the es6 source, but it didn't come up with anything remotely logical. Any plans to release some definitions?

**Comment by dfahlander** [comment]
I would like to do that if there were time. Now i've spent too much time on Dexie the last weeks and need to focus on my main project (which is using observable/syncable though).

I think Dexie.d.ts would have to be adjusted some way (maybe changed Dexie from class to interface with acompanied new() function, like Table and the other classes are defined to be extendable) in order for the addons to put new methods etc on its generated instances. It would be something like:

```ts
declare var Dexie : new()=>IDexie;
```

But I havent tested that it's still possible to derive a subclass when doing so. When that's done, d.ts files could be added for the addons. For Dexie.Observable this would be almost nothing. For Syncable, a few methods (https://github.com/dfahlander/Dexie.js/wiki/Dexie.Syncable.js)

**Comment by dfahlander** [comment]
For now, just cast to any:

(Dexie as any).Syncable.registerSyncProtocol (name, instance);

**Comment by dfahlander** [comment]
If you for some reason felt very much like fixing this, your pull requests are much welcome :)

**Comment by oising** [comment]
@dfahlander Hehe... sure, I'm already using a cast to `<any>` -- I was hoping perhaps you might have something. If I get around to creating some, I will surely send you a PR. Thanks!

**Comment by oising** [comment]
@dfahlander One thing that I'll definitely submit back to you is a SignalR transport. I've figured out a design based on the EventAggregatorProxy and a server-side (c#) implementation of Caliburn.Micro.EventAggregator that can dispatch to a data store adapter. Once it's baked enough to share, I'll send you a PR.

**Comment by oising** [comment]
I've also noticed that the tsc compiler doesn't pick up the typings in the package unless I'm using node module resolution. I am tracking some other github issues and bugs that are currently blocking this from working in jspm -- it appears you're doing everything right; it's just the module resolution in tsc that doesn't work with jspm yet... just an FYI :)

**Comment by oising** [comment]
Oh, and yes -- we'd have to modify your existing `dexie.d.ts` to use interfaces to allow merging to work. It doesn't work with classes as far as I can tell. I'll see what I can do... you've already done a lot to help me. Thanks again.

**Comment by dfahlander** [comment]
Interesting stuff. Thanks for sharing :+1:

**Comment by cherrydev** [comment]
Typescript 1.8 now allows merging into an existing module scope and in the the example, they specifically demonstrate an existing **class** `Observable<T>` and then adding a member to the class by merging in an **interface** also called `Observable<T>`.  Unless I'm misunderstanding the problem that's described in this issue, this feature should effect what you're trying to do here.

This feature is described [here](https://www.typescriptlang.org/docs/release-notes/typescript-1.8.html) under the heading "Augmenting global/module scope from modules" (why no anchor tags, MS??)

**Comment by dfahlander** [comment]
Very interesting info. Thanks!

**Comment by dfahlander** [comment]
They've removed the typescript release notes. New location: 
[Augmenting global/module scope from modules](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#augmenting-globalmodule-scope-from-modules).

**Comment by dfahlander** [comment]
Addons now have typings in Dexie 2.0.0-beta-7. Closing.
