### ISSUE TITLE
callback doesnt get fired for put

### ISSUE THREAD

**Issue by Josephdias92** [dfahlander/Dexie.js#217]
put doesnt fire callback for update

**Comment by dfahlander** [comment]
Do you mean CRUD hook callbacks? If so,  there was an issue when having multiple hook('updating') which has been solved In the beta release today. Can you try the latest release (https://npmcdn.com/dexie@1.3.6-beta.1/dist/dexie.js) and see if it solves your issue!?

**Comment by dfahlander** [comment]
Did you mean that [hook('updating')](https://github.com/dfahlander/Dexie.js/wiki/Table.hook('updating')) wasn't called? Can you verify if this was due to duplicate subscribers? If so, could you verify that this is fixed in the lastest beta?

**Comment by dfahlander** [comment]
https://npmcdn.com/dexie@1.3.6-beta.3/dist/dexie.js

**Comment by dfahlander** [comment]
No answer \O/ ?
Closing
