### ISSUE TITLE
Dexie is not widely known.

### ISSUE THREAD

**Issue by acicali** [dfahlander/Dexie.js#22]
This is the biggest issue with Dexie. SRSLY. I've been in search of Dexie for quite a while, but didn't know that it existed. Instead, I've spent many hours evaluating the alternatives mentioned here:
https://github.com/dfahlander/Dexie.js/wiki/Dexie.js#other-competing-indexeddb-wrappers

How can we solve this problem?

Thank you for this great creation.

**Comment by YuriSolovyov** [comment]
Logo idea:
![out](https://cloud.githubusercontent.com/assets/2168518/7669816/5db30f6c-fc90-11e4-9435-2c1dd56eab34.png)

**Comment by dfahlander** [comment]
Thanks for the logo suggestion. I think it's rather nice.

**Comment by brandonlamb** [comment]
This looks like a great thread to tag onto. Came across Dexie in my weekend of googling angularjs stuff and when I got to the point of needing client side data, Dexie was in many of my search results. So far based on my 30 minutes with it, two thumbs up! :+1:

**Comment by dfahlander** [comment]
@Yuri, could I use your logo? Is it okay if I change background to transparent and text to white? (would work better on the site)

**Comment by YuriSolovyov** [comment]
@dfahlander, sure, do whatever you want

**Comment by YuriSolovyov** [comment]
@dfahlander maybe I can even attach source `.ps` file when I get home later today.

**Comment by YuriSolovyov** [comment]
@dfahlander here is the source 
https://drive.google.com/file/d/0B4txOhp64viVdHg4MTJoaEVnSE0/view

**Comment by brandonlamb** [comment]
:+1: nice looking site

**Comment by dfahlander** [comment]
Thanks @YuriSolovyov , I've picked picked the graphics but kept the current font. Check out if you approve my changes on [dexie.org](http://dexie.org)

**Comment by dfahlander** [comment]
Ps. if you're on mobile, you can't see it because I hide it on small screens because the margin looked to bad there.

**Comment by YuriSolovyov** [comment]
@dfahlander header icons looks good, but favicon feels cut off (right side of letter D)

**Comment by YuriSolovyov** [comment]
@dfahlander how about this: ![favicon](https://cloud.githubusercontent.com/assets/2168518/14297022/88962800-fb85-11e5-9a1e-3e2e5f17c44a.png)

**Comment by dfahlander** [comment]
Thanks, much better!

**Comment by YuriSolovyov** [comment]
Featured in [Progressive Web Apps across all frameworks - Google I/O 2016](https://www.youtube.com/watch?v=srdKq0DckXQ&feature=youtu.be&list=PLNYkxOF6rcIDz1TzmmMRBC-kd8zPRTQIP&t=898)

**Comment by nponiros** [comment]
I created a demo site which includes the docs from the wiki under http://dexie.flexisitegen.com/docs/Home . There are a number of broken links because not every wiki link matches a file name and I didn't try to convert the links to match the files but I guess for a demo it is good enough.

If this is a wanted change, I can create a PR for https://github.com/dfahlander/dexie.js-web to add the docs. Assuming that the docs should be on the website, then there is the question of whether the github wiki should continue to exist. If we have docs on the site and the wiki, we will have to decide which docs are the "master" docs. So basically which docs will be updated and which ones will just be created. Depending on that I can solve the links issues and the code highlighting issues (we use for example "js" in the wiki but prism requires "javascript"). Personally I would prefer to just have the docs on the website as I am not a big fan of wikis in general.

As always feedback is welcome :)

As a side note, I think we should also promote the various addons on the website and maybe in the readme. Perhaps under a "Features" section like: "Dexie supports client/server synchronization with Dexie.Syncable" or "You can use dexie-mongoify to have a MongoDB like API with Dexie".

**Comment by dfahlander** [comment]
That would be nice, to have the docs on the site. The only thing I would be missing would be the super simple way to update typos etc directly from the page. But maybe this could be accomplished by linking to the github's web based file editor for each file. In that case I'm for moving it to the site entirely and replace each MD file in the current wiki with a reference to the site.

Indeed the addons / derived libs including sync-client must be more aggressively promoted. Dexie's Readme is one good place. Could also link to api docs for addons from the documentation page or include docs as well optionally

**Comment by nponiros** [comment]
@dfahlander fixing typos directly on github should not be an issue, at least not for collaborators. If we write the docs in html then any change you make in the website repo should also be instantly online. If we write the docs in markdown we would have to have a build step. In this case the changes will only be online when you build the site and push the html files. I don't know if we can directly build from within github. Maybe that works with jekyll. So do you want to be able to just edit online and release later or do you want any change to be instantly online?

**Comment by nponiros** [comment]
@dfahlander I am not familiar with jekyll. I used my own tool to build the demo site. It will take me some time to get familiar with jekyll (and github pages) but I can give it a try.

**Comment by dfahlander** [comment]
I just pushed a branch I made for some time ago for dexie.js-web. Check it out https://github.com/dfahlander/dexie.js-web/tree/jekyll

**Comment by dfahlander** [comment]
Let's follow up discussion on #464

**Comment by dfahlander** [comment]
README updated to promote addons in this PR https://github.com/dfahlander/Dexie.js/pull/465

It's just a draft.

Comments?

**Comment by douglasg14b** [comment]
@dfahlander You should add appropriate github tags to the project. So it is discoverable on GitHub, and can be recommended by GitHub.

**Recommended:**

`database` `javascript` `indexeddb` `offline` `storage`

**Comment by dfahlander** [comment]
I only know about the npm keywords that we list in package.json: ["indexeddb", "browser", "database"].  What are the github tags and how do you add them?

**Comment by douglasg14b** [comment]
@dfahlander  you can do this with the manage topics button under the repository description 
![image](https://user-images.githubusercontent.com/1400380/53915833-916f6b80-4015-11e9-9d21-8331481c92ce.png)

**Comment by dfahlander** [comment]
Thanks @douglasg14b! Topics now set.

**Comment by dfahlander** [comment]
This has been the nicest issue I've ever got <3
But I believe it is time to close it.
Thanks all!
