### ISSUE TITLE
Apache license file?

### ISSUE THREAD

**Issue by mrkalle** [dfahlander/Dexie.js#227]
We are in the process of starting using Dexie in a commercial web application product. What exactly do we need to supply? 

An Apache license file in the root? But where should Dexie be mentioned?

BR, Carl

BTW, Love the new release!!!

**Comment by dfahlander** [comment]
Glad to hear! :)
Found 
[this](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) great explanation of the Apache 2 license. Hope it helps.

**Comment by dfahlander** [comment]
For us, it doesn't matter where you mention Dexie, as long as it is mentioned somewhere.

**Comment by mrkalle** [comment]
OK! Thank you!
