### ISSUE TITLE
Automatic tests should test Safari

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#230]
Filing this issue as a TODO item.

Should try running the unit test suite on Safari in the continous integration script.
Now we don't do that because it's failing on some tests, but we need to get those on-board as well as on IOS devices.

**Comment by timfish** [comment]
is IndexedDB now fully fixed on [Safari 10](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html)?

> **IndexedDB Support**
Safari’s IndexedDB implementation now fully supports the recommended standard. You may now use the API to store structured data for web applications that work offline or that require large amounts of client-side data caching.

The performance might still be dire and make it unusable...

**Comment by dfahlander** [comment]
No, i've reported a very severe bug https://bugs.webkit.org/show_bug.cgi?id=158833 that has not been even opened by the webkit team. I don't think performance is that bad though.

**Comment by dfahlander** [comment]
NOTE to users though: The rest of the severe bugs are fixed. I support this one is more easy to workaround, I might give it a try. But I really think it's Apples job ;)

**Comment by timfish** [comment]
That bug doesn't inspire confidence in their underlying code and/or testing procedures! So it wont affect me if I'm only using a single object store? Multiple instances of Dexie with a single store?

**Comment by dfahlander** [comment]
You'd be fine with a single object store, yes! And also in most cases also with multiple stores. Actually 1114 of 1123 assertions succeeds in the Dexie unit tests, so most of the stuff are fixed and seems to be reliable.

I just twittered about this and also tried to involve people with some influence to chase the webkit team about this. I hope they fix is ASAP.

**Comment by dfahlander** [comment]
Update: the webkit team fixed the bug last Thursday.  Yippie!  According to a developer at Apple, the latest technical version of Safari now succeeds 100% of Dexie's 1,122 unit test assertions. Now let's just hope it will be published into iOS and MacOS soon.

As soon as there is a Safari version on browserstack with the fix applied, I'll add it to the browserstack configuration.

**Comment by nponiros** [comment]
I just run the tests on Safari for iOS 10.2. Most Dexie unit tests passed (1243 out of 1245). The 2 that did not pass are the blobs tests. Tests for Dexie.Observable and for Dexie.Syncable passed.

**Comment by dfahlander** [comment]
Thanks @poniros. We will be able to opt-out those blob tests for Safari then as soon as browserstack includes iOS 10.2 and latest MacOS Sierra. Tested today but browserstack was still on iOS 10.0 that one still has [this bug](https://bugs.webkit.org/show_bug.cgi?id=158833), making some important tests fail.
