### ISSUE TITLE
Is there a generic version change event?

### ISSUE THREAD

**Issue by mcfarljw** [dfahlander/Dexie.js#231]
Let's say I have the following:

```
var db = new Dexie("People");
db.version(1).stores({friends: "++id,name"});
```

Then I take that same example and update it to:

```
var db = new Dexie("People");
db.version(2).stores({friends: "++id,name"});
```

The only thing I've changed is the version number, but is there a way to subscribe to an event that triggers on the just that change when the user refreshes their browser? _I know it would be silly to update the version when nothing has changed, but I'm just using this example to help clarify things._

**Comment by dfahlander** [comment]
Yes, you can do:

```js
var db = new Dexie("People");
db.version(1).stores({friends: "++id,name"});
db.version(2)
    .stores({friends: "++id,name"})
    .upgrade(function() {
        // Will be triggered if version is below 2.
    });

db.open()
    .catch(function (e) { console.error(e); });

```

**Comment by mcfarljw** [comment]
What if I update the 1 to 2, without adding an extra line containing the previous version?

**Comment by dfahlander** [comment]
You need to keep all previous versions that may have been installed on any of your clients for dexie to work properly on upgrade.
A future version of Dexie may improve this (if I get the time) so that you don't have to keep old versions but instead parse current version from IDB.

**Comment by dfahlander** [comment]
But if nothing has changed in the new version, you don't have to provide each store again. You just need to provide changed, added and deleted stores in the newest version.

If "friends" isnt changed, just do:
```js
var db = new Dexie("People");
db.version(1).stores({friends: "++id,name"});
db.version(2).stores({}).upgrade(function() {
    // Will be triggered if version is below 2.
});

db.open()
    .catch(function (e) { console.error(e); });

```

**Comment by dfahlander** [comment]
Closing
