### ISSUE TITLE
Updating values not all ways working

### ISSUE THREAD

**Issue by gmalkoun** [dfahlander/Dexie.js#235]
Hi 

Great library.  

I have a problem with a browser app that I have built for chrome or Firefox.

On a android tablet I have a set of buttons that I press as I pass through the different stages.

When I hit the button it updates the time in the indexeddb and then rebuilds the button to reflect the next stage. 

I am finding that indiscriminately it doesn't update the details. As I hit the buttons sometimes it takes 2 or 3 hits to move on to the next stage.

Do i need to reload/refresh my Indexeddb? Can dexie force a reload of the indexeddb?

Any ideas would be appreciated.

Thanks

**Comment by dfahlander** [comment]
Read this great article by @nolanlawson:

https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

It's really about understanding promises for understanding how to use the Dexie api or any other Promise based api.

**Comment by gmalkoun** [comment]
Thanks David. I will

On Fri, Apr 15, 2016 at 2:07 AM, David Fahlander <notifications@github.com>
wrote:

> Read this great article by @nolanlawson <https://github.com/nolanlawson>:
>
> https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html
>
> It's really about understanding promises for understanding how to use the
> Dexie api or any other Promise based api.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dfahlander/Dexie.js/issues/235#issuecomment-210022156>
>



-- 
Regards
George Malkoun
0402 133 820
