### ISSUE TITLE
Typescript, nuget and Visual Studio: Cannot find name Dexie

### ISSUE THREAD

**Issue by sameera** [dfahlander/Dexie.js#236]
I'm trying to use Dexie in an Typescript+AngularJs project in VS2015. My module system is CommonJS. I'm unable to get past the error:

`TS2307	Cannot find module 'dexie'.`

I see that this has been reported for AMD before and the issue is still open. I'm attaching a very minimal sample project where I'm seeing this error. 

[DexieTest.zip](https://github.com/dfahlander/Dexie.js/files/222658/DexieTest.zip)

**Comment by dfahlander** [comment]
You need to use npm to install dexie to your typescript project. Otherwise Dexie won't be found anywhere. There's no nuget package for Dexie except Definitelytyped 's outdated d.ts file which is redundant and already included in the npm package.

**Comment by dfahlander** [comment]
Install npm, cd to your project root and type

```
npm install dexie
```
A dir named node_modules will be created with dexie inside it. Dexie's package.json file will inform Typescript compiler where the d.ts file is located if you use moduleResolution 'node' in your tsconfig file.

**Comment by sameera** [comment]
Thanks!
That did get me past the import. 
However, the type Dexie still isn't properly resolved. The line:
`class Database extends Dexie`
causes:
`TS2507	Type 'typeof "/node_modules/dexie/dist/dex...' is not a constructor function type.`

I can get around this by changing this to `extends Dexie.default`
But, then none of the other Dexie types are accessible via `Dexie.` or `Dexie.default`

TS2305	Module '"/node_modules/dexie/dist/dexie"' has no exported member 'Table'.

Sorry, if I'm missing something obvious here. I've not quite got the hang of TS module systems yet; and this is the first module that I came across that required a import/require :) (been using stuff like angular, jquery, etc. d.ts files off of nuget).

**Comment by dfahlander** [comment]
It's sometimes a hassle with all this. You're not alone ;) My own typescript samples doesn't use visual studio. Maybe you've found something that isn't working out of the box when using visual studio's project wizard with dexie. Just to nail it down - could it be that the old d.ts file from Definitelytyped is conflicting? Try delete Dexie.d.ts from scripts folder and see if it helps. Otherwise let me know.

**Comment by sameera** [comment]
I was actually trying to get this work on multiple VS projects. Even tried setting up *proj files around the TS samples in the repo. 
What worked for me was removing the last line of the d.ts file:
`export default Dexie;`

Without this, I can use Dexie without an import statement; Intellisense seems to work perfectly and the code runs just fine :)
I do think I might have to end up commenting out the Thenable declarations when I use it in my actual project as it's using [es6-promise.d.ts](https://github.com/jakearchibald/ES6-Promise) or maybe I would need to wrap them in a module. Either way, it seems that I need to hack the d.ts file :(

**Comment by sameera** [comment]
Once I modified the d.ts file, I simply dropped it in the Scripts/typings folder under a dexie/ folder. I'm sure I'm violating many best practices by doing all of this :)
