### ISSUE TITLE
Creating stores with name as a parameter 

### ISSUE THREAD

**Issue by andokai** [dfahlander/Dexie.js#238]
I have an array of strings where each string represents the name of a store I'd like to create in IndexedDB. All examples seem to suggest that the way to create stores is by specifying the store name as a property as in;
```
db.version(1).stores({
        myObjectStore1: "primaryKey, index1, index2, ..." });
```

I have tried;

`db.version(1).stores['myObjectStore1'] = "primaryKey, index1, index2, ...";`

but that doesn't appear to work. Is there any way I'm able to achieve what I'm after using Dexie?

**Comment by dfahlander** [comment]
The [stores()](https://github.com/dfahlander/Dexie.js/wiki/Version.stores()) method expects an object where each key is the table name and each value a string defining it's primary keys and values.

It's easy to create an object in javascript. And it's easy to add members to it.

Example:
```js
var myStoreNames = ["friends", "todos"];

var schema = {};
myStoreNames.forEach(function (storeName) {
    schema[storeName] =  "primaryKey, index1, index2"
});

var db = new Dexie("MyDB");
db.version(1).stores(schema);

```

**Comment by andokai** [comment]
Hi, thanks for the reply. I realised my mistake and was coming on to close the issue. You beat me to it. Cheers!

**Comment by dfahlander** [comment]
No problems. Cheers!
