### ISSUE TITLE
Define "stores" even when database already exist.

### ISSUE THREAD

**Issue by ncou** [dfahlander/Dexie.js#241]
Hi,

Very nice plugin.
I am currently doing some test and it seems to me there is perhaps an issue (or something i don't understand).

I create a database in one page, and my second page i want to retrieve the data.

In my second page i test with "Dexie.exists()" if the database already exist to open it and query the DB.

It work if i define the "stores" - db.version(1).stores(...) - But my database already exist. why does i need to define again the store ???

Thank you for your enligthment.

Keep up the good work.

**Comment by dfahlander** [comment]
You shouldn't need to use Dexie.exists () because Dexie/IndexedDB will check that for you and only create or upgrade db when needed.

**Comment by dfahlander** [comment]
So basically, you preferably reuse the same js file on both pages where the db is defined

**Comment by ncou** [comment]
thank you it's more clear.

I will close the ticket.
