### ISSUE TITLE
How to use the transaction object returned by table.hook

### ISSUE THREAD

**Issue by agozie** [dfahlander/Dexie.js#243]
`DB.friends.hook('creating',function (pk,obj,transaction){
//please show how to use transaction here
})`

**Comment by dfahlander** [comment]
Transaction is documented [here](https://github.com/dfahlander/Dexie.js/wiki/Transaction) and can be used to manipulate database. The Dexie.Observable addon uses it to generate entries into an oplog (_changes) table whenever a db operation succeeds.

**Comment by dfahlander** [comment]
Planning to release a version that allows hooks to return Promises. If so,  you could have used it for querying database and letting it affect the create operation.

**Comment by dfahlander** [comment]
Closing
