### ISSUE TITLE
Suggestion: Publish latest beta version to NPM using the @next tag

### ISSUE THREAD

**Issue by ChrisPearce** [dfahlander/Dexie.js#245]
To make it easier for users that are regularly testing the latest beta version, it would be helpful if the latest beta version was published to the NPM registry under the @next tag.

Users could then always be sure of obtaining the latest version to test by issuing the command:
`npm install dexie@next`

**Comment by dfahlander** [comment]
Ok. Right now, I publish betas on npm with tag @beta. Is there a common practice to use @next tag instead? If so, I'll just switch.

**Comment by ChrisPearce** [comment]
The NPM tool uses the following tag strategy (as stated in https://docs.npmjs.com/cli/tag):

> Tags can be used to provide an alias instead of version numbers. For example, npm currently uses the tag "next" to identify the upcoming version, and the tag "latest" to identify the current version.

This now seems to have been adopted with many common repositories.

**Comment by dfahlander** [comment]
Ok, thanks! Keeping this issue open til its done.
