### ISSUE TITLE
Running Dexie with MS Edge on a real mobile device :  OpenFailedError: UnknownError occurred when opening database

### ISSUE THREAD

**Issue by joalmeid** [dfahlander/Dexie.js#249]
Running the official sample drom DexieJS, all works fine on Edge browser.
However I'm using it to run inside an appContainer (Hosted Web App). Works good on Desktop, but not on a real device (tried with a Lumia 1520).

I'm getting an error:
Uncaught Promise: OpenFailedError: UnknownError UnknownError occurred when opening database FriendDatabase. OpenFailedError: UnknownError UnknownError occurred when opening database FriendDatabase
   at Anonymous function (http://192.168.1.100/phc2/Dexie.js:2459:45)
   at doResolve (http://192.168.1.100/phc2/Dexie.js:741:13)
   at Promise (http://192.168.1.100/phc2/Dexie.js:585:13)
   at Anonymous function (http://192.168.1.100/phc2/Dexie.js:2457:25)
   at Promise.newPSD (http://192.168.1.100/phc2/Dexie.js:862:13)
   at _promise (http://192.168.1.100/phc2/Dexie.js:2453:17)
   at transactionPromiseFactory (http://192.168.1.100/phc2/Dexie.js:1327:17)
   at resume (http://192.168.1.100/phc2/Dexie.js:1315:29)
   at Anonymous function (http://192.168.1.100/phc2/Dexie.js:1280:17)
   at Array.prototype.forEach (native code)
Dexie.js (892,9)

Have a repro ready to share if needed.

**Comment by dfahlander** [comment]
Which version of Dexie?

**Comment by dfahlander** [comment]
Have you tried [this fiddle](https://jsfiddle.net/dfahlander/3tf5r0cu/) from your device?
Don't know if there are any special conditions related to running inside an appContainer though. Generally, IE (and probably Edge) doesnt allow accessing indexedDB when page is served from local hard drive. But if you host your web app from a local web server on the device this shouldnt be a problem.

**Comment by joalmeid** [comment]
Just tried it with 1.3.6, and the exact same error.

**Comment by joalmeid** [comment]
I'm also checking it out with Microsoft, to check if it is any edgeHTML/Chakra issue when running on mobile.

The scenario actually is running not from local content (inside app package), but actually from a remote web server.

**Comment by joalmeid** [comment]
Just tan the fiddle you mentioned, and I have exact same error:

Using Dexie v1.3.6
UnknownError: UnknownError occurred when opening database MyFriendDB

**Comment by dfahlander** [comment]
Strange. I ran it from a Windows phone 8.1 device on Browserstack with ie11.

**Comment by dfahlander** [comment]
Maybe double check that there's nothing wrong with the particular device you're testing on?

**Comment by joalmeid** [comment]
That's the difference. WP81. uses mshtml (IE web engine). W10Mobile uses edgeHTML (MSEdge web engine)

**Comment by dfahlander** [comment]
Yes, but still strange that indexedDB fails to open mobile Edge browser while it's working fine on Windows 10 desktop's edge browser.

**Comment by joalmeid** [comment]
Exactly. Will bring some insights from Edge team.

**Comment by dfahlander** [comment]
I once managed to make my edge browser corrupt and fail with UnknownError on open. Could reproduce the issue. Only a system reboot after deleting the db made it finally recover from the unstable state. 

https://gist.github.com/dfahlander/5a39328f029de18222cf2125d56c38f7

Probably this is not the case with your device but just wanted to tell in case your device would be in a bad state.

**Comment by joalmeid** [comment]
@dfahlander , just to give some feedback.
Edge team, has confirmed it was an issue/bug and has already been corrected in w10 mobile. It will reach fast ring deployments quite soon. I'll provide further feedback when I test it on my device.
Thanks for the help.

**Comment by dfahlander** [comment]
Aha, thanks for sharing 👍

**Comment by dfahlander** [comment]
Closing to clean up.
