### ISSUE TITLE
Searching middle of value

### ISSUE THREAD

**Issue by robindorbell** [dfahlander/Dexie.js#252]
Great job on this! I do miss one thing though, and that is the possibility to search in the middle of a value. I have for example an article registry in the database, and need to be able to search the description.

The only way I find possible is this, and it's very slow:

```
    this.db.articles
        .orderBy('Description')
        .filter(function (article) {
            return article.Description.toLowerCase().indexOf(args.search) > -1;
        })
        .offset(args.skipCount)
        .limit(args.range)
        .sortBy('Description', function (result) {
            args.success(result);
        });
```

Is there a better way, or is this a limitation to IndexedDB?

**Comment by dfahlander** [comment]
You could use CRUD hooks to emulate full text indexes. Look for full text Sample in the samples dir

**Comment by robindorbell** [comment]
Hi, thank you for your answer! But this form of search would only index words, so that I can easier search for a word in the middle of a text, no? I'd like for a query such as 'service' would show the result (among others) 'u-service'.

I understand that it might not be possible. :)

**Comment by dfahlander** [comment]
Not possible what I know of. There might be advanced algorithms to accomplish something similar but not what I know of. You could always index each character to filter out something before matching with a regexp. If you ran an SQL 'like %middlematch%' query, the database would actually not be able to index that and it would also to a full table scan to find it, unless you use some special index type that some DBs may support. Unless your data is huge, it could probably be good enough to just do as you proposed initially. Maybe replace the indexOf with a regexp makes it a little faster.
