### ISSUE TITLE
InvalidStateError or 'Transaction is inactive' error

### ISSUE THREAD

**Issue by cinterre** [dfahlander/Dexie.js#253]
Hey everyone, I'm almost certain this is something I'm doing (still very new to modern javascript) but I can't for the life of me figure out what is going on. I have an asynchronous FileReader function that I'm trying to get Dexie to wait on before adding the retrieved data into the IndexedDB. I'm doing this conditionally inside of a loop, so doing it in the standard callback fasion would be very tricky.

When I run the code normally, I'm getting an InvalidStateError triggered on line 1842 of Dexie. When run the debugger, the code runs through everything as I would expect, I can see the file being loaded, the data going into the object I want to store etc, but once everything finally resolves I get a 'Transaction is inactive' error. So at this point my inexperience leaves me unable to spot why this asynchronous code doesn't resolve as I would expect. 

Code for the Transaction is below, with the async function in question on line 18.
(db is opened, setup, assigned to a global var)
```javascript
function addPost(event) {

    event.preventDefault()

    db.transaction('rw', db.posts, function*() {

        let INPUT_SELECTOR = '#content input, #content textarea'

        let inputs = document.querySelectorAll(INPUT_SELECTOR)
        let post = new Post()

        for (let input of inputs) {
            let node = new Node()
            node.content = input.value
            node.type = input.name
            if (node.type == 'image') {
                let file = input.files[0]
                let data = yield readFileAsBinary(file)
                node.blob = data
                post.content.push(node)

            } else {
                post.content.push(node)
            }

        }

        post.tags = document.querySelector('[name="tags"]').value.split(',')
        post.authoredDate = new Date(document.querySelector('[name="authoredDate"]').value)

        db.posts.add(post).catch(function (error) {
            console.log(error.message)
        })

        console.log('adding a post...')

    }).then(function() {
        db.posts.each(function (post) {
            console.log(post)

        })
        console.log('All done')
    }).catch(function (error) {
        console.log(error)
    })

}
```
And the function that reads the file. I saw in the docs that one should use Dexie.Promises inside transactions for compatibility, so I made sure to do that:
```javascript
const readFileAsBinary = (file) => {

    let reader = new FileReader();

    return new Dexie.Promise((resolve, reject) => {
        reader.onload = (event) => {
            let data = event.target.result
            resolve(data)
        }

        reader.onerror = () => {
            return reject(this)
        }

        reader.readFileAsBinary(file)

    })
}
```

Any ideas and/or guidance is appreciated. (And I come from a Python background, so I apologize for my communist non-semicolon usage in advance).

**Comment by dfahlander** [comment]
IndexedDB will commit the transaction as soon as you call another async API that is not indexedDB. In you code, this happens here:

```js
let data = yield readFileAsBinary(file)
```

What you should do, is to start the transaction after reading the file. This is also a good thing because then you wouldn't lock db.posts while reading the file.

**Comment by dfahlander** [comment]
I suggest you just replace the db.transaction() line with Dexie.spawn() (or Q.spawn() which would work equally well) and you're done.  You don't need a transaction since you only do a single call to db.post.add().

**Comment by cinterre** [comment]
Thanks for the prompt response, as you said Dexie.spawn is what I was looking for, worked perfectly. 
When I read the docs on trasaction, it mentions that non-indexed db compatible promies will not work, I interpreted it as meaning I needed to use Dexie.Promise. Thinking through it now I get what it actually means, that I should only use transactions for indexed-db related calls as that's what it's expecting. Thanks again for the help!

**Comment by dfahlander** [comment]
It's true that the doc focuses on the Promise type issue, but doesn't explain the second problem - indexedDB's transaction behavior. I'll try to update the docs.

**Comment by dfahlander** [comment]
Updated some docs.
* [Dexie.transaction()](https://github.com/dfahlander/Dexie.js/wiki/Dexie.transaction()#the-auto-commit-behavior-of-indexeddb-transactions)
* [API reference](https://github.com/dfahlander/Dexie.js/wiki/API-Reference#the-auto-commit-behavior-of-indexeddb-transactions)
* [Best practices](https://github.com/dfahlander/Dexie.js/wiki/Best-Practices#2-dont-use-other-async-apis-inside-transactions)
