### ISSUE TITLE
Enhancement: Check Search-Strings w/ and w/o quotes

### ISSUE THREAD

**Issue by Pandiora** [dfahlander/Dexie.js#254]
I think this problem is already known, but I can't find any open or closed issue related to this case.

Lately I was wondering why Dexie gave me wrong results. My working example:

 ```javascript
 idb.opendb().then(function(db){
    db.transaction('rw', ['steam_users', 'users_games'], function(){
      db.users_games.where('app_id').anyOf(summary.appid).each(f => {
        // Only add a user one time to this array if he owns 1 of the game/s
        // This prevents us from sending subs including one of the games
        if(u.indexOf(f.steam_id) === -1) u.push(f.steam_id);
      }).then(function(){
        // Now only add users which does not own the game/s to our summary
        db.steam_users.where('steam_id').noneOf(u).each(j => {
          summary.user.push({steam_id: j.steam_id, username: j.username});
        });
      });
    }).then(function(){
      // We have all the data we need - start processing
      sendResponse('Processed all Data.');

      if(summary.user.length <= 0){
        chrome.tabs.sendMessage(sender.tab.id,{
          msg: 'UpdateProgress',
          percentage: 100,
          message: '....'
        });
      } else {
        processThings(summary, sender.tab.id);
      }
    }).catch(function(err){
      console.log(err);
    }).finally(function(){
      db.close();
    });
  });
});
```

The problem here is, that summary.appids (array) could have numbers w/ and w/o quotes. So I'm using this function now, to fill the array with quotes and unquoted numbers:

```javascript
var appids = summary.appids.map(Number);
appids.push(...summary.appids);
```
Edit: Ok, this only works if the numbers are quoted.

I know one should check for itself if this should be a number and only save it w/ or w/o quotes all the time. But I think it would make Dexie more "fail-resistant" if we check the search-strings w/ and w/o quotes to avoid such mistakes. And yes it would make Dexie slower, especially with a lot of DB-Entrys. :/

**Comment by dfahlander** [comment]
I understand the problem. Still, I would like to do those kind of magic fixes for the user. Not just for performance reasons but also because things could tend to work even though the code is wrong. Type aware languages like typescript could be to the rescue here though (because you'd define an interface or class for each table that the compiler would check when calling anyOf() and other methods).

**Comment by dfahlander** [comment]
Closing.
