### ISSUE TITLE
encrypted database

### ISSUE THREAD

**Issue by jimmywarting** [dfahlander/Dexie.js#255]
Would it be possible to have a encrypted indexedDB that can only be read/write and searchable by a web crypto key?
Database name, Table names, rows, indexes, (everything) encrypted so it can not be read by an attack

**Comment by dfahlander** [comment]
I use encryption in my app but to the cost of lesser indexing capability. You can index a HMAC-Sha digest of the value. The HMAC-Sha is a hash algorithm that also takes an encryption key. To get the correct digest ýou must know the value and the key. But it wont work with ranges or substring matches - just exact matches.

Example:

var KEY = "secret";

```js
function User(name, age) {
    this.data = encrypt({name: name, age: age}, KEY);
    this.nameIndex = hmacSHA(name, KEY);
}

// Store user
db.users.put(new User("Foo", 42));
// Find user by name. Need to know the exact name:
var user = yield db.users.where('nameIndex').equals(hmacSHA("Foo", KEY)).first();

```

**Comment by dfahlander** [comment]
Note though, that the index can the data subject to replay attacks, so if you should be able to index the data you will loose some security value. But sometimes you need to take the least bad of two things...

**Comment by jimmywarting** [comment]
It would be cool to have some authentication in the beginning when you open the database with dexie that whenever you put something in the database it will be encrypted for you, same thing when you query the data.

**Comment by dfahlander** [comment]
Yes, it may be something to accomplish with an addon. Even though only the equals() and anyOf() queries would give any valid results in those cases. Also need to let the addons hook into the WhereClase methods as well as Table.get() + add CRUD hooks. But it's possible.

**Comment by jimmywarting** [comment]
Cool!
I was thinking if there would be anyway to have the database searchable... But i guess you would have to decrypt the hole database first then and have it in the RAM. Perhaps not that efficient... best would maybe to do it yourself somehow, getAll() then filter

**Comment by dfahlander** [comment]
It could be searchable but only by exact match if using hashed indexes with a salt, such as HMAC-SHA.

**Comment by bman654** [comment]
I'm using Dexie and am looking into Encryption.  I just saw that YDN-DB supports [record encryption](http://dev.yathit.com/ydn-db/doc/usage/encryption.html).  Looks like they use salt to protect against the attack mentioned above.

**Comment by dfahlander** [comment]
The only thing that can make encrypted data indexable is either 1) to index a digest (preferably salted), 2) index the encrypted content but skip the random IV (symmetric encryption) or 3) to use assymetric encryption with fixed padding instead of random. Salting a digest will at least avoid brute force attacks of publicly known digests but it doesn't protect from being able to see patterns in the encrypted data (several records with same digest indicates they have something in common). In all three cases you will only be able to match by exact value (not between, below or above). Also, in all three cases, the security level of the encryption will never be as strong as properly encrypted data with random IV's or padding.

**Comment by dfahlander** [comment]
An add-on for encryption is now available: dexie-encryped

npm: https://www.npmjs.com/package/dexie-encrypted
github: https://github.com/mark43/dexie-encrypted

**Comment by baobao12356** [comment]
> 现在可以使用加密附加组件：dexie-encryped
> 
> npm: https://www.npmjs.com/package/dexie-encrypted
> github: https://github.com/mark43/dexie-encrypted



I use dexie-encrypted to query data that has not been encrypted before, and an error will be reported, Error utf8: invalid string, as shown in the figure below, please tell me how to solve it?
![image](https://user-images.githubusercontent.com/22005273/128153379-821f908b-f8c6-4c98-a35a-765216e3ac77.png)

**Comment by dfahlander** [comment]
> > 现在可以使用加密附加组件：dexie-encryped
> > npm: https://www.npmjs.com/package/dexie-encrypted
> > github: https://github.com/mark43/dexie-encrypted
> 
> I use dexie-encrypted to query data that has not been encrypted before, and an error will be reported, Error utf8: invalid string, as shown in the figure below, please tell me how to solve it?
> ![image](https://user-images.githubusercontent.com/22005273/128153379-821f908b-f8c6-4c98-a35a-765216e3ac77.png)

Please follow up on https://github.com/mark43/dexie-encrypted/issues/32
