### ISSUE TITLE
Dexie.js and Electron

### ISSUE THREAD

**Issue by dejaime** [dfahlander/Dexie.js#261]
Hi,

I am having some trouble to use DexieJS inside an Electron desktop application.
The chrome version that is running is 51.0.2704.63

So my question is, does Dexie.js support Electron?
Or it doesn't currently support Electron?

I installed Dexie via npm locally, the problem happens when I try to open the database in the main electron thread, with the following error:
MissingAPIError: indexedDB API not found. If using IE10+, make sure to run your code on a server URL (not locally). If using Safari, make sure to include indexedDB polyfill.

I tried installing indexeddb and indexeddbshim through npm, tried requiring those before initializing Dexie. Tried isolating my Dexie.js usage to a single file (to make sure I wasn't screwing up on different scopes and execution threads).

Any ideas on where to look?

    const Dexie = require ('dexie');
    var db = new Dexie('DBName');

    db.open().catch(function (e) {
        console.error("Open failed: " + e);
    });

>> Open failed: MissingAPIError: indexedDB API not found. If using IE10+, make sure to run your code on a server URL (not locally). If using Safari, make sure to include indexedDB polyfill.

**Comment by dfahlander** [comment]
You need to include Dexie from within a BrowserWindow's page.

**Comment by dfahlander** [comment]
Did it solve your problem?

**Comment by dejaime** [comment]
Yes, requiring it inside of the HTML page solves the problem!

I will try and test it further in the coming days, and see if I can actually bring the already initialized Dexie.js to the main thread (or if I need to keep a dummy window for it).


Thank you for your time!

**Comment by fracz** [comment]
Have you managed to bring the Dexie.js instance to the main electron thread?

**Comment by dejaime** [comment]
@fracz No, I didn't. I ended up using another database solution, but I can't recall whether I used Pouchdb or IndexedDB directly.
