### ISSUE TITLE
Broken Promise rejection

### ISSUE THREAD

**Issue by dpogue** [dfahlander/Dexie.js#264]
I'm having an issue after upgrading to Dexie 1.4.0:

```javascript
MyDB.where('id')
    .equals('does-not-exist')
    .first()
    .then(result => {
      if (result !== null && result !== undefined) {
        return result;
      } else {
        return Promise.reject(result)
      }
    })
    .catch(_ => null);
```

The catch block is never running, despite returning a rejected promise in the handler above.
This worked in 1.3.6.

**Comment by dfahlander** [comment]
Thanks for reporting. Will try to look into it asap

**Comment by dpogue** [comment]
It seems that it does work if I `throw Promise.reject(result)`, but that's not consistent with behaviour of native promises

**Comment by dfahlander** [comment]
Issue was that rejecting with `undefined` triggered the bug. v1.4.1 out in a few minutes.

**Comment by dpogue** [comment]
Yep, 1.4.1 works. Thanks!
