### ISSUE TITLE
how can i fuzzy search

### ISSUE THREAD

**Issue by jimmy0766** [dfahlander/Dexie.js#267]
how can i fuzzy search?
on webSQL , i can use "select * from tb where name like %mm%;"
but ,i can not know how use on indexedDB.

this lib can do it?

**Comment by dfahlander** [comment]
You can do it but not utilizing any index - like on any SQL database, this will be a full-table search:

```js
db.yourTable.filter(x => /mm/.test(x.name).toArray();
```

If your data is large and you really need to utilize indexes to speed up such search, have a look at the [full-text index](https://github.com/dfahlander/Dexie.js/blob/master/samples/full-text-search/FullTextSearch.js) sample that can be achieved by indexing each word as a separate entry. 

See also: #252 and #146.


`

**Comment by jimmy0766** [comment]
thank you ,i will try it.

**Comment by dfahlander** [comment]
Closing

**Comment by rameshsunkara** [comment]
>If your data is large 

I understand this is very old thread, but can you give an estimate of what you consider as large data.
I am trying to assess whether I should go with this simple approach you gave above or go with Full Text Search.

My Data set will have ~10,000 Objects and each object will have 3 fields. Each field wouldn't go beyond 25 characters.

**Comment by dfahlander** [comment]
I think you'd need to test it out but I would recommend indexes in that case. If you can search on prefixes, a plain simple index will do, using the [startsWith](https://dexie.org/docs/WhereClause/WhereClause.startsWith()) operator. If you plan to search for word occurrencies, you can utilize a [multientry index](https://dexie.org/docs/MultiEntry-Index) of an array property where you store all words in lowercase or hashes of those.
