### ISSUE TITLE
Support for Dexie.Promise.resolve()

### ISSUE THREAD

**Issue by bennyn** [dfahlander/Dexie.js#274]
To return Promise-based code which uses synchronous code (code without Promises) I like to use this coding pattern:

```javascript
function myFunction() {
  return Promise.resolve()
  .then(function() {
    // return value from synchronous code
  }).
  .then(function() {
    // return another Promise
  }).
  .then(function() {
    // return a ... Promise
  });
}
```

The use of `Promise.resolve()` in the beginning guarantees that `myFunction` returns a Promise and acts inside like Promise-based code. However, Dexie's Promise implementation seems to no support this practice.

I tried the following but it does not work:

```javascript
function myFunction() {
  return Dexie.Promise.resolve()
  .then(function() {
    // return value from synchronous code
  }).
  .then(function() {
    // return another Promise
  }).
  .then(function() {
    // return a ... Promise
  });
}
```

Is there a similar approach that I could use with Dexie's Promise implementation?

**Comment by dfahlander** [comment]
Oh yes, that should definitely work with dexie. But your sample has invalid semicolons before the `then()` calls.

**Comment by bennyn** [comment]
Hi @dfahlander, thanks for your fast and detailed answer (as always :smile:). I fixed the semicolon issue (as it was only due to copy & pasting). Here is a screenshot of the actual code that I am writing:

![screenshot](https://cloud.githubusercontent.com/assets/469989/16228304/8ff5a090-37b6-11e6-8a7b-9482bd2531bf.png)

It tells me that `resolve()` is an undefined function. If I use an ES6 Promise it works:

![screenshot](https://cloud.githubusercontent.com/assets/469989/16228349/c32b103a-37b6-11e6-873a-b73fb62751cc.png)

**Comment by dfahlander** [comment]
Ok, then it must be an issue with the d.ts file. Let me have a look...

**Comment by dfahlander** [comment]
In my test it works perfectly well to do this:

![image](https://cloud.githubusercontent.com/assets/6791329/16229201/ee062902-37bb-11e6-9dbe-bfa974761b91.png)

I'm using vs code and typescript version 1.8.7.

Are you sure you aren't using an old version of the d.ts file or an old typescript compiler? Check [this guid](https://github.com/dfahlander/Dexie.js/wiki/Typescript) that you've not used tsd or typings to include old d.ts files.

**Comment by dfahlander** [comment]
Did you find the issue or are you still experiencing problems?
