### ISSUE TITLE
Problem with iframe

### ISSUE THREAD

**Issue by michael2043** [dfahlander/Dexie.js#279]
I worked with the code on iOS(9.x) Safari below:

$(function(){
	var idb;
	if(!idb){
		idb = new Dexie("idb01");
		idb.version(1).stores({ tbl03: "[id1+id2],name,age" });
		idb.open();
	}
});
and in body insert a normal iframe
'iframe src="empty.html"'

when I use MacBook to inspect ,I found that two "idb01" was create...,when I remove the iframe from the page and clear cookies and refresh,one "idb01" was left...

In face ,there are many iframes in my project,when update data into indexdb,Dom exception happened
why iframe can increase the numbers of database

**Comment by dfahlander** [comment]
Hard to tell the reason behind this. Are you sure you actually got multiple databases with same name? That should not be possible. Maybe the inspection tool shows multiple db in error?

What version of safari are you using?

**Comment by michael2043** [comment]
iPad:iOS9.2.1
MacBook:MacOS10.10.5,Safari9.0
add a  iframe in body two db with the same name,remove the iframe one left

**Comment by michael2043** [comment]
![Uploading aaa.png…]()
