### ISSUE TITLE
Promise typings issue

### ISSUE THREAD

**Issue by phiresky** [dfahlander/Dexie.js#280]
As far as I can tell the type of `Promise<R>.catch` should be 

`catch<U>(onRejected: (error: any) => U): Promise<R|U>;`

instead of
`catch<U>(onRejected: (error: any) => U): Promise<U>;`

e.g. `Promise.resolve(100).catch(err => "str")` should have type `Promise<string|number>`

see also the Promise definition in Typescript: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L5169-L5181

**Comment by dfahlander** [comment]
Ok, true. Please do a pr (that updates src/Dexie.d.ts) if you have time.
