### ISSUE TITLE
Upgraders have a false API towards their object stores

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#287]
Related to #105 and #1. When an upgrader function attached to a Version instance accesses the provided upgrade transaction (trans), it will only have the object stores from the latest version in it, and believe that indexes from latest versions apply in the upgrader. In practice, you can never delete an object store (setting it to null in a later version) and having an upgrader function reading from it. Secondary problem: If a previous version had an index that has been deleted in a later version, an upgrader cannot utilize the previous index for upgrading to the newer version.

This needs to be fixed and it needs an architectural change.

Todo:
- Let each Version instance have a Transaction instance populated with the object stores that are relevant in that particular version, as well as the available indexes. Should be based on the previous version's stores and indexes plus added stores in current version.
- Stop populating Transaction.prototype with tables. Instead populate the prototype of a Transaction subclass bound to the latest Version instance. Create such Transaction instead of the base transaction on normal transactions. On upgrade transactions, create a transaction based on the version being upgraded.

Also, if possible make upgrader fail if trying to use db.table-style instead of trans.table.

**Comment by chrahunt** [comment]
Do we still want to make upgrader fail on db[table] style access?

**Comment by dfahlander** [comment]
We could allow db[table] style access. I close.

**Comment by dfahlander** [comment]
The issue was solved 2018-06-03 in 3.0.0-alpha.3 with PR #714. Don't understand why I closed it in 2017 already... Anyway, it's solved now.
