### ISSUE TITLE
Cannot import dexie from node_modules with PhpStorm

### ISSUE THREAD

**Issue by CasperPas** [dfahlander/Dexie.js#289]
While writing code in TypeScript with PhpStorm 2016.1.2, this code:
`import {Dexie} from 'dexie';`

shows red underline error:

> TS2305: Module '"..../node_modules/dexie/dist/dexie"' has no exported member 'Dexie'

**Comment by dfahlander** [comment]
Dexie is a default export. You are importing it as if it was a named export.

```js
import Dexie from 'dexie';
```

**Comment by CasperPas** [comment]
Ah, sorry. My PC is a little bit laggy so I tried that and the error still remain.
Thank you for your quick response!

**Comment by ansorg** [comment]
Thanks! This helped me getting it to work in Aurelia.io
