### ISSUE TITLE
Limit for auto incremental primary key

### ISSUE THREAD

**Issue by HerculanoGripp** [dfahlander/Dexie.js#295]
Which limit an auto incremental primary key in dexie ?
What happens when this limit is reached ?

I have db schema like this for:

```javascript
logs = new Dexie('logs');
logs.version(1).stores({
        operation: "++, &code, ope_code, comp, tstam",
        user: "++, &code, user_code, action, tstam"
});
```

Per day my application insert +/-8600 records on db. 
The records are sent to the server from time to time and are deleted from dexie. But records primary key id continues growing up. Is there a problem ?

**Comment by dfahlander** [comment]
In theory, there's only javascript 's limit on the 'number' type which is extremely high. In practice,  I would assume most implementations use a 32 bit int as counter (signed in worst case) which means about 2 billion increments. No, I would not worry about that for a client side db.

**Comment by HerculanoGripp** [comment]
@dfahlander thanks for the help. I think this is not a problem in my application. Limit of auto-increment is too huge.
