### ISSUE TITLE
How to deal with inconsistent behavior between put/bulkPut

### ISSUE THREAD

**Issue by yangchenyun** [dfahlander/Dexie.js#296]
For new/old object with the same unique key, `put` will replace old one with new one; but `bulkPut` will raise reject with error for conflicting ones.

In the case that I always want to replace old with new one, what's the solution I should use?

**Comment by dfahlander** [comment]
No bulkPut() will work as put(). Not raise reject for conflicting ones,
just raise rejects if other constraint errors such as conflicting unique
index.

David Fahlander
*Awarica AB*
Selmedalsvägen 24, 8tr
12936 Hägersten
Sweden
Växel: 08 525 041 90
Mobil: 070 789 14 07
Webb: www.awarica.com


2016-07-28 9:53 GMT+02:00 Steven Yang <notifications@github.com>:

**Comment by alexey-sh** [comment]
So how it is possible to update rows?
For example,
```
db.version(1).stores({
    tests: '++localId,age,&_id'
})
// after that
db.tests.bulkAdd([{age: 1, _id: 1}, {age: 2, _id: 2}]) // ok, it is done
db.tests.bulkPut([{age: 100500, _id: 1}, {age: 2009, _id: 2}]) // raising ConstraintError
```

To be honest I expected updated rows not the ConstraintError.

Thanks for the library 👍

**Comment by dfahlander** [comment]
Maybe you could try using the remote id as primary key. Do you need to separate them?

**Comment by alexey-sh** [comment]
@dfahlander thanks for the response
Can I add into database a record without remote id (if I will setup remote id as pk)?

**Comment by dfahlander** [comment]
Each db record needs a valid pk. If your concern is client-generated offline records, you could prefix those somehow. Even better if your ids are uuids, you could just let the client invent ids if your backend api allows it.

**Comment by alexey-sh** [comment]
@dfahlander thanks for the suggestion.
My backend(be honest it is not my backend literally) does not allow generating ids on the client side.

**Comment by yangchenyun** [comment]
@alexey-sh Thanks for the example, this is the use case I stumbled upon as well.

This is a valid use case when bulk updating the same entry on the front end (for example syncing). The update must identify the unique pk and update the rest of the data.

Right now I have to iterate through the item and do a put one by one. 

I suggest to add a parameter to enable bulkPut to have the same behavior as put.

**Comment by dfahlander** [comment]
bulkPut has the same behavior as put.

**Comment by alexey-sh** [comment]
@yangchenyun 

here is my solution. not tested it though.

```
    function safeBulkInsert (table, data) {
            console.log('safe bulk insert', _.pluck(data, '_id'));
            return new Dexie.Promise(function (resolve, reject) {
                var insertIds = _.pluck(data, '_id');
                return table.where('_id').noneOf(insertIds).delete().then(function (r) {
                    console.log('safe bulk put', data.length, r);
                    var sequence = _.map(data, function (item) {
                        return function () {
                            return table.where('_id').equals(item._id).modify(item).then(function (a) {
                                console.log('modified', a, item._id);
                                if (a === 0) {
                                    return table.add(item);
                                }
                            }).catch(function (e) {
                                console.log(e)
                            });
                        }
                    });
                    utils.sequence(sequence).then(resolve);
                });
            });
        }
```
utils..

```
    sequence:  function (promiseReturningFunctions) {
                var queueEntryPoint = new Dexie.Promise(function (resolve, reject) {

                    resolve();
                });
                promiseReturningFunctions.forEach(function (p) {
                    queueEntryPoint = queueEntryPoint.then(p).catch(function (e) {
                        console.log('CATCH from utils');
                        reject(e);
                    });
                });
                return queueEntryPoint;
            }
```

dfahlander is right. the `put` does the same as bulkPut. it means put will throw the same error as bulkPut.
