### ISSUE TITLE
[Urgent] - How to store form data in database ?

### ISSUE THREAD

**Issue by mbj36** [dfahlander/Dexie.js#299]
I have a form which contains firstname, lastname, middlename, email and various other inputs. I want to store that data offline using dexie.js in browser . How can i do it ?

**Comment by dfahlander** [comment]
Have you even seen the most basic samples at the home page or read the tutorial?

**Comment by mbj36** [comment]
Yes, It would be great if you could guide me through this.
I am doing my internship at Mifos Initiative as a GSOC intern and we are planning to use dexie widely in our angular app. Being a newbie we would need your help :)

**Comment by agozie** [comment]
Please, read the tutorials and practice with the many examples there, then
ask specific questions if any. This area is called "issues", go to the
"wiki" to learn.

**Comment by trihicham6** [comment]
I have a form which contains firstname, lastname, middlename, email and various other inputs. I want to store that data offline using dexie.js in browser . How can i do it ?

**Comment by dfahlander** [comment]
Please post questions on [stackoverflow, tagged dexie](http://stackoverflow.com/questions/ask?tags=dexie)
