### ISSUE TITLE
Weird Safari 9

### ISSUE THREAD

**Issue by alexey-sh** [dfahlander/Dexie.js#303]
Hi

thanks for the library.

I have the following code:

```
function letsDoIt (table, data) {
            console.log('safe bulk insert', _.pluck(data, '_id'));
            return new Dexie.Promise(function (resolve, reject) {
                var insertIds = _.pluck(data, '_id');
                console.log('here is', insertIds);
                table.where('_id').noneOf(insertIds).delete().then(function (r) {
                    console.log('OK', r);
                    resolve();
                }, reject);
}
```

When I called it the `OK` message doesn't appear in console.
What I'm doing wrong? I've included this shim (only for safari) `https://cdn.jsdelivr.net/indexeddbshim/0.1.2/IndexedDBShim.min.js`
It works perfectly in chrome.

Thanks.

**Comment by alexey-sh** [comment]
found error
Error: NotFoundError: DOM IDBDatabase Exception 8

**Comment by alexey-sh** [comment]
solved with shim

**Comment by dfahlander** [comment]
Ok. Thanks for sharing.

**Comment by alexey-sh** [comment]
I would share the snippet too

```
var isSafari = navigator.vendor && navigator.vendor.indexOf('Apple') > -1 &&
navigator.userAgent && !navigator.userAgent.match('CriOS');
var dbOptions = {};
if (isSafari) {
    window.shimIndexedDB.__debug(true);
    dbOptions.indexedDB = window.shimIndexedDB;
}
var db = new Dexie("dbName", dbOptions);
```

**Comment by dfahlander** [comment]
Ok. When providing indexedDB in options, it's very important to also provide the implementation of IDBKeyRange:

```js
if (isSafari) {
    dbOptions.indexedDB = window.shimIndexedDB;
    dbOptions.IDBKeyRange = window.shimIndexedDB.constructor.modules.IDBKeyRange;
}
```

**Comment by dfahlander** [comment]
Ok. Dexie will use the shim by default if it is included. The rationale behind that is that we assume that you wouldn't want to include the shim if it's not needed. See https://github.com/dfahlander/Dexie.js/issues/63.

However, it's perfectly fine to do as you do, but when specifying an indexedDB implementation, you must also provide the implementation to IDBKeyRange. Also, you should probably inactivate the shim in the else-statement to prohibit the default behavior.

```js
if (isSafari) {
    dbOptions.indexedDB = window.shimIndexedDB;
    dbOptions.IDBKeyRange = window.shimIndexedDB.constructor.modules.IDBKeyRange;
} else {
    dbOptions.indexedDB = window.indexedDB;
    dbOptions.IDBKeyRange = window.IDBKeyRange;
}
```

**Comment by alexey-sh** [comment]
@dfahlander 
```
> window.shimIndexedDB.constructor.modules.IDBKeyRange
< TypeError: undefined is not an object (evaluating 'window.shimIndexedDB.constructor.modules.IDBKeyRange')
```

`window.shimIndexedDB.constructor` is not defined

**Comment by dfahlander** [comment]
Ok, debugged it. Should just remove 'constructor':

```js
if (isSafari) {
    dbOptions.indexedDB = window.shimIndexedDB;
    dbOptions.IDBKeyRange = window.shimIndexedDB.modules.IDBKeyRange;
} else {
    dbOptions.indexedDB = window.indexedDB;
    dbOptions.IDBKeyRange = window.IDBKeyRange;
}
```
