### ISSUE TITLE
delete() not working if done in an onClick event

### ISSUE THREAD

**Issue by rvelhote** [dfahlander/Dexie.js#304]
Hello,

**Browser:** Chromium 51.0.2704.79 Ubuntu 16.04 (64-bit)

I am trying to delete a record during an onClick event but the record does not get deleted. If I call the delete() method directly there is no problem. I get the same issue with update() but add() works correctly.

```

    var db = new Dexie("photosdb");
    db.version(1).stores({ photos: "++id,filename,emails,date,is_sent" });
    db.open();

    var PhotoDatabase = {
        getPhotos: function() {
            return db.photos.where('is_sent').equals(0).toArray();
        },
        delete: function(id) {
            return db.photos.delete(id);
        }
    };

    window.PhotoDatabase = PhotoDatabase;

```

Some things were removed from the next sample for it to have a smaller size:

```
window.PhotoDatabase.getPhotos().then(function(photos) {
    var table = document.getElementById("offline-file-list");

    photos.forEach(function(p, i) {
        var deleteButton = document.createElement("button");

        deleteButton.type = "button";
        deleteButton.dataset.id = p.id;
        deleteButton.dataset.filename = p.filename;
        deleteButton.innerHTML = "Delete";
        deleteButton.className = "btn btn-danger btn-xs";
        deleteButton.onclick = onDeleteClick;

        operations.appendChild(deleteButton);
    });
});
```
And finally the delete onClick event. Note that if I call ```window.PhotoDatabase.delete(id)``` directly outside the click event everything works as expected.

```
var onDeleteClick = function() {
    var id = this.dataset.id;
    var filename = this.dataset.filename;

        window.PhotoDatabase.delete(id).then(function() {
            // This gets called correctly and when I refresh the record is still there
            document.querySelector("[data-id='" + id + "']").style.display = "none";
        });
};
```

I appreciate any help. Is there something obvious here that I'm missing?

Best regards,
Ricardo Velhote

**Comment by dfahlander** [comment]
That's strange. Check that id is of type Number when having retrieved it from this.dataset.id, before using it in the call to delete(). If it of some reason has been converted to a string, or if it would point to a non-existing id, the call to PhotoDatabase.delete(id) would still resolve successfully ([WriteableTable.delete()](https://github.com/dfahlander/Dexie.js/wiki/WriteableTable.delete()).

**Comment by rvelhote** [comment]
You are very correct David. It's an issue of data type. I was looking at the debugger for both calls and didn't notice the difference between 8 and "8".

When calling delete() directly I was passing an integer but when reading from the element's data attribute I was getting a string. Passing the id variable through ```parseInt()``` solves the issue.

Thank you very much for the quick reply.

**Comment by dfahlander** [comment]
:+1:
