### ISSUE TITLE
Angular2 vs Dexie : Syntax Error with async

### ISSUE THREAD

**Issue by An0d** [dfahlander/Dexie.js#309]
Hi,

I'm trying to run the "[Hello World (TypeScript)](https://github.com/dfahlander/Dexie.js#hello-world-typescript)" sample in an Angular2 app (2.0.0-rc.6)

When I add the following line `db.transaction('rw', db.friends, async () => { });`
I'm encountering the following error :

`Error: SyntaxError: Unexpected identifier`

For your information I added the following blocks / lines in systemjs.config.js :
Under the "map" section :
`'dexie': 'npm:dexie/dist/dexie.js'`

Under the "packages" section :
`'dexie':{
        format: 'amd'
      }`

My Angular2 project is based on the [Angular2 - Quickstart repository](https://github.com/angular/quickstart)

Any idea ?
Thank you

**Comment by dfahlander** [comment]
Typescript compiler cannot use async / await when targeting ES5, which is the case in tsconfig for angular2 quickstart. Either, skip using async / await and use promise-style instead. Or configure tsconfig to target ES6 and transpile it further with babylon or babel. Or simply wait for a better future version of tsc that can handle async functions and output to ES5.

**Comment by dfahlander** [comment]
Typescript 2.1 will handle async await when transpiling to ES5 according to the [typescript road map](https://github.com/Microsoft/TypeScript/wiki/Roadmap).

**Comment by An0d** [comment]
Ok, thanks :-)

**Comment by dfahlander** [comment]
Confirmed that you can use typescript 2.1 and compile directly to ES5 without involving babel.

You will need Typescript 2.1 beta and Dexie ^2.0.0-beta.2 for it to work.

Here's the source:

https://github.com/dfahlander/Dexie.js/tree/master/samples/typescript
