### ISSUE TITLE
Compound Index with anyOf

### ISSUE THREAD

**Issue by kkirby** [dfahlander/Dexie.js#31]
Hello.

I tried to query the database using a compound index and anyOf, but it threw a few exceptions. The first being that the key passed to continue was the same as the current key. Which is a simple fix, because Dexie is comparing the key values using === which doesn't work on array keys. The second problem was that the bound keys had the lower key being larger then the higher key. Probably another simple fix.

**Comment by Paril** [comment]
I think this is still an issue; performing an anyOf on an index of [x+z] with input of [ [ -2, 0 ], [ -3, 0 ] ] seems to reproduce the problem. Is there a way to supply a custom sorter or something? Should I just sort the data before sending it through?

**Comment by dfahlander** [comment]
Reopening it.

**Comment by dfahlander** [comment]
@Paril, Could you check if this is solved in latest version?

**Comment by dfahlander** [comment]
Reason I ask is because I've generally changed the way sorting is done in anyOf to sort via indexedDB.cmp() that should make it behave better.

**Comment by dfahlander** [comment]
Verified this has been fixed indeed.
