### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by krassx** [dfahlander/Dexie.js#310]
I am using rollup.js in my build flow and it constantly fails to process Dexie due to circular dependecies in errors.js and Promise.js. They both seems to import utils and are imported by it.

I think we can get rid of these deps in utils.js and use plain Promise and hardcoded error definition.

**Comment by dfahlander** [comment]
Cyclic dependencies are supported by ES6 and rollup. https://github.com/rollup/rollup/wiki/Cycles.

**Comment by krassx** [comment]
I have read these docs, but that is no help. I always get Rollup warnings during build and eventually my final bundle fails to run. I had to fork Dexie and fix cyclic deps to make it work for me.

I think it's worth mentioning that I use 'iife' as a rollup output format, so I have no any modules as a result.

**Comment by dfahlander** [comment]
Unless you need to cherry-pick modules, you could just include dist/dexie.es6.js into your rollup flow.

**Comment by dfahlander** [comment]
Dexie's build script uses rollup to output UMD format (IIFE, AMD, CJS combined) and it works perfectly. Which version of rollup are you using?

**Comment by krassx** [comment]
I am using 0.34.13.

**Comment by dfahlander** [comment]
Ok, then it's more up-to-date than mine. Thanks for the response. I used to publish a rolled-up ES6 module at dist/dexie.es6.js but moved it away for some reason. The build script creates it though using rollup of src/Dexie.js. Maybe I should put it back again and start pointing esnext:main to that version instead. Keeping this issue open.

**Comment by krassx** [comment]
Would be really great to have it back. Thank you.

**Comment by dfahlander** [comment]
I've put `dist/dexie.es6.js` back and pointed package.json to it rather than pointing to src/Dexie.js. This should hopefully resolve the issue.

Please try:

```
npm install dexie@1.4.3-rc --save
```

... and report me back if it works for you.
Thanks,
David

**Comment by krassx** [comment]
Thank you. Will try and respond.

**Comment by krassx** [comment]
It works. Tried with 1.4.3-rc.

**Comment by dfahlander** [comment]
Good. The reason I get it working is because I've been using an older version of rollup. Cyclic dependencie are broken in the newest version of rollup, see: https://github.com/rollup/rollup/issues/995

**Comment by krassx** [comment]
Got it. Thanks.
