### ISSUE TITLE
Transactions fail during Chrome's print preview

### ISSUE THREAD

**Issue by acicali** [dfahlander/Dexie.js#314]
I'm not sure where to begin troubleshooting this issue, but I'm getting errors from bulkPut() when they happen while Chrome's print preview dialog is displayed.

Here's the exact scenario:

- A polling loop runs in my application once a minute that gets updated objects from the server and writes them to an IndexedDB collection using Dexie.bulkPut().
- Touching the object's timestamp on the server causes that object to be sent to the client on the next polling iteration. This system normally works well.
- If the Google Chrome print preview dialog is displayed during a polling loop, Dexie.bulkPut() fails with the following: "BulkError: myCollection.bulkPut(): 1 of 1 operations failed. Errors: AbortError: The transaction was aborted, so the request cannot be fulfilled."

I left the print preview opened for a while in order to reproduce this issue - it is possible that Chrome is delaying the write operation during that dialog. Might there be an intentional timeout failure for these writes?

**Comment by dfahlander** [comment]
There's no timeout in any write operation. Are you using crud hooks or not? Bulkput (and put) behaves differently with crud hooks on than when theres no crud subscriber. So I'm just curious about a hint. In case you're not subscribing to hook ('creating') or hook ('updating') the flow of bulkPut is so trivial that i auspect it to be a chrome bug. If you are subscribing to the hooks, the flow is also pretty simple but a little more operations takes place.

**Comment by acicali** [comment]
No crud hooks, just a simple bulkPut().

I believe you are correct that this is a Chrome issue. It turns out that my polling loop wasn't the cause - Chrome actually seems to pause JavaScript execution during the display of the print dialog, so that polling wasn't happening. It was though, the result of this combination: HTTP Request > then( window.print(); return response; ) > then( bulkPut(response.collection) )

Using a stopwatch confirms the error requires exactly one minute of delay before the write fails. This is the only reference I could find to an intentional TimeoutError: https://bugs.chromium.org/p/chromium/issues/detail?id=339229

My issue is resolved easily, but I'm not sure if this should actually be considered a bug in Chrome or not. Opinions?

**Comment by dfahlander** [comment]
Interesting. Timeout is not part of the standard. Understand the issue though, but one minute is short when debugging or watching a print dialog. Can't see the reason why they stop javascript execution during the print dialog though.
