### ISSUE TITLE
Add bower ignore section

### ISSUE THREAD

**Issue by jarrodek** [dfahlander/Dexie.js#319]
When getting Dexie from bower it clones whole repository. However directories like `src`, `test`,`tools` and all the JS maps are not important in production environment.
It's not critical but I have to add another exception in my app's build script to not copy some files when building the app. It may help more people I guess.

The ignore section in `bower.json` file could look like this:
```
"ignore": [
  "**/.*",
  "**/tmp/",
  "addons/*/bower.json",
  "samples/",
  "*.njsproj"
  "src",
  "test",
  "tools"
],
```

**Comment by dfahlander** [comment]
Thanks! I've updated bower.json according to your suggestions and also test and tools under each addon. Will be included in next release. Might be a rc release.

**Comment by jarrodek** [comment]
Great! thanks
