### ISSUE TITLE
 bulkPut() with non-inbound keys requires keys array in second argument

### ISSUE THREAD

**Issue by sachinsan** [dfahlander/Dexie.js#322]
Hi, 
First of all thank you for Dexie, its simply Awesome!! 

I am getting the following error
Unhandled rejection: InvalidArgumentError: bulkPut() with non-inbound keys requires keys array in second argument.
Below is my code which is part of a project. The weird thing is when i run it as a separate html / js it works fine but doesn't as part of my bigger project. Kindly guide. 

 `$("#btnDatabaseToDB").click(function (e) {       
        var db = new Dexie("sampleDB");        
        db.version(1).stores({ Customer: 'CustomerID, Name, Flag' })
        db.open()
        list = [];
        for (i = 0; i < 2; i += 1) {
            tmp = {
                'Phone': "12121",
                'Address': "Address",
                'Name': "Name" + i,               
                'City': "City",
                'Email': "Email",
                'Flag': 0,
                'ImagePath': "sachin"
            };
            console.log('adding item ' + i);
            list.push(tmp);
        }
        insertRecords(db, list);
    });
	
    var insertRecords = function (db, list) {
        custList = [0, 1];
        db.Customer.bulkPut(list).then(function () {
            console.log("Done putting 2000 Testdata all over the place");
        }).catch(Dexie.BulkError, function (e) {           
            console.error("Some Customers didn't get downloaded Failed= " + e.failures.length);
        });
        console.log('Finished insertRecords ');
    };
`

**Comment by dfahlander** [comment]
The error message may be misleading but I believe it is due to that you are missing to provide the inbound primary key 'CustomerID' in the objects you are adding. Must provide that property  in all objects you send into bulkPut()

**Comment by sachinsan** [comment]
Did add that as par the objects and also tried by sending array of primary keys. Something wrong no sure.

Updated one! 
`$("#btnDatabaseToDB").click(function (e) {       
        var db = new Dexie("sampleDB");        
        db.version(1).stores({ Customer: 'CustomerID, Name, Flag' })
        db.open()
        list = [];
        for (i = 0; i < 2; i += 1) {
            tmp = {
			    'CustomerID': i,
                'Phone': "12121",
                'Address': "Address",
                'Name': "Name" + i,               
                'City': "City",
                'Email': "Email",
                'Flag': 0,
                'ImagePath': "sachin"
				
            };
            console.log('adding item ' + i);
            list.push(tmp);
        }
        insertRecords(db, list);
    });
	
    var insertRecords = function (db, list) {
        custList = [0, 1];
        db.Customer.bulkPut(list).then(function () {
            console.log("Done putting 2000 Testdata all over the place");
        }).catch(Dexie.BulkError, function (e) {           
            console.error("Some Customers didn't get downloaded Failed= " + e.failures.length);
        });
        console.log('Finished insertRecords ');
    };`

**Comment by dfahlander** [comment]
Please ask these kind of questions at stackoverflow.com and tag them 'dexie'.  I've no time to debug this code.  Sorry.

**Comment by sachinsan** [comment]
Sure will do that. Thanks.
