### ISSUE TITLE
Unhandled rejection?

### ISSUE THREAD

**Issue by skygragon** [dfahlander/Dexie.js#323]
I/chromium(14134): [INFO:CONSOLE(1231)] "Unhandled rejection: AbortError: Transaction aborted", source: file:///android_asset/www/js/vendors/dexie.js (1231)

not sure when will this happen?

**Comment by dfahlander** [comment]
Did you get a stack with the error? Normally this error will  happen due to a previous error. If you are using Dexie 1.4.x and set `Dexie.debug = true` (or access the page from locahost), the `error.stack` will contain the async flow that preceeded the error.

**Comment by skygragon** [comment]
Thanks your advice. Now I got one more string print from e.stack, which told one previous error at table.update(key, newValue). The weird thing is I can still read records from the same table w/o any error, thus I guess maybe that db is in 'readonly' somehow?

I'm using Dexie.js in ionic framework (which wraps HTML5 into a native app on mobile), and this issue occurs when I quit my app on Android => clean the backend processes/cache => re-launch the app => then failed in updating table...

**Comment by dfahlander** [comment]
Make sure you don't mix promises within your transaction scope. Also make sure to open transaction in 'rw'  mode. See [https://github.com/dfahlander/Dexie.js/wiki/Best Practices#3-dont-use-other-async-apis-inside-transactions](https://github.com/dfahlander/Dexie.js/wiki/Best Practices#3-dont-use-other-async-apis-inside-transactions)

**Comment by dfahlander** [comment]
Cannot really guide you more than that without a code snippet that shows what you are trying to do. I have to make these guesses only.

**Comment by skygragon** [comment]
Actually I don't explicitly call transaction API, but I'm not sure if I'm using 'non-Dexie' promises, my error occurs on Line 156 here => https://github.com/skygragon/careercup-mobile/blob/master/www/js/services/db.js

And I remember that this promise ($q) is introduced quite recently, while I hit this error long time ago when I'm still using normal callback ways ...

**Comment by skygragon** [comment]
Here are some findings so far by tracing in Dexie.js:
1. checkFinished() is called for this update() calling, and step in resolve(successCount=1);
2. then in tempTransaction() L1783, the trans._completion.then() is never called?

I'm not familiar with this workflow, is it caused by 'non-Dexie' promise as you said?

**Comment by dfahlander** [comment]
Looking at your code I couldn't see anything at all that could make this error occur. If you don't do explicit transactions you can mix promises however you like. So that shouldn't be an issue. 

Does the error only happen after quit/clean/relaunch? It reminds me of another issue with Electron apps (chromium based desktop apps) where re-launching the process can lead to IndexedDB instability while two Electron processes compete about the backing database file. Electron's indexedDB support fails when two or more processes are running at the same time. Maybe this is not applicable to cordova applications, I'm don't know whether it launches its own chromium or relies on the native browser (which would not have this issue).

If multiple-process is not the issue, I couldn't think of anything else than an internal Dexie bug triggered by invalid indata to the update() method, such as an invalid key type or similar. To debug this, include the non-minified version of Dexie and set `Dexie.debug = "dexie";`at startup. The stack will then contain more details about where in dexie.js the error happens.

**Comment by skygragon** [comment]
I/chromium( 7294): [INFO:CONSOLE(19)] "Failed to update question because AbortError: Transaction aborted
I/chromium( 7294):     at IDBTransaction.<anonymous> (file:///android_asset/www/js/vendors/dexie.js:2766:52)
I/chromium( 7294):     at IDBTransaction.<anonymous> (file:///android_asset/www/js/vendors/dexie.js:1250:26)
I/chromium( 7294): From previous:
I/chromium( 7294):     at new Transaction (file:///android_asset/www/js/vendors/dexie.js:2687:31)
I/chromium( 7294):     at Dexie._createTransaction (file:///android_asset/www/js/vendors/dexie.js:1744:19)
I/chromium( 7294):     at tempTransaction (file:///android_asset/www/js/vendors/dexie.js:1760:31)
I/chromium( 7294):     at WriteableTable.getIDBObjectStore (file:///android_asset/www/js/vendors/dexie.js:2199:102)
I/chromium( 7294):     at WriteableCollection._write (file:///android_asset/www/js/vendors/dexie.js:3398:45)
I/chromium( 7294):     at WriteableCollection.Dexie.derive.from.extend.modify (file:///android_asset/www/js/vendors/dexie.js:3720:28)
I/chromium( 7294):     at WriteableTable.Dexie.derive.from.extend.update (file:///android_asset/www/js/vendors/dexie.js:2653:65)
I/chromium( 7294):     at file:///android_asset/www/js/services/db.js:169:8", source: file:///android_asset/www/js/controllers/question.js (19)

**Comment by dfahlander** [comment]
The internal transaction is aborted of no reason. Does this happen only when cleaning / relaunching the app? Could it be that you relaunch the app while the old process is still not killed?

**Comment by dfahlander** [comment]
Transaction abort can also happen when hard disk limit is reached.

**Comment by skygragon** [comment]
That might be a race condition between the old process and the new re-launch one since I only see this error when relaunching...

**Comment by gitawego** [comment]
I have exactly the same problem. it happens when there are a of data in indexedDB. (but hard disk has still a lot of space.)

**Comment by dfahlander** [comment]
@gitawego Are you using [CRUD hooks](https://github.com/dfahlander/Dexie.js/wiki/Table.hook('updating')) or [Table.mapToClass()](https://github.com/dfahlander/Dexie.js/wiki/Table.mapToClass())?

**Comment by gitawego** [comment]
@dfahlander sorry for the delay, I didn't use any hooks nor mapToClass. 
in fact it doesn't occur systematically, some of my users reported this bug when they have a lot of data stored in indexedDB (the application stores images in base64).
I will try the new update to see if it resolves the problem.

**Comment by dfahlander** [comment]
I don't think the new release will help because it only fixes issues bound to using hooks when the hook subscriber throws. 

There are several possible runtime errors that may result in AbortError:

1. Out-of memory 
2. Transaction timeout (only chrome has. It's 30 or  60 seconds,  don't know which). When viewing a print dialog for example, js execution is paused and transaction times out.
3. Out of hard disk space.

**Comment by uncletammy** [comment]
@gitawego @dfahlander ,

I'm also having this problem while using Dexie for storing base64 images as strings using an Angular 1.5.8 front end.  

Everything works as expected on desktop (Chromium 51.0.2704.79 running on Debian 8.5 ) .  When using the same app features on Chrome (52.0.2743.98 running on Android 4.4.4)  , it fails with the same "Transaction Aborted" error even though I'm also not using the transactions API directly. 

` AbortError: Transaction aborted↵    at IDBTransaction.<anonymous> (https://192.168.1.143/js/dependencies/other/dexie.1.4.2.min.js:1:30954)↵    at IDBTransaction.<anonymous> (https://192.168.1.143/js/dependencies/other/dexie.1.4.2.min.js:1:9394)" `

After the error occurs, I can continue to save substantial amounts of data in the same indexDB collection.  This to me indicates it's not a problem with the amount of hard disk space.  Could it have anything to do with the fact that I'm running the site locally over HTTPS with a self signed certificate?

**Comment by dfahlander** [comment]
@uncletammy No, the fact you are accessing site over local self-signed has nothing to do with the issue.

@uncletammy and @gitawego: Are you indexing the property that contains the base64 data? I'm thinking of whether it could be a limit of indexed string keys so that it fails with large base64-coded images?

**Comment by uncletammy** [comment]
@dfahlander 

I didn't think it was related.  

No, I'm not indexing the property with the base64 data.  Here are my indexes and an example record.

```js

  db.version(1).stores({
    thingie: 'identity,id,status'
  });

```

```js

{
  "identity": 1477436143599,
  "status": "queued",
  "frames": [
    {
      "timestamp": 1477436143517,
      "data": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQ ... O7X1S18l6d9f8uWMFG7WnTR2vbfV9Fr62M43TyKFjUM5J3E8YGeuMHA9MsD3FeXNydflk7JO0VZa6d/N/5aGNatRik5u7W27vpe+l+v3fl//9k=",
      "width": 480,
      "height": 480,
      "meta": {
        "focalLength": 35
      }
    },

    ...

    ],
  "thumbUrl": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQ ... 5J3E8YGeuMHA9MsD3FeXNydflk7JO0VZa6d/N/5aGNatRik5u7W27vpe+l+v3fl//9k=",
  "images": [
    {
      "thingie": 72,
      "width": 480,
      "height": 480,
      "meta": {
        "focalLength": 35,
        "sequenceNumber": 23
      },
      "timestamp": 1477417506736,
      "status": "uploaded",
      "createdAt": "2016-10-25T17:46:51.945Z",
      "updatedAt": "2016-10-25T17:47:02.225Z",
      "id": 525,
      "thumbUrl": "https://s3-us-west-2.amazonaws.com/byah/byah/byah/1477417506988/1477417506736_thumb.jpg",
      "imageUrl": "https://s3-us-west-2.amazonaws.com/byah/byah/byah/1477417506988/1477417506736.jpg"
    },

    ...


  ],
  "imageCount": 25,
  "deleted": false,
  "announced": true,
  "progress": 0,
  "user": 6,
  "devMode": false,
  "deviceMeta": {
    "browser": "chrome",
    "version": 51
  },
  "approved": false,
  "adMeta": {
  	"object": "with",
  	"probably": "30",
  	"keys": "and",
  	"values": "of",
  	"all": "data types",
  	"including": "other",
  	"deep": "objects."
  },
  "_available": true,
  "createdAt": "2016-10-25T22:55:43.632Z",
  "updatedAt": "2016-10-25T22:55:43.632Z",
  "id": 75
}
```

**Comment by uncletammy** [comment]
@dfahlander 

Here is a simplified example of the pattern by which I update the records.  In my actual code I handle errors properly.

```js

var db = new Dexie('thingies');

db.version(1).stores({
  thingie: 'identity,id,status'
});

function doOnlyOneThing(someThingieId){

  var i = $q.defer();
  
  db
  .thingie
  .get(someThingieId)
  .then(function(myThingie){

    _.extend(myThingie,{
      'some': 'new',
      'properties': '!'
    });

    db
    .thingie
    .update({identity: myThingie.identity},myThingie)
    .then(function(){

      _.extend(myThingie,{
        'even': 'more',
        'properties': '!!!!'
      });

      db
      .thingie
      .update({identity: myThingie.identity},myThingie)
      .then(function(){

        db
        .thingie
        .get(someThingieId)
        .then(function(currentThingie){
          i.resolve(currentThingie);
        });

      });

    });

  });

  return i.promise;

}

function doAllTheThings(someThingieId){

  var i = $q.defer();

  db
  .thingie
  .get(someThingieId)
  .then(function(myThingie){

    var doOne = function(){

      doOnlyOneThing(someThingieId)
      .then(function(thingie){
        if (thingie.someProperty === true){
          doOne(someThingieId);
        }
        else {
          i.resolve(thingie);
        }
      })

    };

    doOne();
  });

  return i.promise;

}

doAllTheThings(15)
.catch(logIt)
.then(function(myPerfectThingie){
  console.log('we did it!',myPerfectThingie);
});

```

**Comment by skygragon** [comment]
@gitawego the "lots of" data sounds like a promising RC? My db also has 15k+ records in one table, not sure if this cause this sort of AbortError?

**Comment by dfahlander** [comment]
This issue may be related to #360. That issue also occurred when using Table.update() and Collection.modify(). I recommend to update to Dexie 1.5.1 or Dexie 2.0.0-beta.4, depending on which major you are on. Please reply if this resolves the issue.

**Comment by uncletammy** [comment]
@dfahlander , 

After upgrading to Dexie 1.5.1 located at https://unpkg.com/dexie@1.5.1/dist/dexie.js , the problem still exists.  Any other ideas?  Anything I can do to help troubleshoot?

**Comment by uncletammy** [comment]
@dfahlander , @skygragon @gitawego 

After further debugging, I finally got it to work as expected.  It didn't work immediately after upgrading to 1.5.1 .  What did seem to fix it though was bypassing a custom method which modified the record using `angular.extend` just before adding the record to my Dexie collection.  Someone more familiar with Angular might be able to shed more light on why.  Are any of you guys using Angular ?

@dfahlander, thanks for your hard work on this library.  Also thanks for being present to help with issues.  I know it's incredibly tough to do both of those things at the same time.

**Comment by dfahlander** [comment]
Thanks for your feedback! I looked up the [source for angular.extend](https://github.com/angular/angular.js/blob/master/src/Angular.js#L365) but it seems to be pretty harmless what I could see. I'm glad you solved the issue though.

**Comment by skygragon** [comment]
Here is what I tested recently:

* Dexie.js 1.5.1
* Android 4.4.4 (indexedDB supported)
* inject several records like: "++id, &name, *tags, data"
* update random 1 record on column "tags".

1. with 16k records, 100% hit abortError on updating.
2. with 8k records, never hit error.
3. with 12k records, randomly hit error.
4. with 16k records (strip data column), never hit error.

Seems there is some soft limit on the mobile indexedDB usage, but I'm not sure what's the accurate number is, neither how to check the runtime usage on the phone... :(

**Comment by dfahlander** [comment]
@skygragon  Would be interesting to find out why Dexie doesn't fail with QuotaExceededError rather than AbortError. Either if you could debug what happens within Dexie before or fails, or if you could share this repro for someone else to debug. I'm hoping to find a way to detect Quota errors and produce a better error.

**Comment by CraigCav** [comment]
@dfahlander I'm not sure if this helps, but it appears that IndexedDB does not trigger `onerror` when `QuotaExceededError` occurs. Instead, `onabort` is called on the `IDBTransaction` and the `QuotaExceededError`  is then accessible from `idbtrans.error`.

I think the best thing to do in this case would be something like:
```js
idbtrans.onabort = wrap(ev => {
    preventDefault(ev);

    // if abort was caused by exceeding disk quota, bubble the underlying QuotaExceededError
    var error = idbtrans.error.name === 'QuotaExceededError' ? idbtrans.error : new exceptions.Abort();

    this.active && this._reject(error);
    this.active = false;
    this.on("abort").fire(ev);
});
```

**Comment by CraigCav** [comment]
Or (if I'm following the format for Dexie errors correctly), the `QuotaExceededError` could be bubbled up with:

```js
idbtrans.onabort = wrap(ev => {
    preventDefault(ev);
    // pass through the underlying idbtrans.error so we can tell if the disk quota was exceeded
    this.active && this._reject(new exceptions.Abort(idbtrans.error));
    this.active = false;
    this.on("abort").fire(ev);
});
````

**Comment by kiranNegiloni** [comment]
Currently I am facing an issue with Dexie version 1.4.1.  I am using the minified version of the library.

**Below is the exception details.**
Unhandled rejection: AbortError: The transaction was aborted, so the request cannot be fulfilled.

Android OS : KitKat 4.4.2. I have noticed whenever internal storage is less than 1GB transaction gets aborted. Any help is much appreciated as we are facing issues in production environment. Thanks in advance.

**Comment by dfahlander** [comment]
Fixed to this issue has been done in the master branch. Try upgrade to dexie@2.0.0.rc.1 and chances are you'd get more informative error message on Quota exceeded

**Comment by kiranNegiloni** [comment]
@dfahlander  Thanks alot for the quick response. I have upgraded to dexie@2.0.0.rc.1 and tested, Now I am getting Quota exceeded exception. But I have 700 - 800 MB space in internal storage. Please let me know if we can do something for Quota exceeded exception.

**Comment by dfahlander** [comment]
@kiranNegiloni Nice to hear that you got a better error message. There might be restrictions on indexedDB quota not related to the actual hard disk space. Try using [navigator.storage.persist()](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist) which should give your more quota if user agrees.
