### ISSUE TITLE
Where(...).equals(...).toArray() returns NaN instead of null

### ISSUE THREAD

**Issue by ykadosh** [dfahlander/Dexie.js#324]
I have a `null` value stored in the database. When retrieved, a value of `NaN` is received instead of `null`. For example, if the following is stored in the database:
```javascript
{value:null}
```
And a query is made:
```javascript
db.where(...).equals(...).toArray().then(function(rows){
    console.log(rows[0]);
});
```
Then the console will show
```javascript
{value:NaN}
```
Instead of `null` as it should.
Note that I have verified using Chrome DevTools that in fact `null` is stored in IndexedDB and not `NaN`.

**Comment by dfahlander** [comment]
Can you provide the code that reproduces this (concrete code)?

**Comment by ykadosh** [comment]
Upon further investigating I discovered that the issue was related to Chrome DevTools, not to Dexie. When a value of `NaN` is stored in IndexedDB, Chrome DevTools show a value of `null` instead. You can see it in [this fiddle](https://jsfiddle.net/f3b3mz6g/1/).

Thank you for your help, sorry for the confusion.
