### ISSUE TITLE
AbortError with bulkAdd since updating from 1.3.6 to 1.4.2

### ISSUE THREAD

**Issue by julienfouilhe** [dfahlander/Dexie.js#328]
Hi, since i updated to 1.4.2, I get this AbortError quite a lot as you can see:

<img width="385" alt="screen shot 2016-10-11 at 12 41 19 am" src="https://cloud.githubusercontent.com/assets/867741/19253466/84e055aa-8f4b-11e6-8361-232667a3ca6a.png">

It only happens on Chrome and Chrome mobile.
I talked to some users that had the problem and even if they deleted the database they were still getting the error.

The code generating the error is very simple and was working before:

   ```
 this.actions.bulkAdd(actions).then(later(function() {
      return callback && callback(null, actions);
    }))
    .catch('ConstraintError', function() {
      db.editActionForScore(actions, callback);
    })
    .catch('InvalidStateError', function() {
      return callback && callback(null, actions);
    })
    .catch(function(err) {
      this.exception('bulkAddActionForScore', err);
      return callback && callback(err, actions);
    }.bind(this));
```

`later` is just a little function that executes moments after.

Do you think some bug could have been introduced?

**Comment by dfahlander** [comment]
Is this code executed within a transaction or transaction-less?

**Comment by julienfouilhe** [comment]
@dfahlander No, I don't use any transaction. And I have a queue of events which waits for the previous action to be finished, so there's only one dexie call executed at once.

Should I use a transaction?

**Comment by dfahlander** [comment]
No you wouldn't need to, I'm just trying to nail the issue down. Could you show the referred code and I'll try to reproduce it in a unit test. Specifically I would like to see the following:

* Your entire method declaration
* The 'later' function

**Comment by dfahlander** [comment]
Also if you could try setting `Dexie.debug = 'dexie'` and post the call stack of the AbortError.

**Comment by dfahlander** [comment]
Also the souce for And db.editActionForScore()

**Comment by julienfouilhe** [comment]
Thanks a lot for your help, really!

Here is the full method declaration. I bind it to the Dexie instance (db._indexedDB).

```
  db.bulkAddActionsForScore = function(actions, callback) {
    if (!this.setup) {
      return callback && callback(new Error('No database connection opened'), null);
    }
    if (!this.isOpen()) {
      this.logger('addActionForScore: Open back indexeddb connection');
      this.open();
    }
    this.actions.bulkAdd(actions).then(later(function() {
      return callback && callback(null, actions);
    }))
    .catch('ConstraintError', function() {
      db.editActionForScore(actions, callback);
    })
    .catch('InvalidStateError', function() {
      return callback && callback(null, actions);
    })
    .catch(function(err) {
      this.exception('bulkAddActionForScore', err);
      return callback && callback(err, actions);
    }.bind(this));
  }.bind(db._indexedDB);
```

And here is the later function (I use it so the errors I throw in `.then` aren't caught by Dexie's promise):

```
  var later = function(cb) {
    return (function() {
      var a = arguments;

      setTimeout(function() {
        cb.apply(this, a);
      }.bind(this));
    }.bind(this));
  }.bind(this);
```

I'll set the Dexie.debug flag for the next update! :)

**Comment by dfahlander** [comment]
I couldn't reproduce it. There are some issues related to AbortError. Could yours be one of them? :

* Out of disk space on mobile device may cause AbortError
* Transaction timeout (in case a print dialog is open during the operation) may cause AbortError in Chromium only.

**Comment by julienfouilhe** [comment]
@dfahlander Yes, I wasn't able to reproduce it either, hence why I came here :)

I asked a user about his disk space yesterday and he told me that even though there was free space, he had had some issues with it so it may be related. I'll add a warning for users who get this error and ask them if their disk is full.

I'll get back to you with a full stack trace though!

Thanks!

**Comment by julienfouilhe** [comment]
I asked a few more users about this and they said that freeing space resolved this!

So you can close this issue, it would be good to have a clearer error though, like `QuotaExceededError` which was the one I was getting before.

Thanks!
Julien
