### ISSUE TITLE
Issues when used in Ionic v2 (potentially Cordova as well?)

### ISSUE THREAD

**Issue by wwoods** [dfahlander/Dexie.js#333]
I npm install'd dexie and imported it into my Ionic v2 project.  Some weird issues arose when I tried to serve up my application, mostly from `src/utils.js`.  It turns out that `keys`, `_hasOwn`, `_global$7`, and maybe others end up getting set after the functions that use them are called.  E.g., the bundled javascript generated at `www/build/main.js` compiles it in this order:

```
prop(...);

...

const keys = Object.keys;
function prop() { /* uses keys() somewhere */ }
```

Since javascript is read top-down, keys is undefined when `prop()` gets called for the first time.

This seems to be the result of the bundler getting the wrong file order... Not sure which component is responsible (Ionic / Cordova or Dexie), but as it is a usability issue for Dexie with Ionic, I wanted to mention it here.

**Comment by dfahlander** [comment]
I think it's related to [this](https://github.com/dfahlander/Dexie.js/issues/310) and [this](https://github.com/rollup/rollup/issues/995) issue.

Try:

```
npm install dexie@next-1
```

if it resolves the issue. I've removed the cyclic dependencies there.

**Comment by wwoods** [comment]
That indeed resolved the issue.  Thanks!

**Comment by dfahlander** [comment]
Closing.
