### ISSUE TITLE
How can get last id from table.

### ISSUE THREAD

**Issue by Malarkey86** [dfahlander/Dexie.js#344]
I can get all items but i have to do a loop to get the last one item.
How can do it by query?

I have one table and three fields: {id, name, phone,} But I need to get phone from biggest id.

**Comment by dfahlander** [comment]
There are a bunch of samples [here](https://github.com/dfahlander/Dexie.js/wiki/API-Reference#quick-reference). And you'll find the api reference [here](https://github.com/dfahlander/Dexie.js/wiki/API-Reference) 

To retrieve the oldest friend:

```js
db.friends.orderBy('age').last()
```
