### ISSUE TITLE
incorrect typescript signature for table.hook method

### ISSUE THREAD

**Issue by ERobishaw** [dfahlander/Dexie.js#347]
**CURRENTLY**

```
 hook: {
            (eventName: string, subscriber: () => any): void;
            creating: DexieEvent;
            reading: DexieEvent;
            updating: DexieEvent;
            deleting: DexieEvent;
        }
```

**FIX:**
Add "any?" member to subscriber definition

**WRONG**
`(eventName: string, subscriber: () => any): void;`

**CORRECT**
`(eventName: string, subscriber: (any?) => any): void;`

**Comment by dfahlander** [comment]
Ok, thanks!

**Comment by dfahlander** [comment]
@ERobishaw Please verify the latest npm release fixes the issue for you.
