### ISSUE TITLE
Better API alternative for "db.open"?

### ISSUE THREAD

**Issue by jampekka** [dfahlander/Dexie.js#35]
I'm evaluating Dexie.js for my client side DB needs and it seems very nice, but as a lazy reader I missed that I needed to open the database before anything happens. If I don't open it, no error is given anywhere but promises just don't trigger, which I wondered for a while.

I see that the rationale for the open to work the way it does is the queuing, which indeed is a nice feature to have (although I've still not fully grasped what's their role in comparison to transactions). However, having such a strong "internal state" that is easy to overlook is often a bit smelly. I think eg. the stores-method could return a new object to avoid the "stateness".

**Comment by dfahlander** [comment]
Closing this issue now since it has been opened for a while with no more comments.
