### ISSUE TITLE
Dexie.d.ts needs ReadonlyArray as an option of IndexableType

### ISSUE THREAD

**Issue by wwoods** [dfahlander/Dexie.js#356]
As title.  Basically, if you have a `ReadonlyArray`, it currently won't work with e.g. `anyOf()` because that function only takes an `Array`, not a `ReadonlyArray`.  Naturally though, `anyOf()` doesn't require a mutable array.

**Comment by wwoods** [comment]
Also: get() should specify whether it returns `null` or `undefined` when the object does not exist, in conformance with `--strictNullChecks` in Typescript 2.

**Comment by dfahlander** [comment]
Thanks!! If I forget to follow up on this, please send a pull request with the fix (should commit the change to src/Dexie.d.ts) or remind me ;)

**Comment by wwoods** [comment]
Minor update - `IndexableType` needs to cover all bases with respect to Dexie.maxKey (needs to include `string[]` looks like):

    Argument of type '(string[] | Done)[]' is not assignable to parameter of type 'IndexableType'. Type
            '(string[] | Done)[]' is not assignable to type '(string | number | Date)[]'. Type 'string[] | Done' is not
            assignable to type 'string | number | Date'. Type 'string[]' is not assignable to type 'string | number |
            Date'. Type 'string[]' is not assignable to type 'Date'. Property 'toDateString' is missing in type
            'string[]'.

**Comment by wwoods** [comment]
declare type IndexableTypeParts = string | number | Date | null | Array<Array<void>>;
    declare type IndexableType = IndexableTypeParts | Array<IndexableTypeParts>;

    static maxKey: Array<Array<void>> | string;

It's on my list to make a pull request with this stuff.  Should also add `static minKey: number`... and set it to `Number.NEGATIVE_INFINITY`: https://www.w3.org/TR/IndexedDB/#dfn-key.

**Comment by dfahlander** [comment]
Thanks for clarifying these things out, and also for planning to create a PR. Much appreciated :+1:

**Comment by wwoods** [comment]
Awesome, thanks for the merge :)
