### ISSUE TITLE
How to query a range from a collection?

### ISSUE THREAD

**Issue by bennyn** [dfahlander/Dexie.js#366]
In [our application](https://github.com/wireapp/wire-webapp) we want to query the first 30 items (sorted by date). In order to achieve this, we do the following:

```coffeescript
load_events_from_db: (conversation_id, start, end, limit = 30) ->
  @db['conversation_events']
  .where 'conversation'
  .equals conversation_id
  .reverse()
  .sortBy 'time'
  .then (records) ->
    return records.filter (record) ->
      timestamp = new Date(record.time).getTime()
      return false if start and timestamp >= start
      return false if end and timestamp <= end
      return true
  .then (records) ->
    return records.slice 0, limit
```

As you can see we are querying all items to sort them then in a reverse order by `time`. Is this the recommended way of doing it or is there another best practice?

P.S. I am sorry for the CoffeeScript but I hope it's still understandable.

**Comment by dfahlander** [comment]
The most optimal way to do this kind of query, is to use a compound index of [conversation+time].

Your query would be:
```js
db.conversation_events
  .where('[conversation+time]')
  .between([conversation_id, -Infinity], [conversation_id, Dexie.maxKey])
  .reverse()
  .limit(limit)
  .toArray();

```

You might need a fallback for IE, Edge and old Safari versions. IndexedDBShim claims to polyfill compound index also for IE/Edge. IE won't complain over declaring the compound index, so if you don't want to use the shim, you could just fallback to your current query if the optimized query fails.

**Comment by bennyn** [comment]
Thanks for your great response, @dfahlander.

I tried this query but all I am getting is:
> TypeError: Invalid key provided. Keys must be of type string, number, Date or Array<string | number | Date>.

It complains about this part: `where('[conversation+time]').between([conversation_id, start], [conversation_id, end])`. 

I will check what's wrong with it.

**Comment by bennyn** [comment]
@dfahlander Thanks for your great answer!

Will your solution also work in Microsoft Edge? Because it requires a [compound index](https://github.com/dfahlander/Dexie.js/wiki/Compound-Index) and I read that Microsoft Edge's IndexedDB implementation [doesn't support compound indices](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/indexeddbarraysandmultientrysupport/).

I am also a bit confused that you can pass arrays to `between`. Will the two arrays in your example be treated as `lowerBound` and `upperBound` (as described [here](https://github.com/dfahlander/Dexie.js/wiki/WhereClause.between()))?

If I am right with my `lowerBound` and `upperBound` assumption, can I then include both limits by declaring `.between [conversation_id, start], [conversation_id, end], true, true`?

**Comment by dfahlander** [comment]
It won't work on ie or edge unless you polyfill it with indexeddbshim or idb-iegap. So I wrote earlier in this thread. IE won't complain over declaring the compound index, so if you don't want to use a shim, you could just fallback to your previous version of the query if the optimized query fails.

**Comment by dfahlander** [comment]
Yes, you are passing a lower- and upper bound array-key to Collection.between() which means you can pass true, true in the end to include both lower and upper boundaries in the query.
