### ISSUE TITLE
Multi-index within Compound?

### ISSUE THREAD

**Issue by wwoods** [dfahlander/Dexie.js#368]
I've got a db and would like to do this:

```ts
db = new Dexie();
db.version(1).stores({
  obj: '++id, [*tags, received]'
});

//Example 'obj': { id: 1, tags: [ 'a', 'b', 'c' ], received: Date.now() }
```

The purpose of an index like this would to be to quickly get a sorted list for each tag.  Currently, specifying and index this way will cause Dexie to throw an error.  Is there another way to specify this in Dexie currently?  If not, might be worth adding.

As a workaround for now, I am storing the 'tags' column with the 'received' date included in each entry.

**Comment by dfahlander** [comment]
It's not possible in IndexedDB to combine multiEntry with compound. There have been others asking for this to the W3C group.

I think your workaround solution is the best one for this purpose.

**Comment by wwoods** [comment]
Ok, kind of figured but thought I'd log an issue just in case.  Thanks!

**Comment by sumit6b** [comment]
If possible could you please explain what is the workaround solution here. I have exactly the same scenario.
Should I make a s separate tag level table? with [tag + received] as index? Which would mean I can't use multiEntry Index?

**Comment by dfahlander** [comment]
Use multiEntry index on a property containing an array of strings where each entry is an array of 2 entries: tag and received.

**Comment by sumit6b** [comment]
Thanks @dfahlander for the reply. I have implemented the first solution which you have suggested.
So my index is ` *folder `
```
[
  [folderId1, timestamp, filter],
  [folderId2, timestamp, filter2]
]
```
this value is going to get persisted in two rows in the index which would be

```
[folderId1, timestamp, filter],
[folderId2, timestamp, filter2]
```
which is correct. But I am facing problem while making the query

so let's say we have three rows:
```
[18, 1583932800000, 0]
[18, 1583936400000, 0]
[18, 1583939572000, 0]
```

My query is

`await table.where("folder").between([18, 1583932800000, 1], [18,  1583939572000, 1], true, true).toArray();`

which is returning all 3 rows instead of an empty response.

I can't move this timestamp to last because then it will destroy the ordering.

**Comment by dfahlander** [comment]
How do your objects look like? `{folder: [[folder1, timestamp, filter], [folder2, timestamp, filter]]}` ?

**Comment by sumit6b** [comment]
Objects are Thread and Folders.
Threads have an "unread" field
A thread could belong to multiple folders. (eg 18, 19)
Intent of the query is to fetch all unread threads which belong to some folder ( say 18) and the result should be sorted by timestamp.

So thread table will look like:
```
db.version(x).stores({
    thread: 'threadId,  *folders, unread'
});
```
If an unread thread belongs to two folders, i'll be saving the thread as
```
{
  threadId: 123
  folders: [18, timestamp1, 1], [19, timestamp2, 1],  // 1 means unread === true
  unread: true
}
```

I have to fetch unread threads which have belongs to 18 folder, sorted by timestamp1.

**Comment by dfahlander** [comment]
Ok. Switch the order of read and timestamp and you will be able to find all unread thread for a certain folder and get it sorted by timestamp. An array key is not magic - it's compared by comparing the included parts in order.
