### ISSUE TITLE
anyOfIgnoreCase issue

### ISSUE THREAD

**Issue by swampthang** [dfahlander/Dexie.js#369]
What an awesome thing you've assembled here! Thanks so much for making this available. So far it's been the best solution for me. I don't know if this is just misuse of the function or a bug. I'm betting on the former. This is an Electron app.

This function opens the database and searches by keyword. The keywords are stored in a space-separated string in the field, `keywords` and I'm using an array for the argument (the str arg is split at spaces and stored as searchArr). The table name is `available` in a db named `assetdb`:
```
function doArtSearch(str) {

  var searchArr = str.split(' ');
  var db = new Dexie("assetdb");
  var files = [];
  db.version(1).stores({ available: "++id,parent_folder,category_folder,filepath,filename,keywords,select_menu,category_name" });
  db.open()
  .then(function(){
      console.log(searchArr);
      var collection = db.available.where('keywords').anyOfIgnoreCase(searchArr);
      collection.each(function(svg) {
        console.log('Found: ' + svg.filename + ' in category ' + svg.category_name);
        addFiles(svg.filepath);
      })
      .then(function(svgs){
        addToFileBrowser();
      });
  })
  .catch( function (err) {
    console.log(error (err.stack || err));
  });

  function addFiles(file) {
    files.push(file);
  }

  function addToFileBrowser() {
    populateFileBrowser(null,files,true);
    resetFileBrowser($('#file-browser-container'));
  }
}
```
Here's a screenshot of inspector showing the `keywords` key field in the `available` table.
<img width="593" alt="screen shot 2016-11-12 at 7 02 14 pm" src="https://cloud.githubusercontent.com/assets/428757/20243084/7b477dd0-a90d-11e6-8d31-230d1e6696ad.png">
I passed the word "Addict" into the searchArr and I'm not getting any errors but nothing is returning to the collection even though I see that keyword in one of the db entries (in the screenshot above). Here are 2 screenshots from a debug session in Dexie.js -  one in the file and one returning to my function. After it gets to the collection.each loop it's obviously empty because it hops right over it and never hits the breakpoint.

 Hoping you can recognize anything that might point me in the right direction. Thanks again for the awesome code!

<img width="740" alt="screen shot 2016-11-12 at 7 11 46 pm" src="https://cloud.githubusercontent.com/assets/428757/20243107/2b470138-a90e-11e6-8183-b1ccd9fc3e0a.png">

<img width="937" alt="screen shot 2016-11-12 at 7 12 49 pm" src="https://cloud.githubusercontent.com/assets/428757/20243113/77c94e76-a90e-11e6-96d8-ade1ec63b8df.png">

**Comment by dfahlander** [comment]
Your stored keywords are space delimited sentences. If you search for a word,  such as 'Addict', it would only match the exact word 'addict',  not a sentence containing it. 

You should index keyword as multiEntry (prefix it with a star) and store an array of keywords instead of a space delimited string. Then your current query would hit a match.

**Comment by swampthang** [comment]
Thanks for the quick reply. I changed the `keyword` indexing to...
```
db.version(1).stores({ available: "++id,parent_folder,category_folder,filepath,filename,*keywords,select_menu,category_name" });
```
Here's what the db now looks like (I first removed the db and started over by running `indexedDB.deleteDatabase("assetdb")` in the console to removed the db and then rebuilt.)
<img width="678" alt="screen shot 2016-11-13 at 7 19 52 am" src="https://cloud.githubusercontent.com/assets/428757/20245957/115a00ea-a972-11e6-8c63-4f20bfc54fdf.png">
The search terms are still being passed in as an array. I'm still not getting a hit. Should I loop through the array and pass them in one at a time?

**Comment by dfahlander** [comment]
No, it's correct to pass an array to anyOfIgnoreCase(). Not sure why you don't get a hit as it seems you've querying it correctly.

If you don't come further, I could try looking at it if you could post a self-contained reproducable code that I could just open in a web browser and verify expected results agains actual results.

**Comment by swampthang** [comment]
I can try but not sure I can fully emulate what's happening in the app. I _am_ running this function when the app loads so the function above only runs when a search is conducted. Could this be the problem? I don't fully understand what happens when you create an instance of Dexie in a function and then create another instance of the same db later in another function.

```
function initAllAssetLibriaries() {

  var db = new Dexie("assetdb");
  db.version(1).stores({ available: "++id,parent_folder,category_folder,filepath,filename,keywords,select_menu,category_name" });
  db.open().catch( function (err) {
    console.log(error (err.stack || err));
  });

  db.transaction('rw', db.available, function*() {
    var populate = false;
    if ((yield db.available.count()) === 0) {
      populate = true;
    }
    // obj is like -> {path: userLibrary, sel: 'general'}
    for ( let obj of appDataAssetsDirs ) {

      var mainDir = obj.path;
      var dirs = getDirectories(mainDir);
      var rows = processDirectoryFiles(mainDir,dirs,obj);

      if( rows !== null ) {
        if ( populate ) {
          for ( let row of rows ) {
            db.available.add(row);
          }
        }
        setSVGSelectMenu(obj.sel);
      }
    }
  }).catch ( function (e) {
    console.error(e.stack);
  });
}
```

**Comment by swampthang** [comment]
Just to see if that was it, I declared the db at the top of the file like...
```
var assetDb = new Dexie("assetdb");
assetDb.version(1).stores({ available: "++id,parent_folder,category_folder,filepath,filename,keywords,select_menu,category_name" });

```
Then changed the init function to:
```
function initAllAssetLibriaries() {

  assetDb.open().catch( function (err) {
    console.log(error (err.stack || err));
  });

  assetDb.transaction('rw', assetDb.available, function*() {
    var populate = false;
    if ((yield assetDb.available.count()) === 0) {
      populate = true;
    }
    // obj is like -> {path: userLibrary, sel: 'general'}
    for ( let obj of appDataAssetsDirs ) {

      var mainDir = obj.path;
      var dirs = getDirectories(mainDir);
      var rows = processDirectoryFiles(mainDir,dirs,obj);

      if( rows !== null ) {
        if ( populate ) {
          for ( let row of rows ) {
            assetDb.available.add(row);
          }
        }
        setSVGSelectMenu(obj.sel);
      }
    }
  }).catch ( function (e) {
    console.error(e.stack);
  });
}
```
... and changed the search function to:
```
function doArtSearch(str) {

  var searchArr = str.split(' ');
  var files = [];

  assetDb.transaction('r', assetDb.available, function () {

    var collection = assetDb.available.where('keywords').anyOfIgnoreCase(searchArr);
    collection.each(function(svg) {
        console.log('Found: ' + svg.filename + ' in category ' + svg.category_name);
        addFiles(svg.filepath);
      })
      .then(function(svgs){
        addToFileBrowser();
      });

  }).catch(function (err) {
    console.log(error (err.stack || err));
  })

  function addFiles(file) {
    files.push(file);
  }

  function addToFileBrowser() {
    populateFileBrowser(null,files,true);
    resetFileBrowser($('#file-browser-container'));
  }
}
```
As you can see, once I open the db connection it stays open. Still getting the same null results. I'm gonna create a JSON copy of the first 100 rows of the table and add it here. If you're curious, I could give you access to the repo and push up a branch you could test locally. The README of the repo contains step-by-step details on how to install.

**Comment by swampthang** [comment]
Ok, I'm an idiot. I failed to add the multiEntry prefix in ```initAllAssetLibriaries()```
Had only added it to the search function. D'oh! Thanks. You can consider this closed.

**Comment by dfahlander** [comment]
Great to hear! Hope it works satisfactory now. Let me know if it does.

I sometimes cannot hold myself from giving some advices regarding how to consume the Dexie API more simplistic and also robust. Especially the first bullet below. It took myself long time before a started understanding how to consume promises this way and now I now it's become the principle everywhere in my code.

1. Let your promise-facing functions always return a promise. so that you can call your func().then() and .catch(). You can do this simply by beginning each function with a return statement of the first promise-based call and chain the flow in then() and at last return the final result.
2. By doing the above thing, you wont need to catch every possible promise but can have a top-level catch-all catcher for any error that could occur.
3. Don't open the database each time you need to query it. Queries will be faster if you have a singleton Dexie instance in your application that lives through your application.

```js
// Let the assetDB be declared in its own module (or file if not using modules)

function doArtSearch(str) {
  // Always start by returning the result from a promise-returning function:
  return db.transaction('r', assetDB.available, function () {
    var searchArr = str.split(' ');
    // Returned promise will make transaction resolve with it:
    return assetDb.available
      .where('keywords')
      .anyOfIgnoreCase(searchArr)
      .toArray();
  }).then(function(svgs){
    // By returning a result here, your entire function's final promise will resolve with
    // this value.
    return svgs.map(function(svg) { return svg.filepath; });
  });
}

// Catch the entire chain instead from the event where someone clicked the search button
$('#someSearchButton').click(function() {
  doArtSearch($('#someInputText').val()).then(function (files) {
    addToFileBrowser(files);
  }).catch(function (err) {
    // One place to catch any error in the chain (instead of catching within your search function)
    console.error(error (err.stack || err));
  });
});

function addToFileBrowser(files) {
  populateFileBrowser(null,files,true);
  resetFileBrowser($('#file-browser-container'));
}

```

Actually, the transaction block is not needed here because we're just doing a single operation in it, so the code could equally well be written like this:

```js
function doArtSearch(str) {
  return assetDb.available
    .where('keywords')
    .anyOfIgnoreCase(str.split(' '))
    .toArray();
  }).then(function(svgs){
    // By returning a result here, your entire function's final promise will resolve with
    // this value.
    return svgs.map(function(svg) { return svg.filepath; });
  });
}
```
