### ISSUE TITLE
Update version in IndexedDB with Dexie js

### ISSUE THREAD

**Issue by fulltic** [dfahlander/Dexie.js#370]
Hello!!
I have a problem :-( . I think it's not very complicated

I have one database with these tables:

db.version(**1**)
        .stores({
            customers: "++id,name,surname,doc,phone,email,[surname+doc]",
            products: "++id,cod,description,purchase_price,sale_price",
            invoices: "++id,number,id_client,date,center,type",
            lines_invoices:"++id,id_invoice,id_product,quantity,unit_price,discount,iva,concept"
        });

I want to add two more fields

db.version(**2**)
        .stores({
            customers: "++id,name,surname,doc,phone,email,[surname+doc]",
            products: "++id,cod,description,purchase_price,sale_price",
            invoices: "++id,number,id_client,date,center,type,**total**",
            lines_invoices:"++id,id_invoice,id_product,quantity,unit_price,discount,iva,concept,**total**"
        });

As I could enlarge my fields without losing the data, with the version gives me error.

Thank you very much in advance

**Comment by dfahlander** [comment]
You need to specify both version 1 and version 2 so that Dexie can compute the diff and add the new indexes. 

That said, a future version of Dexie will be able to diff against the installed version instead.  But for now, that is what you need to do.
