### ISSUE TITLE
Calling WebCrypto API from within an upgrade transaction

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#374]
Continuing the question from @sechel on #317 into this own issue.

### Background

WebCrypto is a promise based API that does not play well with IndexedDB transactions on any browser due to the characteristics of IndexedDB transactions where all async API's will make a transaction fire off except if the API called was against the transaction itself. The reason WebCrypto is asynchronic, is that it enables the API to do heavy computations within a worker thread instead of the GUI thread.

This leaves 2 options for encrypting data with IndexedDB:

1. Use another JS based synchronous crypto library instead of WebCrypto. Not all encryption algorithms are CPU intensive and many of them wouldn't need to be executed by worker threads-could be to be async anyway except for some performance gain on some heavy cryptographic computations. If using symmetric key encryption, it's pretty fast anyway and can be done in the same thread.
2. Use WebCrypto, but prepare the encryption before starting an indexedDB transaction.

### Upgrading Solution

@sechel needs to encrypt data when upgrading from version A to version B. He wants to use WebCrypto for encrypting the data, but it is impossible to invoke withing an upgrade transaction so he needs another solution.

A working solution would need to combine an upgrader function with the [db.on('ready')](https://github.com/dfahlander/Dexie.js/wiki/Dexie.on.ready) event. The upgrader can flag entities for being in need of encryption, while db.on('ready') listener can call WebCrypto and perform the actual encryption.

[db.on('ready')](https://github.com/dfahlander/Dexie.js/wiki/Dexie.on.ready) will be called whenever the indexedDB.open()'s onsuccess event has been triggered, but before Dexie's db.open() promise resolves. From there, it is possible to do additional asynchronic preparation of the database before the it will be considered open.

By returning a promise from your event listener of db.on('ready'), the db will be blocked )for all but yourself) until your promise resolves so that your app code don't need to think waiting for your upgrader to complete.

Here's my suggestion:
```js

db.version(A).stores({myTable: 'id, indexes...'});
db.version(B).stores({myTable: 'id, indexes..., isEncrypted'}).upgrade(()=>{
    // Mark all entities to be unencrypted:
    return db.myTable.toCollection().modify({isEncrypted: 0});
});

db.on('ready', encryptIfNeeded);

const LIMIT = 1000; // Have some kind of limit to spare memory and be able to show progress...

function encryptIfNeeded () {
    return db.myTable.where('isEncrypted').equals(0).limit(LIMIT).toArray(entities => {
        console.log(`Found ${entities.length} entities in need of encryption`);
        return Promise.all(entities.map(entity => window.crypto.subtle.encrypt({
            name: "AES-CBC",
            iv: window.crypto.getRandomValues(new Uint8Array(16))
        }, key, entity.secretField).then (encrypted => {
                entity.secretField = encrypted;
                entity.isEncrypted = 1;
                return entity;
            })));
    }).then(encryptedEntities => {
        return db.myTable.bulkPut(encryptedEntities).then(()=>{
            if (encryptedEntities.length === LIMIT) {
                console.log("Need to find more entities in need of encryption...");
                return encryptIfNeeded();
            }
            console.log("Done encrypting all data.");
        });
    });
}

```

Note that this solution will require Dexie 2.0 because it needs to keep zones alive between native promise calls.

**Comment by sechel** [comment]
Great, thank you very much. I will have to meditate a little on this solution in order to understand the implications that it imposes on my migration strategy 😄. In particular: What happens if I keep adding database versions and migration steps? This code needs to stick around in the `on('ready')` forever, right? I may prefer a version number specific implementation. What if there were multiple migration steps involved, this very one somewhere in the middle? Intuitively I would say that it is be better to prepare the data that is needed for the migration depending on the current db version. And then using it in the upgrade transaction. Would it be possible to add handlers like `on('abouttoupgrade')`or `on('upgradefinished')` to do such kinds of work?

**Comment by wwoods** [comment]
Just my two cents - I got around this problem (was using File I/O) with code like the following:

```ts
db.version(B).stores(...).upgrade(async () => {
  let bufferToEncrypt = [];
  let bufferToStore = [];
  let encryptDone = false;
  let readerDone = false;
  //Spawn a thread to read from the db - every tick must have db activity
  let reader = (async () => {
    await db.myTable.each((obj) => {
      bufferToEncrypt.push(obj);
    });
    readerDone = true;
  })();
  //Spawn a thread outside of the transaction that will do any non-indexedDB processing
  let encrypter = (async () => {
    while (bufferToEncrypt.length > 0 || !readerDone) {
      if (bufferToEncrypt.length === 0) {
        await sleep(10); //Wait on setTimeout(), basically.
        continue;
      }
      //Swap buffers so reader can keep reading
      let toEncrypt = bufferToEncrypt;
      bufferToEncrypt = [];

      for (let b of toEncrypt) {
        await encrypt(b);
        bufferToStore.push(b);
      }
    }
    encryptDone = true;
  })();
  //And spawn a writer to put the encrypted results back (every tick must have indexedDB activity)
  let writer = (async () => {
    while (bufferToStore.length > 0 || !encryptDone) {
      if (bufferToStore.length === 0) {
        //indexedDB operation to wait on - here's the downside of this approach:
        //Busy waiting.  Since every tick needs indexedDB activity, we have to use
        //an indexedDB operation, which might slow down the CPU.  But, everything
        //happens in one transaction.
        await db.myTable.count();
        continue;
      }
      let buffer = bufferToStore;
      bufferToStore = [];
      await db.myTable.bulkPut(buffer);
    }
  })();
  //The writer is the final piece of the pipeline to finish.  Wait on it, then our
  //transaction is done.
  await writer;
});
```

If you wanted to enact a `LIMIT` like in @dfahlander 's code, you'd just need to modify the reader appropriately (rather than an foreach loop), and use another `await db.myTable.count()` busy loop to wait for more items to finish being encrypted and written.

**Comment by sechel** [comment]
I came up with a little improvement over the solution that @dfahlander presented above. Mainly I store so called `postUpgradeJobs` during the upgrade transaction. Then in the `on('ready')` handler I `await` those jobs in order to block the open Promise as long as it takes for all `postMigrationJobs` to complete.

```typescript
class MyDexie extends Dexie {

  public myTable: Dexie.Table<MyClass, number>;
  private postMigrationJobs: (() => Promise<void>)[] = [];

  constructor(name: string) {
    super(name);
    this.version(A).stores({myTable: 'id, indexes...'});
    this.version(B).stores({myTable: 'id, indexes...'}).upgrade(() => {
      this.postMigrationJobs.push(async () => { 
        // WebCrypto calls using the data from version A
      });
    });
    this.on('ready', async () => {
      for (let job of this.postMigrationJobs) { await job(); }
    });
  );

}
```

A drawback I see here is that this does not come with a guarantee that all jobs will be processed in the event of a page reload right in between upgrade and the resolution of `on('ready')`. Furthermore I don't know yet how to handle cases where multiple migrations are performed and a later migration depends on the data processed by on of the `postUpgradeJobs`.

**Comment by dfahlander** [comment]
@sechel Yes your solution is more generic, and I agree that it must be so. I think could safe up for page reload (as you're also concerned about), by persisting the postMigrationJobs instead in its own table.

```ts
class MyDexie extends Dexie {

  public myTable: Dexie.Table<MyClass, number>;
  private _postMigrations: Dexie.Table<{version: number},number>;

  constructor(name: string) {
    super(name);
    this.version(A).stores({myTable: 'id, indexes...'});
    this.version(number between A and B).stores({_postMigrations: 'version'});
    this.version(B).stores({myTable: 'id, indexes...'}).upgrade(() => {
      db._postMigrations.add({version: B});
    });
    this.on('ready', ()=>this._runPostMigrations());
  );

  private async _runPostMigrations() {
    let nextJob = await this._postMigrations.orderBy('version').first();
    if (!nextJob) return;
    if (nextJob) switch (nextJob.version) {
      case B: // await encryption job tied to version B.
    }
    await this._postMigrations.delete(nextJob.version);
    return runPostMigrations();
  }

}
```

The only thing to be aware of is to never remove an index or table that a post migrator will need.

As this is somewhat cumbersome and as I am about to rewrite the upgrade framework, I'm hoping to do something about it with respect to this use case (and @wwoods use case).

**Comment by sechel** [comment]
@dfahlander Nice.
> As this is somewhat cumbersome and as I am about to rewrite the upgrade framework, I'm hoping to do something about it with respect to this use case.  

That would be great.

**Comment by wwoods** [comment]
@sechel If you were planning on encrypting everything at once and then waiting on it, and want everything to be safe in case of page reloads, future upgrades, etc, why not consider the busy wait approach to keep everything in the upgrade transaction?  It's not a typical busy wait like in C - in Chrome anyway, CPU usage is only 70-80% of a single core.  And that's assuming that your event engine isn't pinging back anything other than the count - the more other processing you have going on in your page, the less CPU time the count() is going to claim.

You could further reduce the CPU usage of the count() busy wait by merging the reader and writer threads, and only count()ing when there is neither reading nor writing work to be done.  All told, the overhead should be quite small.

**Comment by dfahlander** [comment]
@wwoods. I'm curious of integrating your busy wait approach into Dexie. In a [new proposal for promise-compliant indexeddb](https://github.com/inexorabletash/indexeddb-promises), a new method Transaction.prototype.waitUntil() will allow non-indexeddb operations to execute without loosing the transaction. We could 'polyfill' this in Dexie in advance and when a browser implements it, we could use that one instead.

I've no idea how much work this would put on the database engine, and whether count() or get() is the best API to use. count() may take longer to execute (which is good), but will also put the database to hard work all the time, while I suppose get() will spend most of the time in communication between browser and database but resolve faster. What you think?

**Comment by sechel** [comment]
@wwoods I will have a try with it. As you pointed out the big pro of your approach is that everything happens in the transaction and only in the transaction.

**Comment by sechel** [comment]
This was fast, thanks!

**Comment by dfahlander** [comment]
Closing issue as it now can be solved using Dexie.waitFor()
