### ISSUE TITLE
Upgrade is never called on first version

### ISSUE THREAD

**Issue by nicolashenry** [dfahlander/Dexie.js#377]
I wanted to initialize some data in upgrade but the upgrade function does not work on the first version.
```typescript
db.version(1).stores({
	test: '++id,name'
})
.upgrade(trans => {
	// does not reach here
	trans.test.add({ test: 'test' });
});
```

**Comment by dfahlander** [comment]
Use db.on.populate

**Comment by nicolashenry** [comment]
This seems nice but my goal is to initialize the data from the first (or from a later) version of the database in order to test the upgrade process from different states. Is there a way to do it with on.populate ? From what I understand this will initialize the database directly to the latest version.

**Comment by dfahlander** [comment]
Version 1 will never need an upgrader because it's the initial version. You can only get upgraders run when you have a database installed that is of a prior version than the declared one.

**Comment by nicolashenry** [comment]
I understand but it means I can't populate a database from a particular version. I suppose I will have to do it manually without dexie.

**Comment by dfahlander** [comment]
You could define the db in two phases. First with initial version and fill it with content. Then close it and drive the new schema and open that one. When second db opens it will have a previous version installed with data in it.
