### ISSUE TITLE
karma-qunit gives extraneous errors in test code

### ISSUE THREAD

**Issue by chrahunt** [dfahlander/Dexie.js#381]
While refactoring some tests I received extraneous errors on failing tests.

![extra error](https://cloud.githubusercontent.com/assets/2312275/20642355/8e17fcb4-b3da-11e6-842d-923a5f203b6e.png)

These come from karma-qunit, which assumes QUnit has a `dump` method. The specific location in karma-qunit is here:

![karma-qunit location](https://cloud.githubusercontent.com/assets/2312275/20642357/a89b20fc-b3da-11e6-9b71-93015ce02329.png)

`runner` is initialized to QUnit which is passed in on karma initialization.

This should be fixed by updating qunit to anything later than [1.15.0](https://github.com/qunitjs/qunit/releases/tag/1.15.0).

**Comment by chrahunt** [comment]
The local version of QUnit in `test/qunit.js` has had the following changes:

1. comment out some function in qunit: [`efd8d1`](https://github.com/dfahlander/Dexie.js/commit/efd8d19d0e750aba0bf2461d68deabf6c6103274#diff-e276582eaf2528d13407883aef7027bf)
2. add some console logging: [`91c4cb`](https://github.com/dfahlander/Dexie.js/commit/91c4cbd4b858d704be36cc0020988c9c713d22ff#diff-e276582eaf2528d13407883aef7027bf)
3. fix previous logging: [`c5f772`](https://github.com/dfahlander/Dexie.js/commit/c5f772fdff2989120f4109a1cc1182af38c2c9fa#diff-e276582eaf2528d13407883aef7027bf)
4. add polyfillIE option to QUnit: [`872ee1`](https://github.com/dfahlander/Dexie.js/commit/872ee1e540b4fa6b2b6ac9f855cbd3d8569bf5e3#diff-e276582eaf2528d13407883aef7027bf)
5. update indexeddb shim capitalization: [`36a466`](https://github.com/dfahlander/Dexie.js/commit/36a466ff74227c72bc2f3eafbfd34b6e12e79da3#diff-e276582eaf2528d13407883aef7027bf)
6. add dontoptimize which is passed through to `test/dexie-unittest-utils.js`: [`cc60e4`](https://github.com/dfahlander/Dexie.js/commit/cc60e4ec44338d425f757cc1a3cf1533faab8922#diff-e276582eaf2528d13407883aef7027bf)
7. add longstacks option for printing long stack traces, added options to `test/dexie-unittest-utils.js`: [`a0cb75`](https://github.com/dfahlander/Dexie.js/commit/a0cb75fc6cd173e656cddb467418339c2dc63495#diff-e276582eaf2528d13407883aef7027bf)

I'm not sure what 1 is about.

2 and 3 can be substituted with a callback set using [`QUnit.log`](https://api.qunitjs.com/QUnit.log/).

For 4 - 7 can this be moved strictly to `dexie-unittest-utils.js` or put back in `run-unit-tests.html` as we are able?

**Comment by dfahlander** [comment]
Thanks for sorting out all these changes! 4-7 are the only things we'd actually need. 4 is questionable as it doesn't work anyway (but should be fixed in the polyfill, so we could keep it)
