### ISSUE TITLE
Add Property [Symbol.toStringTag] to Dexie.Promise

### ISSUE THREAD

**Issue by ChrisPearce** [dfahlander/Dexie.js#389]
When creating observables from Dexie.Promise objects, I'm encountering TypeScript compile errors such as:
[ts] Argument of type 'Dexie.Promise<MyType>' is not assignable to parameter of type 'Promise<MyType>'.
       Property '[Symbol.toStringTag]' is missing in type 'Promise<MyType>'.

Does Dexie.Promise support the property Symbol.toStringTag?

**Comment by dfahlander** [comment]
Thanks, I put it on todo.

**Comment by dfahlander** [comment]
@ChrisPearce, I've added [Symbol.toStringTag], but unfortunately I think you will continue getting compile error with Observable.from() since it expects exactly Promise<T> or subclass thereof. Try instead with Observable.from(Promise.resolve(dexiePromise)).

**Comment by dfahlander** [comment]
Looking into it a bit more, Promise<T> in lib.es6.d.ts is an interface, not a class. Of some reason, the declaration of Dexie.Promise in dexie.d.ts is not compatible with that interface. Probably just some other adjustments of dexie.d.ts would need to be done to be fully compatible with Promise<T> in lib.es6.d.ts.
