### ISSUE TITLE
Syncing stops after status: ERROR_WILL_RETRY

### ISSUE THREAD

**Issue by martindiphoorn** [dfahlander/Dexie.js#39]
In my protocol implementation i check first if there is an valid login. If it aint there  i skip the sync in the following way:

``` javascript
var sync = function (context, url, options, baseRevision, syncedRevision, changes, partial, applyRemoteChanges, onChangesAccepted, onSuccess, onError) {
    if (!isLoggedIn()) {
        console.log("Not logged in!, calling onError");
        onError("not logged in retry after five", 5000);
        return;
    }
    // Skipped rest off code which is based on the AjaxSyncProtocol.js
}
```

after five seconds i see the status going to "SYNCING".

Nothing happens anymore after that.

My expectation was that it would try to sync again.
Or did i miss something?

Parts of my console.log:
Sync Status changed: CONNECTING
Not logged in!, calling onError
Sync Status changed:  ERROR_WILL_RETRY
<after 5 seconds>
Sync Status changed:  SYNCING

**Comment by martindiphoorn** [comment]
As a notice this never became stable enough. So we stopped using the sync part.

**Comment by dfahlander** [comment]
I'm sorry to hear that. I've been prioritizing Dexie before the addons so far, and I think the addons need to be rewritten a lot. Or maybe someone builds better sync-/observe- addons based on the [CRUD hooks](https://github.com/dfahlander/Dexie.js/wiki/Table.hook%28%27creating%27%29)

**Comment by dfahlander** [comment]
Suppose it's fixed with the PR. Closing. Please reopen if not!
