### ISSUE TITLE
Dexie.Observable on existing database

### ISSUE THREAD

**Issue by nicolashenry** [dfahlander/Dexie.js#390]
Hello,

I just discovered dexie.observable plugin but I can't make it work.
If I add
```ts
import 'dexie-observable';
```
the following error occurs
```
Unhandled rejection: NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```
It seems (with some debugging) that the error means that "_changes" does not exist, I probably miss something but I don't know what exactly.
(I use dexie 2.0.0-beta.6 and dexie-observable 0.2.1)

**Comment by dfahlander** [comment]
You'd need to update the version of your schema to allow the addons to add its tables and indexes. This is not described anywhere. Will update wiki. Let's say your current version is 3. Then you should add a new line:

```js
db.version(4).stores({});
```
 No new tables added. Just to make it possible for the addons to add their tables.

**Comment by nicolashenry** [comment]
Ok nice, it seems to work :). Thanks!
