### ISSUE TITLE
AngularJS and DexieJS 

### ISSUE THREAD

**Issue by martindiphoorn** [dfahlander/Dexie.js#40]
For an project i am creating an AngularJS wrapper for Dexie.

Are there other people who have done the same?
Or are there people who would like to have this?

(Also posted on google groups)

**Comment by martindiphoorn** [comment]
Happy new Year!

I hope you like ngDexie. If you have any questions or suggestions you can create a issue at the project site.

**Comment by martindiphoorn** [comment]
Just as a warning! I just released a version 0.0.8 which is not backwards compatible!

**Comment by dfahlander** [comment]
Closing this issue now and thanks @martindiphoorn for creating ngDexie!
