### ISSUE TITLE
table get broken in 2.0.0-beta.6

### ISSUE THREAD

**Issue by g8tguy** [dfahlander/Dexie.js#404]
table.get({keyPath1: value1, keyPath2: value2, ...}, callback);

this isn't working, 

supplied parameters didn't match any signatures off call target.
```ts
db.states.get({component: this.component, key: key}, data => {
    return data
 })

```
could you please show a working example?

**Comment by nponiros** [comment]
Your error description sounds like a typescript compiler error. Did you run the code and got an exception or do you use typescript and the compiler gave the error?

**Comment by g8tguy** [comment]
as it turns out the problem was with chrome caching the Tables indexes
