### ISSUE TITLE
RFC: Split Dexie.Synable into multiple modules

### ISSUE THREAD

**Issue by nponiros** [dfahlander/Dexie.js#409]
I think that it would be a good idea to split Dexie.Syncable into multiple smaller modules. With multiple modules it will be easier to write isolated unit tests for the various functions. I believe that it will be easier to get Dexie.Syncable out of alpha if we have isolated unit tests for its functions. I personally also find multiple smaller modules to be more readable and easier to understand than one large module.

From what I have seen, the build process can handle multiple modules so we shouldn't have an issue there.

Challenges:

* Many functions access variables which are global to the module or the parent function. This makes it harder to have those functions in their own module. We would have to pass all global variables as separate parameters or as options object
* I'm currently not sure how easy it will be to actually write isolated unit tests since Dexie.Syncable does not seem to use karma and the Dexie karma configuration only references the dexie file in the dist folder and not each individual file in the src directory. From what I can tell we would need to add a karma config which can reference the individual files

**Comment by dfahlander** [comment]
You're 100% right. Should identify the private state vars and make them available somehow to splitted modules. Either via the db.syncable property, or some other strategy. Whatever seems most natural and easy to understand. Could use ES6 classes or even typescript if we would benefit from that.

Want to do the same for Dexie.js as well. At least cutting out Collection, Table and WhereClause for a start.

**Comment by nponiros** [comment]
I don't think typescript would help us with Syncable but it can help with Dexie as we wouldn't need separate .d.ts files. Off course if Dexie is written in typescript then we should also write Syncable in typescript.

Cutting out Collection, Table and WhereClause and using classes for them sounds like a good ideas as it can fix https://github.com/dfahlander/Dexie.js/issues/341 and off course allow us to easier write isolated unit tests for those.

I could start working on Syncable and also add unit tests and we can later decide when to merge. I could open a long standing PR to better track the changes.

**Comment by dfahlander** [comment]
That would be awesome. Dexie.Syncable / Dexie.Observable is a mess right now ;)

**Comment by nponiros** [comment]
PR was merged. Closing this issue.
