### ISSUE TITLE
Better `count` and `groupby` equivalent 

### ISSUE THREAD

**Issue by Bnaya** [dfahlander/Dexie.js#415]
I have the following collection:
```
index:
++id | userName | date

document:
id | userName | date | text 
```
My sql query is:
```sql
SELECT count(id), `userName` FROM `posts` GROUP BY `userName` WHERE `date` > %somedate%
 ```

My current dexie code is  
```typescript
    return db.posts.where('date').aboveOrEqual(date)
    .toArray().then(function (posts) {
        return posts.reduce(function (summary, {userName}) {
            if (summary.has(userName)) {
                summary.get(userName).amountAppeared++;
            } else {
                summary.set(userName, {userName, amountAppeared: 1})
            }

            return summary;
        }, new Map<string, {userName: string, amountAppeared: number}>());
    })
    .then(function (summary) {
        return Array.from(summary.values());
    });
```

Which fetching all of the records since the given Date and sum them on the js memory.

is there a better way to achieve it?

Thanks!

**Comment by dfahlander** [comment]
In your sample you are returning an array of counts without including the userName. Assume you want to return summary and not summary.values(), use one of the samples further down. In case you just want total posts count from given date, it would just be:

```js
return db.posts.where('date').aboveOrEqual(date).count();
```

In case you want it for a single user, make sure to index '[userName+date'] and do:
```js
return db.posts
    .where('[userName+date'])
    .between([username, date], [username, Dexie.maxKey])
    .count();
```

However, if you want a collected summary of all counts per user from given date, you could use each() instead of toArray() to save memory. 

```ts
const summary = new Map<string, {userName: string, amountAppeared: number}>();
return db.posts.where('date').aboveOrEqual(date).each(post => {
    let {userName} = post;
    if (summary.has(userName)) {
        summary.get(userName).amountAppeared++;
    } else {
        summary.set(userName, {userName, amountAppeared: 1})
    }
}).then(()=> {
    return summary;
});

```

Another (even more optimal) approach would be to execute several count() queries in parallell:

```js

function userPostCountSince(userName, date) {
    return db.posts
        .where('[userName+date'])
        .between([username, date], [username, Dexie.maxKey])
        .count();
}

async function usersPostCountSince(date) {
    // Retrieve all unique usernames using unique query:
    const uniqueUsernames= await db.posts.orderBy('userName').uniqueKeys();
    return await Promise.all(uniqueUsernames.map(async (username) => {
        return {
            userName: username,
            count: await userPostCountSince(username, date);
        };
    });
}

```

**Comment by dfahlander** [comment]
Heads-up though: compound indexes are not supported in IE or Edge (yet). [IndexedDBShim](https://www.npmjs.com/package/indexeddbshim) claims to polyfill this for Internet Explorer. There's also my polyfill [idb-iegap](https://github.com/dfahlander/idb-iegap) to try out.

**Comment by Bnaya** [comment]
Thanks for the info!

**Comment by g8tguy** [comment]
!הי בניה - תפתח ת' שאלה שוב בבקשה
But what about `db.table.where({ user: this.user, date: this.date })` - isn't this approach using the compound index routine underneath? Does it mean that  `Dexie 2.x`, Criteria filters don't work in Edge and IE?

**Comment by dfahlander** [comment]
Yes they will work on ie/edge but the will fallback to not using compound index
