### ISSUE TITLE
How to patch Dexie Promise for zone.js

### ISSUE THREAD

**Issue by nicolashenry** [dfahlander/Dexie.js#416]
I currently have this working monkey patch for zone.js :
```ts
const dp = Dexie.Promise.prototype;
const thenFn = dp.then;

function thenZone() {
	for (let i = 0; i < arguments.length; i++) {
		const arg = arguments[i];
		if (typeof arg === 'function') {
			arguments[i] = Zone.current.wrap(arg, 'zone wrapped Dexie promise (then)');
		}
	}

	dp.then = thenFn;
	const result = dp.then.apply(this, arguments);
	dp.then = thenZone;
	return result;
}

dp.then = thenZone;
```
I don't know why I need to put restore the original "then" method in the prototype before calling it (the callbacks are never called if I don't).

Is there another recommended way to do it ?

**Comment by nponiros** [comment]
Hm I'm not sure I understand your problem correctly but can't you just do this:

```
const dp = Dexie.Promise.prototype;
const thenFn = dp.then;

function thenZone() {
	for (let i = 0; i < arguments.length; i++) {
		const arg = arguments[i];
		if (typeof arg === 'function') {
			arguments[i] = Zone.current.wrap(arg, 'zone wrapped Dexie promise (then)');
		}
	}

	const result = thenFn.apply(this, arguments);
	return result;
}

dp.then = thenZone;
```

**Comment by nicolashenry** [comment]
If I just do : 
```ts
const dp = Dexie.Promise.prototype;
const thenFn = dp.then;

function thenZone() {
	return thenFn.apply(this, arguments);
}

dp.then = thenZone;
```
Everything is broken but I think it should work.

**Comment by nicolashenry** [comment]
Following this comment https://github.com/dfahlander/Dexie.js/blob/master/src/Promise.js#L195, I thought that something had been done for this case.

**Comment by nicolashenry** [comment]
@nponiros Am I understandable ? I'm sorry if my english is too bad or if I'm just unclear.

**Comment by dfahlander** [comment]
@nicolashenry

What would be the reason to do so? There should be no need to wrap Dexie in Zone.js as they should be compatible as they are.

**Comment by nponiros** [comment]
I am not really familiar with the Dexie.Promise code. It might be that there is a bug in that code or the way you tried to replace `then` was not correct. I'm also not familiar with `Zone`, maybe the way you wrapped `then` was wrong.

**Comment by nicolashenry** [comment]
@dfahlander The main problem is that I use Angular 2.x and Angular 2.x use zone.js for the change detection.
Zone.js is currently patching functions and classes like setTimeout/setInterval/XMLHtt̂pRequest/Promises/... for each callbacks. Angular use it to detect changes but IndexedDB is not managed by zone.js (I don't know exactly why).

As a result, when I use a Dexie.Promise the change detection is not working directly. I already found some solutions : 
- Wrapping Dexie.Promise calls in a native Promise each time
- Calling manually the angular change detector class "ChangeDetectorRef" each time
- Patching IndexedDb or Dexie.js

From my point of view, the simplest way seems to patch Dexie because there is less methods to patch than IndexedDB and I don't have to care about change detection afterward. The piece of code in my first message is currently working as intended but I wanted to know id there was another cleaner way to do it.

**Comment by nponiros** [comment]
@nicolashenry consider using the ChangeDetectorRef. As I mentioned I am not very familiar with Dexie.Promise but from what I see there are plenty of internal then() calls and you probably don't want angular to execute the ChangeDetection algorithm every time Dexie internally uses a promise. Using the ChangeDetectorRef you can be much more flexible and decide when to call it which can make a big difference performance-wise. You could even take your components out of the change detection tree and change detect when you know Dexie is done.

**Comment by dfahlander** [comment]
What I've read is that Zone.js supports patching indexedDB now, but they used to not patch it before. Know many other people using angular 2 with Dexie without having to patch zone.

**Comment by nicolashenry** [comment]
@nponiros Angular is already doing it for almost every other asynchronous callbacks, I don't want Dexie to be an exception. 

@dfahlander My bad, I was not up to date it seems but I still have some change detection issue with the latest stable zonejs which is still fixed by my patch, I will try to find out why.

**Comment by nicolashenry** [comment]
Ok I just found my problem, I was doing this : 
```ts
export class MyDB extends Dexie {
...
}

export const myDb = new MyDB();
```

```ts
import { myDb } from './my-db';
@Injectable()
export class MyService {
    ...
    myMethod() {
        return myDb.myTable.where(...).equals(...);
    }
}
```
It seems that I created the database instance too soon for Angular.
Injecting the database instead of creating it in the module solved my problem : 

```ts
@Injectable()
export class MyDB extends Dexie {
...
}
```

```ts
import { MyDb } from './my-db';
@Injectable()
export class MyService {
    constructor(
        private MyDb myDb
    ) {
    }
    ...
    myMethod() {
        return this.myDb.myTable.where(...).equals(...);
    }
}
```

Sorry for the noise, it could be nice to have some working examples to use Dexie with some popular framework like Angular2, React, etc Thanks for your responses.

**Comment by dfahlander** [comment]
Don't be sorry. Knowing the pitfalls of using Dexie with angular 2 is important for other angular users and it seems you've found such pitfall that must be avoided. You've just followed our guidelines of exporting the db instance. As it turns out, this seems to be an anti pattern for angular. 

If any one who is experienced with angular 2 could write a nice sample that would be great to have under samples/.

**Comment by nponiros** [comment]
Hm I don't see why the first approach shouldn't work. From what I remember zonejs is loaded before angular. Maybe I can test this tomorrow.

**Comment by nponiros** [comment]
@nicolashenry I tested Dexie with angular 2 this morning and had no issues with your first approach. Maybe your issue was a too old angular, zone or Dexie version or some other part of your app. In any case I added an angular 2 sample here: https://github.com/dfahlander/Dexie.js/pull/417

**Comment by nicolashenry** [comment]
I updated my dependencies to the latest ones, I think that my building system may be in cause here. I use the systemjs builder https://github.com/systemjs/builder to make a unique bundle file to load (including angular templates).
Note that the problem occurred only on the first call and sometimes it worked randomly.
I will try to make a minimal similar example from your sample when I can.
