### ISSUE TITLE
Syncable poll pattern without "again" stays in connecting state

### ISSUE THREAD

**Issue by nponiros** [dfahlander/Dexie.js#419]
If the `onSuccess()` call of the initial `sync()` call didn't include the `again` key with a valid number, the sync node stays in the CONNECTING state. We should disconnect the active peer in this case just like we do when a subsequent `onSuccess()` call doesn't receive an `again` property.

Is there any reason why the peer is not disconnected currently? From what I can see there is no way for the `sync()` function to be called again in this case to get us out of the CONNECTING state.

**Comment by dfahlander** [comment]
There is no reason to behave as it is doing now. I think as you say,  it should behave the same way as it does for subsequent continuations.

**Comment by nponiros** [comment]
I can add the fix in https://github.com/dfahlander/Dexie.js/pull/413 or I could open a new pull request if you would prefer that

**Comment by dfahlander** [comment]
Fixing as part of #413 sounds good to me.
