### ISSUE TITLE
Dexie.Observable possible bug in message passing

### ISSUE THREAD

**Issue by nponiros** [dfahlander/Dexie.js#429]
In the typings for Observable sendMessage() and broadcastMessage() declare the `message` property as type `any`. As it seems when a message is consumed, any message which is not of type `object` is not passed to the 'message' handler as part of the argument. For some reason consumeMessage() deletes the `message` property and then adds it back to the message using Dexie.extend(). I don't why this is done. I would expect to receive the message as `message` property in the argument of the 'message' handler.

So the question is: are the typings wrong or should consumeMessage() be implemented differently? I also didn't find any documentation on the 'message' event, is it considered private?

**Comment by nponiros** [comment]
As it seems broadcastMessage() doesn't work correctly. It does broadcast on all db instances but it broadcasts multiple messages for each instance. If we have two instances with sync nodes each instance will receive 2 messages. If we have 3 instances each instance will receive 3 messages and so on. I'm assuming that this is a bug. @dfahlander can you confirm that this is a bug?

**Comment by dfahlander** [comment]
Wow, that's a bug if so

**Comment by nponiros** [comment]
It seems to be an issue with intercomm in general not only broadcast. If one instance sends messages to different destinations, then all destinations will receive their message multiple times. It seems that the message deleting in consumeIntercommMessages() happens too late. I will see if I can fix this somehow.

Any thoughts on my first comment @dfahlander ?

**Comment by dfahlander** [comment]
I'm not at the computer today but I recall I was confused by this code as well last week so I extracted the typings.

**Comment by nponiros** [comment]
Okay, no worries. Get back to me when you can.

**Comment by dfahlander** [comment]
Hoping to get some time tonight to look at it

**Comment by nponiros** [comment]
So I managed to fix the multiple messages issue by wrapping the reading and deleting of messages in consumeIntercommMessages() into a 'rw' transaction to block further reading until we manage to delete the nodes. As it seems the _intercomm table was read multiple times before the messages got deleted. This is probably due to the (as it seams) synchronous nature of Observable.on.intercomm.fire.

Maybe you have a better fix but at least my tests pass now.

I will put the fix along with tests into the open PR for refactoring observable.

**Comment by dfahlander** [comment]
@nponiros To answer the first question, this messaging framework has never been documented and was intended for internal use by Dexie.Syncable. The way it mix-ins the real message with its meta-data is not a nice solution.. Would've been better to keep it as the message property. And it is okay to change that. The only place that calls db.on('message') is Dexie.Syncable.js line 39 (as of your latest PR)

```js
db.on('message', function(msg) {
        // Message from other local node arrives...
        Dexie.vip(function() {
            if (msg.type === 'connect') {
                // We are master node and another non-master node wants us to do the connect.
                db.syncable.connect(msg.protocolName, msg.url, msg.options).then(msg.resolve, msg.reject);
            } else if (msg.type === 'disconnect') {
                db.syncable.disconnect(msg.url).then(msg.resolve, msg.reject);
            } else if (msg.type === 'syncStatusChanged') {
                // We are client and a master node informs us about syncStatus change.
                // Lookup the connectedProvider and call its event
                db.syncable.on.statusChanged.fire(msg.newStatus, msg.url);
            }
        });
    });
```

No other addon than Dexie.Syncable use it. And I don't think anyone could expect this undocumented API of an aphla-stage module to be backward compatible.

**Comment by dfahlander** [comment]
The reason to put 'any' in the d.ts was that the editor would complain if specifying an interface. Could have been done as with IPersistantContext and allow dynamic properties on the interface, but I was too sloppy for that. If changing the API to keep message as a property, the d.ts would be clearer and could define "msg" but keep "message" as 'any'. If we define it as Object, the user will have to cast it to access its properties. And generics is not useful here since on('message') is separate from sendMessage()/broadcastMessage().

**Comment by nponiros** [comment]
I would say "changes" should get an object with "message" property of type "any" instead of merging the properties of the message property as its done now. I will prepare something tomorrow and adjust the d.ts file a bit.

**Comment by dfahlander** [comment]
Exactly

**Comment by nponiros** [comment]
This fix is in the latest release. Closing.
