### ISSUE TITLE
equals support for boolean?

### ISSUE THREAD

**Issue by Script47** [dfahlander/Dexie.js#431]
Does the `equals` function support pure boolean check?

Take the following query,

```javascript
db.amateur_levels.where('completed').equals(true).count(callback);
```
it should return 0, however it returns,

```javascript
[...]Error: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key.[...]
```

when the query is changed to the following,

```javascript
db.amateur_levels.where('completed').equals('true').count(callback);
//------------------------------------------^    ^--------------------
// Note the single quotes!
```

it now displays 0 with, so is there support for `true` and `false`?

**Comment by nponiros** [comment]
As far as I know there is no support for boolean in equals. where() and equals() use indexeddb indexes and those don't support boolean values. As a workaround you could use 1 for true and 0 for false. You could convert those to boolean when you read from db if needed and convert back to number when saved.

**Comment by Script47** [comment]
@nponiros thanks for the speedy response, much appreciated. Yep, I was considering using integer flags.

**Comment by nponiros** [comment]
You're welcome :)
