### ISSUE TITLE
Dexie: WebSocket Sync from Service Worker

### ISSUE THREAD

**Issue by puhazh** [dfahlander/Dexie.js#433]
Dexie WebSocket sync is not working when db.syncable.connect(...) is called, Browser: Chrome, Version: 54. 

Does Dexie WebSocket sync support connections from Service Worker?

**Comment by nponiros** [comment]
I can't think of a reason why Dexie.Syncable shouldn't work in a service worker but I'm not sure if websockets work in service workers. Did you get any error? Maybe you could try with ajax and Dexie.Syncable to see if Dexie.Syncable is the issue or just the websockets example.

**Comment by nevf** [comment]
It may be because WebSocketSyncProtocol.js is loaded after you've called ```db.syncable.connect( "websocket", ... ``` It depends on how you are loading the module. 

I had this issue using the jspm loader and have updated ```WebSocketSyncProtocol.js``` to wrap the code inside:

````
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('dexie')) :
    typeof define === 'function' && define.amd ? define(['dexie'], factory) :
    (global.Dexie = global.Dexie || {} );
}(this, (function (Dexie) { 'use strict';

....
})));
````

**Comment by puhazh** [comment]
@nevf I am using importScripts() from Service Worker to load Dexie and other scripts. importScripts is synchronous and module not loaded doesn't look like the problem here. 

NB: Everything works fine and syncs perfectly when used from a page. 

@nponiros WebSockets from Service Worker works fine, I had tried connecting to other services and looks fine.

Here is the Stack Trace:

Error
    at S (http://localhost:3000/lib/Dexie.min.js:1:4608)
    at new U (http://localhost:3000/lib/Dexie.min.js:1:6692)
    at Object.n.syncable.connect (http://localhost:3000/lib/dexie-syncable.min.js:1:11139)
    at eval (eval at evaluate (:117:21), <anonymous>:1:13)
    at http://localhost:3000/service-worker.js:33:1

I just have the minified files, will update the stack trace later with the in-minified version.

**Comment by puhazh** [comment]
I could see the following code in Dexie.js, (and other references to document. )

`var n = document.createElement("div");`

Guess these are dependent on DOM which might be causing the issue when run from a Service Worker?

**Comment by nponiros** [comment]
Dexie works in workers (at least there are tests for it). The websocketserver shim uses document. The shim is from what I know used to get the server to work in the browser for tests. You shouldn't need it if you run the socket server with node.js.

**Comment by puhazh** [comment]
@nponiros  Dexie works perfectly in Service Workers, the issue I face is only when using sync with the Dexie.Syncable add-on.

**Comment by nponiros** [comment]
@puhazh I'm sorry but I can't help you without some more information. I never used Syncable in a Service/Web worker and I also didn't see something in Syncable which would prevent it from functioning in a worker (I might have missed something off course). If you could post a stack trace with the non-minified version of Dexie and Dexie.Syncable, I might be able to help you. As I already mentioned `document` is used in websocketserver-shim.js but not in Dexie/Syncable/Observable. In case you are including that, it might be the cause of the error.

**Comment by puhazh** [comment]
@nponiros Sorry for the delay in getting the stack trace with the unminified files. The files/links in dist folders appears to be out of sync and I am facing issues because of that. 

Ex: The link to dexie.js (unminified) in the dist folder (or using tag latest in unpkg https://unpkg.com/dexie@latest/dist/dexie.js),  doesn't have the method hasBeenClosed which is expected by the Dexie.Syncable.js  (https://unpkg.com/dexie-syncable@latest/dist/dexie-syncable.js).

Tried using https://unpkg.com/dexie@^2.0.0-beta/dist/dexie.js for dexie.js (unable to find matching version for the add-ons), gives me some other errors.

Would be great if you could update the links in dist folder for all add-ons and dexie to the same version. 

Appreciate any help here.

**Comment by nponiros** [comment]
Dexie.Syncable and Dexie.Observable have other versions than Dexie. The latest version for Syncable and Observable is 0.9.2. The latest compatible version of Dexie is 2.0.0-beta.7.
Please use the following:
https://unpkg.com/dexie@2.0.0-beta.7/dist/dexie.js
https://unpkg.com/dexie-syncable@0.9.2/dist/dexie-syncable.js
https://unpkg.com/dexie-observable@0.9.2/dist/dexie-observable.js

**Comment by puhazh** [comment]
@nponiros Thank you for the links. I used the links and sync works perfectly fine from the service worker too. I am not facing the issue which I got earlier. 

Thank you for all your assistance.

**Comment by delebash** [comment]
Thank you @nponiros.  I just spent alot of time trying to figure out what I was doing wrong. :)
