### ISSUE TITLE
Should try use typescript 2.1 in place of babel

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#435]
Typescript 2.1 supports transpiling plain js to ES5 but does it without bloating the code. Typescript package installs on seconds while the babel suite takes minutes to install, and comes with loads of dependent packages.

Due to the way babel transforms the code, I've been avoiding things like destructuring, for-of loops, const and let to avoid unnecessary bloated output. If using tsc --allowJs instead of babel, this wouldn't be a problem anymore since tsc --allowJs generates cleaner and smaller ES5 code.

Suggestion is to try out to change the build tool to replace babel with tsc and see how it goes. Measure the size of the minified output and make sure tests runs as expected. A plus is also that it would be a small step to migrate the code, or parts of it to typescript if we'd want to.

**Comment by piuccio** [comment]
As a typescript ignorant I prefer if you write ES6 code and transpile with babel. That's the best approach for people using webpack / rollup

**Comment by nponiros** [comment]
The typescript compiler can output es6 and es5 code so users of dexie shouldn't have any issues if dexie itself is written in typescript.

**Comment by dfahlander** [comment]
It turned out to go well, but I wasn't able to use rollup-plugin-typescript as there are some issues with it. Also, using tsc as a plain JS transpiler isn't the most obvious use case so I've created a step-by-step flow that is run when doing `npm run build`

1. Transpile from ES6 --> E5 (`tsc --allowJS (other flags)`)
2. rollup result
3. Minify and replace version/date etc.

Typescript transpiles all but generator functions (will be solved in a future version of typescript). Since our test suite uses generator functions a lot, I needed to use babel for that particular reason. So tests are built a little differently:

1. tsc
2. babel (only with regenrator plugin)
3. rollup

For the addons babel wasn't needed because no tests used generator functions.

After the latest PR, you must do npm install again to be able to build it. Also on addon dirs.

**Comment by dfahlander** [comment]
To build all (src, tests + minify etc), still use:

```
npm run build
```

Now, eslint is also invoked in the build flow.

To watch all, still use
```
npm run watch
```

If watch without minification etc (still both src and tests):

```
npm run watch dev
```
