### ISSUE TITLE
RFC: Change a syncNode's options without having to delete it

### ISSUE THREAD

**Issue by nponiros** [dfahlander/Dexie.js#447]
From what I can tell the only way to change the options of a remote syncNode is to delete the node and recreate it with connect(). During connect if a node with the given URL is found, the options are just ignored. I don't know if there is a reason for this behavior. Deleting the node seems to be problematic as that could delete all the changes of the node that were not synchronized yet and it does delete all changes in the \_uncommittedChanges table.

One possible solution for this would be to not ignore the options if `connect()` is called on an already existing node. From what I can tell the node would have to be disconnected and reconnected for the new options to take effect and be passed to the `sync()` function. This should be documented in the wiki if we choose this solution.

Another solution would be to have a new method `setOptions(url, options)` which would automatically disconnect and reconnect the node for the options to take effect.

Furthermore it would be nice to have a method `getOptions(url)` which would return the options for a syncNode. This is not so important as there are other ways to get the options if needed but I think it would be cleaner/safer if Syncable offers this method, especially if we have a `setOptions()` method.

The reason why I would like to be able to set and get the options is because I want to allow a user of my app to configure the options without having to store the options myself or having to delete the node to be able to set new options.

**Comment by dfahlander** [comment]
connect() should not ignore the options I think, no matter if we'd also support setOptions() and getOptions(). You're right that a connect() with different options should reconnect the node.

**Comment by dfahlander** [comment]
I'm ok with adding setOptions() and getOptions(). But I think that connect() with alternate options not reconnecting is a bug and should also be solved.

**Comment by nponiros** [comment]
Okay, thanks for the input @dfahlander . Will try to fix/implement this asap.
