### ISSUE TITLE
Shared DB between main process and Web Worker

### ISSUE THREAD

**Issue by wasd171** [dfahlander/Dexie.js#449]
Hi!

Is it possible to access the same DB from main process and WW? Seems that if I do the usial 
```
const db = new Dexie('MY_DB');
```
on both WW and main thread, I get two dbs created.

**Comment by dfahlander** [comment]
Yes they can share db and as long as your worker is executing in the same origin, you should access the same db.

**Comment by wasd171** [comment]
It was some issue with webpack and `worker-loader`. Setting it in inline mode fixed the issue.
