### ISSUE TITLE
Dexie Query, Group, Sum 

### ISSUE THREAD

**Issue by LeFrach** [dfahlander/Dexie.js#453]
Hello everybody,
I come here to "db.query" your help, please.
I have a db like this :
        
```
        var db = new Dexie("Order");
	db.version(1).stores({
	order: "++id,idOrder,Catalog,Category,TotalPrice"
	});
```
        
With multiples objects insert :
        
```
        {
        Catalog : "Design",
        Category : "Tattoos",
        idOrder : "98",
        TotalPrice : "20"
        }
         {
        Catalog : "Design",
        Category : "Other Tattoos",
        idOrder : "98",
        TotalPrice : "10"
        }
         {
        Catalog : "Design",
        Category : "Other Tattoos",
        idOrder : "98",
        TotalPrice : "15"
        }        
        {
         Catalog : "Book",
         Category : "Adventure",
         idOrder : "98",
         TotalPrice : "19" 
        }
```
        
I try since few days, again and again, to build a query that return informations like this : 
 
```
        Design (x3) = 45$
            -> Other Tattoos (x2)  = 25$
            -> Tattoos (x1)  = 20$
            
        Book (x1) = 19$
            -> Adventure (x1) =  19$
```
            
I despair of getting there :(
Someone can help me to build this query ? I appreciate it 
Really really thank you for help

**Comment by nponiros** [comment]
From what I know you will not be able to do what you want directly using just Dexie. You could use `each ()` to read every element in your store and manually filter the data and create an object with the information you need. You could also use `toArray()` and then filter that array and collect the infos you need.

**Comment by LeFrach** [comment]
Hello nponiros, 
I created a function that goes in this direction effectively, I imagined that a "simple" way could be help me.
Thank you :)

I have function for 'catalog' and another one for 'category'.
I play after with a little bit of jQuery and I successfully do What I want :)

Exemple of my 1st function, arr is my array with catalog, prixArray the prices.

```
function foo(arr, prixArray) {

var a = [],	b = [], prev;
arr.sort();
for (var i = 0; i < arr.length; i++) {
if (arr[i] !== prev) {
a.push(arr[i]);
b.push(1);
} else {
b[b.length - 1]++;
}
prev = arr[i];
}

var u = document.getElementById("groupeBy");
var t = "<table class='table table-striped table-bordered'><tr><th>Catalogue</th><th style='text-align:center;'>Prix</th><th style='text-align:center;'>Ligne</th></tr>";

for (var h = 0; h < a.length; h++) {
var methode = a[h];
var montant = prixArray[methode];
methode = escapeRegExp(methode);
t += "<tr><td  width='70%' >" + a[h] + " <span rel='" + methode + "' class='buttonGamme btn btn-xs btn-primary pull-right'><i class='fa fa-angle-down'></i></span></td><td width='15%' style='text-align:center;'>" + montant + "</td><td width='15%' style='text-align:center;'>" + b[h] + "</td></tr>";
t += "<tr class='" + methode + "' style='display:none;' ><td style='padding:0px;' colspan='3'><table id='" + methode + "'  class=' table-bordered' style='margin:0;width:100%;'></table></td></tr>";
}
t += "</table>";
u.innerHTML = "" + t + "";
}
```

Thank you to try to help me ! Have a good night :)

**Comment by nponiros** [comment]
@LeFrach can this issue be closed or do you have further questions?

**Comment by LeFrach** [comment]
Yes sorry
