### ISSUE TITLE
Some syncable tests are not running

### ISSUE THREAD

**Issue by nponiros** [dfahlander/Dexie.js#458]
When `npm test` is called in Dexie.Syncable, some of the defined tests don't seem to be running. The test files directly under the test directory (tests-syncable.js, tests-syncable-partials.js etc.) are, from what I can tell, not run by npm. Those are only run when `test-syncable.html` is called. Is this wanted or did something go wrong during refactoring?

**Comment by dfahlander** [comment]
I made the build rewrite on huey. Observable tests  got converted to modules and part of build but I missed to complete it for syncable. Think they could be moved into unit?

**Comment by nponiros** [comment]
There might be conflicts because those tests require syncable and most unit tests don't import syncable. Those should work as part of the integration tests (I had them there before). If you don't have time to fix it now, I can have a look tomorrow.

**Comment by dfahlander** [comment]
In dexie-observable, I could successfully mix them by specifying {addons: []} in the ones that didn't expect the addon to be active. The integration test suite is just the Dexie suite with a dummy sync protocol active to verify that all normal Dexie tests pass also with the addon active.

**Comment by nponiros** [comment]
okay, will try to put those test into the unit folder and push as part of https://github.com/dfahlander/Dexie.js/pull/459 so that the new tests actually run on travis

**Comment by nponiros** [comment]
The tests were added in https://github.com/dfahlander/Dexie.js/pull/459
