### ISSUE TITLE
Uglify error SyntaxError: Unexpected token: operator (>)

### ISSUE THREAD

**Issue by Bnaya** [dfahlander/Dexie.js#460]
The code that provided in package.json.module /  package.json.es:next needs to be a valid es5 code, except of the es6 modules syntax. (as rollup guidelines )

Currently its contain other es6 features as arrow functions.

When Uglifying js code that contains also dexie code it breaks with that following error:
`SyntaxError: Unexpected token: operator (>)` because of an error function  

That error didn't happen with dexie beta.7 but with beta.9

**Comment by Bnaya** [comment]
Rollup guidelines 
https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

**Comment by nponiros** [comment]
Thanks for the info @Bnaya . I guess we shouldn't target es2015 in the build script, just es2015 modules and target es5 for the rest.

**Comment by dfahlander** [comment]
The name of the modules (currently `dexie.es6.js`) is inaccurate if so. Seems we should name it `dexie.jsm`?

**Comment by dfahlander** [comment]
Using extension `dexie.es.js` instead of `dexie.jsm`. Reasons:
* jsm extension is not yet standardized and code editors doesn't detect that it is JS.
* rollupjs distributes its own ES modules as with 'es.js' file extension.

**Comment by dfahlander** [comment]
Side note: Now also configured the addons to produce es.js outputs.
