### ISSUE TITLE
Move docs to dexie.org

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#464]
Follow-up from #22.

**Comment by dfahlander** [comment]
The [jekyll](https://github.com/dfahlander/dexie.js-web/tree/jekyll) branch: Just followed the guide for setting up jekyll on github. index.html was renamed.

The goal should be to rewrite the current index.html to be jekyll-compliant and have links to the documentation.

**Comment by dfahlander** [comment]
To get it moving, I've now merged in the branch to the main gh-pages branch, so we can watch it at [dexie.org/index-jekyll.html](http://dexie.org/index-jekyll.html).

Also created a github project with some tasks we will need to do: https://github.com/dfahlander/Dexie.js/projects/1

**Comment by nponiros** [comment]
Nice! Will have a look at it later tonight and try to asses how much effort it will take to convert the wiki pages to jekyll compatible markdown

**Comment by dfahlander** [comment]
There's a nice guide here. I think we should put the MD files under a new directory _pages rather than _posts. https://www.taniarascia.com/make-a-static-website-with-jekyll/

**Comment by dfahlander** [comment]
I was able to test site locally after installing jekyll by writing
```
jekyll serve
```

![image](https://cloud.githubusercontent.com/assets/6791329/22423816/bfe3d4ba-e6f3-11e6-9733-b6bb9f5bc62a.png)

**Comment by nponiros** [comment]
So I had a quick look at jekyll after spending half an hour installing it and resulting in removing the Gemfile and Gemfile.lock (there is some version mismatch I guess). The good news is that converting the wiki pages shouldn't be more work than with the tool I created. I guess it will take half a day to a day to add front-matter, fix all links, add links to edit the file. The bad news is I will need to create layouts in jekyll and I'm not familiar with its syntax. I would say depending on the requirements (how many different layouts are needed, do we switch to sass, different headers/footers etc) the switch shouldn't take more than a few days.

Personally I think we should start with the simplest possible solution (probably just take the layout from the demo site I created) and after we made the switch we can improve the layouts etc. The reason for that: the longer we keep docs in the website git and the wiki the more work it will be later to again migrate any changes made in the wiki.

**Comment by dfahlander** [comment]
A minimal design is a big step anyway.  Could improve design later on.

**Comment by nponiros** [comment]
Well I'm making some progress here. I created a docs folder instead of _pages because it is easier this way to have the right URLs later. Next step would be to add front-matter, fix the layout and remove useless stuff

**Comment by nponiros** [comment]
@dfahlander do you like the design of the demo site (documentation part, index was unchanged) I made for a first version or do you want anything changed?

**Comment by dfahlander** [comment]
I think it's fine for now. It seems to use the same font and the same logo which is good. Could be enhanced over time. The blue background color seems a little to strong maybe. A lighter color might be better. Table of contents might be possible to improve. Maybe have list-style: none on the items in table of contents. Possibly have a fixed height and overflow-y: auto on it to generate scrollbars. But I could laborate with the design when I get some time. Also see if we could sew it together better with the index page.

**Comment by nponiros** [comment]
okay. I will see what I can do. I will create a PR for the website repo (Saturday at latest) so you can have a look and make changes.

**Comment by nponiros** [comment]
Pull request is open https://github.com/dfahlander/dexie.js-web/pull/3 .

**Comment by nponiros** [comment]
@dfahlander please enable issues for the dexie.js-web repository. I found some links which are broken in the wiki (Promise.then(), Promise.catch()) do not exist as wiki pages. It would be could if we can have issues like that on the dexie.js-web repo.

**Comment by dfahlander** [comment]
It's enabled

**Comment by dfahlander** [comment]
Thanks @nponiros for the awesome work with moving the docs! It's now up and running on http://dexie.org/docs. Anyone following this issue, please have a look at the new docs and give your feedback!

**Comment by dfahlander** [comment]
Closing this as docs are moved.
