### ISSUE TITLE
bulkPut: "at least one key does not satisfy the uniqueness requirements"

### ISSUE THREAD

**Issue by nbrustein** [dfahlander/Dexie.js#469]
When using bulkPut, I'm getting the following error:

`Unhandled rejection: BulkError: stems.bulkPut(): 135 of 135 operations failed. Errors: ConstraintError: Unable to add key to index '[languageId+name]': at least one key does not satisfy the uniqueness requirements.`

I'm guessing that this is actually expected, but I don't understand why.  The docs for `put` say "If an object with the same primary key already exist, it will be replaced with the given object. If it does not exist, it will be added."  Since the `bulkPut` docs do not say otherwise, I would have expected `bulkPut` to behave the same way.  But then how could there be a uniqueness error?

Maybe there is some update to the docs that need to be made?

**Comment by dfahlander** [comment]
Yes but it in your case you seem to have a unique index side by side with the primary key. This error seems not to be a primary key violation.  Have you defined the index [languageId+name]  to be unique?

The bulkPut() method can replace a document of its primary key exists already. Not other unique indexes. In your case, maybe you could use  [languageId+name] as primary key instead of as an index?

**Comment by nbrustein** [comment]
Thanks.  That makes sense.

Is the only kind of primary key you can have an auto-incremented integer one?

**Comment by nponiros** [comment]
No you can have any supported indexeddb type as primary key as far as I know but it has to be unique. Dexie.Observable for example supports uuids (string type). I use [cuid](https://github.com/ericelliott/cuid) which is also a string

**Comment by dfahlander** [comment]
No. Any indexable type can be used and you don't need ++ even though many of our samples use it. 
Indexable types are string, number, Date or Array<string | number | Date>.  With indexedDB 2.0 (not reliable yet) you will also be able to use binary keys such as Uint8Array both for primary key and index.

**Comment by nbrustein** [comment]
Ah I see it in the docs now. "The first entry in the schema string will always represent the primary key."

Thanks a lot for the help.  I'll go ahead and close this.
