### ISSUE TITLE
Using where - startsWith Clause with JSON data

### ISSUE THREAD

**Issue by geelus** [dfahlander/Dexie.js#474]
I have a Customer object with JSON data as customer phone.
Something like this:
{
FirstName,
LastName,
Phones:
    {
      Type,
      Number
    },
   {
      Type
      Number
    }
}

The question is that how can I search for a phone number? For example using startsWith?

**Comment by dfahlander** [comment]
Assuming Phones is an array of objects. IndexedDB will not be able to index arrays of objects within the document. It can index arrays (multiEntry indexes), but only arrays of simple types. So either you convert your model to a relational model (separate table for Phones and link Customer to it by id), or complement the Customer table with a plain (redundant) PhoneNumbers array just for searching.

## Relational Model
```js
import Dexie from 'dexie';
import dexieRelationships from 'dexie-relationships';

var db = new Dexie('mydb', {addons: [dexieRelationships]});
db.version(1).stores({
    Customers: '++Id, FirstName, LastName',
    Phones: '++Id, CustomerId -> Customers.Id, Type, Number'
});

// Populate the DB
db.on('populate', async ()=>{
    let customerId = await db.Customers.add({
        FirstName: 'Foo',
        LastName: 'Bar'
    });
    await db.Phones.add({
        CustomerId: customerId,
        Type: 'work',
        Number: '+46123456'
    });
});

// To search for customers having a phone prefix:
async function searchPhone(prefix) {
    let phones = await db.Phones
        .where('Number').startsWith(prefix)
        .toArray();

    let customers = await db.Customers
        .where('id').anyOf(phones.map(phone => phone.CustomerId))
        .with({Phones: 'Phones'});

    return customers;
}

searchPhone('+46').then(result => {
    console.table(results);
});
```

## Using multiEntry (redundantly for indexing)

```js
import Dexie from 'dexie';

var db = new Dexie('mydb2');
db.version(1).stores({
    Customers: '++Id, FirstName, LastName, *PhoneNums'
});

// Populate the DB
db.on('populate', ()=>{
    return db.Customers.add({
        FirstName: 'Foo',
        LastName: 'Bar',
        Phones: [{
            Type: 'work',
            Number: '+46123456'
        }],
        PhoneNums: ['+46123456']
    });
});

// To search for customers having a phone prefix:
function searchPhone(prefix) {
    return db.Customers
        .where('PhoneNums').startsWith(prefix)
        .distinct()
        .toArray();
}

searchPhone('+46').then(result => {
    console.table(results);
});
```

**Comment by geelus** [comment]
Brilliant! Thank you very much for your prompt response.

I believe this is the best library for indexeddb and by the way I love the bulk features. It's perfect for synchronization with the server.

Thanks for creating such a fantastic library.

**Comment by geelus** [comment]
By the way, can you please also tell me how to index arrays of simple types like string? I really care about the phone numbers only and can store them as an array. How can I use "startWith" with that?

**Comment by geelus** [comment]
Sorry I just saw that. I'm deleting the question now.
