### ISSUE TITLE
InvalidStateError

### ISSUE THREAD

**Issue by KonishiLee** [dfahlander/Dexie.js#478]
Unhandled rejection: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. i get the array when db.open() success, but this error remind me that db don't open.please tell me how to fix.

**Comment by KonishiLee** [comment]
@dfahlander  please tell me how to fix it , " A mutation operation was attempted on a database that did not allow mutations."  error on Firefox browser with windows. on mac it's normal.

**Comment by dfahlander** [comment]
Not sure. Googling it turns out to this answer :

https://ckon.wordpress.com/2016/02/14/mutation-operation-error/

Other answers are also about that error beeing thrown when a transaction was used from a non - indexedDB callback.

**Comment by KonishiLee** [comment]
you mean i should add try catch into code? but i use dexie including callback, when i get array i coding db.open().then(function(){ //get arrary }); ,if i join try catch, that the indexedDB can't open, then how to use it ?

**Comment by dfahlander** [comment]
You use promise catching 

```js
db.open().catch(function (error) {
    // handle error
}) 
```

**Comment by KonishiLee** [comment]
if i catch the error, then what should i do?

**Comment by dfahlander** [comment]
That's up to you dude ;) 

If error.name is 'InvalidStateError', I probably show a dialog that informs user on how to enable indexedDB according to the link I googled for you (if you've tested and it seem to be accurate. Have you?)

**Comment by KonishiLee** [comment]
Thank u very much for your answer to my question :) . Have a nice weekend.
