### ISSUE TITLE
How to update a table where table name is a variable ?

### ISSUE THREAD

**Issue by LeFrach** [dfahlander/Dexie.js#484]
Hello, 
I hope you fine.

I Would like to update a table, but my table name is a variable.

```
nomTable = "quantite"+Id+"";
nomPrix = "prixTotal"+Id+"";

db.comorder.update(ligne, {
nomTable: "0",
nomPrix: "0"
});
```
Can you help me about this ? Many thanks :)
Xavier

**Comment by LeFrach** [comment]
It must be simple if nobody answers :)
I will found it by myself, I have understand the message :)

**Comment by dfahlander** [comment]
Sorry for not answering but by your example code  I'm not sure I understood your question. If I only listen to your text and not your sample, you want to create tables whose names are dynamically defined.  You can create an empty javascript object and dynamically assign properties to it and then send it to version ().stores().

**Comment by LeFrach** [comment]
Hello, 

I have already create my tables, quantite0 and quantite1.
I want to update values but I want to know if  in my sample nomTable and nomPrix can be a variable ?

For example : 

db.comorder.update(ligne, {
**"nomTable"+var**: "10",
**"nomPrix"+var**: "5"
});

What is the good syntax to reach this goal ?

**Comment by dfahlander** [comment]
Ok, so what is `db.comorder` then? What table is "comorder"?

What is ligne? What does "10" and "5" represent?

**Comment by dfahlander** [comment]
Maybe I could give you some links that might help?

[db.table()](http://dexie.org/docs/Dexie/Dexie.table()) is the method to use to get a table by name. Maybe you should use it to get your [Table](http://dexie.org/docs/Table/Table) instance:

```js
var table = db.table("nomTable"+var);
```

Then to update an item in that table, use [Table.put()](http://dexie.org/docs/Table/Table.put())

```js
table.put(updatedObject[, id]);
```

If you just want to update a certain property, use [Table.update()](http://dexie.org/docs/Table/Table.update())

```js
table.update(id, {propToUpdate: newValue});
```

Not that all these methods returns a Promise to inspect for the results.

**Comment by LeFrach** [comment]
I realize that the words I used are wrong :( I am very sorry about that :)

If I take your last sample : table.update(id, {propToUpdate: newValue});

It is the property "propToUpdate" itself  that I want to variabilise like this : 

My real property's name is "quantite1"

```
var one = 1;

var quantite = "quantite";					
var test = quantite+one; // test = quantite1

table.update(id, {test: newValue});
```

The result is :

![exemple](https://cloud.githubusercontent.com/assets/25138916/23896421/a9c117ba-08a9-11e7-99c7-3c91f1e0d4eb.png)

Property "test" is created, but I want update property "quantite1" :)

I dont want you to loose your time, I'm embarrassed :)

**Comment by LeFrach** [comment]
I reach the goal by multiple if ... else if ...

```
if (dataPrix == "prix0") {
dbc.commande.update(idLigneCommande, {
prixTotal0: "" + calcul + "",
quantite0: "" + quantite + ""
});
} else if (dataPrix == "prix1") {
dbc.commande.update(idLigneCommande, {
prixTotal1: "" + calcul + "",
quantite1: "" + quantite + ""
});
} 			
```
