### ISSUE TITLE
Hook to operation completion

### ISSUE THREAD

**Issue by jampekka** [dfahlander/Dexie.js#49]
I may be understanding something wrong, but I can't seem to find a clean way to hook into database modification operations (at least "creating", "deleting") so that I could easily get called back when the operation/transaction has been completed. Ie if I read the database during the creating/deleting or even creating.onsuccess/deleting.onsuccess, the database is still in the state that it was prior to the modification. If there's a "canonical" way on how it should be done, a hint in the documentation of the hooks would be great.

The rationale for such a hook is that I want to decouple the parts changing the DB and displaying the DB by just reacting to the state changes of the database. This is probably quite a common use case.

**Comment by dfahlander** [comment]
Closing issue
