### ISSUE TITLE
Calling .reverse() changes length of query result to my page size limit

### ISSUE THREAD

**Issue by marko911** [dfahlander/Dexie.js#492]
I've been banging my head over this and I have no idea why this is happening but in my code : 

``` this.db.transaction('r', this.db.partners, function () {
     this.currentQuery = Dexie.currentTransaction;
            var queryResult =self.db.partners;
            if (order === 'desc') {
              queryResult = queryResult.reverse();
            }
```

On a regular query where order ==='asc' , my queryResult returns 128 items, as soon as I reverse the order aka set order to 'desc', the queryResult returns 10 items, precisely same number I set for my page size in the pagination part : 

``` return queryResult
                .offset((pageNumber - 1) * pageSize)
                .limit(pageSize)
                .toArray()
```

I confirmed this by changing page size to 17. Same thing, reversed the order and queryResult returned 17 items. Why does it do this?

**Comment by dfahlander** [comment]
limit(N) means that it will limit the number of results to maximum N records. So basically if you have a pageSize of 10, call limit(10), you should expect only 10 records in the result.

However, it sounds very strange that you would get 128 items just because not calling reverse().

**Comment by marko911** [comment]
I limit the returned query result to say 10. But my count is 128. When I just do a reverse after this, my count becomes 10. Just to clarify that part.

**Comment by dfahlander** [comment]
Can you post the entire code?

**Comment by dfahlander** [comment]
I mean post a code that reproduces it: both with and without reverse()

**Comment by marko911** [comment]
```
 query: function (searchString, order, pageSize, pageNumber) {
          var self = this;
          if (this.currentQuery) {
            this.currentQuery.abort();
          }
          this.db.transaction('r', this.db.partners, function () {
            this.currentQuery = Dexie.currentTransaction;
            var queryResult =self.db.partners;
            if (order === 'desc') {
              queryResult = queryResult.reverse();
            }
            if (!_.isEmpty(searchString)) {
              queryResult = queryResult.filter(function (partner) {
                return _.includes(partner.name.toLowerCase(), searchString.toLowerCase());
              });
            }
            Dexie.ignoreTransaction(function() {
              queryResult.count(function(count) {
                self._setTotalResults(count);
              });
            });
            return queryResult
                .offset((pageNumber - 1) * pageSize)
                .limit(pageSize)
                .toArray()

          }).then(function (result) {
            self._setFilteredPartners(result);
          }).catch(function (error) {
            console.error('Error querying partners: ', error);
          });
        }
```

**Comment by marko911** [comment]
Thats the function that gets called, the only difference betweeen a queryResult with count 128 and count 10 is the value of order.

**Comment by dfahlander** [comment]
Ok, it's because Dexie's Collection is not immutable and you are executing count() in parallell with setting a limit() onto the Collection. You can use [Collection.clone()](http://dexie.org/docs/Collection/Collection.clone()) to make it immutable.

Also, it's always a good thing to await all promises (also the count()) promise. Use Promise.all() to await the count() and the query() in parallell.

```js
{
    query: function (searchString, order, pageSize, pageNumber) {
          var self = this;
          this.db.transaction('r', this.db.partners, function () {
            var queryResult =self.db.partners;
            if (order === 'desc') {
              queryResult = queryResult.reverse();
            }
            if (!_.isEmpty(searchString)) {
              queryResult = queryResult.filter(function (partner) {
                return _.includes(partner.name.toLowerCase(), searchString.toLowerCase());
              });
            }
            return Dexie.Promise.all([
                queryResult.count(),
                // Use clone() as offset() and limit() otherwise mutates the same query that is counted
                queryResult.clone() 
                    .offset((pageNumber - 1) * pageSize)
                    .limit(pageSize)
                    .toArray()]);
          }).then(function (countAndResult) {
              self._setTotalResults(countAndResult[0]);
              self._setFilteredPartners(countAndResult[1]);
          }).catch(function (error) {
              console.error('Error querying partners: ', error);
          });
        }
}
```

**Comment by dfahlander** [comment]
True, db.table is a Table instance, while db.table.reverse() returns a Collection instance. [Table.reverse()](http://dexie.org/docs/Table/Table.reverse())

**Comment by dfahlander** [comment]
Seems all parts of your code only needs a Collection, so you could pass the Collection instead of the Table into your function to get less confusion.
