### ISSUE TITLE
Grunt giving problems with minimized file

### ISSUE THREAD

**Issue by martindiphoorn** [dfahlander/Dexie.js#50]
For my projects i'm using grunt to build all javascript into one large file. However when i use bower install dexie it will use the minified source.

```
"main": "dist/latest/Dexie.min.js",
```
I would like to suggest to change this line (bower.json) into the not minified version. 

My error when trying to build with grunt is:
```
Running "ngAnnotate:dist" (ngAnnotate) task
Generating ".tmp/concat/scripts/vendor.js" from ".tmp/concat/scripts/vendor.js"...ERROR
>> error: couldn't process source due to parse error
>> Line 43462: Unexpected token in
Warning: Task "ngAnnotate:dist" failed. Use --force to continue.
```

I have reproduced this error on an other dexie project.

**Comment by dfahlander** [comment]
This issue could be due to that the Dexie.min.js had a leading BOM in earlier versions which is removed since some versions now. Can I close this issue?

**Comment by martindiphoorn** [comment]
This seems to be fixed! thanks
