### ISSUE TITLE
What is preferred - Dexie.Promise.reject(e), Promise.reject(e) or throw e in nested transactions?

### ISSUE THREAD

**Issue by StabbarN** [dfahlander/Dexie.js#504]
Can you please clarify how to reject/throw in the safest way when using nested transactions in [Best Practices](http://dexie.org/docs/Tutorial/Best-Practices.html)?

After reading chapter 4 `Stick to Dexie.Promise and never use another Promises within transactions!` I thought that we should always reject failures by `Dexie.Promise.reject()` but then I read `An alternate way of rethrowing the error is to replace throw error; with return Promise.reject(error).` in chapter 6 which makes me confused. Why use `throw error;` in the example instead of `Dexie.Promise.reject()`?

Is `throw e` just as safe as `Dexie.Promise.reject(e)` in any nested transacation? If yes, how come `Promise.resolve(e)` is forbidden but `throw e` okay?

**Comment by dfahlander** [comment]
The docs may be a little ambivalent between Dexie 1.x and Dexie 2.x. In the latter, it is safe to use static functions from the global Promise - no need to stick to Dexie.Promise.reject(). Hope to release 2.0 stable soon. It's been around for quite a while.

If you throw an exception `throw e`, the resulting promise will reject - same effect as returning `Promise.reject(e)`. Returning Promise.resolve(e) from your then-handler is both unnescessary will not result in a rejection - instead, your main promise will just resolve with the error as value.

Should only rethrow errors if you have not fully handled it. Thus transaction will abort and resulting promise reject. If that is not desired, you can handle them and not rethrow. Transaction will commit and resulting promise resolve.

**Comment by dfahlander** [comment]
I checked the docs, and they're targeting 1.x still, so I corrected Promise.resolve() to Dexie.Promise.resolve() there. Thanks for noting it ;)

**Comment by magnus-staberg** [comment]
Thanks for your quick reply and an awesome lib. Looking forward to Dexie 2!

>The docs may be a little ambivalent between Dexie 1.x and Dexie 2.x. In the latter, it is safe to use static functions from the global Promise - no need to stick to Dexie.Promise.reject().

Hmm, okay, my interpretation of what you just said - In Dexie 1.x we shouldn't use static functions from the global Promise in any transaction. `throw e`, `Promise.resolve()` and `Promise.reject()` are equally unsafe.

> Returning Promise.resolve(e) from your then-handler is both unnescessary will not result in a rejection - instead, your main promise will just resolve with the error as value.

Yes, resolving with an error is ambiguous :).

**Comment by dfahlander** [comment]
Thanks! You can use dexie 2 already with

```
npm install dexie@next
```
or CDN
```html
<script src="https://unpk.com/dexie@2.0.0-beta.10"></script>
```
Almost everything (normal use) is backward compatible.
