### ISSUE TITLE
multiple unique constrain

### ISSUE THREAD

**Issue by ricking06** [dfahlander/Dexie.js#506]
```
var db_me = new Dexie("UI_LANGUAGE");
db_me.version(1).stores({
  languages: "++id,&code,title", 
  words: "++id,language_id,index_name,title"
});
```

I want `language_id` and `index_name` to be unique together as a pair. Is that possible in Dexie ? `&` makes them unique but individually not as  a pair.

**Comment by nponiros** [comment]
It sounds like you want to use a compound index (http://dexie.org/docs/Compound-Index). Check also the browser limitations on that page

**Comment by ricking06** [comment]
@nponiros but then when doing a where with only using `language_id` i get  `KeyPath language_id on object store words is not indexed`

**Comment by dfahlander** [comment]
You can index them both together and separate without having to use a new property

```js
db_me.version(1).stores({
  languages: "++id,&code,title", 
  words: `
    ++id,
    language_id,
    &[language_id+index_name],
    index_name, 
    title
    `;
});
```
