### ISSUE TITLE
"TS2304: Cannot find name 'Storage'" error when compiling a web worker written in TypeScript

### ISSUE THREAD

**Issue by sergkr** [dfahlander/Dexie.js#512]
I am trying to write a web worker in TypeScript that uses Dexie, but I'm running into a compilation error from dexie's use of the `Storage` type (which may not be available in web worker context).

To reproduce the issue:

```
npm init
npm install --save dexie
npm install --save-dev typescript
```

Note I'm using the following package versions:

```
npm ls
+-- dexie@1.5.1
`-- typescript@2.2.2
```

Then create a worker using TypeScript that imports dexie:

**worker.ts:**
```
import Dexie from 'dexie';
console.log('Hello from worker land!');
```

Now try to compile it using TypeScript, using the proper context for web workers:

```
tsc --lib es6,webworker worker.ts
```

Note this results in a compilation error:

```
node_modules/dexie/dist/dexie.d.ts(57,24): error TS2304: Cannot find name 'Storage'.
```

As far as I can tell, the `Storage` type refers to the [Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Storage) (session storage and local storage), which are not accessible from a web worker context, so it makes sense that it can't compile.

Short of dropping down to vanilla JavaScript for web workers, is there a workaround for this?

**Comment by nponiros** [comment]
If I remember correctly dexie does work in webworkers and this is just a compiler error. Since typescript can emit javascript even when there are compiler errors you could just ignore the error.
You could also just define `Storage` as a type to avoid the error or try to extend `--lib es6,webworker` to contain whatever d.ts file contains `Storage` (probably `dom`).

**Comment by dfahlander** [comment]
You could also try dexie@next (version 2.0-beta.10) with no dependence of localStorage

**Comment by sergkr** [comment]
I appreciate the help!

> Since typescript can emit javascript even when there are compiler errors you could just ignore the error.

Sure, that works, but obviously it's less than ideal. The build system for the project I'm hoping to use this for actually halts the build in case of compilation errors, though it's something I could disable (or just use pure JS for web workers instead, which I think I'll be going with for the time being).

> You could also just define Storage as a type to avoid the error

I'm still a bit new to TypeScript, but how do I do that? In my example, I tried putting this as the first line of worker.ts (before importing dexie), but it still gave me a compilation error:

```
declare var Storage: any;
```

Also tried:

```
interface Storage {}
```

But I was still getting the error in both cases. I'm wondering if I won't actually be able to fix this from my worker.ts file (short of messing with `dexie.d.ts` inside the module).

> or try to extend --lib es6,webworker to contain whatever d.ts file contains Storage (probably dom).

Well, if I add `dom`, then it complains about a bunch of duplicate declarations - I don't think you can use `dom` together with `webworker`, since they share a lot of types.

If I replace `webworker` with `dom`, then I run into other issues since there are global functions that have different call signatures between the DOM version and the web worker version. For example, `postMessage` can be called with a [single parameter](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage) when called from a web worker, but not in DOM. So if I have this in my web worker:

```
postMessage("This is a message from a web worker");
```

Trying to compile it with the `dom` lib results in:

```
error TS2346: Supplied parameters do not match any signature of call target.
```

> You could also try dexie@next (version 2.0-beta.10) with no dependence of localStorage

I tried it, but I'm running into the same compilation error (`Cannot find name 'Storage'`). Looking at the `dist/dexie.d.ts` file that ships with both dexie 1.5.1 and 2.0.0-beta.10, looks like they both have this block in there:

```
    static dependencies: {
        indexedDB: IDBFactory,
        IDBKeyRange: IDBKeyRange,
        localStorage?: Storage
    };
```

By the way, is there separate API documentation for Dexie 2, or is it pretty much identical to Dexie 1.5 so I can use the same docs?

**Comment by dfahlander** [comment]
@sergkr Sorry for late answer. I see. It's wrong that localStorage is part of dependencies in 2.0. Will remove it. Thanks for reporting.

To answer your question, the API docs are the same. Where there is a difference, the docs will tell point out the difference. Deprecated parts of the 1.x API is listed under http://dexie.org/docs/Deprecations.

**Comment by sergkr** [comment]
Thanks @dfahlander!
