### ISSUE TITLE
url is not always unique in _syncNodes

### ISSUE THREAD

**Issue by martindiphoorn** [dfahlander/Dexie.js#52]
In some race conditions it is possible that there will be created an seconde entry in the _syncNodes. This happend to me when i was firing an disconnect and a connect right after each other.

Example:
On the login page i tell that sync should be disconnected. However when running from an app it should take the saved credentials and perform an login.

``` javascript
db.syncable.disconnect(url);

// some more code

if (isCordovaApp) {
   // do login
  db.syncable.connect(provider,url);
}
```

This way i have seen more then one entry for the same url in the _syncNodes objectStore. I have fixed this in my code by changing the order and using the promises returned.

My biggest problem is that after running the resync it sometimes returns all the current object store contents as type 1 or type 3 to the backend in the next sync. When looking closely at it, i noticed that there where 2 sync connections instead off 1.

**Comment by nponiros** [comment]
@dfahlander does https://github.com/dfahlander/Dexie.js/pull/412 with the unique url index fix this issue? If yes maybe we can close it.

**Comment by dfahlander** [comment]
Yes. Thanks. And merry Christmas :)

**Comment by nponiros** [comment]
Thanks. Same to you
