### ISSUE TITLE
angular 2 unable to extend dexie

### ISSUE THREAD

**Issue by abdulkareemnalband** [dfahlander/Dexie.js#526]
I'm using `"dexie": "2.0.0-beta.10"` and extending my class as `export class appCache extends Dexie`
but this is thowing `type error` as `Uncaught TypeError: Object prototype may only be an Object or null: undefined`

I'm using `webpack` , `awesome-typscript-loader` plugin and `typescript@2.2.0` and have set `"moduleResolution": "node"`

I'm getting error from this call `extendStatics(d, b);` in complied javascript  where `d` is appCache and `b` is `undefined` 
I think it should be `Dexie` but it is not getting set

**Comment by abdulkareemnalband** [comment]
even manually creating `appCache` by `new appCache` throws same error but `new Dexie('db')` works

**Comment by nponiros** [comment]
Maybe a problem with your import or your config? There is an example here albeit a bit old https://github.com/dfahlander/Dexie.js/tree/master/samples/angular2.
This https://github.com/jsperts/workshop_unterlagen/tree/master/angular/examples/Redux example is newer and also works with extends.

**Comment by abdulkareemnalband** [comment]
Thanks for hint i was importing dexie by `import {Dexie} from 'dexie';`

It should be  `import Dexie from 'dexie';`  // no brackets

Thanks again I'm closing this issue now

**Comment by stombeur** [comment]
Hi, I also ran into this problem, maybe explicitly state in the docs that you have to use the default import? Or is this super-obvious?

**Comment by nponiros** [comment]
@stombeur I wouldn't call it super-obvious but all our examples (at least the ones I know of and definitely the ones in the README) use a default import. So if anyone misses that, I doubt that mentioning it somewhere in the docs would help much..

As far as I know all older libraries which were just global objects prior to ECMAScript modules are using a default export. So trying to use default import would be my first choice with dexie.
