### ISSUE TITLE
DataError: Data provided to an operation does not meet requirements. when trying to put

### ISSUE THREAD

**Issue by barrytam20** [dfahlander/Dexie.js#527]
Think I'm trying to do something relatively simple, where I have a wrapper on top of dexie. However, whenever I try to do a put, I am getting a 

_DataError: Data provided to an operation does not meet requirements._

Below is some code, is there anything that I am doing wrong?

  private items: Dexie.Table<Object, string>;
    
  constructor() {
    super('myDb');
    this.version(1).stores({
      items: 'key, value'
    });
  }

  public setItem(cacheKey: string, item: Object): Promise<boolean> {
    return new Promise( (resolve, reject) => {
      this.items.put(item, cacheKey).then( (message: string) => {

**Comment by dfahlander** [comment]
Ok, it's because when keys are "inbound" in your schema (which is the most common case), you "must not" specify the key argument to Table.put() since it is already included with the item.

Maybe what you really want is a non-inbound table where the items does not include the key. Then, define your schema like this:

```js
this.version(1).stores({
    items: '' // Basically leave an empty string here
});
``` 

Then to put stuff into it:

```ts
class X {
  ...
  setItem(cacheKey: string, item: any) : Promise<string> {
    // Side-note: When consuming Promise-based APIs, you never need
    // to wrap it in another Promise. Just return the promise you get. In this case
    // the return value is the same key as was given (a string)
    return this.items.put(item, cacheKey);
  }
}
```

If what you put into it, is an Object, and you want to index a certain property, but still keep it non-inbound:

```ts
this.version(2).stores({
    items: ', propToIndex1, propToIndex2' // Keep first entry empty for non-inbound keys
});

```

A typical use would then be:

```ts
{
  dummyQuery() {
    return this.items.where('propToIndex1').between(10,20, true, true)
      .toArray();
  }
}

**Comment by barrytam20** [comment]
This worked, thanks!!

**Comment by darkowic** [comment]
Thank you for this!
@dfahlander it would be nice to add this note in the `Table.put()` documentation :)

**Comment by dfahlander** [comment]
Indeed. The docs should clarify this better for both put, add, bulkPut and bulkAdd. The docs are open for editing by anyone. If one visits http://dexie.org/docs/Table/Table.put() with enough screen resolution (not mobile), there is an edit button that allows editing the page. In the background, you are forking the site and generating a pull request.

**Comment by levant-x** [comment]
Hi there! I have to comment this issue again as either there's a bug or docs are inconsistent. I'm using the lib ^3.0.3 with TS, following the instructions on the inline user-defined PK ([https://dexie.org/docs/Version/Version.stores()]) but it refuses to store any data with schema lacks a property named id. I do provide a PK, just not named id, and getting this DataError. Could someone explain it?

**Comment by dfahlander** [comment]
@levant-x You can specify [inbound](https://dexie.org/docs/inbound) or outbound PK. Inbound keys must exist on every object you put. In your case, you have probably used inbound keys named it 'id' when you declared your `version.stores(...)`. You decide whether you want then inbound or not and if so, the keyPath to that property (such as 'id' or 'nested.pk').
