### ISSUE TITLE
error when `add` data on newest Google Chrome 58.0.3029.96

### ISSUE THREAD

**Issue by astronaut1712** [dfahlander/Dexie.js#528]
I updated newest version of Google Chrome (58.0.3029.96) and face this error. I tried with old version, it worked fine.
```
let db = new Dexie("example");
...
db.table('users').add({name: "Anh Tuan", login: "tuanna"});

-> "Error
    at getErrorWithStack (file:///.../dist/bundle.js:17084:12)
    at new DexieError (file:///.../dist/bundle.js:17213:19)
    at IDBTransaction.<anonymous> (file:///.../dist/bundle.js:19673:47)
    at IDBTransaction.<anonymous> (file:///.../dist/bundle.js:17940:23)"
```
I tried with sample and it raised the same error.
http://rawgit.com/dfahlander/Dexie.js/demo/samples/react/build/

**Comment by dfahlander** [comment]
I tried to run http://rawgit.com/dfahlander/Dexie.js/demo/samples/react/build/ from my Chrome (Version 58.0.3029.96 (64-bit)) and for me it works as expected.

**Comment by dfahlander** [comment]
What it might be, is if Chromium has an migration bug, that is, if the database was defined on version < 58 and getting migrated to Chrome 58, the bug appears.

As Chrome 58 adds IndexedDB 2.0 support, it wouldn't be strange if they are facing migration issues as new types suddenly regards valid as keys (binary keys - array buffers and typed arrays). 

Anyone else experience issues with Chrome 58?

**Comment by astronaut1712** [comment]
I ran on Chrome 58 on Ubuntu 16.04.

**Comment by astronaut1712** [comment]
I found problem is from "Quota exceeded" when I enable debugging. But I don't know why my available storage is 2GB, it is fail. When I free space, It works fine. I don't know how Chrome calculates the quota for storage.
