### ISSUE TITLE
Resync problems

### ISSUE THREAD

**Issue by martindiphoorn** [dfahlander/Dexie.js#53]
As you know i have created an resync option in the folowing steps:

+ disconnect url
+ remove the tables we want to resync
+ delete url with: syncable.delete(url)
+ connect url

I have added an log line in every step to see that everything goes in the right order. And that goes  perfectly by using the promises of Dexie.

However since the last release the changes table is not cleaned right. Remember that delete just all entries? The current code deletes all changes entries before _syncNode.myrevision:
```
return db._changes.where("rev").below(oldestNode.myRevision).delete()
```
My problem is that step 2 (Removing the tables) will have an higher revision number. So all the deletes will be send to the server when connecting again!

This is not always the case, so i think it goes together with the multiple synchronisation issue.

**Comment by dfahlander** [comment]
Martin, did we fix this issue or is it still open?

**Comment by martindiphoorn** [comment]
We have stopped using the sync as we had too many issues with it.

The issues we experienced where:
- Duplicate synchronisation sessions
- Sync stops after restarting off app
- Sync starts when not started
- Problems with trying to create a resync
