### ISSUE TITLE
get().then issue in IE

### ISSUE THREAD

**Issue by startovernow** [dfahlander/Dexie.js#531]
Hello,

The following code works correctly in Chrome ($EndDate displayed as "07/012017"), but in IE 11/Edge, the breakpoint inside "**then**" never get hit, so the moment format function is not called and $EndDate displayed as "7/1/2017 12:00:00 AM".

The EndDate is in JSON date format; "/Date(1494824400000)/"

Any help greatly appreciated!

![image](https://cloud.githubusercontent.com/assets/18681747/25762109/186d795c-31a3-11e7-976b-e8d7d836596f.png)

**Comment by dfahlander** [comment]
Hard to find the cause of your issue based on this info only. Consider writing down a repro that seeds the db from scratch before running that query. Chances are you have different data in your ie browser from what you have in the chrome browser. It seems strange though that the 'then' callback never get hit. If you also catch the promise, you'll see if it fails. IE does for example not support compound primary keys, so if you've defined such, this query would fail already within the implicit call to db.open(). Again, catch the returned promise, or watch your console for unhandled rejections to detect that.

**Comment by startovernow** [comment]
Thanks much! You are correct on having different data., I changed schema in chrome but forgot to do it in IE....
Again, thank you!
