### ISSUE TITLE
Collection.filter vs Array.filter

### ISSUE THREAD

**Issue by plaxdan** [dfahlander/Dexie.js#539]
We are trying to optimize our use of Dexie for a large IndexedDB database (can easily contain around a million records) which powers our offline SPA. One thing we noticed is that filtering records using `Collection.filter` is much slower than just performing the filter after `Collection.toArray` has been called.

[This codepen](http://codepen.io/plaxdan/pen/pPqEGr?editors=0010) shows a simple example where filtering using Dexie is about half as fast as with the array. Below are the results on my Mac with `Chrome Version 58.0.3029.110 (64-bit)`. In our application, there is around a 10x difference.

![image](https://cloud.githubusercontent.com/assets/382348/26325767/7d69d29c-3ef5-11e7-8ff7-e0410940108b.png)

Is this normal? Our assumption was that performing the filter using the Dexie API would be faster. You will notice that changing the filter function to something super simple like: `collection.filter(() => true)` still results in the slowdown.

**Comment by nifgraup** [comment]
The two examples are taking different code path in toArray, https://github.com/dfahlander/Dexie.js/blob/master/src/Dexie.js#L2209.

**Comment by dfahlander** [comment]
Collection.toArray () uses getAll() whenever possible. getAll() is hard to beat since it only results in a single callback instead of one per database record. However it might consume more memory.

**Comment by plaxdan** [comment]
Thanks for the updates. We're exploring options for adding more indexes to the tables in question.
