### ISSUE TITLE
startsWith on compound index?

### ISSUE THREAD

**Issue by plaxdan** [dfahlander/Dexie.js#544]
Is there no way to perform a [`WhereClause.startsWith()`](http://dexie.org/docs/WhereClause/WhereClause.startsWith().html) on a compound index? The following snippets are [from this fiddle](https://jsfiddle.net/x5rf3qzd/1/). 
 
```javascript
db.version(1).stores({
	friends: '++id,first,last,[first+last],age'
});

//...

db.friends.add({first: "Mickey", last: "Mouse", age: 42});

//...

// Expected the following to return Mickey Mouse..but it returns nothing.
return db.friends
	.where('[first+last]')
	.startsWith('M')
	.toArray();
```

The following variants were also tried, but to no avail:

```javascript
// Pass an array of items - this behavior is implied by 
// http://dexie.org/docs/Compound-Index.html
return db.friends
	.where('[first+last]')
	.startsWith(['M', 'M'])
	.toArray();

// Use startsWithAnyOf
return db.friends
	.where('[first+last]')
	.startsWithAnyOf(['M', 'M'])
	.toArray();
```

**Comment by dfahlander** [comment]
No, but startsWith() is actually just sugar for between(prefixString, prefixString + '\uffff').
So lets say you want to search for documents where type="email" and name starts with "a", you could express it like

```js
db.documents.where('[type+name]').between(
    ["email", "a"],
    ["email", "a\uffff"])
```
...assuming you've indexed "[type+name]".

**Comment by edotassi** [comment]
@dfahlander this should be added in the docs 😄
