### ISSUE TITLE
Typescript error from dexie.d.ts file

### ISSUE THREAD

**Issue by wjheesen** [dfahlander/Dexie.js#547]
Declaration `readonly [Symbol.toStringTag]: "Promise";` causes the following error:

`TypeScript error: node_modules/dexie/dist/dexie.d.ts(134,26): Error TS2339: Property 'toStringTag' does not exist on type 'SymbolConstructor'.`

 My compiler options in tsconfig:

```JSON
"compilerOptions": {
  "module": "commonjs",
  "moduleResolution": "node",
  "noEmitOnError": true,
  "target": "es5"
}
```

**Comment by nponiros** [comment]
Symbol belongs to es6 but you are using target es5. Try adding
```
"lib": [
      "es2016",
      "dom"
    ]
```
To your tsconfig compilerOptions
