### ISSUE TITLE
"Not a valid key" error on Android 4.1.2

### ISSUE THREAD

**Issue by bboydflo** [dfahlander/Dexie.js#549]
Hi, I have updated Dexie to v2.0.0-beta.11 and also indexedbshim to version 3.0.1. I get this error when I try to delete a row by id. I am using Dexie like: 
`this.db[table].where({id: id}).delete();`

It used to work fine when using an older Dexie (v. 1.5.7) and indexedbshim v.2.2.1.

**Comment by dfahlander** [comment]
Ok. thanks for letting me know. Would you have a chance to track it down a bit?
* Exception stack trace (using Dexie.debug="dexie")
* Have you checked that typeof id === "number" || typeof id === "string"

**Comment by bboydflo** [comment]
The id is a number. It seems it is not a Dexie error, there are no errors thrown by Dexie. It is most probably an indexeddbshim error. It works fine in latest chrome without the shim. I will try to seek an answer on indexeddbshim repo. 

Thanks!

**Comment by dfahlander** [comment]
Florin, there might be the case that Dexie beta.11 doesn't pick up the shim by itself anymore, see https://github.com/dfahlander/Dexie.js/releases/tag/v2.0.0-beta.11 under "Breaking change"

**Comment by bboydflo** [comment]
I have setup a test page for the indexeddb functionality I need in my app and currently only testing on Android 4.1.2 WebView to make sure that the IndexedDBShim + latest Dexie works.

The shim is only loaded when needed (!Modernizr.indexedb || iosVersion <9 ) before Dexie.

With the latest IndexedDBShim (3.0.1) I cannot get these tests to pass, not even the first one which is opening a database connection. I keep getting "DOM Exception 18" and if I test something else the app hangs because I do not get any response or error back. 

I have then tried to use latest Dexie + an older version of IndexedDBShim (2.1.1) and I almost all the tests to pass besides deleting a row by id. There I get a Dexie error: "Not a valid key" (see first comment). In this setup the same "SECURITY_ERR: DOM Exception 18" is caught by the IndexedDBShim. 

I have made some research and this error can be related with opening an WebSQL database from 'file:///' but I have the correct setup, because it has worked before (Dexie 1.5.7 + IndexedDBShim 2.1.1). 

To resume: I cannot get latest Dexie (v2.0.0-beta.11) to work with IndexedDBShim 2.1.1.

**Comment by dfahlander** [comment]
Ok. Did you try whether calling [shimIndexedDB.__useShim();](https://www.npmjs.com/package/indexeddbshim#shimindexeddb__useshim) before including dexie makes it work? (as suggesed in beta11 release notes?)

**Comment by bboydflo** [comment]
I have tried many combinations. 

When I use  IndexedDBShim 2.1.1 the DOM Exception 18 gets caught by the shim and I get only one test to fail, but when I update the shim Dexie will catch the same error and then hangs. 

The best combination that almost worked was something like this:
`
<script type="text/javascript">
if (!Modernizr.indexeddb || iosVersion <9) {
  // load indexeddb shim 2.1.1
  document.write('<script src="file:///android_asset/dist/js/indexeddbshim.min.js">\x3C/script>');
} 
</script>
`
Using 'shimIndexedDB.__useShim()' in this case won't help Dexie to pass this delete row by id error. 

When I use IndexedDBShim 3.0.1 the DOMException 18 gets caught by latest Dexie and none of the tests will pass.

Using 'shimIndexedDB.__useShim()' in this case won't help Dexie either.

**Comment by bboydflo** [comment]
Sorry to bother that much but now latest Dexie passes all the tests on Android WebView 4.1.2 including latest IndexedDBShim (3.0.1). There was already a database created with IndexedDBShim version 2.1.1. 

It is clearly stated on IndexedDBShim repo that: "Besides some backward-breaking (though standard-compliant) behavioral fixes (see CHANGES), there are changes coming in version 3 which will also unfortunately cause data stored under version 2 to break. We are not able to provide you with an automated upgrade path, so you will need to either stick with version 2 or migrate users' data yourself to the new SQL storage format (whose changes are considerable; CHANGES also lists these breaking database format changes)."

Thanks very much for the support!
