### ISSUE TITLE
Remove the BOM

### ISSUE THREAD

**Issue by miracle2k** [dfahlander/Dexie.js#55]
Using the NPM package, I end up with a BOM in the middle of my JS build output. While browserify possibly removes the BOM (https://github.com/substack/node-browserify/issues/313), unless there was a regression, I am using es6ify and reactify transforms that might mess with this.

Its my understanding that a BOM is not recommended in UTF-8, and it would be a lot painless, if removed.

**Comment by dfahlander** [comment]
Thanks! I'll might have to check through the comments and remove swedish characters that may have made the editor add the BOM.
