### ISSUE TITLE
Possibly out of date documentation on updating hook

### ISSUE THREAD

**Issue by cfilipov** [dfahlander/Dexie.js#550]
The [`Table.hook('updating')`](http://dexie.org/docs/Table/Table.hook('updating').html) documentation states (emphasis added):

> If it is desired to know whether the modification will succeed or not, use **this.onsuccess = function(updatedObj){}** or this.onerror = function(error){} to be called after the object has been updated.

The bolded part leads one to believe that an updated object will be passed to the `onsuccess` handler, however, that does not appear to be the case. I am using version `2.0.0-beta.10`, and my `onsuccess` method is receiving what appears to be the primary key of the updated object. Furthermore, the [unit test](https://github.com/dfahlander/Dexie.js/blob/9676f85b20912d1d24ba1e7bef136ed6bc319af4/test/tests-crud-hooks.js#L155) for the updating hook doesn't expect an input to`onsuccess` at all.

As a workaround I can apply the mods on a copy of the object myself, but the updated object in `onsuccess` would be very useful.

**Comment by dfahlander** [comment]
Thanks for this input. Putting it in backlog for making the code work as documented and add/update unit tests to verify it.
