### ISSUE TITLE
Hooks and context

### ISSUE THREAD

**Issue by acidhax** [dfahlander/Dexie.js#56]
I found an issue in how Dexie deals with contexts within hooks.
Trying to use this code:

`
db.table.hook("creating", this._onCreate.bind(this, "Series"));
`
It causes the _onCreate function to lose access to the context needed for <context>.onsuccess. This is causing me to create an anonymous function to call my own function.

    var self = this;
    db.season.hook("creating", function (primKey, obj, trans) {
	    this.onsuccess = self._onCreate.bind(self, "Season", primKey, obj, trans)
    });

**Comment by dfahlander** [comment]
It's not an issue but you may have opinions on the impact of using bind(). Your workaround seems doable though :)

**Comment by acidhax** [comment]
Hooking into an event should allow me to pass it on to another instance, with no knowledge of Dexie. That's the point of an event. Events shouldn't lead me to execute more Dexie core code. There's a disconnect in using an event system, and then overriding an optional object property.

**Comment by dfahlander** [comment]
I'll take your feedback into account into the rewrite in next version. I will try to keep it backward compatible in any case.

Thanks,
David

**Comment by dfahlander** [comment]
Closing issue.
