### ISSUE TITLE
SecurityError on Safari

### ISSUE THREAD

**Issue by gigamorph** [dfahlander/Dexie.js#565]
Hello,

I have an application that uses Dexie and it is failing on Safari (the desktop version). I'm pretty sure it worked before but recently found out about it by examining user complaints. 

The fiddle from the Dexie homepage https://jsfiddle.net/dfahlander/3tf5r0cu/ also produces error in the Log: 
```
Using Dexie v1.5.1
SeurityError - This browser doesn't like fiddling with indexedDB.
Go run some samples instead at: https://github.com/dfahlander/Dexie.js/wiki/Samples
```

I also put the example code from the GitHub README (which is mostly the same code) to my CodePen: https://codepen.io/gmorph/pen/gxObEz?editors=1001 and you can (hopefully) see the alert popup says 

```
Error: OpenFailedError: SecurityError IDBFactory.open() called in an invalid security context
```

It works fine on Chrome, FireFox, MS Edge (in VirtualBox), and Opera instances that I have on my MacBook Pro, but only Safari (Version 10.1.2 (11603.3.8)) is failing on me.

Hopefully it will ring a bell with the core developers :) Thank you.

**Comment by nponiros** [comment]
Hey there, I don't know this error but I can try to reproduce it tomorrow. Have you tested with dexie v2 also? Could it be an issue with codepen and jsfiddle? Maybe those are running the code in an iframe which causes issues?

**Comment by gigamorph** [comment]
My apologies. While creating the CodePen example I totally forgot about the original problem. Yes, I think there's a (probably known) problem of running the code with codepen and jsfiddle, I would also appreciate explanation on that problem, but that wasn't really what made me come here. After some fiddling the problem seems to be that I was trying to save an object that is not serializable (with a link to a class instance with functions and possibly some recursive data), and that might have caused the error. Which now leaves me wondering, how does it work on other browsers then?

**Comment by nponiros** [comment]
Could it be that other browsers failed silently? It might also be a browser bug, not the first time browsers implement things differently.

**Comment by dfahlander** [comment]
I am not 100% sure, but I've always supposed the problem has been that Safari forbids to access IDB from an iframe.

**Comment by sechel** [comment]
Thats right, it such a problem that we need to open a separate tab just to support safari. Extremely ugly.

**Comment by lsentkiewicz** [comment]
I also have a problem with Safari.
I have a webworker with following code (inside a class):
```js
    this.db = new Dexie('db');
    this.db.version(1).stores({
      events: 'serialNumber',
    });
    this.db.events.toArray();
```
See video http://take.ms/MRml4 The page is totally broken.
It works if I comment out ` this.db.events.toArray();`. I can't see any error in the console because the page is reloading.
I am testing ^1.5.1, but I get the same result on v2.
Safari: Version 10.1.2 (12603.3.8)

**Comment by lsentkiewicz** [comment]
Here is a quick example where you can reproduce the bug.
index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <script type="text/javascript">

      var w = new Worker("worker.js");
      
        
    </script>
</head>
<body>
aaa
</body>
</html>
```

worker.js
```js
self.importScripts('https://unpkg.com/dexie@latest/dist/dexie.js');

var db = new Dexie('db');
db.version(1).stores({
  items: 'id',
});
db.items.toArray();

console.log('worker started')
```
Video: http://take.ms/Qdeyc

**Comment by lsentkiewicz** [comment]
@dfahlander
Any chance that you can look at this? Is it a bug in Safari or in dexie.js?

**Comment by dfahlander** [comment]
Hi, I've reproduced it and it is an issue when using IDBObjectStore.getAll(). Could be the following Safari bug: https://bugs.webkit.org/show_bug.cgi?id=175609

A workaround is to apply a filter:

db.items.filter(x => true).toArray()

I think we would have to add another special treatment for Safari to work around this internally in Dexie.

**Comment by dfahlander** [comment]
This issue is actually 2 separate issues:
1. Safari doesn't like indexedDB from iframes - not a Dexie issue.
2. Safari bugs out when calling IDBObjectStore.getAll() from a worker. We've done a workaround for this in 2.0.0 release. This workaround shut down getAll() feature on too many browsers though, so it is being updated to be more fine grained - see discussion on PR #579.

Anyway, both these issues are solved, so I close this.

**Comment by sechel** [comment]
I believe safari doesn't like indexeddb from an iframe of a third party origin (producing invalid security context errors). Same origin iframes seem to work.

**Comment by OKNoah** [comment]
Yeah, I think this is still an issue in Safari if the iFrame is cross-origin. Maybe it's a good security precaution, but makes some of my development difficult/impossible.
