### ISSUE TITLE
Impossible to modify an object through an asynchronous action in a hook

### ISSUE THREAD

**Issue by madarche** [dfahlander/Dexie.js#57]
Hello,

First, thank you for Dexie.js, this is really a nice way to use IndexedDB!

At the moment it's possible to exec an asynchronous action in the table hooks (for example with a promise). But if a hook modifies the object (obj), it is actually not persisted because when the object is later fetched it bears no trace of the modification.

    db.some_store.hook('creating', function(primKey, obj, trans) {
        execAPromise();
    });

Could there be a way to tell to wait until the async action is finalized?

Maybe something like the following:

    db.some_store.hook('creating', function(primKey, obj, trans, done) {
        execAPromise().then(done);
    });

But it's not Promise-oriented at all :-(

Any ideas about it?

Thank you

**Comment by madarche** [comment]
I know the `creating` hook can have return value but it's use to possibly generate an ID.

So I'm sure you ran into this problem before. So there should be a solution :-)

Cheers,

**Comment by dfahlander** [comment]
Related to #14. There is a solution on its way. This is a limitation, yes! The change is a part of a larger change with a redesign of the internal chaining of filters to be asynchronic and then make the hooks take advantage of that.

You may modify the obj but in current version, that has to be done in the same call to have any effect.

Kind regards,
David

**Comment by madarche** [comment]
Hello David,

Yes this is definitely a duplicate of #14. Maybe the title of #14 could be edited to reflect the generic nature of the limitation. This is why I've missed it when I checked for duplicates.

Best regards
