### ISSUE TITLE
Set keyPath/primary Key

### ISSUE THREAD

**Issue by davidychow87** [dfahlander/Dexie.js#575]
Hi, I'm not very familiar with indexeddb, but it seems like it is possible to change the primary key (keypath?) to be something other than an auto-incrementing integer (a string). How is this done with Dexie (and how do you specify the primary key when a row is added? Thanks!

**Comment by nponiros** [comment]
If you want to define a store which has a custom key then just don't use `++` during the store definition.
Docs for store definition http://dexie.org/docs/Version/Version.stores().html .

Note that you can define the primary key during store definition but you cannot change the primary key of an existing store.

To specify the key during add you could just pass an object containing your data and one property containing the key. Assuming the name of the key is `id` you could do something like this:

```
var toAdd = {
  id: 'myID',
  data: 'Foo bar',
  moreData: 'Foo bar2'
};

table.add(toAdd);
```

Docs for table.add() http://dexie.org/docs/Table/Table.add().html

**Comment by davidychow87** [comment]
Thanks for the quick reply. Now I am having a little trouble indexing. I have a store defined as:

db.version(1).stores({
     series: "++id,name"
})

I thought that this would make 'name' to be index1, however, the following doesn't work:

db.series.add({
     name: 'John'
})
     .then(() => {
          return db.series.where('name').equals('John').toArray();
     })
     .then(name => {
          console.log(name)
     })

I get the following error: 
Unhandled rejection: SchemaError: KeyPath name on object store series is not indexed

How do I index name? Thanks again.

**Comment by davidychow87** [comment]
Actually, it seems that clearing the storage and restarting the server has solved the issue. Thanks.
