### ISSUE TITLE
Error: NotFoundError: DOM IDBDatabase Exception 8 on iOS8

### ISSUE THREAD

**Issue by aaron-schmidt** [dfahlander/Dexie.js#58]
Safari on iPad Air (**iOS 8.1.2**)

Dexie.open() results in the error "**Error: NotFoundError: DOM IDBDatabase Exception 8**"

Example:

    <script src='/js/vendor/Dexie.js'></script>
    <script>
    	var idb = new Dexie('hockey');
    	idb.version(1)
            .stores({
            	players: '&key, teamId, nationality'
            });
    	idb.open()
            .catch(function(error) {
            	alert(error.toString()); // Error: NotFoundError: DOM IDBDatabase Exception 8
            });
    </script>

IndexedDB is supported in iOS8. If a test page is created using the following example: http://www.raymondcamden.com/2014/09/25/IndexedDB-on-iOS-8-Broken-Bad ... this will function correctly, with IndexedDB successfully opening and storing data.

Happy to provide further details if required.

**Comment by tszpinda** [comment]
it maybe related to this safari issue:

https://bugs.webkit.org/show_bug.cgi?id=136937

and its caused by: 
Dexie (line 537):
adjustToExistingIndexNames(globalSchema, idbdb.transaction(idbdb.objectStoreNames, READONLY));

**Comment by aaron-schmidt** [comment]
As outlined in https://bugs.webkit.org/show_bug.cgi?id=136937 this is only an issue on iOS if multiple stores are passed to idbdb.transaction().

The following change to Dexie.js will remove the error on iOS *but only* if the database contains a **single store**:

Change (~ line 531):

    else if (idbdb.objectStoreNames.length > 0)
        adjustToExistingIndexNames(globalSchema, idbdb.transaction(idbdb.objectStoreNames, READONLY));

To:

    else if (idbdb.objectStoreNames.length > 0) {
        var storeNamesString = idbdb.objectStoreNames.length > 1 ? idbdb.objectStoreNames : idbdb.objectStoreNames.item();
        adjustToExistingIndexNames(globalSchema, idbdb.transaction(storeNamesString, READONLY));
    }

Note that using an array that contains a single value will also work:

    else if (idbdb.objectStoreNames.length > 0) {
        var storeNamesString = idbdb.objectStoreNames.length > 1 ? idbdb.objectStoreNames : [idbdb.objectStoreNames.item()];
        adjustToExistingIndexNames(globalSchema, idbdb.transaction(storeNamesString, READONLY));
    }

**Comment by nolanlawson** [comment]
Seems like you've found a new IndexedDB bug in iOS 8. Could you provide a live example and file a bug on WebKit? :)

**Comment by nolanlawson** [comment]
Oh nevermind, I see that this IS the same bug. What you're saying is that there's a workaround. (If there's only one store, open using `'databasename'` rather than `['databasename']`.)

I made a live test case anyway, just for kicks: http://bl.ocks.org/nolanlawson/1d407ac013d92bf998cb

**Comment by dfahlander** [comment]
Solved. See comments on 
[this commit](https://github.com/dfahlander/Dexie.js/commit/79790227dde989fc4ce6d99cfcb50d373a4a6ec5)
