### ISSUE TITLE
How to access existing database?

### ISSUE THREAD

**Issue by OscarRobertRodriguez** [dfahlander/Dexie.js#582]
Okay, this is probably a noob question but I was wondering how can I access an existing database that I created with a previous function. I'm not sure if the code I got from the docs works. I try using this code in the new function : 

```javascript
function loadHtml() {
 new Dexie('albums').open().then(function (db) {
 	// how do i access the vaules from here. if i console.log(db) if just gives me db object
})
.catch('NoSuchDatabaseError', function(e) {
    // Database with that name did not exist
    console.error ("Database not found");
}); 

};
```

I'm trying to access this data so that I can run through it with a for loop to pass it to handlebars and display the HTML. Any help would be appreciated.

**Comment by OscarRobertRodriguez** [comment]
Still not sure what I'm doing.

**Comment by dfahlander** [comment]
Typically you should rather follow the most basic samples from dexie.org to declare a database, no matter whether you are creating it for the first time, or accessing an already existing database:

    var db = new Dexie('MyDatabase');

    // Define a schema
    db.version(1).stores({
        friends: 'name, age'
    });

Dexie will take care of creating the DB in case it doesnt exist, or just open it as is if it exists.

**Comment by OscarRobertRodriguez** [comment]
thanks
