### ISSUE TITLE
Type 'Dexie.Promise<any>' is not assignable to type 'Promise<any>'

### ISSUE THREAD

**Issue by IAmPicard** [dfahlander/Dexie.js#586]
Hi,

I'm trying to use Dexie in a TypeScript electron app, and I'm seeing this error message when attempting to chain Dexie queries with normal Promises:

```
error TS2322: Type 'Dexie.Promise<void>' is not assignable to type 'Promise<void>'.
Types of property 'then' are incompatible.
Type '{ <U>(onFulfilled: (value: void) => Thenable<U>, onRejected: (error: any) => Thenable<U>): Promis...' is not assignable to type '<TResult1 = void, TResult2 = never>(onfulfilled?: ((value: void) => TResult1 | PromiseLike<TResul...'.
Type 'Dexie.Promise<any>' is not assignable to type 'Promise<any>'.
Property '[Symbol.toStringTag]' is missing in type 'Promise<any>'.
```

FWIW, I'm using "es2015" as compilerOptions.target and I have "latest" for both dexie (1.5.1) and typescript (2.5.2).

Any tips?

Thank you!

PS I'm still fairly new to TypeScript / JS so I apologize if I'm missing something obvious.

**Comment by dfahlander** [comment]
Try with dexie@2.0.0-rc.1 Please reply if it solves the problem or not

**Comment by IAmPicard** [comment]
Yes, updating to 2.0.0-rc1 fixed the problem. Thank you!
