### ISSUE TITLE
Question: is it a bad idea to use the promise implementation from dexie?

### ISSUE THREAD

**Issue by bboydflo** [dfahlander/Dexie.js#588]
Hi, I've checked the docs and since `dexie` has it's own `Promise` polyfill I want to use that throughout my app instead of yet another promise polyfill. It seems that it's not a good idea. I keep getting this kind of errors: `TypeError: Method Promise.prototype.then called on incompatible receiver`. 

Can be that dexie's Promise implementation should only be used by dexie?

**Comment by dfahlander** [comment]
I would not recommend using Dexie.Promise as a general Promise polyfill. I think it's better to use some tested polifyll like https://github.com/taylorhakes/promise-polyfill and make sure it is set globally on window object + only do that if typeof Promise === 'undefined' or !window.Promise. Nowadays this is only needed for really old browsers like IE.

Also, in Dexie 2.0 you will no longer need to care for using Dexie.Promise in your application code. It is now safe to use Promise.all(), Promise.race() and new Promise(...) within transaction zones as Dexie will patch the global Promise itself within its own transaction zones, but leave it native outside. Just make sure not to import Promise as a module  - polyfill window.Promise instead in page bootstrap if needed.

**Comment by bboydflo** [comment]
thank you. I chose rsvp.js and it works!
