### ISSUE TITLE
[License]The license are template and incomplete.

### ISSUE THREAD

**Issue by vankai** [dfahlander/Dexie.js#596]
https://github.com/dfahlander/Dexie.js/blob/a5fec1f36cdd764a98bf050c641363fab6321833/LICENSE#L189
Which year was 'yyyy'? 
(Of course I knew it was '2014'. 😂

**Comment by dfahlander** [comment]
Hmm. Think I need some guidance here. Looking at another apache-licensed software, cassandra, they have also kept the templated copyright: https://github.com/apache/cassandra/blob/trunk/LICENSE.txt

Somebody who knows whether one should remove the "APPENDIX: How to apply the Apache License to your work." or not? And whether to fill in the copyright owner and year?

**Comment by vankai** [comment]
Hmmm.It seems that the templated copyright doesn't matter so far. ☕️ 

I created several repositorise with different license on github, and only the MIT and the BSD(2-Clause) replaced  templated onwer with my account's name. What if my account's name is a fake name? Should I alter the fake name in the license file? However, the GPL and the MPL , both copyleft, contains none of these templates .

So, when you want to stress the ownership, just change it. For example, transfer this repository to another user or to an organization should leave the previous ownership infomation in the license.

I am afraid that taking these templated copyright for granted may cause some issues in the future, including these repos whose license are still templated.

**Comment by dfahlander** [comment]
Thanks a lot @vankai for bringing it up. Reading through [this guide](http://www.apache.org/dev/apply-license.html#new) from Apache, it seems that the file must be accompanied by a NOTICE file containing the copryight info, so need to fix that.
