### ISSUE TITLE
Well documented

### ISSUE THREAD

**Issue by Garito** [dfahlander/Dexie.js#597]
Hi!
I know this would sound bad but could you delete the Well documented feature from the homepage?
It is not true at all... by far... no way... not even close

**Comment by nponiros** [comment]
Thanks for the feedback. I guess it depends what you compare the docs with. Compared to the indexeddb docs, dexie is well documented (at least this was true some years ago).

Do you have any feedback on what we could improve? Is there to few information or is it not well structured?

**Comment by Garito** [comment]
I do:
EXAMPLES WITH CONTEXT!!!!!!!
There aren't to many examples... never. Imagine them as test cases
Context meaning you must provide a complete usable example not partial ones
The more context you give the better

For instance:
If you open a connection and you first use it for writting it will be opened as wr but if you first read it will be opened as w only (at least that's what I've deduced by myself)
So if you do table.each or table.toArray and then try to update or delete... it will fail
There are not single one example were you could see how to solve this issue when you need to read first then write
Perhaps I'm totally wrong, but that's the whole point: the documentation doesn't explain this

I can understand that documenting is hard but this library has as 2nd most important feature good documentation (not compared with anything)

**Comment by nponiros** [comment]
Yeah an example for each operation would be good.

Your example sounds like a confusion between a transaction and a direct operation on the store. Sounds like the docu might need some restructuring there.

Unfortunately improving the docs costs time (which I don't have till end of next year) and money and in the end @dfahlander will have to decide what to do.

If you have time and want too, feel free to improve the docs by sending a pull request to https://github.com/dfahlander/dexie.js-web

**Comment by Garito** [comment]
To help, first I must to understand it, don't you think so?

**Comment by nponiros** [comment]
You can learn by doing but you need time for that. I personaly often have to read the code to understand what is happening because some library is not (well) documented. But as I said you really need time and motivation for that.

For dexie I actually started by refactoring dexie syncable and fixed parts of the documentation and the examples (after also asking here to make sure I understood things right). But it did take like a week or so to finish..

**Comment by dfahlander** [comment]
@Garito I'm sorry you had bad experience with the docs. To my defence, I've always tried to be consistent in every sample, to write down the code from A to Z (from declaring a db instance to using it).  I think we got plenty of samples [here](http://dexie.org/docs/Samples.html), [here](http://dexie.org/docs/API-Reference.html#quick-reference) and in for most of the methods we have.

I've only got good reactions of the documentations so far, but I guess some negative reactions must come sooner or later, and here we have it ;) I hope we could turn it into an improvement of the docs for those places were you found it in lack of context.

Regarding your negative experience with [transaction](http://dexie.org/docs/Dexie/Dexie.transaction().html) modes, the documentation page of [Dexie.transaction()](http://dexie.org/docs/Dexie/Dexie.transaction().html) only lists the two modes there are in IndexedDB ("rw" (read/write) and "r" (read-only). There is no "w" (write-only) mode. And these are just the two modes supported by IndexedDB. I might misundestand what you meant though, so please correct me if I'm answering the wrong question.

**Comment by Garito** [comment]
Could you point me here to check a complete example (from new Dexie) of how to read all the records of a table, loop them and delete them one by one (my use case will update the server in the loop but there is no need to reflect that in the example)
So far, the examples I've found are incomplete (like those in the quick reference link you put here)

First thing I was learned in my computing carrer is not to obviate things and most part of the doc examples only ilustrate the command not how to prepare it

**Comment by Garito** [comment]
Sorry I've discovered ZangoDB
