### ISSUE TITLE
table clear

### ISSUE THREAD

**Issue by tszpinda** [dfahlander/Dexie.js#60]
Hi, first got to say its a pleasure to work with yours library.

I think there is a issue with clear method it returns error when used with bind method, example:

var db = new Dexie('cleartest');
        db.version(1).stores({
            foo: '&id',
            bar: '&id',
        });
        db.open();
        db.foo.clear().then(db.bar.clear).catch(alert);

it errors with:
"TypeError: undefined is not an object (evaluating 'this.hook')"

**Comment by dfahlander** [comment]
Thanks for apprechiating the library.

By looking at the code, I see that you are sending 'db.bar.clear' as a pure function argument, which will invalidate the 'this' reference. There is not chance for the clear() method to know which Table instance to work with. A corrected version of your test would be:

```js
        var db = new Dexie('cleartest');
        db.version(1).stores({
            foo: '&id',
            bar: '&id',
        });
        db.open();
        db.foo.clear().then(function() {
            return db.bar.clear();
        }).then(function() {
            alert("Successfully cleared foo and bar")
        }).catch(alert);
```

Did I get it right?

**Comment by tszpinda** [comment]
oh silly error, this works too:
db.foo.clear().then(db.bar.clear.bind(db.bar))

although not sure which one is easier to read

**Comment by dfahlander** [comment]
True. Your works identically. It also returns the promise from db.bar.clear so that your chain of promises is intact and the final then() or catch() will in include its operation.

A question of taste which one is the simplest...
