### ISSUE TITLE
Too many returns on where().equals()

### ISSUE THREAD

**Issue by modir** [dfahlander/Dexie.js#600]
I have in my application a dexie query where afterwards the code starts to run several times.

I wrote more details here: https://stackoverflow.com/questions/46941851/why-is-the-code-running-several-times-from-here-on

As I wrote I expect to get only one Collection and not many. At least according to the documentation it should be like this.

I tested it with dexie Version 2.0.1 and Firefox 56 and Chrome 62.

**Comment by dfahlander** [comment]
Thanks for reminding. I just answered the question on stackoverflow.

**Comment by modir** [comment]
Thanks.. I wrote a comment. Maybe you see something wrong in the fiddle.

**Comment by dfahlander** [comment]
Closing this issue as it was solved over phone. Thanks!
