### ISSUE TITLE
Removing `fake`, `doFakeAutocomplete`, etc

### ISSUE THREAD

**Issue by chrahunt** [dfahlander/Dexie.js#603]
Based on the comment [here](https://github.com/dfahlander/Dexie.js/issues/105#issuecomment-262737335), it seems like these variables and methods to facilitate auto-complete are useful only in a limited scope. They may make the code require a bit more effort to parse for would-be contributors. Can these be removed?

**Comment by nponiros** [comment]
Modern IDEs should be able to use typescript declaration files to enable autocompletion so I guess we could remove these.

**Comment by dfahlander** [comment]
Sure. All fake() code can absolutely be removed. Thanks!
