### ISSUE TITLE
Delete doesn't reduce the disk usage

### ISSUE THREAD

**Issue by benitogf** [dfahlander/Dexie.js#604]
Found that delete doesn't actually remove the data from disk, but it does remove the entries in db. Tested on chrome 61 using v2.0.1:

`await db.items.filter(function (item) {
      return keys.indexOf(item.id) !== -1
}).delete()`

Tried to replicate on a fiddle but the devtools don't capture the db there, and couldn't find a method to get the size of db as it's provided there.

**Comment by dfahlander** [comment]
I suppose chromium's IndexedDB implementation does what many other DB engine does - just marks deleted items until some cleanup code is run on a schedule or when space is needed. Anyhow, this is nothing that Dexie can control. It's up to the browser to implement the IndexedDB specification. And if you still think it's an issue, it should be filed in [chromium's bug tracker](https://crbug.com/wizard)

**Comment by benitogf** [comment]
Thanks for the explanation @dfahlander no idea if it's actually an issue, would need more testing to check if like you said a cleanup is scheduled at some point, from what I've seen it's not.

Found that we have this available on some browsers: 
https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate https://www.chromestatus.com/features/5630353511284736

it doesn't let us determine the usage distribution (localStorage, sessionStorage, indexedDb) but still would be nice to expose a method from dexie based on this, or at least include a reference in the docs, what do you think?

**Comment by dfahlander** [comment]
Thanks for the links. Definitely, we should provide docs about the new storage API as it can be very relevant to indexedDB usage.

**Comment by dfahlander** [comment]
Samples for using StorageManager added: http://dexie.org/docs/StorageManager

**Comment by dfahlander** [comment]
Closing this issue as it is not Dexie-related.
