### ISSUE TITLE
Security error: Open DB in Firefox 56 and above

### ISSUE THREAD

**Issue by 01fade** [dfahlander/Dexie.js#614]
Hi,

I have built a browser extension using this library to store data locally.
I get an error, when opening the data base with dexie!

```SecurityError: The operation is insecure.```

I have tested the Hello World code and it happens, as well, so I think it's not anything in my code.
My browser extension runs fine in Chrome. 
Would greatly appreciate any help with this! As the Chrome extension has around 78K users and I just launched it for Firefox, it ran fine a couple days ago!

THANKS!

**Comment by dfahlander** [comment]
Anyone else that has had written a Firefox addon that accessed indexedDB? Pinging @ginnipankaj, @achintverma, @damoclark.

**Comment by 01fade** [comment]
Hello! I found the root of the problem actually, I totally forgot that I changed my privacy setting in Firefox to "Always use private browsing mode" and that doesn't work with Dexie. So, it was just me, sorry! Closing issue.

Thanks for creating this library btw. I think it's great and makes a lot of things easier, keep up the good work!

**Comment by dfahlander** [comment]
Thanks for sharing.
