### ISSUE TITLE
Unhandled rejection: Invalid key provided in Microsoft Edge/IE

### ISSUE THREAD

**Issue by steophy** [dfahlander/Dexie.js#615]
Hello there, I'm having problems using Dexie with Microsoft Edge or Internet Explorer.
I get this error every time I'm querying the Database because I'm using a combination of two floats as a key:

```
   db.buildings
                      .where("[lat+long]")
                      .between([data.llc_lat, data.llc_lng], [data.urc_lat, data.urc_lng])
                      .toArray((res) => {
                          this.addHexagons({
                              success: true,
                              data: res,
                          });
```

The problem is that using multiple keys is the only way to achieving what I want to do because there is no other way to sue two 'where' clauses...

How can I solve this?

**Comment by dfahlander** [comment]
IE/Edge does not support [compound keys](http://dexie.org/docs/Compound-Index). In your case, I doubt you can benefit from compound keys anyway, because the query would return items with longitudes outside your desired rectangle.

I would suggest to only index the longitude only and put a js filter to filter out the latitude range:

```js
db.buildings.where ('long')
   .between (data.llc_lng, data.urc_lng)
   .and(x => x.lat >= data.llc_lat && lat < data.urc_lat)
   .toArray()
```

**Comment by steophy** [comment]
Thanks for the input, I think you forgot a 'x' in the third line:
```.and(x => x.lat >= data.llc_lat && x.lat < data.urc_lat)```

This query, by the way, returns no results, I don't know why...
That's how I set up the db:
```

              db.version(1).stores({
                  buildings: "id, name, address, lat, long, purchased",
                  // versions: "++id, version",
                  versions: "++id, version",
                  // }, { keyPath: "[lat+long]", autoIncrement: true });
              });
```
