### ISSUE TITLE
bulkPut returning changeset info

### ISSUE THREAD

**Issue by akonwi** [dfahlander/Dexie.js#620]
I'm using bulkPut because I want everything to be an upsert. I'd like to know though which entries were new/updated. 

does it make sense for bulkPut to return this information instead of or in addition to the last added key?

something like:

``` javascript
db[table].bulkPut(entities).then(changes => ...)
```

the changes object returned to the callback would look like

``` javascript
{
  inserts: [...],
  updates: [...]
}
```

**Comment by dfahlander** [comment]
It would make sense if it wasn't for that it would come with a cost. It would require a preflight query for existing keys, as bulkPut will not get that info from IndexedDB. That's the reason not having it built-in, but you can perform that pre-query yourself to get what you want:

```js

/**
 * @param {Dexie.Table} table Table to upsert to.
*/
function upsert (table, entities) {
  const primKeyProp = table.schema.primKey.keyPath; // For example "id".
  const primaryKeys = entities
    .filter(ent => primKeyProp in ent) // If id not present, must be autogenerated (++id) or fail
    .map(ent => ent[primKeyProp]);
  return db.table(table)
    .where(primKeyProp).anyOf(primaryKeys) 
    .primaryKeys() // Queries keys only (faster than toArray())
  .then(existingKeys => {
    existingKeys = new Set(existingKeys);
    return db.table(table).bulkPut(entities).then(()=> ({
      inserts: entities.filter(ent => !existingKeys.has(ent[primKeyProp])),
      updates: entities.filter(ent => existingKeys.has(ent[primKeyProp]))
    }));
  });
}
```

**Comment by dfahlander** [comment]
In case you are implementing a generic solution, such as for sync, you may also have a look at the CRUD hooks:

[Table.hook('creating')](http://dexie.org/docs/Table/Table.hook('creating'))

[Table.hook('updating')](http://dexie.org/docs/Table/Table.hook('updating'))

[Table.hook('deleting')](http://dexie.org/docs/Table/Table.hook('deleting'))

**Comment by akonwi** [comment]
yea i was really hoping i wouldn't need to the pre-queries. I probably should have just checked the indexeddb docs to see whether that information is available with puts before I posted haha. 

I'd rather not use the hooks because I only want to subscribe once the db is updated and the hooks seem to be invoked prior to the db changing. 

Thanks for the suggestions. I'll close this now
