### ISSUE TITLE
In addons.forEach: "fn is not a function"

### ISSUE THREAD

**Issue by douglasg14b** [dfahlander/Dexie.js#625]
I'm trying to start Dexie with the relations addon:

```ts
import Dexie from 'dexie';
import relationships from 'dexie-relationships'

export class AppDatabase extends Dexie {
    constructor(){
        super('AppDatabase', {addons: [relationships]});
    }
}
```

And I get the following error:

> fn is not a function

Under

```js
    addons.forEach(function (fn) {
        fn(db);
    });
```

In the compiled output it's trying to pass `relationships.default` into the `super` call instead of `relationships`

**Comment by dfahlander** [comment]
Seems to be a problem with certain bundling configurations and combos webpack / rollupjs / tsconfig module type. In Dexie, I had to add a dummy 'default' static property to the Dexie class for the same reason - some import configurations made it available as a simple require() while others expected a 'default' property from the required result. Different bundlers seems to treat imports differently.

I hope adding a property named 'default' on dexie-relationships will do it. I assume you can work around it until then.

Cheers,
David

**Comment by douglasg14b** [comment]
@dfahlander 

It wouldn't come in correctly no matter what I added or tried.

I ended up copy/pasting the source into it's own file and importing it like a normal module in my source code. However, creating the tables with the relations seems to work, but typescript will no longer compile because it cannot find `with` on type `Table`.

Any idea what else I need to do to get that part working?

**Comment by dfahlander** [comment]
@douglasg14b Thanks for reporting this. I assume you are not alone but somehow we haven't captured this problem before. Probably due to different tsconfigs, packaging configs or so. It would be great if you could help us by sharing a package.json, webpack.config.js and tsconfig.json that reproduces this error so we could deal with it once for all.

**Comment by dfahlander** [comment]
Just found this: https://github.com/dfahlander/Dexie.js/issues/186#issuecomment-194190807

This was the reason for the default property Dexie.default that I assume we must add to dexieRelationships as well if it should work no matter if tsc is targeting ES <= 5 or ES >= 2016.

**Comment by ccgman123** [comment]
I have been having the same problem getting this add-on to work with Angular 5.  After reading this and some of #186 I decided to mess around with the tsconfig.json settings.   

By changing the line 
"target": "es5" 
to 
"target": "es6" 
made dexie-relationships import properly 

I only tested it with angular 5.0.0 and  angular cli version 1.6.3
I hope this helps some one.

I really enjoy dexie and the relationships addon cant wait to see the project develop.

**Comment by dfahlander** [comment]
@ccgman123 or @douglasg14b I would need help from someone to verify that dexie-relationships@1.2.9 resolves this issue.

**Comment by Willem676** [comment]
I recieved this error when running my application with ng serve. Updating to 1.2.9 resolved this issue for me!

**Comment by jayaddison** [comment]
It looks like I've run into this issue during experimentation with Webpack 5, `ts-node` and the `dexie-observable` plugin.  It appears as:

```
TypeError: addon is not a function
    at ./containers/frontend/node_modules/dexie/src/classes/dexie/dexie.ts:210:29
    at Array.forEach (<anonymous>)
    at new Dexie (./containers/frontend/node_modules/dexie/src/classes/dexie/dexie.ts:210:12)
```

Perhaps the same fix from https://github.com/ignasbernotas/dexie-relationships/commit/046cecfa4a58b6e754ad35ae0207bbcfdf8f03ea might apply to the `dexie-observable` (and other?) addons?

Unfortunately assigning a `default` value to the imported module doesn't seem to work in this case (TypeScript prevents it, I think).

**Comment by jayaddison** [comment]
NB: My issue in https://github.com/dfahlander/Dexie.js/issues/625#issuecomment-790957462 was resolved by following the latest documentation and simply `import`'ing the addon, without any need to specify it as an `addons` argument to the `Dexie` constructor.  That seems neater, as another benefit.
