### ISSUE TITLE
indexeddb readonly so shim will not work

### ISSUE THREAD

**Issue by martindiphoorn** [dfahlander/Dexie.js#63]
We just find out that window.indexedDb is readonly. The problem is that shim can't set the indexeddb and we can't even open the database.

https://github.com/axemclion/IndexedDBShim/issues/167

Because off this problem we can't deploy our ionic application to IOS. Could you please look into it?

**Comment by dfahlander** [comment]
Please help me verify if my last commit makes it work together with the latest version of the shim.

**Comment by martindiphoorn** [comment]
I have tried the code and it did not work. The problem is with shim i think. I have not found a way to fix this yet. Thanks for trying.

**Comment by dfahlander** [comment]
For making this work, you need to change the source code of indexedDBShim.js.

You have to make the following changes in indexedDBShim:

Change:
```js
if (window.shimIndexedDB) {
            window.shimIndexedDB.__useShim = function(){
                window.indexedDB = idbModules.shimIndexedDB;
                window.IDBDatabase = idbModules.IDBDatabase;
                window.IDBTransaction = idbModules.IDBTransaction;
                window.IDBCursor = idbModules.IDBCursor;
                window.IDBKeyRange = idbModules.IDBKeyRange;
                // On some browsers the assignment fails, overwrite with the defineProperty method
                if (window.indexedDB !== idbModules.shimIndexedDB && Object.defineProperty) {
                    Object.defineProperty(window, 'indexedDB', {
                        value: idbModules.shimIndexedDB
                    });
                }
            };
            window.shimIndexedDB.__debug = function(val){
                idbModules.DEBUG = val;
            };
        }
```

to

```js
if (window.shimIndexedDB) {
            window.shimIndexedDB.__useShim = function(){
                window._indexedDB = idbModules.shimIndexedDB;
                window._IDBDatabase = idbModules.IDBDatabase;
                window._IDBTransaction = idbModules.IDBTransaction;
                window._IDBCursor = idbModules.IDBCursor;
                window._IDBKeyRange = idbModules.IDBKeyRange;
                // On some browsers the assignment fails, overwrite with the defineProperty method
                if (window._indexedDB !== idbModules.shimIndexedDB && Object.defineProperty) {
                    Object.defineProperty(window, '_indexedDB', {
                        value: idbModules.shimIndexedDB
                    });
                }
            };
            window.shimIndexedDB.__debug = function(val){
                idbModules.DEBUG = val;
            };
        }
```

**Comment by dfahlander** [comment]
Little note here:

It seems you get the following exception when trying out this workaround without calling window.shimIndexedDB.__useShim():

    "indexedDB API not found. If using IE10+, make sure to run your code on a server URL (not locally). If using Safari, make sure to include indexedDB polyfill."

What you need to do is to call window.shimIndexedDB.__useShim() after including the indexeddb-shim and before including Dexie.js.

**Comment by martindiphoorn** [comment]
I have forwarded this on to an collegae of mine with apple hardware. Hopefully he has time soon.

**Comment by dfahlander** [comment]
From now on, to use the shim instead of the native IDB support, just include the [indexedDBShim](https://rawgit.com/axemclion/IndexedDBShim/master/dist/IndexedDBShim.min.js) before including Dexie. See #77 .

**Comment by bboydflo** [comment]
Quick question: What's the best way to use indexedDBShim with Dexie when writing common js modules? I would like to use indexedDBShim only when required (Modernizr.indexeddb = false, or Modernizr.ios = true).

**Comment by dfahlander** [comment]
Good question that has not been answered so far. IndexedDBShim is not a true commonjs module (doesnt put anything in module.exports), so if you require it in, you'll get an empty module. What you get though, is that window.shimIndexedDB will be set to its version of the `indexedDB` global. By looking at the source I found that this instance have an indirect pointer to other IDB classes through its constructor property.

Please test this and report back if it solves the solution. I think this could be something to put in a wiki page if so.

```js
require('indexeddbshim'); // sets window.shimIndexedDB = new IDBFactory() (shim's indexedDB)
if (Modernizr.indexeddb && !Modernizr.ios) {
    // Force using native indexedDB
    Dexie.dependencies.indexedDB = indexedDB; 
    Dexie.dependencies.IDBKeyRange = IDBKeyRange;
} else {
    // Force using the shim
    Dexie.dependencies.indexedDB = shimIndexedDB;
    Dexie.dependencies.IDBKeyRange = shimIndexedDB.constructor.modules.IDBKeyRange;
}

```

**Comment by dfahlander** [comment]
Updated the comment after reading docs from yepnope. Maybe there's a simpler way. The idea is that you:

1. Load the shim conditionally
2. Force Dexie to use it if loaded.

**Comment by dfahlander** [comment]
Updated the above comment again. Hope that it's now more clarified. Please verify that my preferred solution works because I haven't tested it out.

**Comment by bboydflo** [comment]
The preferred solution works well! I am though using `document.write('<script src="/dist/js/indexeddbshim.min.js">\x3C/script>');` The only concern I had was that the script will load asynchronously, but I tested it and works well! 

Perhaps is a good idea to include your above solutions to the documentation

Thanks a lot!

**Comment by dfahlander** [comment]
It's asynchronic in one way - it will execute after that your script-adding-script finishes. BUT it will definitely execute before any other script tags on the page that occurs below. So it's safe.
