### ISSUE TITLE
Database size remains same after Table.clear()

### ISSUE THREAD

**Issue by romankubis** [dfahlander/Dexie.js#631]
Hello,
I am "synchronising" items in Indexed DB with data in MySQL database. After Table.clear() I am using Table.add() but Indexed DB size constantly grows (Application tab in Chrome Developer Tools). Is it normal? Maybe I don't understands Indexed DB principles...
 
Thank you.

**Comment by dfahlander** [comment]
It should not grow after you clear the table unless you are using dexie-observable / dexie-syncable, which records historic data until it has been synced to server. However, the browser may choose to delete items lazily, I haven't looked into that personally, but it wouldn't be strange if it did for performance reasons. If so, the cleared data should be released when implementation chooses to free up space...

**Comment by romankubis** [comment]
Thank you David for your response. Maybe it will be lazy deletion, because browser sometimes shows lower value of occupied space.
