### ISSUE TITLE
the error version when new a db with the appointed version number

### ISSUE THREAD

**Issue by asdip138** [dfahlander/Dexie.js#636]
like this,when I new a db and appointed the version of the db is 1,but I get the db with version number which equals 10. Also, when I appointed the version of the db is 2, I get the db with version number which equals 20.
var db = new Dexie("DEXIE");
	db.version(1).stores({
	students: 'id,name,age',
	teachers: 'id,name,phone'
});

**Comment by nponiros** [comment]
This is normal, see https://github.com/dfahlander/Dexie.js/issues/59

**Comment by fgilio** [comment]
@dfahlander I guess this issue can be closed

**Comment by dfahlander** [comment]
Thanks @fgilio
