### ISSUE TITLE
WhereClause.equals() ; not accepted array 

### ISSUE THREAD

**Issue by zeroone2005** [dfahlander/Dexie.js#639]
id is primkey 

`let k = [3,4];
db.history.where('id')
.equals(k)
.delete()
.then(function(deleteCount){
                        if(0 < deleteCount){
                            if(fun)fun();
                        }
                   });`

if equals() parameter is array.  no record has been deleted;

` let k = [3,4];
  db.history.where('id')
                   .anyOf(k)
                   .delete()
                   .then(function(deleteCount){
                        if(0 < deleteCount){
                            if(fun)fun();
                        }
                   });`

anyOf() is run;

**Comment by dfahlander** [comment]
What do you mean with anyOf() is run?

**Comment by zeroone2005** [comment]
.equals(Array) can't delete record
.anyOf(Array) can delete record

**Comment by dfahlander** [comment]
Are the primary keys (ids) arrays or numbers? If the ids are numbers, then equals would fail naturally since [3,4] != 3 && [3,4] != 4.

**Comment by zeroone2005** [comment]
TKS
