### ISSUE TITLE
database size increases exponentially using put

### ISSUE THREAD

**Issue by benitogf** [dfahlander/Dexie.js#641]
Hello, I did a small test using `navigator.storage.estimate()` after noticing this issue with 10 sequential updates using [put](http://dexie.org/docs/Table/Table.put()) on a table, with the same data entry:

```
    ....
    let initial = await navigator.storage.estimate()
    let qts = []
    for (let update of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) {
      await testTable.put(testItem)
      let qt = await navigator.storage.estimate()
      qts.push(qt)
    }
    console.log('QUOTAS:', initial, qts)
```
with the item already in db:

`initial: {quota: 6459437875, usage: 474420299}`

10 sequential updates with the same data: 

```
0 {quota: 6459437875, usage: 490228774}
1 {quota: 6459437875, usage: 513381317}
2 {quota: 6459437875, usage: 545568505}
3 {quota: 6459437875, usage: 530063149}
4 {quota: 6459437875, usage: 578629388}
5 {quota: 6459437875, usage: 594437863}
6 {quota: 6459437875, usage: 610172526}
7 {quota: 6459437875, usage: 620228518}
8 {quota: 6459437875, usage: 636037023}
9 {quota: 6459437875, usage: 684525909}
```

So far I think that the issue is happening only on chrome, tested on windows.

**Comment by benitogf** [comment]
The results on linux and firefox are quite different, much better actually, the size increases with the first 'put' but is not exponential.

with the item already in db:

`initial:  {quota: 897581056, usage: 16013786}`

10 sequential updates with the same data:

```
0 {quota: 897581056, usage: 26573274}
1 {quota: 897581056, usage: 37219354}
2 {quota: 897581056, usage: 26573274}
3 {quota: 897581056, usage: 26573274}
4 {quota: 897581056, usage: 37219354}
5 {quota: 897581056, usage: 37219354}
6 {quota: 897581056, usage: 26573274}
7 {quota: 897581056, usage: 37219354}
8 {quota: 897581056, usage: 26573274}
9 {quota: 897581056, usage: 26573274}
```

**Comment by dfahlander** [comment]
Just a theory: It might be that the internal implemetation of put() in chrome and Firefox actually just adds another object and marks the existing one as deleted. I assume there is a garbage collection / vacuum cleaning in place and triggered when usage approaches the quota.

**Comment by benitogf** [comment]
ok got it, feel free to close this one then, doesn't seem related to dexie since it works fine on linux/firefox, thanks for your quick reply friend 😄

**Comment by sechel** [comment]
I did experience this in an IDB instance in Chrome, too. It got 60 GiB big until it reached the quota limits 😄. I believe one has to trigger some kind of `vacuum` command for the backend db. After deleting some cache DBs is reduced its size by a whooping 59 GiB to normal.
