### ISSUE TITLE
[question] is it possible to change primary key in db version upgrade?

### ISSUE THREAD

**Issue by skygragon** [dfahlander/Dexie.js#646]
the 1st version I have auto incremental id, but in 2nd version I need to use specific id for some reason. Is it possible to use db versioning to modify old ids in db? or do we have other better option?

**Comment by dfahlander** [comment]
It's not possible to change primary key in an upgrade. However, an auto-incremented primary key will not complain if you give it a value - the autoincrement is just a default. And you are not bound to using numbers.

**Comment by skygragon** [comment]
@dfahlander I'm wondering if this would work:
1. read all old records and modify their id in memory
2. delete all old records in db
3. refill db with those modified records

But my question is when would I do this, is there a callback available when dexie detect a db upgrade needed?

**Comment by dfahlander** [comment]
Yes that is possible but you would have to change table name:

```js
const db = new Dexie('mydb');
db.version(1).stores({
  friends: '++id, name, age'
});
db.version(2).stores({
  friends2: 'id, name, age'
}).upgrade(()=>{
  return db.friends.toArray().then(objs => {
    return db.friends2.bulkAdd(objs);
  });
});
```

It's also actually possible to do it without changing table name, but this is a little bit more "hacky" and that your browser supports IndexedDB 2.0:

```js
const db = new Dexie('mydb');
// Only supply version 2:
db.version(2).stores({
  friends: 'id, name, age'
});
const db_open = db.open;
db.open = ()=>{
  let tmpDb = new Dexie('mydb');
  return tmpDb.open().then(()=>{
    tmpDb.close();   
    if (tmpDb.verno >= 2) {
      return db_open.apply(db);
    }

    tmpDb.version(1).stores({
      friends: '++id, name, age'
    });
    tmpDb.version(2).stores({
      friends2: 'id, name, age'
    }).upgrade(trans =>{
      return db.friends.toArray().then(objs => {
        return db.friends2.bulkAdd(objs);
      }).then(()=>{
        // Remove old table and rename new.
        tmpDb.backendDB().deleteObjectStore('friends');
        // This requires IndexedDB 2.0 feature available
        //  in Chrome, FF and Safari but not IE/Edge:
        trans.objectStore('friends2').name = 'friends';
      });
    });

    return tmpDb.open().then(()=>{
      return tmpDb.close();
    }).then(()=>{
      return db_open.apply(db);
    });
  });
}


// From here, you should just be able to use db as if version 2 is applied, such as:
db.friends.add({id: 'xyz', name: 'foo', age: 33}).then(...)...
```

**Comment by skygragon** [comment]
Thanks @dfahlander for your detailed guide.
I made it work by setting a flag in upgrade() and then manually check the flag later after db.open(). then I just read all records and clear the db, and refill the db with new ids.

**Comment by dfahlander** [comment]
Good to know you found a solution :)

**Comment by iAmWillShepherd** [comment]
@skygragon , I'm having the same problem you were. Would you mind sharing your code that allowed you to rename the primary key?

**Comment by iFlameing** [comment]
> It's not possible to change primary key in an upgrade. However, an auto-incremented primary key will not complain if you give it a value - the autoincrement is just a default. And you are not bound to using numbers.

How I can change the primary key from autoincrement to a particular value.
