### ISSUE TITLE
Unsubscribe from db.on('changes') 

### ISSUE THREAD

**Issue by blended-dev** [dfahlander/Dexie.js#654]
Hi,
    I have been using dexie-observable in my project where I need to run a set of operations once an object in the db has been modified. All this is part of a 'live-update' feature in my app. When the session is started, I need this live-update function to be operational but once the session is ended, I want to unsubscribe to the db changes. I generate one object that handles the db changes part and delete it once the session is closed. All these observers are alive and they pile up after a few open-close session operations. Simply put, is there something like window.detachEventListener() for dexie-observable so that I can unsubscribe from db.on('changes') operation ?

Thanks a lot in advance ! :smile:

**Comment by dfahlander** [comment]
Yes, db.on('changes').unsubscribe(fn)

**Comment by blended-dev** [comment]
@dfahlander Thank you for the quick response !
