### ISSUE TITLE
Include info about searching for one element of a compound index in documentation

### ISSUE THREAD

**Issue by nbrustein** [dfahlander/Dexie.js#657]
I'm wondering if it's possible to query for records that match just the first part of a compound index.

Seems like it would be good to have an answer to this question one way or the other in the compound index docs, maybe near where it says "it can be efficiently looked up using..."

Just to be clear about what I mean.  Considering the example index in the docs, would there be a way for me to search for all records where `firstName==='foo'`

**Comment by dfahlander** [comment]
Thanks for sharing. Yes in current version, it's only possible using the between() operator.

```js
db.friends.where('[firstName+lastName]').between(
    [searchedFirstName, Dexie.minKey],
    [searchedFirstName, Dexie.maxKey])
```
I could update the sample.

**Comment by nbrustein** [comment]
Awesome.  Thank you for the quick response.

**Comment by nbrustein** [comment]
It doesn't look like Dexie.minKey and Dexie.maxKey are accessible (using version 1.5.0).

I was able to accomplish the same thing though, with 0 and 'zzzzzz'. Right?

**Comment by dfahlander** [comment]
Yes, if you only use numbers and strings, that's totally fine. You could also use between `-Infinity` and `'\uffff'`
