### ISSUE TITLE
3.0.0-alpha.1: TypeScript 2.7 errors

### ISSUE THREAD

**Issue by dpogue** [dfahlander/Dexie.js#659]
Trying out the 3.0.0-alpha.1, and getting a few TypeScript errors with an existing codebase:

* <code>TS4053: Return type of public method from exported class has or is using name 'PromiseExtended' from external module "/Project/node_modules/dexie/dist/dexie" but cannot be named.</code>

* <code>TS2694: Namespace '"/Project/node_modules/dexie/dist/dexie".Dexie' has no exported member 'Transaction'.</code>

* <code>TS4050: Return type of public static method from exported class has or is using name 'Table' from external module "/Project/node_modules/dexie/dist/dexie" but cannot be named.</code>

I can fix the second one by doing `import Dexie, { Table } from 'dexie'`.
The other two are from places where I have functions that return things from Dexie.

I don't think it's a huge problem if the imports have to change (particularly since it's a major version bump), but it's probably an issue if you can't have things that return Dexie types.

**Comment by dfahlander** [comment]
Thanks for sharing!

* TS4053: I wonder what could be the best way to deal with this. PromiseExtended<T> is a generic interface, exported by dexie.d.ts. It's aliased (for backward compatibility) as Dexie.Promise<T> by declaring a module "Dexie" with a type Promise<T>=PromiseExtended<T>. I don't understand the problem here. Help wanted ;)

* TS2694: Could be that your code declares Dexie.Transaction. If so, I might just need to alias Transaction under Dexie namespcace unless we'd get the same issue as the one above.

* TS4050: Still don't understand why tsc complains here either.

If you'd have a chance to share your tsconfig and some failing code, it would probably help me trying to narrow down the issue. What typescript version are you using?

Thanks for testing out the alpha ;)

**Comment by dfahlander** [comment]
If I'm not mistaken, this issue seems to have been solved in the very latest Typescript release (2.9): https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#relaxing-declaration-emit-visiblity-rules.

**Comment by dpogue** [comment]
I can confirm that my project *compiles* with Dexie 3.0.0-alpha.3 and TypeScript 2.9, but I'm somehow getting an error inside TypeScript when trying to run tests... nothing that indicates that it's Dexie-related, but upgrading Dexie is the only change I made before this started happening 😕

**Comment by dfahlander** [comment]
Ok, thanks for testing. May I ask what is the error message?

**Comment by dpogue** [comment]
It's https://github.com/Microsoft/TypeScript/issues/25047
I tried typescript@next but got all sort of errors about require and sourcemaps, so I'm leaving it alone for the moment

**Comment by dfahlander** [comment]
Seems to be related, and solved in typescript master. I hope they will merge the fix into their 2.9 branch and release a 2.9.x. We can only wait so far... :-)

The official fix if on TS < 2.9 seems to add explicit imports into library modules of all dexie-types that are being implicitly returned. Haven't tested that this works though. I will hopefully to get some time to repro this and try that some day.... or wait for next TS release.

**Comment by dpogue** [comment]
Okay, trying this again with TypeScript 3.0 RC, and still running into the same error. The library works fine with TypeScript 3.0 RC and Dexie 2, so it has to be something that changed in the newer version.

However, this seems to be more of a WebPack build error than a TypeScript error now:
```
Uncaught ReferenceError: require is not defined
at http://localhost:9876/base/webpack.tests.js?19bbeda260bfd4f15252e9e617dc700ddb22c4bd:67330:35

ReferenceError: require is not defined
    at Module../node_modules/dexie/dist/dexie.mjs (http://localhost:9876/base/webpack.tests.js?19bbeda260bfd4f15252e9e617dc700ddb22c4bd:67330:35)
    at __webpack_require__ (http://localhost:9876/base/webpack.tests.js?19bbeda260bfd4f15252e9e617dc700ddb22c4bd:20:30)
    at Module.<anonymous> (http://localhost:9876/base/webpack.tests.js?19bbeda260bfd4f15252e9e617dc700ddb22c4bd:139134:115)
    at Module../src/helpers/spec/idb.ts (http://localhost:9876/base/webpack.tests.js?19bbeda260bfd4f15252e9e617dc700ddb22c4bd:139138:30) 
```

I wonder if it's supposed to be loading the dexie.mjs file? I don't see any `require` calls in there though... 😕

**Comment by dfahlander** [comment]
Webpack is probably choosing the mjs file due to the "module" attribute in package.json. Could upgrade/downgrade webpack help?

**Comment by dpogue** [comment]
Aha! Got it to work and everything seems to work! :)

The trick was adding `{ test: /\.mjs$/, include: /node_modules/, type: 'javascript/auto' }` to the webpack config (for anyone who happens to run into the same issue)

**Comment by dpogue** [comment]
So I guess the original errors are no longer a problem, and we can close this issue :)
