### ISSUE TITLE
Dexie fractional versioning increment

### ISSUE THREAD

**Issue by Anruin** [dfahlander/Dexie.js#660]
Hi, the problem is not related to Dexie itself, rather to how Javascript works. Decided to post it here if someone will run into same problem I did.

I'm using fractional versioning (0.1, 0.2, ...) to have integer versions of IDB not multiple of 10 (1, 2, ...). My application has design with ability to create tables dynamically, and with each new table I increment version by 0.1. So the problem is that `(0.1 + 0.1 + 0.1) !== 0.3` in Javascript (tested in Chrome 65), and after 3rd migration Dexie crashes with errors and does not allow to add more versions. So the workaround that I use is explicit rounding for the next version I want to update the database to:
`+(version + Database.VersionIncrement).toFixed(1)`.

I hope that it will help someone.

**Comment by dfahlander** [comment]
Thanks for sharing 👍

**Comment by Anruin** [comment]
No problem. Thanks for Dexie, it is awesome.
Should we close the issue or leave it open? Maybe some built-in fix is possible for this?

**Comment by dfahlander** [comment]
True, Dexie should protect from that. I've resolved it in the master branch, which is on 3.0.0-alpha, so it might take a while before it comes to a stable state. If anyone is eager to fis this for the next 2.0 stable (which will come out sooner), feel fre to PR the similar commit to the "master-2" branch.
