### ISSUE TITLE
Create new stores/tables to existing DB

### ISSUE THREAD

**Issue by GoChartingAdmin** [dfahlander/Dexie.js#661]
In my use case, I need to add new tables based on user interaction.  Basically whenever the user selects a certain stock, the client gets data from server, creates a new store (store name same as stock ticker) and then saves the data into that store using bulkPut method.

It works great the first time I am creating the database and the first stock store.  But my attempts to dynamically add stores to the DB is throwing errors

Code so far:

 ```
           const storeName = `${ticker.symbol}_${exchange}_${resolution.type}`;     
            const db = new Dexie(`App`);  
            const tableNames = db._storeNames;
            tableNames.push(storeName);
            var stores = {};
            tableNames.forEach(function (each) {
                stores[each] = "date"
            });
            db.version(1).stores(stores); 
            const table = db[storeName];       
            table.bulkPut(ohlc).then(function(lastKey) {
               console.log("Successfull loaded",lastKey)
            }).catch(Dexie.BulkError, function (e) {
                console.error ("Some raindrops did not succeed");
            });
```

Please let me know how do I dynamically add stores to an existing DB

**Comment by dfahlander** [comment]
There is a similar question at stackoverflow you could have a look at https://stackoverflow.com/questions/39000780/errors-with-indexeddb-versions-and-dexie-js?rq=1

**Comment by dfahlander** [comment]
That said, as IndexedDB is architected around static schemas (all DB connections has to close before mutating the schema), I would advice you to rethink the architecture to use static schema instead if possible. In principle, there's no reason to create new tables for new data as you could store the stock identifier in a property and index that together with your other indexes.

Let's say you're indexing price and have the stock per table.

```js
var dynamicSchema = {};
dynamicSchema.stockX = "id,time,price";
db.version(x).stores(dynamicSchema)
```
...you could replace that with:

```js
db.version(x).stores({
   stockEvents: 'id,[stock+time],[stock+price]'
});
```
And to query all prices within a given time range for a certain stock:
```js
db.stockEvents.where('[stock+time]')
  .between(
    [theStock, fromDate],
    [theStock, toDate])
  .toArray();
```

And to query all times a certain stock has gone over $25:
```js
db.stockEvents.where('[stock+price]')
  .between(
    [theStock, minPrice],
    [theStock, Infinity])
  .toArray();
```
Much of this is covered in [this page](http://dexie.org/docs/Compound-Index)

**Comment by GoChartingAdmin** [comment]
Great.  One last query.  Should I use bulkPut or just put to store the price data against a given stock within the table.  Say the stock is AAPL and the price data (which is an array) that I retrieved from server is in the variable OHLC.  How do I store this array data against AAPL in your suggested schema

OHLC format:

```
[
[date1,open1,high1,low1,close1,volume1],
[date2,open2,high2,low2,close2,volume2],
[date3,open3,high3,low3,close3,volume3],
[date4,open4,high4,low4,close4,volume4],
]
```

**Comment by dfahlander** [comment]
Use bulkPut()

```js
const data = [
[date1,open1,high1,low1,close1,volume1],
[date2,open2,high2,low2,close2,volume2],
[date3,open3,high3,low3,close3,volume3],
[date4,open4,high4,low4,close4,volume4],
];

await db.tableName.bulkPut(data.map(a => ({
  date: a[0],
  open: a[1],
  high: a[2],
  low: a[3],
  close: a[4],
  volume: a[5]
})));

```

**Comment by GoChartingAdmin** [comment]
Per your schema
db.version(x).stores({
   stockEvents: 'id,[stock+time],[stock+price]'
});
Will I require the stock name (AAPL) to be part of the array or somewhere which makes it possible to make those queries you suggested

**Comment by dfahlander** [comment]
Yes, so just add it into the bulkPut() snippet I suggested.

**Comment by dfahlander** [comment]
Based on your data sample and my bulkPut() suggestion, depending on what queries you are going to make, you might want to index '[stock+date]'

```js
db.version(X).stores({
  stockData: `
    ++id,   
    [stock+date]`
});

```

Then you can query a certain stock's data between two given dates. I suppose that's the use case. If you need to make more advanced queries, just add additional indexes.

**Comment by GoChartingAdmin** [comment]
When I ran the below query, I got the below error
 Declaration: // Adding id in the schema was throwing an error on bulkPut
```
const db = new Dexie("GoCharting");
db.version(1).stores({
    stockEvents: '[stock+date]'
});
```

Query:

```
db.stockEvents.where('[stock+time]').below([theStock, startTime]).reverse().limit(limit).toArray().then((data)=> {		
					//do Something
				})
```

 SchemaError: KeyPath [stock+time] on object store stockEvents is not indexed

**Comment by nelu** [comment]
this would be useful for timeseries table naming design, if you are planning to name your tables with  yyyy-mm-dd for large sets of data 50gb / year
