### ISSUE TITLE
Save blob in DB more than origin in 10 times

### ISSUE THREAD

**Issue by fix2015** [dfahlander/Dexie.js#667]
Hi all, have a pb, i tried to save blob file (video) by part in DB and than donwload by part and save on desctop. And all work fine, but origin file 600mb in DB around 7000mb.
How it work i split file, on part around 10 mb and push in DB and than get from DB by id.
Here's my config:
` 
var db = new Dexie('test');
        db .version(1)
            .stores({
                frame: '++id,frame'
            });
        db .open()
            .then(function(){
                callback({'type' : 'ready'});
            })
            .catch(function (e) {
                console.log(e)
                console.error("Open failed: " + e.stack);
            })
`
I was check size in DB with dev tools chrome tab -> Aplication -> clear storage(before check i was clear everything)

**Comment by dfahlander** [comment]
May be related to #665. Just a reminder, not index the property that host the video part. Don't know if that is the case, but if so just make sure you don't.

In case this is related to #665, try work around the issue by storing the video parts as new originArrayBuffer.slice(startPos, endPos). Blob.slice() might not be enough as it may point to same backing ArrayBuffer (as bug #665 seems to be that IndexedDB can store the entire ArrayBuffer anyway).

**Comment by fix2015** [comment]
i did nothing speacil for this - 'not index the property that host the video part'
and second i save in DB exactly how it in example #665  
`    const smallArray = new Uint8Array([1,2,3])
    const result = await db.myTable.put({id: 1, array: smallArray})
    console.log("First insert was successful with result", result)`
And tested it on all browser same effect, so you think we can't fix it?

**Comment by dfahlander** [comment]
Issue #665 is still too new for me to know whether it's a bug or not. But if it is, a workaround would be to clone the backing array of the Uint8Array or Blob. I suppose cloning can be done via ArrayBuffer.prototype.slice(). Blob and Uint8Array also have slice() but I don't think it's sufficient as it may point out the same backing arraybuffer, just on different positions.

**Comment by fix2015** [comment]
checked same effect

**Comment by dfahlander** [comment]
What data type is stored in your 'frame' index?

**Comment by fix2015** [comment]
buffer = [1,2,4......]
frame = [new Uint8Array(buffer),  new Uint8Array(buffer),  new Uint8Array(buffer)]

**Comment by dfahlander** [comment]
Ok, so why are you indexing it? Will you use it in a query?

**Comment by fix2015** [comment]
what do you mean indexing?

**Comment by fix2015** [comment]
after i put all data, i just use this command
`   db.frame.where({id: obj.store.key})
        .first(function(data){
           callback({
               'type' : 'get',
               'data' : data
           });
        })`

**Comment by dfahlander** [comment]
You pasted you "config" where you had:

```js
var db = new Dexie('test');
        db .version(1)
            .stores({
                frame: '++id,frame'
            });
        db .open()
            .then(function(){
                callback({'type' : 'ready'});
            })
            .catch(function (e) {
                console.log(e)
                console.error("Open failed: " + e.stack);
            })

```

The "frames" store has one primary key ("id") and one index "frame".

If you index it, IndexedDB has to build up a btree on the values, which may be the reason for the huge storage size.

**Comment by dfahlander** [comment]
Should only index properties that you want to query on in your where()-clauses. And even though binary keys kan be index, you would typically only index small binary keys and definitely not videos or images.

You can still store the video of course in the "frame" property and retrieve it back when querying by id, but just omit the indexing of it.

**Comment by fix2015** [comment]
Oh yes, its true, sorry for take your time it was my bad, thank you very much @dfahlander -> the best

**Comment by dfahlander** [comment]
No problems :) I suppose you're not alone and that there may be a lot of users doing the same out there. So it's good this came up!
