### ISSUE TITLE
Dexie is sometimes hard to debug because of missing context in error event object

### ISSUE THREAD

**Issue by dasboe** [dfahlander/Dexie.js#669]
I'm using `window.addEventListener('unhandledrejection', callback)` for global error handling of Dexie.js. My Problem is I often find myself in a situation where it's hard to debug my code because the error event object does not give enough meaningful information of where the error occurred in my code. Here is a very distilled example of a type of error which I had a hard time debugging: 
```
window.addEventListener('unhandledrejection', function(e) {
  // The output of the error object does not give any meaningful information where the error occured
  console.log(e);
});

var db = new Dexie("TestDuplicateKey");
db.version(1).stores({ test: 'id' });

db.open().then(function() {
  return db.test.add({ id: 1 });
}).then(function() {
  return db.test.add({ id: 1 });
});
```
Fiddle: https://jsfiddle.net/1ksfk1hv/

Here is all information I get from the error event object in the console output:

> message: "Key already exists in the object store."
> name: "ConstraintError"
> stack: "Error
>     at getErrorWithStack (https://unpkg.com/dexie@2.0.1/dist/dexie.js:322:12)
>     at new DexieError (https://unpkg.com/dexie@2.0.1/dist/dexie.js:451:19)
>     at mapError (https://unpkg.com/dexie@2.0.1/dist/dexie.js:481:14)
>     at handleRejection (https://unpkg.com/dexie@2.0.1/dist/dexie.js:965:14)
>     at IDBRequest.<anonymous> (https://unpkg.com/dexie@2.0.1/dist/dexie.js:4220:9)
>     at IDBRequest.<anonymous> (https://unpkg.com/dexie@2.0.1/dist/dexie.js:1178:23)"
> 

I'm not sure if I should do something differently, this is a limitation I have to live with or if this is something which could be improved in Dexie.js.

**Comment by dfahlander** [comment]
Yes, you can set Dexie.debug to true to enable long call stacks:

```js
Dexie.debug = true;
```

I updated the fiddle accordingly and after running it, the log will tell you the exact line where the error occurred, see screenshot:

![image](https://user-images.githubusercontent.com/6791329/36734338-6fc5db2a-1bd3-11e8-97c9-b3045c1db169.png)

Note: Dexie.debug will be default true when served from localhost. 

http://dexie.org/docs/Dexie/Dexie.debug

**Comment by dasboe** [comment]
Thank you - this helps a lot! I'm running my tests in a Jasmine suite and therefore Dexie.debug has been set to false by default.
