### ISSUE TITLE
I create 2 instance in two pages to pass data, while I write sth in one , can not read from the other one

### ISSUE THREAD

**Issue by 85204** [dfahlander/Dexie.js#673]
I use electron to create two pages in the same origin "file://"
each pages has one instance, and then I write some thing in DB in page one, send a message to the page two,
then the instance in page two try to read the same DB, but read nothing.

Two pages have the same code below, one for write,the other for read

```
import Dexie from 'dexie'
let db = new Dexie("database");
db.version(1).stores({
    loginStatus: '++id',
});

    saveUserLoginStatus: async (username, keycheck) => {
        await db.transaction('rw', db.loginStatus, async () => {
            await db.loginStatus.where('id').above(0).delete()
            await db.loginStatus.add({ username, keycheck })
        })
    },
    getUserLoginStatus: async () => {
        let result
        await db.transaction('rw', db.loginStatus, async () => {
            result = await db.loginStatus.toArray()
        })
        if (result.length !== 0) return result[0]
    }
```

**Comment by 85204** [comment]
I try to debug, it show right result sometimes.
I don't know why?
And how to make it stable

**Comment by dfahlander** [comment]
Are you waiting for the promise from saveUserLoginStatus() to complete before communicating to other page to load data?

**Comment by 85204** [comment]
yes, all functions are waiting for the promise, as you see that all functions has async/await symbol.
I found that sometimes I type   db.loginStatus.toArray()  in console, it shows data, but at the same time still read nothing in script. it's really strange.
I use electron 1.8.2  version of chromium is 59
here is procedure flow

init page one - let db = new Dexie("database")
init page two - let db = new Dexie("database")
page one - saveUserLoginStatus()
send massge to page two - remote.BrowserWindow.fromId(pageTwoId).webContents.send('init')
page two - getUserLoginStatus()

**Comment by 85204** [comment]
Does dexie or indexedDB have cache system?

**Comment by dfahlander** [comment]
Dexie does not cache anything, but Chrome's indexedDB implementation might. I stumbled on the NOTE on [this mozilla page](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Adding_retrieving_and_removing_data) stating that Firefox went over to "relaxed" durability. Might be the case with Chrome as well.

That's just a theory though. I tried briefly to find similar bug in [chrome issue tracker](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=indexeddb+transaction&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids) but couldn't find it.

It could also depend on how the two different Electron based pages are launched. Are they in different Electron processes? Maybe it's "relaxed durability" related if so. If on same process, it could be so as well depending on the underlying implementation.

Think a repro of this would be great for this issue for filing it on [Chrome issue tracker](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=indexeddb+transaction&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids) and also [Electron's github page](https://github.com/electron/electron/issues).

**Comment by 85204** [comment]
I'm sorry. It's a bug from my code.
I found [this issue](https://github.com/w3c/IndexedDB/issues/99) 
It said that chrome doesn't use cache, saves data immediately, while edge not.
And then I re-check if every function has wait for promise,and found one not wait.

It works fine now.
Thanks for your reply, sorry for wasting your time.

**Comment by dfahlander** [comment]
Thanks for sharing! 👍
