### ISSUE TITLE
QUESTION: Is it possible to add new tables after the database is already open?

### ISSUE THREAD

**Issue by maxfi** [dfahlander/Dexie.js#684]
I'd like to add tables ad-hoc after my app has already read/written to other tables in the same database. For example:

```js
// books.js
const db = new Dexie('library')
db.version(1).stores({
  books: '_id'
})
db.books.put({_id: 1, title: 'Some book'})
```
then some time later:

```js
// magazines.js
const db = new Dexie('library')
db.version(1).stores({
  magazines: '_id'
})
db.magazines.put({_id: 1, title: 'Some magazine'})
```

Basically I'd like to avoid having to specify all possible tables prior to reading/writing from the database. Any ideas? Thanks in advance and keep up the great work! Cheers.

**Comment by dfahlander** [comment]
IndexedDB was not designed for dynamically adding tables on the fly. It is possible though, but you must keep in mind that each time you need to add a new table, other tabs working towards the same database will either block your schema update request, or have to close down and stop functioning as expected.

If you however want to do it, you just need to call db.close(), then increment the version number, putting new tables in it, then reopen it.

```js
async function extendSchema(db, extendedSchema) {
  db.close();
  db.version(Math.round(db.verno + 1)).stores(extendedSchema);
  return await db.open();
}
```
If you have your app open in another tab, it's ongoing transactions will block the upgrade at first. Then when their transactions are done, your upgrade will resume, but the other tab will close it's database connection.

See also https://stackoverflow.com/questions/45064466/passing-dexie-collection-from-variable/45068302#45068302

**Comment by maxfi** [comment]
Thanks so much for your assistance @dfahlander. [It's greatly appreciated!](http://s2.quickmeme.com/img/fb/fb23b2827744ce93b889d80e0a25a0b67953dc70a9ba6634e38be4556db69f30.jpg) I'm just stepping up to IndexedDB from localStorage and loving Dexie from the few days I've been working with it!

What I'm trying to build is a library to persist Meteor's [`minimongo`](https://github.com/meteor/meteor/tree/devel/packages/minimongo) in-memory collections. As such I only ever need to index the `_id` field as all queries will be run against the `minimongo` collection after it's rehydrated by Dexie. 

From some quick tests an approach that appears to work well is simply creating a database and table for each `minimongo` collection that needs to be persisted. This way the library consumer can persist a `minimongo` collection at any time during an app's execution without having to declare everything upfront on app start. It also means that if persistence isn't required in certain situations then no extra resources are consumed. So basically I'm thinking something like this:

```js
const persistCollection = collection => {
  // ...
  const {name} = collection
  const db = new Dexie(`__persisted_collections-${name}`);
  db.version(1).stores({ 
    [name]: '_id'
  })
  db[name].bulkPut(collection.find())
  // ... 
}
```

Besides some extra overhead when the databases are first created, and perhaps a slight overhead after that, are there any major issues with this approach?

I've also just come across [`Dexie.Observable`](http://dexie.org/docs/Observable/Dexie.Observable) which seems like the perfect thing to replicate changes to in-memory collections in other windows/tabs. [So much awesome!](https://sayingimages.com/wp-content/uploads/so-much-awesome-meme.jpg)

**Comment by dfahlander** [comment]
Thanks for the thanks 👍 :)
Your solution would be perfectly fine since you will get different independent databases. And it will consume less resources than using my suggested solution as each key will be smaller.

Note: Just don't forget to return the promise from bulkPut() so that persistCollection() returns a Promise that resolves when it has been persisted. 

**Dexie.Observable**

Works but is not that optimal right now. I am working on a new version that will be much faster and consume less storage. That one will have a nicer API on top of Rx.Observable or ES-observables. Cannot promise when it is out, but it will not need the meta tables that it uses right now.

**Comment by maxfi** [comment]
Thanks again for your assistance  @dfahlander and apologies for the late response! My library is working great so far in beta and I will link to it here when it's published. Looking forward to the new observable API. 🎉
