### ISSUE TITLE
Global exception handler for promises

### ISSUE THREAD

**Issue by janmisek** [dfahlander/Dexie.js#69]
Dexie.on.error consumes only database/transaction exceptions. There is discussed issue #43 which clarify the behaviour. But I would say Dexie promises needs the global exception handler. 

I am chaining the promises very much, also combining with other Promise/A+ implementation.  Also using global exception handler for whole application which push the exceptions to server logs. 

With current Dexie implementation I have to explicitly catch each exception in promise and push it to global exception handler. Also other promises implementation has the global onerror event, so this makes Dexie pretty much incompatibile with rest of my app.

**Comment by dfahlander** [comment]
I got it. It makes sense indeed to have a global exception event as a static property on Promise.

I'll keep the issue open as a todo item. Hopefully to be implementet in the coming month.

Thanks for sharing!
David

**Comment by dfahlander** [comment]
Implemented in src/Dexie.js and added documentation for it on the wiki.
Will be part of Dexie v1.0.4.
