### ISSUE TITLE
[Question] How to disable info/warning log (js console) from Dexie 

### ISSUE THREAD

**Issue by jokamax** [dfahlander/Dexie.js#692]
Hi,

For production purpose, is there a way to disable warning/info log from Dexie ?
Ex : _The query {"pj_id":"347","set_id":"3","set_field":"mtyp"} on sbook_project_settings would benefit of a compound index [pj_id+set_id+set_field]_

Thanks,

Jonathan

**Comment by dfahlander** [comment]
Currently no. Should make it dependant on [Dexie.debug](http://dexie.org/docs/Dexie/Dexie.debug) flag.

**Comment by dfahlander** [comment]
Fix released in Dexie 3.0.0-alpha.3
