### ISSUE TITLE
Data refreshing in dexie when database version upgrade.

### ISSUE THREAD

**Issue by sivapolisetty** [dfahlander/Dexie.js#698]
Hi, 
I am a newbie to Dexie. I am facing trouble in refreshing my dexie table data. Please provide guidance on how to achieve this.

I created an application with DB version 1 and populated data.  Now my requirement is refreshing of table data with new data whenever there is a new version of data is available on the server.  The version of data is driven with config. In config, if I upgrade data version number, dexie database should be populated with a new set of data. 

```js
var db = new Dexie("dexie");
db.version(1).stores({
    customers: 'id,name,location'
});

let latest_version = 2 //latest version is driven from config
db.version(latest_version).stores({
    customers: 'id'
}).upgrade (function (trans) {
       // check what is the Dexie database current version , if it is older load new data with fetching
       // ajax service to get new data
      // load new data into customer database.
});
```

Please provide some insight how this can be achieved.
Thanks,
Siva

**Comment by dfahlander** [comment]
You cannot fetch data in upgrade function, but I would suggest having a look at using db.on('ready') instead where you can do async fetching before the database is considered finally open

http://dexie.org/docs/Dexie/Dexie.on.populate.html#ajax-populate-sample
