### ISSUE TITLE
IndexedDB is getting bigger on each page refresh

### ISSUE THREAD

**Issue by mrvik** [dfahlander/Dexie.js#699]
### Structure:
```` JSON
"version": 0.1,
"stores":{
	"cache": "path",
	"upstreamDB": "id,tipo,nombre,coordenadas,localidad",
	"localidadesDB": "id_loc,nombre"
}
````
There are another properties inside of the upstreamDB, one is a image stored as a blob and another a string from `URL.createObjectURL`

The script that runs on each refresh does a fetch of about 75 images at a 600x600 res. The `cache` table only stores cache when there isn't a ServiceWorker (what's not the case now).
The blob and the url reference are stored on the IDB using Dexie with another properties (some of them indexed), but all of them are short strings, booleans and numbers (all <100).
Before it saves all of this data to the IDB, does a `db.upstreamDB.clear()` The app takes 8MB on first load and it increases (I've noticed that when reached 1300MB) on every reload.

**Comment by dfahlander** [comment]
Not sure if this you are referring to app memory or storage size. App memory should not increase with Dexie as it does no caching. Storage size in IndexedDB is not released immediately when you clear a table. It seems IndexedDB does not delete the content that you clear but just mark it as deleted. I suppose it will release the storage eventually when reaching a certain percent of the quota, but this is just a theory though. Most databases works the same - deletion is lazily done for performance reasons.

Not sure if this answers the question enough, but this is an area where I've got similar questions about before and it may depend on what browser implementation your app is running on.

**Comment by mrvik** [comment]
Yes, question solved. It seems to be more likely an upstream issue. I'm
using Google Chrome Stable. I've no tested it on another browsers. The
issue is with the persistent storage. Thanks for replying so fast.
