### ISSUE TITLE
Seems impossible to filter on boolean fields

### ISSUE THREAD

**Issue by n1k0** [dfahlander/Dexie.js#70]
```js
var Dexie = require("dexie");
var db = new Dexie("articles");
db.version(1).stores({articles: "id++,title,archived"});
db.articles.add({title: "plop", archived: true});
db.articles.where("archived").equals(true).each(function(article) {
  console.log(article);
}); 
```

Will throw:

```
Data provided to an operation does not meet requirements.
	node_modules/dexie/src/Dexie.js:1448:0
	src/js/local.js:52:16
```

Am I missing something obvious?

PS: Sample requirebin available here: http://requirebin.com/?gist=e3b249bdee2cc15184e3

**Comment by dfahlander** [comment]
Of some reason, the idb spec does not allow booleans as keys. Only Number, Date, String and Array. I was also surprised by this fact but it means you must use 0 and 1 instead of false and true.

**Comment by n1k0** [comment]
Do you think adding support for boolean keys would be achievable, and would make sense? Eg. by implicitely casting them to appropriate number values… I have no idea how much complicated/dangerous/odd that would be, but that would certainly help a lot mapping existing real world datasets to fit in databases :)

**Comment by dfahlander** [comment]
I could not add that support without rewriting the objects on both read and write. All creates and updates would have to be checked for booleans recursively and converted to numbers and in all reads and queries we would have to rewrite back again. This would add complexity to the library that I don't think is worth. I want to keep the library as close to the native idb as possible to make it easy to debug and understand.

**Comment by n1k0** [comment]
What you describe is just what I had to do on my end :( I can totally live with it, and get your point. 

Maybe just adding a notice to the docs is worth doing, though.

**Comment by dfahlander** [comment]
Added key requirements in the documentation of WhereClause.equals()

**Comment by n1k0** [comment]
Great!

**Comment by marcodenic** [comment]
just spent 2 hours trying to use .equals(true) instead of .equals(1)

why is that not documented on this page: http://dexie.org/docs/WhereClause/WhereClause.equals()

please add a sane example because that is NOT obvious.

**Comment by ChrisProlls** [comment]
Hi !
I used `.where('myField').equals(1)` and `myField` is stored and indexed like a boolean in IndexedDB, but I cannot retrieve my items.
Is that supported by both **IndexedDB** ans **Dexie** ?

**Comment by dfahlander** [comment]
booleans are not indexable in IndexedDB. You need to store myField as a number, string, Date, ArrayBuffer, TypedArray or Array<number | string | Date | ArrayBuffer | TypedArray>

**Comment by ChrisProlls** [comment]
Got it ;)
Thanks !

**Comment by h0jeZvgoxFepBQ2C** [comment]
Oh god, why is this not documented in big red letters... Could you maybe hightlight it even more? thanks 😞

**Comment by dfahlander** [comment]
Added [this info](https://dexie.org/docs/Version/Version.stores()#indexable-types) to the docs. Would it do?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Looks good.. Best solution would be if ```equals``` and other query matchers throw a clear exception, instead of this vague ```Data provided to an operation does not meet requirements.```?

**Comment by dfahlander** [comment]
The error message is provided by the browser and varies. Error name will always be "DataError" according to the IndexedDB spec. Adding a layer that validates type in Dexie would mean to do that job twice. Don't think it's worth it. But if many people would suffer from this, it may be an idea to do it. But for example, bulkAdd() would have to iterate the array and check types before forwarding it to IDB. That would come with a cost.
