### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by adussaq** [dfahlander/Dexie.js#705]
I’ve read the where you are going paper and it looks promising. One thing I’d love to see developed is a more complex where query so searching Dexie feels more like querying Mongo. You are close with the single layer object based query in where, but nested objects and object operators could be built out. Just a thought. Thank you!

**Comment by dfahlander** [comment]
You're very welcome! Indeed, I'm planning chained where-clauses, orderBy on Collection, nested and expressions to be part of the new API. Part of the features are are listed [here](https://feathub.com/dfahlander/Dexie.js). The syntax for nested expressions will probably be different from what is suggested in the [Support for Complex Queries feature](https://feathub.com/dfahlander/Dexie.js/+3)
