### ISSUE TITLE
can't get dexie observable working with TypeScript

### ISSUE THREAD

**Issue by jmagaram** [dfahlander/Dexie.js#706]
=== SUMMARY - Can't seem to access dexie-observable/api from TypeScript. Any time I attempt to do that I get a "can't find module" error. I did get the dexie-observable stuff working from javascript without any attempt to import TypeScript definitions, so I suspect there is some kind of issue with the TypeScript definition files. I've created a couple bare-bones projects that illustrate the problem. See my shorter posts below. ===

I've been using Dexie for basic CRUD operations and it all works just fine. I've gotten it to work in Jest as well. So then I tried using dexie-observable and one of my tests fails with "Cannot find module". I have no clue what is going on. I've tried Googling for hours. The TypeScript compiler seems happy it is just that things fail at runtime. I've added dexie-observable to my package.json and I see it in my node_modules folder. I can run the "CreateUUID" function, so I've definitely accessing some of the dexie-observable code. But the `db.on("changes"...)` is failing with the module error. Any clues would be greatly appreciated. If I change  the db.on from `changes` to `banana` TypeScript complains so VS Code is definitely picking up some of the correct code. Also, I've done the `npm install dexie --save` and 
`npm install dexie-observable --save` too.`

= Update =
Now I'm getting a compilation error when I try to run my web site, rather than just running Jest tests. `Module not found: Can't resolve 'dexie-observable/api' in` which I suppose is a good thing. Now need to try to get it to compile.

    import Dexie from 'dexie'
    import 'dexie-observable'
    import { DatabaseChangeType } from 'dexie-observable/api';
    import * as ConfigureDexie from './configureDexie'

    beforeAll(async () => {
        ConfigureDexie.forNode();
        const db = new LocalIndexedDatabase();
        await db.actionItems.clear();
    });

    interface ActionItem {
        readonly id: string;
        readonly title: string;
        readonly isComplete: boolean;
    }

    class LocalIndexedDatabase extends Dexie {
        public actionItems: Dexie.Table<ActionItem, string>;

        constructor() {
            super("obsdb");
            this.version(1).stores({
                actionItems: 'id, title, isComplete'
            });
            this.version(2).stores({});
        }
    }

    // pass
    test("can create a UUID", () => {
        const id = Dexie.Observable.createUUID();
    });

    // pass
    test("can save and get", async () => {
        const db = new LocalIndexedDatabase();
        await db.actionItems.put({ id: "1", title: "call dad", isComplete: false });
        const x = await db.actionItems.get("1");
        expect(x!.title).toBe("call dad");
    });

    // This test fails with Cannot find module 'dexie-observable/api'
    // The TypeScript compiler seems happy but things fail when running
    // the test.
    test("can observe any kind of change", async () => {
        const db = new LocalIndexedDatabase();
        let someChange = false;
        db.on("changes", changes => {
            someChange = true;
        });
        await db.actionItems.put({ id: "1", title: "call dad", isComplete: false });
        expect(someChange).toBe(true);
    })

Here is my tsconfig.json...

    {
      "compilerOptions": {
        "outDir": "build/dist",
        "module": "esnext",
        "target": "es6",
        "lib": [
          "es6",
          "dom"
        ],
        "sourceMap": true,
        "allowJs": true,
        "jsx": "react",
        "moduleResolution": "node",
        "rootDir": "src",
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "suppressImplicitAnyIndexErrors": true,
        "noUnusedLocals": false,
        "baseUrl": "."
      },
      "exclude": [
        "node_modules",
        "build",
        "scripts",
        "acceptance-tests",
        "webpack",
        "jest",
        "src/setupTests.ts"
      ]
    }

**Comment by jmagaram** [comment]
OK I've investigated this further and something weird is happening. Here is a bare-bones project that tries to use dexie-observable.

https://codesandbox.io/s/kmzp626x67

This compiles OK with Chrome. But if I open the link on Edge I get the "cannot find module" error. Why is it compiling ok on Chrome but not Edge?

**Comment by jmagaram** [comment]
Probably not a TypeScript issue. I moved the Dexie observable code into a .js file and this gets a "Module not found" error.

    import Dexie from 'dexie'
    import {
        DatabaseChangeType
    } from 'dexie-observable/api';

    export function registerChangeCallbacks(db) {
        db.on('changes', function (changes) {
            changes.forEach(function (change) {
                switch (change.type) {
                    case 1: // CREATED
                        console.log('An object was created: ' + JSON.stringify(change.obj));
                        break;
                }
            });
        });
    }

**Comment by jmagaram** [comment]
Turned on tracing of module resolution in the build script. Looks ok but is not working.

     ======== Resolving module 'dexie-observable/api' from 'C:/Users/justi/source/repos/gtd/src/db/observe.test.ts'. ========
     Resolution for module 'dexie-observable/api' was found in cache from location 'C:/Users/justi/source/repos/gtd/src/db'.
     ======== Module name 'dexie-observable/api' was successfully resolved to 'C:/Users/justi/source/repos/gtd/node_modules/dexie-observable/api.d.ts'. ========

**Comment by jmagaram** [comment]
I created a brand new project using "create-react-app". Then I added dexie and dexie-observable and did npm install. Added the minimum code to `trydexie.ts` and tried to reference it from `index.tsx`. It compiles ok. But when I try "npm start" I get the error about not being able to find the module dexie-observable/api. I'm going to have to give up here. Here is the code:

https://github.com/jmagaram/dexieobstest

**Comment by dfahlander** [comment]
Not as I initially thought. Really frustrating when simple examples just don't work. However, I won't have time to dig any deeper into this for now. A quick google ended up with me looking at https://github.com/wmonk/create-react-app-typescript/issues/246.

The strange think is, whoever produces the error message:

```
Module not found: Error: Can't resolve 'dexie-observable/api' in '/Users/daw/repos/dexieobstest/src'
```
...if it is typescript or webpack, seems to misunderstand the node resolution model. 'dexie-observable/api' is not relative but it is being search for on local src path instead of looking in node_modules.

**Comment by jmagaram** [comment]
I wish I could help but this is above my head. Only 3 week into Javascript, node, etc. for me. I'm trying to get it to work by casting to "any".

**Comment by dfahlander** [comment]
Yes, do that! The only thing you're missing is the typings for it.

**Comment by jmagaram** [comment]
Ran into the same problem trying to get the sync feature working.

**Comment by jmagaram** [comment]
I did an obvious thing - just copied all the type definitions into a .ts file in my project rather than using the file that was downloaded into the modules folder. Now I can access it.

**Comment by Nulifier** [comment]
I ran into this same problem and wasn't able to solve it by just copying the definitions in.

Could you add an empty js file called api.js in the published library. The issue seems to be that typescript reads the definitions just fine, but webpack tries to read a non-existent module. I tried adding this file on my local copy and it works fine.

I can issue a pull request if required.

**Comment by dfahlander** [comment]
Please pull request. Great you found the reason, thanks!

**Comment by Nulifier** [comment]
See Pull Request #734

**Comment by balovbohdan** [comment]
I prefer to create 'Dexie.ts' wile with this contents:
`import * as DexieSystem from 'dexie'; export default DexieSystem.Dexie;`

**Comment by balovbohdan** [comment]
I prefer to create 'Dexie.ts' file with this contents: `import Dexie from 'dexie/dist/dexie.js'; export default Dexie;`. But notice: you have to create 'global.d.ts' file and declare 'js' modules: `declare module '*.js'`.
