### ISSUE TITLE
put fails on Safari 

### ISSUE THREAD

**Issue by rico** [dfahlander/Dexie.js#718]
My app works flawless on any browser except Safari (11.1.1). 

The operation failing is a simple `dexie.[table].put()`. 

The error says:

    Unhandled rejection: UnknownError: An internal error was encountered in the Indexed Database server
    mapError
    handleRejection
    handleRejection@[native code]

At this point, Safari deletes **all** IndexDB databases. After a restart (of Safari), the database is recreated and populated (using `bulkPut()`).

Does anybody have an idea for debugging or a workaround? 

I'm using dexie 2.0.4.

**Comment by rico** [comment]
I have figured it out. It is the missing `BLOB` support in this version of Safari. This seems to be a very annoying situation with Safari.

**Comment by dfahlander** [comment]
See #618
