### ISSUE TITLE
Better approach for fetching the max value from a table

### ISSUE THREAD

**Issue by rahulecomp** [dfahlander/Dexie.js#723]
Hi first of all a big thanks for this awesome api and for maintaining it. I wanted to know the right approach for fetching max value from a table . I have to fetch only one row from table with the key having the max value.  I follow this approach as my key whose max value i try to get is not an index.

//Searching for max value of modified in table

table.reverse().sortBy('modified').then(function(values){
    let value = values[0];
})

The drawback of this approach is although it provides me the data I need,  I end up fetching the entire table of values whereas I would rather restrict it to only 1 value instead. Is there a  way wherein I could use a limit or a first based approach for fetching only 1 record as it may help with the performance.

**Comment by dfahlander** [comment]
```js
table.orderBy('modified').last()
```

**Comment by rahulecomp** [comment]
Indexed it and  implemented the solution and there is considerable memory performance. Thanks for the great suggestion. Just wanted to know would create an impact if my modified has null values.

**Comment by dfahlander** [comment]
Yes, all non-indexable types will be omitted in the result of orderBy(), including null, undefined, boolean, object. So for example, if you have some objects that lacks the "modified" property (or have it set to null), they will not be enumerated when using table.orderBy('modified').

**Comment by rahulecomp** [comment]
Excellent just like I wanted 👍

**Comment by tobiasBora** [comment]
Is it possible to specify when creating an index (in my case a compound index) a custom sorting algorithm? I'd like to find the maximum integer, but the table may also contain tables (in case of error), and I don't want to fetch these in some queries.
