### ISSUE TITLE
Question: Is it possible using a compound index with a key array?

### ISSUE THREAD

**Issue by fakob** [dfahlander/Dexie.js#724]
Hi, 

Using a whereclause on a `compound index` with a single `key` parameter works fine.
```
imageDB.frameList.where('[fileId+frameNumber]').equals([fileId, frameNumber]).toArray()
```
As it is possible to pass an Array as a `key` parameter I hoped that this also works for `compound index`, but it does not seem so. 
```
const fileIdAndFrameNumberArray = [['fileId1', 0], ['fileId2', 341]];

// this works
imageDB.frameList.where('[fileId+frameNumber]').equals(fileIdAndFrameNumberArray[0]).toArray()

// this does not
imageDB.frameList.where('[fileId+frameNumber]').equals(fileIdAndFrameNumberArray).toArray()
```
Am I doing something wrong?

Btw, thank you for Dexie.js. I am using it in my [MoviePrint tool](http://movieprint.fakob.com/2018/05/alpha-release-is-out/) storing frames and it works great.

**Comment by dfahlander** [comment]
You can use the anyOf method instead of equals and pass an array of arrays to it

**Comment by fakob** [comment]
Ah, thanks for the quick answer. Sorry, I had missed that.
