### ISSUE TITLE
Offset condition on an array of values just generates the last result set

### ISSUE THREAD

**Issue by rahulecomp** [dfahlander/Dexie.js#730]
Hi I came across this strange error . I am using offset condition on a where clause condition .
For example : 
```
var owners = [1,2];
table.where('ownerId').anyOf(owner).offset(offset).limit(pagesize);
```
I end up getting only the values of last result set that is where ownerId is 2. Adding any count condition before adding the offset and limit condition generates value of both ownerIds.
```
table.where('ownerId').anyOf(owner).count()
```
I presume offset condition is picking up values of only the last data set.

I am using dexie 1.4.1 .

**Comment by dfahlander** [comment]
Version 1.4.1 is some years old. Please verify with latest stable.

**Comment by rahulecomp** [comment]
@dfahlander  Just want to assure the backward compatibility considering the fact of deprecated apis.
