### ISSUE TITLE
Table.add/put does not strip functions from the model

### ISSUE THREAD

**Issue by mloffer** [dfahlander/Dexie.js#759]
When attempting to add a record from a model that contains an arrow function, Dexie throws a warning and fails to update the database:

Example model:
```
export class Test {
    private _myBackingProperty = true;
    isTrue = () => this._myBackingProperty;
}
```

`db.test.add(new Test());`

```
Unhandled rejection: DataCloneError: Failed to execute 'add' on 'IDBObjectStore': function () { return _this.myBackingProperty; } could not be cloned.
Error: Failed to execute 'add' on 'IDBObjectStore': function () { return _this.myBackingProperty; } could not be cloned.
```

**Comment by mloffer** [comment]
Upon further testing, this appears to work as expected. Apologies.

**Comment by dfahlander** [comment]
This is a behavior of IndexedDB (and correct behavior according to the structured clone specification): All *enumerable* own properties will be cloned.

You will need to do a workaround for this. For example, setting your function on the prototype (a typical method), OR making the function property non-enumerable using a experimental decorator from a library, or using Object.defineProperty().

**Comment by mloffer** [comment]
Thank you for the detailed explanation! Much appreciated.
