### ISSUE TITLE
modify is not updating

### ISSUE THREAD

**Issue by Akumzy** [dfahlander/Dexie.js#760]
Am trying to modify collections gotten from filter methods but i keep on getting 
`Unhandled rejection: Error: Error: `
with unhelpful stack trace and the table is not being updated too
```js
export async function rename({ rel, path, type, oldPath, stats }) {
	try {
		if (type == 'RND') {
			db.items.filter(e => e.dir.startsWith(oldPath)).modify(function(item) {
				let dir = item.dir.replace(oldPath, path),
					rel = relativePath(dir)
				item.dir = dir
				item.rel = rel
				console.log({ item })
			})
		}
		await db.items.update(stats.ino, { rel, dir: path })
		db.items.toArray().then(docs => {
			store.commit('SET_ITEMS', docs)
		})
	} catch (error) {
		console.log(error)
	}
}
```
![screenshot from 2018-10-29 11-17-08](https://user-images.githubusercontent.com/25849232/47643900-0a911a80-db6d-11e8-80fd-ba62bed70053.png)

**Comment by dfahlander** [comment]
Without knowing the root of the issue yet. I would first recommend to handle promises synchronously in order to understand where it goes wrong:

```js
export async function rename({ rel, path, type, oldPath, stats }) {
	try {
		if (type == 'RND') {
			await db.items.filter(e => e.dir.startsWith(oldPath)).modify(function(item) {
				let dir = item.dir.replace(oldPath, path),
					rel = relativePath(dir)
				item.dir = dir
				item.rel = rel
				console.log({ item })
			})
		}
		await db.items.update(stats.ino, { rel, dir: path })
		await db.items.toArray().then(docs => {
			store.commit('SET_ITEMS', docs)
		})
	} catch (error) {
		console.log(error)
	}
}
```

**Comment by Akumzy** [comment]
I just add await to the query and getting this error message
`"Failed to execute 'update' on 'IDBCursor': The effective object store of this cursor uses in-line keys and evaluating the key path of the value parameter results in a different value than the cursor's effective key.`

I was trying to update the primary key while modify the actual data
[got the answer here](https://stackoverflow.com/questions/22727346/update-single-column-of-indexeddb-records-using-id-key)
```js

export async function rename({ rel, path, type, oldPath, stats }) {
	try {
		if (type == 'RND') {
			await db.items
				.filter(e => e.dir.startsWith(oldPath))
				.modify(function(item) {
					let dir = item.dir.replace(oldPath, path),
						rel = relativePath(dir)
					item.dir = dir
					item.rel = rel
					console.log({ item })
				})
		}
		await db.items.update(stats.ino, { rel, dir: path })
		db.items.toArray().then(docs => {
			store.commit('SET_ITEMS', docs)
		})
	} catch (error) {
		console.log(error)
	}
}

```

**Comment by Akumzy** [comment]
sorry I didn't see your comment before closing the issue.
Any thanks lot
