### ISSUE TITLE
mapToClass() doesn't create TypeScript objects for child objects

### ISSUE THREAD

**Issue by domholmes** [dfahlander/Dexie.js#761]
I may be doing something wrong here.

I have a Typescript object hierarchy, Client has many Projects and Projects have many Tasks. These are configured as for example Array<Project>.

I have included a call to `this.clients.mapToClass(Client);`. When I retrieve a `Client` via Dexie `await this.clientsTable.toArray()`, I end up with a `Client` TypeScript object but with a projects property as an array of plain Javascript objects without their relevant getters/setters and just the scalar properties. My expectation was that the object graph be TypeScript objects all the way down. Is there any way to achieve this if things are worked as intended?

Thanks

**Comment by dfahlander** [comment]
Have a look at typeson. Here's a fiddle that uses it with Dexie : https://jsfiddle.net/dfahlander/qacL14tu/

**Comment by domholmes** [comment]
Thanks! I'll take a look.

**Comment by dfahlander** [comment]
I just updated the sample to clarify you can have nested structures with classes

https://jsfiddle.net/dfahlander/qacL14tu/
