### ISSUE TITLE
The upgrade process not works for me

### ISSUE THREAD

**Issue by gtzinos** [dfahlander/Dexie.js#765]
Hello,

I used the following code to initialize a database.

    var db = new Dexie("Users");

    db.version(1).stores({
        friends: "firstName,lastName"
    });

    db.friends.put({firstName: "George", lastName: "Tzinos"});

Then i tried to use the upgrade process to add a new field with name "comment"
    
    var db = new Dexie("Users");

    db.version(1).stores({
        friends: "firstName,lastName"
    });

    db.version(2).stores({
        friends: "firstName,lastName,comment"
    }).upgrade (trans => {        
        return trans.friends.toCollection().modify (friend => {
            friend.comment = "Test commend";
        });
    });

But it seems like i executed no command in the database.

**Comment by dfahlander** [comment]
The upgrade to version 2 will only happen once. Maybe you had already ran version 2 without the upgrade code and added it later? What happens if you add a `version(3)` with the upgrader attached? Does it run this time?

```js
var db = new Dexie("Users");

db.version(1).stores({
    friends: "firstName,lastName"
});

db.version(2).stores({
    friends: "firstName,lastName,comment"
}).upgrade (trans => {        
    return trans.friends.toCollection().modify (friend => {
        friend.comment = "Test commend";
    });
});

db.version(3).upgrade (trans => {        
    return trans.friends.toCollection().modify (friend => {
        friend.comment = "Test commend";
    });
});
```

**Comment by gtzinos** [comment]
I upgraded only once. But it doesn't work.

Chrome version: Version 70.0.3538.77 (Official Build) unknown (64-bit)
OS: Ubuntu 16.04

**Comment by dfahlander** [comment]
Haven't heard this issue before. Are you using dexie@next or the stable one?

**Comment by dfahlander** [comment]
I put this test based on the master branch (version 3.0.0-alpha) but it worked as expected:

```js
promisedTest ("issue-765", async ()=>{
    // Version 1
    let db = new Dexie('issue765');
    db.version(1).stores({
        friends: "firstName,lastName"
    });
    await db.friends.put({firstName: "George", lastName: "Tzinos"});
    db.close();

    // Version 2
    db = new Dexie('issue765');
    db.version(1).stores({
        friends: "firstName,lastName"
    });    
    db.version(2).stores({
        friends: "firstName,lastName,comment"
    }).upgrade (trans => {        
        return trans.friends.toCollection().modify (friend => {
            friend.comment = "Test commend";
        });
    });

    // Verifying
    const friends = await db.friends.toArray();
    deepEqual(friends, [{
        firstName: "George",
        lastName: "Tzinos",
        comment: "Test commend"
    }], "Upgrader should have run");
});
```

**Comment by gtzinos** [comment]
Now it works great, probably something makes the difference in your code. 

After some tests, I found that it doesn't work without the following line:

       // Verifying
      const friends = await db.friends.toArray();

**Comment by dfahlander** [comment]
Ok I see. So you were still on version 1 all the time.

The reason that the line await db.friends.toArray() must happen, is because [db.open()](http://dexie.org/docs/Dexie/Dexie.open()) must be called for an upgrade to happen. I normally leave out the explicit call to db.open(), as it is implicitely called whenever an operation is done towards the db. In this case toArray().

**Comment by gtzinos** [comment]
Cool, thank you very much!
