### ISSUE TITLE
Issues with Collection.raw and Table.mapToClass

### ISSUE THREAD

**Issue by 1n0m** [dfahlander/Dexie.js#768]
The documentation says that if Collection.raw() is used with a table that is mapped to a class, then plain javascript Objects will be returned. This only seems to be true sometimes.

Table.mapToClass Documentation:
> Applies only to instances returned by [...] but not for callbacks that are part of the filtering query: [...] or if Collection.raw() is being used. In all the latter cases, the methods will emit plain javascript Object instances directly from the database without cloning it into an instance of the mapped class.

For example, I would expect the following code to return plain Objects, but instead it returns instances of Friend

`db.friends.mapToClass(Friend);`
`db.friends.toCollection().raw().toArray();`

However, the following code will return plain Objects. Weirdly this only works if limit is used twice.

`db.friends.mapToClass(Friend);`
`db.friends.toCollection().raw().limit(10).limit(10).toArray();`

Here is a JSFiddle demonstrating the issue: https://jsfiddle.net/1o9c73t2/

**Comment by dfahlander** [comment]
Thanks for the report! Turns out we have a bug that whenever the optimized IDB method IDBIndex.getAll() can be used, we ignore the valueMapper property that was set to null by raw().

**Comment by 1n0m** [comment]
Thanks!
