### ISSUE TITLE
Just make it work on Safari

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#77]
I hereby file this issue as a todo item to make it possible to utilize the IndexedDBShim without having to modify it and call __useShim() etc. Just include the shim and then include Dexie and it should use the shim by default!

== Background ==

Ever since Safari came with its poor native indexedDB support, lots of users have been struggeling with making Dexie work on Safari. There have been some workarounds introduced into Dexie that makes it behave better in Safari but still not perfect. Many users feel that due to the poor indexedDB support built-in to Safari, it would be better to continue using the IndexedDBShim (targetting the WebSQL backend). However, this had become really tricky and the following issues suggests how to make the shim work on modern safari browsers:

Issue #68 
Issue #65 
Issue #63

**Comment by dfahlander** [comment]
Notice: The indexedDBShim is not 100% perfect but it seems that it is still better than the broken native indexedDB support. There are some issues with the shim as well but most common use cases works pretty well.

**Comment by dfahlander** [comment]
Fixed.

From now on, if you prefer to use IndexedDBShim before the native IndexedDB support on Safari, just include the indexedDBShim before including Dexie.js and it will use it instead of the native indexedDB.

**Comment by zebastianviden** [comment]
Hi. Am using the latest Dexie and indexeddbshim. Included shim before Dexie as proposed, then it broke in Firefox, and in Chrome it used WebSQL as default.

**Comment by dfahlander** [comment]
Just include the shim for safari browsers.

**Comment by eclipse1985** [comment]
Hi, in my webapp I want to use native implementation of IndexedDB in case of Chrome Browser, and the shim if Safari. If I include the shim before dexie, all browser will use websql over native implementation... There is a way I can use to force dexie to use the shim only if the browser is Safari (all implementations iOS/OSX, cause if always poor...) ?

**Comment by dfahlander** [comment]
Inspect the user agent and include the shim if it matches. 
This is typically done server-side but you can also accomplish it client-side only:

```html
<script>
if (is_safari) {
    document.write('<script src="https://rawgit.com/axemclion/IndexedDBShim/master/dist/indexeddbshim.js">\x3C/script>');
}
</script>

```

**Comment by eclipse1985** [comment]
Actually I currently use this solution, but is so dirty :)
In my mind there is something like:
> var db = new Dexie("MyDatabase",{ force_shim_if_safari:true });

Is it possible to implement something like this in future implementations?

**Comment by dfahlander** [comment]
It's possible in version 1.4.x to specify the implementations of indexedDB and IDBKeyRange to use:

```js
var db = new Dexie ("MyDatabase", {
    indexedDB: window.indexedDB, // or the shim's version
    IDBKeyRange: window.IDBKeyRange // or the shim's version.
});
```
