### ISSUE TITLE
Using a database in an upgrade handler prevents subsequent upgrade handlers from running

### ISSUE THREAD

**Issue by sechel** [dfahlander/Dexie.js#770]
I have a problem: I run an upgrade step that takes some data from the current database and moves it into a different database. I want to do this in the secure environment of a migration to be sure that everything is atomic. Now, it seems to me that when I touch a different database in an upgrade handler this prevents all other subsequent upgrade handlers from running. The version of the database however is increased. Just the work has not been done.
See this fiddle for an example of this behaviour: https://jsfiddle.net/sechel/ym98pjLg/
Comment out `line 20` to see the effect:
```javascript
let dbName;

QUnit.module('Dexie Migration with extra DB', {
	beforeEach: async () => {
  		dbName = 'TestDB-' + Math.random();
	}
});

QUnit.test('migrate and open DB', async assert => {
	assert.timeout(1000);
	const done = assert.async();
	let db = new Dexie(dbName);
	db.version(1).stores({test: 'id'});
	await db.test.put({id: 1});
	await db.open();
	db.close();
	db = new Dexie(dbName);
	db.version(1).stores({test: 'id'});
	db.version(2).stores({test: 'id'}).upgrade(t => {
		new Dexie(dbName + '-another-unrelated-db');
  	});
	db.version(3).stores({test: 'id'}).upgrade(t => {
		assert.ok('migration handler has been run');
  		done()
  	});
	await db.open();
	await db.test.put({id: 2});
	db.close();
	await db.delete();
});
```

**Comment by dfahlander** [comment]
Thanks for the nice repro!

I see two issues.

1. The upgrade zone is never finished when a Dexie instance is created. ≈Dexie constructor generates dbReadyPromise and openCanceller. I believe the existance of them prohibits the zone to complete until they're settled. I beed to continue debugging this.
2. I tried to use Dexie.waitFor() in the upgrader but it failed. This issue, I've solved and I've also managed to do an atomic copy of objects from the db being upgraded into a new one created in the scope. Still having probs with not version 3 being called.

Will take up this later.

**Comment by sechel** [comment]
Hey David, thanks for the quick investigation, appreciate it it very much! I successfully use ‘Dexie.waitFor()‘ and transfer my data to the new DB. My issue is really the next upgrade handlers that do not execute. 
Greetings from Berlin
Stefan

**Comment by dfahlander** [comment]
Fixed in master
