### ISSUE TITLE
Full text search with lunr example doesn't work

### ISSUE THREAD

**Issue by barneycarroll** [dfahlander/Dexie.js#775]
The cited example for full text search with lunr doesn't work. There are a couple of issues with the original source - Lunr API invocation has changed; you'll need HTTPs to access the example web service; we now have `toArray`; for my own benefit I felt I had to rewrite it as arrow-laden await / async code to trace the logic with less async ambiguity and to see the wood for the (then / function / return) token trees.

[Anyway, here's a live sandbox featuring the cleaned up and modernised example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgxrqwAc2BeVgBEOMfGkoB3ABQBKADpomLVgCcYWCGgAmMFawHAAvgqVsolAOb7WSyrHzmL+AEaatU27HloT1ZW5gAD2soAFc0FSlZfQA+ViNvX2Y2CxgaABVKAGt6AGUaNWxrOkD+GIVWVgDA-G4IbhgoTVEVcKkKytYwiPwabPoIAC9dKRKab0rExT82OBgMFXIAC2sMOABPRVYpLWcSVgBHUN11mViO3d6VDGYMchoIaikAchVn-cvyBa04fei+OLADqVT7fOD4CRLXQwdogPo5ZhyEAyfAwI4YKBwKRHE4ovoAQRU13Wsg6himAHoKawABKNBoqOBJZQsBb8bZQDDORr7GjrBpnAHxDpqDTaXTIPkNAC6IS5jQ6HQgYFG-JgrAAhHwBM8LCpKKFuM8Jp1HFJOdyoCaOp4YJK1awAD6O1jPB44Z7S83yq0KYw+abJVgsSjcayqgWxYVoSq25AR9XO13umDG1gAaldAFFtJ6pKKAip7TLvP6FAA3SgQLTbNabcjbQWA1gdArraOdYM0NkvfGcdS8V0Z9j9ng0fa6-WG40KYFdnvPQTwAqUdaaKxaDhctapk2VOcYCQYCBsNAwCSsAAK+o0cyiajgdnLMH2akIMHuTY7ndYAHlnO+9z4GscAQBYaDtDGP6VNUMBaIIABC+A6LAdDCN2zg7i8dAsMa+xzp2QJQdBlR+KE5DkPAcCsIgqjwE+L4ET+1C6PqeiVLRb4fuOTGVIYJBMXurDkrOxFdqGpJiXOrIqDQLwAMKFA8aAblumFzDOUliaYrC7NYZ4XkugQQDCSI4TQSJTJ2lzPoyjwQQAjCiIYPlIwBfCoPy0UiABkmA4CQYwkAAVPC9BMiAIliZcob0JJ0l9Nw8ViTJcmLpIaDmBgWjrjYYKaZ2c46Q+oRQDQ1ECIex6nueV43hAd4PgxUZEdBEhuJI+BYDQFjENQXxQFAmHkFk1geT8LW8XRj5QM+bm6c4tG7Ps41wLRq3CVZJEoWk6rtdonXdb1j6KBiQ13FkTFlmJlT-oBNDAXAoHgZBJG6ZQ5ChDgtAuJQWjrMB3ANNo8lLNA7hTSCH1ffQD3kEpMBZrA31pXA8P1DQBUkTIAk3Z0rVvcGiw0a6SycNwa1UkdfVoPgVBYBSNMUvig3yWCRAnUauOE6w1BZTWtFud2KipDQ5KTXj0HC6LtQLLDAByf0tOolDPqD4OjAsotCdB-FTXreNCVFhUpYlkkm52qUvOk1zMGAlAqGKViUAB3GsH07BEhg6xY-u2kzHlnkVX+rtAeWGLHFiJVleCq1bZUIZJfH86yS8ACSzC6Mpqndppc6XAUNxwHcDxPEiKgSEiHzOHTYJ-F+BOdqt+D2yoWZ3EsUTAP5L7u0EYsN1NoJB8BWjuI3JE97y-fc4TYXMLRouZAi+SFFgoz9zj+s65tc7G50CUSUJCULrk8yLGDKmsK3LYgO+cBZMeSK+y2YlmlVJ7Bufyw7Hsrr34-CAxpk6J2SpbYWaUz4LGWLlG+SIqDhDoCoZ+yd35Hk-nMaBndlqugQbQXQwDRLgKPnOE+qdnhQIvrAh2t8AFPxAC-OcaDqpfywb-CcdCgEyBAWbY+ptT7f0vlYOBcItZpBQaQt+lgpAf1mII9hyYxGY24UQzooCTT+ljBwH+MAZAT1tKiIkDspC6LJB0SAmBBrtgnqAycBojSoOkelM8Gosb+nJLIEAZA5iwHuPZBAiAQAAHZEAACYHKRWlGQJoaAsgBNQCAHueAdDGVwGQUIKgoB4DJjQCmiAqThG4FkJw9MKQpJMgAAVCfgAADPgAALGUhqNAylBBMhzLxcI1R4DRioDGkUSDoGwLgQJ3QVCdIyVkwJOS8kFLQEUkplAGZjKqfgAAzPgAArBSMZHSyBShGSAXp-TDDSkMEAA).

Despite `tokens` being declared as a multi-entry field, and the web service data structure conforming  to expectations (AFAICT), `db.cards.where("tokens").equals(query)` yields nothing. In fact, `.toArray()` even returns `undefined` rather than an empty array. 

What's going wrong in this example?

**Comment by dfahlander** [comment]
Thanks for looking into this. That sample may be outdated. Could replace it with your sample instead.

The reason your sample didn't return anything from toArray() was that you didn't return the result from toArray().

[Here's an updated sample](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgxrqwAc2BeVgBEOMfGkoB3ABQBKADpomLVgCcYWCGgAmMFawHAAvgqVsolAOb7WSyrHzmL+AEaatU27HloT1ZW5gAD2soAFc0FSlZfQA+ViNvX2Y2CxgaABVKAGt6AGUaNWxrOkD+GIVWVgDA-G4IbhgoTVEVcKkKytYwiPwabPoIAC9dKRKab0rExT82OBgMFXIAC2spLWcSVgBHUN0ATxlY1nX8cgWtOA78CSXdGHaQPpzmORAZfBgdjCg4KR39iasXqUACCKhUGD2sgA3AoFAB6eGsAASjQaKku02SrBYC34rCkUAwzkamxoewahz4cWAHTUGm0umQ5IaAF0QsTGh0OhAwKMKTBWABCPgCADkFhUlFC3DFgMqjkJnKggI6nhgzIFrAAPtrWGKaBAcGLWUqSSqFMYfFjlCxKNxViyYFSaWq-HYNfyGjq9QajTA5awANT6gCi2hNUnpARUmrZ3itCgAbpQIFoCRg4HtFASXfFWB0Cnt4h1KriVDQpGKQZx1Lx9cH2LWeDRNhKpTK5XC0J0cTQ8VXBPACpQ9porFoOMTMwH5QWe50MBIMBA2EPAhBRDpYHQq3QWF3rb27dxZKX58f+xWqwBhQqGtATqfOGeH3vn0zHZzWNAwCRCIJNwefcaFeOcTiTXQ4AgagpAARneO01F+YAzhUC5EALEAADJMBwEgxhIAAqJ56EuEBDDnJcVzYE57XoM8j06E9GPPctKzFQRJDQcwMC0ccbHOOA306D8ZlUeBQigGg4GsajV1YX9-wABSlDQ5ijeA7Ego5aQXXsJDcSR8CwGgLGIagzigKAX3ILJrDQi5dPPXtkO0+5gC-TD1k2Ry4EwvzWEo7te17bc0kFQztGM0zzLgSzvhsjA7JcoKQtCgB5ZxCBgcgaHwTNoIsNB2n00KtEochQhwWgXEoLQ9gK7gGm0G8lmgdxUrCyrqvofLyHvGBQ1gGqOLgAb6hoETQtYGQSC6ksypmuBFlYTCxSWThuH8xFYostBTkoLB4X2+EQWsm8hKIeK0FlealtC6hePTTCpGAK9UhoSjnIemaPrSWoFj6gA5eqWnUShILajrRgWT65xmwx7pmyokdSudgrKti+lPOdsYHMV0ghZgwEoFQGSsShstytg+nYcFIREsTsUCgQspyvL8CTb5dl+ZCpJk04hKmS97VYsr2KrABJZhdAfJ9+0Pc95No5whfQuAXCkrIQS0dw-JMjBTze1K8JgZHQrGc9vupAk9Jms2Ld7QjUtI5hMM+zJnnyQosFGIJxkN43gBYFQbbiUOMZkaPYSxiWccY9944J3J5kWdrH1YUm9FeHK4CyFdXmmi9OkVFWcTT5Y1g2fU84LiA5RF5iE6bssrw41OFmWATs6wqhwjoFQi9brpLCkcu5i7pZq7bfvaF0Rv0rbsW8eT68xU79Oe7JrC68LkBi-PMvlwUyf05n2v4HrxemOX3Hz3x9fN+7zPe9ef7QIP1fe2PmiK6ni+Bo4ZpBvtjFeHQrSVDODQKuzp7adHVB8cEZMpDOggR0SAmBrLFngXfKskppSyhHoqTi1AYBChElaSisgQBkDmLAPKMFmB4DggAZkQHBAADBRVkZAmhoCyAgFA6BsC4EQCAHQG5cBkFCCoKAeBNo0G2ogRE4RuBZCcFQY6kjNwAAEABM+BOH4AACzwn4iwcxgFRDEFoY8AUeBxoqEmhREgIicB4G6CoOxsj5HiMUco1Rt0NGHWOl4gx+BWH4AAKzwi8ddOxTpHETV4DwwwQA)

**Comment by dfahlander** [comment]
[Using a limit on the search result](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgxrqwAc2BeVgBEOMfGkoB3ABQBKADpomLVgCcYWCGgAmMFawHAAvgqVsolAOb7WSyrHzmL+AEaatU27HloT1ZW5gAD2soAFc0FSlZfQA+ViNvX2Y2CxgaABVKAGt6AGUaNWxrOkD+GIVWVgDA-G4IbhgoTVEVcKkKytYwiPwabPoIAC9dKRKab0rExT82OBgMFXIAC2spLWcSVgBHUN0ATxlY1nX8cgWtOA78CSXdGHaQPpzmORAZfBgdjCg4KR39iasBwQDQ0KQAJgArIcrn0AIIqFQYPayADcCgUAHpMawABKNBoqS7TZKsFgLfisKRQDDORqbGh7BqHPhxYAdNQabS6ZCMhoAXRCtMaHQ6EDAoyZMFYAEI+AIAOQWFSUULcBWAyqOanCqCAjqeGC8qWsAA+ptYCpoIJgCv5OrpeoUxh8JOULEo3FWfJgLLZBr8diNkoaZotVptGtYAGpLQBRbR2qScgIqY0C7wuhQAN0oEC0VIwcD2iipfvirA6BT28Q6lXJKjBCrhnHUvEtMfYrZ4NE2SpVao1GLQnTJNApUgVgngBUoe00Vi0HFpRdtmsrI86GAkGAgbGngQgoh0sDok7oLCHrtHHu4sjrG5v48bk4AwoVrWhF8vnKur6OH1MY5nGsNAYAkIQgiPB4LxoV51xObNdDgCBqCkABGd4PTUX5gDOFQLkQSsQAAMkwHASDGEgAConnoS4QEMddt13NgTk9eh72vTpby4h8GybQRJDQcwMC0BcbHOOB-06QCZlUeBQigGg4GsFi91YMCIIABRVDQ5mTeA7CQo52U3UcJDcSR8CwGgLGIagzigKBf3ILJrHwi5TIfUccOM+5gGAoj1k2Ty4CIsLWCY4dR1HE80mlSztGs2z7LgRzvhcjA3J8qKYtigB5ZxCBgcgaHwIsUIsNB2nM2KtEochQhwWgXEoLQ9gq7gGm0V8lmgdxcrixrmvocryA-GA41gFqmzgCb6hoGTYtYGQSCG2s6pWuBFlYIiFSWThuHC7FUoctBTkoLBMXOzE4Wc18pKIdK0HVdatti6hRILIipGAZ9UhoJjvI+laAbSWoFjGgA5dqWnUSgkL6gbRgWQH1xWwx3pWyosdy9dorq-i+jvddiYnBV0iRZgwEoFQuSsShitKtg+nYRFkRkuTSUigQipKsr8Gzb5dl+HClJU04pKmJ9PT4uqBMnABJZhdE-b9xyvB91LY5wpYIuAXCUrI4S0dwwpsjA7z+3LyJgbHYrGB9gdZKkzJWu2HdHKjcro5giMBzJnnyQosFGIJxkt63gBYFQXbiWOCZkZP0SJhWSa4gD04p3J5kWfqv1YWm9FeEq4CyXdXmWx9Om1HWyTz5Y1g2S0y4riANRlniM67+tnybXOFmWCTi+IqhwjoFQq97rpLCkeu5iHpZm77cfaF0Tv8r7uWyezl8FUH-OR7p4i28rkBq4fOudw0xf85X1v4HbzfuO30mH3J-fD+HwvR9ecG4IX13qOa+rEG5LwflaNGaQX7Ex3h0F0lQzg0Cbr6d2nRDQfERHTKQvoEEdEgJgZyNZ0Fv0nMqVU6oZ7ainNQGAMoZIuiYrIEAZA5iwDKqhZgeB0IAGZEDoXQoxfkZAmhoCyAgFA6BsC4EQCAHQh5cBkFCCoKAeBDo0GOogbE4RuBZCcFQa6CijwAAFwT4AAAz4AACyYnEiwOxUFRDEFYY8KUeB5oqEWoxEg0icB4G6CoVxKi1FyI0VonRr19GXWuoEsx+BeH4EhJiQJz1XE+g8QtXgwjDBAA) speeds up the queries a lot.

**Comment by barneycarroll** [comment]
Oh wow! Haha thanks @dfahlander. I've been away from the keyboard for too long. Thanks for spotting my mistake! Feel free to use this example in the documentation if that suits.

**Comment by dfahlander** [comment]
I start by linking to this issue from where the lunr sample is referenced. I think the sample needs some small tweaks before becoming official sample. For example it should call getTokenStream() with the query as well to get more accurate results, and maybe handle multiple words if needed.

If you for some reason would improve it further, please post a link and I could use it. I'm glad you did the heavy lifting of downloading accurate data, and finding out how to use the new lunr api. Thanks!

**Comment by stephent** [comment]
It seems that the [updated sample](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgxrqwAc2BeVgBEOMfGkoB3ABQBKADpomLVgCcYWCGgAmMFawHAAvgqVsolAOb7WSyrHzmL+AEaatU27HloT1ZW5gAD2soAFc0FSlZfQA+ViNvX2Y2CxgaABVKAGt6AGUaNWxrOkD+GIVWVgDA-G4IbhgoTVEVcKkKytYwiPwabPoIAC9dKRKab0rExT82OBgMFXIAC2spLWcSVgBHUN0ATxlY1nX8cgWtOA78CSXdGHaQPpzmORAZfBgdjCg4KR39iasBwQDQ0KQAJgArIcrn0AIIqFQYPayADcCgUAHpMawABKNBoqS7TZKsFgLfisKRQDDORqbGh7BqHPhxYAdNQabS6ZCMhoAXRCtMaHQ6EDAoyZMFYAEI+AIAOQWFSUULcBWAyqOanCqCAjqeGC8qWsAA+ptYCpoIJgCv5OrpeoUxh8JOULEo3FWfJgLLZBr8diNkoaZotVptGtYAGpLQBRbR2qScgIqY0C7wuhQAN0oEC0VIwcD2iipfvirA6BT28Q6lXJKjBCrhnHUvEtMfYrZ4NE2SpVao1GLQnTJNApUgVgngBUoe00Vi0HFpRdtmsrI86GAkGAgbGngQgoh0sDok7oLCHrtHHu4sjrG5v48bk4AwoVrWhF8vnKur6OH1MY5nGsNAYAkIQgiPB4LxoV51xObNdDgCBqCkABGd4PTUX5gDOFQLkQSsQAAMkwHASDGEgAConnoS4QEMddt13NgTk9eh72vTpby4h8GybQRJDQcwMC0BcbHOOB-06QCZlUeBQigGg4GsFi91YMCIIABRVDQ5mTeA7CQo52U3UcJDcSR8CwGgLGIagzigKBf3ILJrHwi5TIfUccOM+5gGAoj1k2Ty4CIsLWCY4dR1HE80mlSztGs2z7LgRzvhcjA3J8qKYtigB5ZxCBgcgaHwIsUIsNB2nM2KtEochQhwWgXEoLQ9gq7gGm0V8lmgdxcrixrmvocryA-GA41gFqmzgCb6hoGTYtYGQSCG2s6pWuBFlYIiFSWThuHC7FUoctBTkoLBMXOzE4Wc18pKIdK0HVdatti6hRILIipGAZ9UhoJjvI+laAbSWoFjGgA5dqWnUSgkL6gbRgWQH1xWwx3pWyosdy9dorq-i+jvddiYnBV0iRZgwEoFQuSsShitKtg+nYRFkRkuTSUigQipKsr8Gzb5dl+HClJU04pKmJ9PT4uqBMnABJZhdE-b9xyvB91LY5wpYIuAXCUrI4S0dwwpsjA7z+3LyJgbHYrGB9gdZKkzJWu2HdHKjcro5giMBzJnnyQosFGIJxkt63gBYFQXbiWOCZkZP0SJhWSa4gD04p3J5kWfqv1YWm9FeEq4CyXdXmWx9Om1HWyTz5Y1g2S0y4riANRlniM67+tnybXOFmWCTi+IqhwjoFQq97rpLCkeu5iHpZm77cfaF0Tv8r7uWyezl8FUH-OR7p4i28rkBq4fOudw0xf85X1v4HbzfuO30mH3J-fD+HwvR9ecG4IX13qOa+rEG5LwflaNGaQX7Ex3h0F0lQzg0Cbr6d2nRDQfERHTKQvoEEdEgJgZyNZ0Fv0nMqVU6oZ7ainNQGAMoZIuiYrIEAZA5iwDKqhZgeB0IAGZEDoXQoxfkZAmhoCyAgFA6BsC4EQCAHQh5cBkFCCoKAeBDo0GOogbE4RuBZCcFQa6CijwAAFwT4AAAz4AACyYnEiwOxUFRDEFYY8KUeB5oqEWoxEg0icB4G6CoVxKi1FyI0VonRr19GXWuoEsx+BeH4EhJiQJz1XE+g8QtXgwjDBAA) may be broken (haven't been able to work out why so far). Catches an exception here:

`{ line: 2025, column: 51, sourceURL: 'dexie' }`

**Comment by harrisonlo** [comment]
Is the sample broken? How do I trigger search in the console on flems.io? I don't see an exception error
