### ISSUE TITLE
Dexie throws AbortError instead of QuotaExceededError when running out of disk space

### ISSUE THREAD

**Issue by bennyn** [dfahlander/Dexie.js#776]
I was testing what happens to an IndexedDB instance when running out of disk space. To simulate this scenario, I used Microsoft's [consume.exe debugging tool](https://blogs.msdn.microsoft.com/vijaysk/2012/10/26/tools-to-simulate-cpu-memory-disk-load/) to use all of my computer's disk space.

I was expecting Dexie to throw a [QuotaExceededError](https://dexie.org/docs/DexieErrors/Dexie.QuotaExceededError) but I received an [AbortError](https://dexie.org/docs/DexieErrors/Dexie.AbortError) which had the message "QuotaExceededError " (notice the space at the end!).

Because Dexie does not throw a `QuotaExceededError`, I cannot handle it with `catch('QuotaExceededError', ...)` as suggested in the [docs](https://dexie.org/docs/DexieErrors/Dexie.QuotaExceededError#sample-using-promisecatch).

**Screenshot**

![unbenannt](https://user-images.githubusercontent.com/469989/48952605-0a552680-ef43-11e8-861b-78e917404d5c.PNG)

To verify that there is no IndexedDB quota available, I was executing `navigator.storage.estimate()` which was reporting: `{quota: 26947, usage: 26947}`. Maybe this helps constructing a test case.

Here is a minimal example to reproduce the issue (for me it's 100% reproducible):

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>HTML5</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/dexie/3.0.0-alpha.6/dexie.js"></script>
    </head>
    <body>
        <p>I want to catch a `Dexie.QuotaExceededError`.</p>
        <script>
          (async () => {
            const db = new Dexie('MyDatabase');

            db.version(1).stores({
              friends: '++id, name, age'
            });

            const friend = {
              name: 'Camilla',
              age: 25,
              street: 'East 13:th Street'
            };

            const {quota, usage} = await navigator.storage.estimate();
            console.log(`Quota: ${quota}, Usage: ${usage}`);

            await db.friends.add(friend)
              .then(() => console.log(`Saved ${friend.name}.`))
              .catch('QuotaExceededError', error => {
                console.log('If you see this message, then error handling works as expected.', error);
              })
              .catch(error => {
                console.log('error.message', error.message);
                console.log('error.name', error.name);
                console.log('error', error);
              });
          })();
        </script>
    </body>
</html>
```

If you have the `consume.exe` debugging tool (which ships with the [Windows Server 2003 Resource Toolkit](https://superuser.com/questions/396501/how-can-i-produce-high-cpu-load-on-windows)), then you can run `consume -disk-space` to run out of disk space. When doing that and executing my code from above, then you should see the `AbortError` from Dexie (which should be a `QuotaExceededError`).

**Comment by dfahlander** [comment]
Thanks, will see how this should be solved best. Very nice of you to nail down this behavior 👍

**Comment by dfahlander** [comment]
The reason for Dexie's behavior is that it just reflects the native IndexedDB behavior - neither the onsuccess or onerror events gets signalled on the operations. Instead, the "abort" event on the IDBTransaction gets signaled. The underlying error can be picked from the 'error' property on IDBTransaction instance. When this happens, Dexie will reject the transaction promise with AbortError and put IDBTransaction.error as inner exception.

For now, I think updating the docs to inspect AbortError.inner property would be the most safe thing to do if we should continue to reflect what is happening natively.

**Comment by dfahlander** [comment]
@bennyn I've updated the docs to inspect error.inner in the catch clause. Could you verify that the new docs are accurate? Kind regards /David

**Comment by bennyn** [comment]
@dfahlander I updated my code and I was able to catch the error (big 👍 on this one):

```js
db.friends.add(friend)
.then(() => console.log(`Saved ${friend.name}.`))
.catch(error => {
if ((error.name === 'QuotaExceededError') ||
  (error.inner && error.inner.name === 'QuotaExceededError')) {
  console.log('If you see this message, then error handling works as expected.', error);
} else {
  console.log('Here is something wrong:', error);
  console.log('error.message', error.message);
  console.log('error.name', error.name);
  console.log('error', error);
}
});
```

Catching the error on [Table.add()](https://dexie.org/docs/Table/Table.add()) now works. 

In most of my test runs the `QuotaExceededError` came up when executing `db.friends.add`, but I also had a case where opening the database didn't even work. 

**Error message:**
> DOMException: Encountered full disk while opening backing store for indexedDB.open.

Unfortunately I haven't been able to reproduce this case. Do you have an idea on how to catch this error (full disk when opening database) too?

**Comment by dfahlander** [comment]
Thanks @bennyn for testing it out and finding the other DOMException that could occur! No, I haven't heard about it. It would be very interesting if that exception could be identified. For an unknown error, if you could log:

* **error.name**
* **error.code**
* **error.message**
* error.inner && **error.inner.name**
* error.inner && **error.inner.code**
* error.inner && **error.inner.message**

Might be something browser-specific, but any findings would be of interest.

**Comment by dfahlander** [comment]
Edit: Maybe hard to reproduce, but if it would happen again, having that info would be very nice to have

**Comment by bennyn** [comment]
Ok! If it ever happens again, I will trace the error and report back. Closing this issue now as it has been resolved through the docs. Thank you very much!

**Comment by dfahlander** [comment]
Should also inspect inner of [OpenFailedError](https://dexie.org/docs/DexieErrors/Dexie.OpenFailedError) because unless db.open() was called explicitely, the underlying error that rejected the implicit call to db.open() will be encapsulated within an OpenFailedError when an operation such as Table.add() was attempted.

**Comment by YourDev2018** [comment]
I was making the same mistake with myself, over and over again.

Only resolved when I discovered that there was little space on my SSD (less than 1GB) and I freed up more space.

At the same moment the error disappeared.

**Comment by 24e** [comment]
> 我一遍又一遍地对自己犯了同样的错误。
> 
> 只有当我发现我的SSD上的空间很小（小于1GB）并且我释放了更多空间时才解决。
> 
> 在同一时刻，错误消失了。

示范一下
