### ISSUE TITLE
Using dexie-export-import and get export() and import() function undefined

### ISSUE THREAD

**Issue by giddens9527** [dfahlander/Dexie.js#786]
I'm using dexie with my electron app and it works perfectly. Recently I want to add dump JSON feature to my app and found there's already a package for this. I imported the package and tried to export the data from my existing db as suggested from the README. But there was error saying export is undefined. Just as
```
import Dexie from 'dexie';
import 'dexie-export-import';

const db = new Dexie(key);
db.version(1).stores({ files: '++id,name,content' });
db.on('populate', () => { ......

console.log(db.export)
```
outputs undefined.

I also tried
```
import { exportDB } from 'dexie-export-import'
......
await exportDB(db);
```
the error message is "Cannot convert undefined or null to object dexie"

I'm using dexie 2.0.4 (also tried the lasted alpha version, same error though).

**Comment by eduard2014** [comment]
I started to use dexie-export-import but it shows me the same error at production. In development mode it works well and I can generate the export and after that I can import de database.  This is the error stack.  

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at c (dexie.js:44)
    at Function.b (dexie.js:112)
    at dexie-export-import.mjs:411
    at dexie-export-import.mjs:68
    at Object.next (dexie-export-import.mjs:49)
    at dexie-export-import.mjs:53
    at Object.next (dexie-export-import.mjs:49)
    at dexie-export-import.mjs:53
    at Object.next (dexie-export-import.mjs:49)

I'm using dexie(3.0.0-alpha.6), dexie-export-import(1.0.0-alpha.8), typescript(3.2.2) and webpack(4.27.1).

**Comment by dfahlander** [comment]
Thanks for the report. I will not be able to track down this issue for the nearest month. I suppose there would be no specific dexie-knowledge required to track it down though as it seems to be webpack related. So if there is anyone kind out there who could, it would be great.

**Comment by amxmln** [comment]
Could this be related to the `dexie-export-import` simply not extending the right prototype if it’s included via an `import` statement and then running through Webpack? I ran into this issue just now and for me importing and using `exportDB` works, at least in development (I couldn’t try it in production yet), but db.export is `undefined`.

So perhaps the `Dexie` imported by `dexie-export-import` is a different object than the one imported when the database is created, i.e. right before importing `dexie-export-import`?

**Comment by dfahlander** [comment]
The standalone functions `importDB()`, `exportDB()` and `importInto` are equivalent of calling `Dexie.import()`, `db.export()` and `db.import()` repectively. So my advice here is to use them instead.

**Comment by amxmln** [comment]
Yes, I gathered as much from reading through the source-code of the addon. Perhaps this could be made clear in the README? I will report again if I have any issues running this in production like the OP mentioned.

**Comment by dfahlander** [comment]
Indeed. I just now added export/import to the official dexie docs: https://dexie.org/docs/ExportImport/dexie-export-import. There this stands a bit clearer. Will update the package README.md too.

**Comment by amxmln** [comment]
Thank you for your quick response and this package in general, it’s been a bliss to use!
