### ISSUE TITLE
Safari Dexie+IndexedDBShim not blowing up... but not working either.

### ISSUE THREAD

**Issue by isaacbdawson** [dfahlander/Dexie.js#79]
In the inspector it looks like my databases are being created, but they are empty.
I see these errors in the console after an attempted add transaction.

[Error] 0: Data Error - Could not eval key from keyPath
	n (IndexedDBShim.min.js, line 2)
	(anonymous function) (IndexedDBShim.min.js, line 2)
	(anonymous function) (IndexedDBShim.min.js, line 2)
[Error] TypeError: 'undefined' is not an object (evaluating 'e.preventDefault')
	onerror (Dexie.js, line 1273)
	(anonymous function) (IndexedDBShim.min.js, line 2)

**Comment by isaacbdawson** [comment]
an update to my issue specifically, it appears to be related to having keys that are [field1+field2]

not sure at this point where the actual problem is (dexie, indexedbshim, safari)

they do, however, work fine in chrome/android

**Comment by dfahlander** [comment]
The shim doesn't support array keys (compound /composite keys) - same limitation as internet explorer has. A general problem with the shim is also that it doesn't fire correct error events so when something like this happens, you will also get exceptions in Dexie.js when it tries to call e.preventDefault().

Except maybe checking for the existance of preventDefault in the error event, this is something that we cannot solve in Dexie. I wish I had some time to try debug the IDBShim but also hope the owner or someone else could look more into that. SQL has built in support for composite keys, so I suppose it wouldn't be to hard to implement it in the shim.

**Comment by isaacbdawson** [comment]
is there also an issue with transaction and the shim?

**Comment by dfahlander** [comment]
There are a bunch of unit tests that fails when using the shim. I believe transaction should work because its the foundation of indexedDB. But it depends what you mean with transaction. You can try running the Dexie unit test suite at test/run-unit-tests.html and click the shim checkbox when in safari or chrome.

**Comment by dfahlander** [comment]
Also,  make sure to use the latest version of the shim from githu.

**Comment by isaacbdawson** [comment]
I think I finally narrowed down the problem I was having. 
Apparently it does not like you running where statements on things other than the key?!
