### ISSUE TITLE
Dexie.Observable: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by bennyn** [dfahlander/Dexie.js#791]
We are using `dexie-observable` in our web application and our error reporting shows the following error for some of our clients:

> Message: Cannot read property 'indexOf' of null

It complains about [the following code](https://github.com/dfahlander/Dexie.js/blob/v2.0.4/addons/Dexie.Observable/src/on-storage.js#L6):

> if (event.key.indexOf("Dexie.Observable/") === 0) 

So it seems like that the `event` does not always has a `key` property, so the `indexOf` operation fails. Can you double check that?

**Comment by dfahlander** [comment]
It is reacting to the "storage" event. When storage is cleared, it may not come with a key. A valid fix would be to null-check event.key.
