### ISSUE TITLE
Add AMD module loading

### ISSUE THREAD

**Issue by Nilos** [dfahlander/Dexie.js#80]
It looks like dexie.js is always assigning itself to a global variable.
It would be nice to also be able to use dexie.js with amd module loading.

**Comment by dfahlander** [comment]
Should be resolved now. Also added a sample requirejs app under samples/requirejs that demonstrates how to use Dexie with requirejs.

**Comment by dfahlander** [comment]
Reopening because the issue needs to be applied for addons as well.

**Comment by Nilos** [comment]
Thanks!
