### ISSUE TITLE
Table schema not changes until data pushed

### ISSUE THREAD

**Issue by panthera** [dfahlander/Dexie.js#808]
Lately I noticed something that on changing the table version, the update is not reflecting straight away until some data is pushed on to the updated schema. The sample code that I followed is provided below, is it the expected behavior 

           ` var db = new Dexie("test_db");
                   db.version(1).stores({
                   friends: 'name,shoeSize' });
		   db.version(2).stores({
                   friends: 'name,shoeSize,brand'
                   }).upgrade(tx => {
			return tx.friends.toCollection().modify(friend => { friend.brand='n/a' })
		  });

          //
          // Put some data into it
          //
		  
		  db.friends.put({name: "zerocool", shoeSize: 8, brand:'nico'}).then (function(){
              //
              // Then when data is stored, read from it
              //
              return db.friends.get('Samuel');
          }).then(function (friend) {
              //
              // Display the result
              //
              alert ("Samuel has shoe size " + friend.shoeSize);
          }).catch(function(error) {
             //
             // Finally don't forget to catch any error
             // that could have happened anywhere in the
             // code blocks above.
             //
             alert ("Ooops: " + error);
          });`

**Comment by dfahlander** [comment]
The upgrade will happen once you do any of the following:

1. call db.open()
2. Interact with the database in any way (which will implicitly call db.open() under the hood)

So if you want to make sure the upgrade happens, do db.open().then(...)

**Comment by panthera** [comment]
Thanks, tried as you suggested and it's working like a charm. Once again thanks for the quick response.
