### ISSUE TITLE
Travis build fails (unknown reason) since 2019-03-28

### ISSUE THREAD

**Issue by dfahlander** [dfahlander/Dexie.js#821]
On 2019-03-28 addons-tests started failing on travis on karma code "webServer.listen()". The first time it happened was 2019-03-28 after merging a PR into master. Unit tests work fine when run locally but not in travis. The same date (2019-03-28), travis had status issues for a long time with slow VM boot times. It could be related. Need to file this issue on travis somehow. I suppose there's a karma-related workaround.

**Comment by oleersoy** [comment]
I usually just ask directly on the Travis-CI github repository.  [Here's are some of the questions I've asked in the past.](https://github.com/travis-ci/travis-ci/issues?q=is%3Aissue+author%3Aoleersoy+is%3Aclosed)  BanzaiMan (Banzai!) has always been beyond helpful in getting it resolved.

I've been researching how to test Angular with Jest as I prefer headless runners.  I noticed that theres [fake-indexeddb](https://github.com/dumbmatter/fakeIndexedDB) for unit testing.  Ever considered running everything with Jest and fake-indexeddb?

Wish I could help more.  Need to get up to speed on the details.

**Comment by dfahlander** [comment]
Thanks! It's just that the first thing their readme sais, is "No issues in this repo". Seems they've moved their collaboration into their forum.

**Comment by oleersoy** [comment]
Ah they are running their own discourse server now.  I just logged in with my github account and after that just click on the hamburger icon and select new, and then `new topic`.  I just created a request for help:

https://travis-ci.community/t/travis-build-failing-for-dexiejs-and-we-are-not-sure-why/2867

Usually they as for the full build log, which can be retrieved from the travis home page by clicking on 'Raw Log' on the virtual machine console that shows the build progress.  

Do you have a link to the Travis Home Page that shows the DexieJS build?  I tried looking but it's not showing me the build terminal when I click on current, and so I'm assuming that only the owner of the account is allowed to see it.

**Comment by dfahlander** [comment]
Thanks @oleersoy ! When I for example list commits on github and click the build status icon (green or red) it will take me to the travis builds and I can see the logs.

Here's the failing travis logs for the latest master commit: https://travis-ci.org/dfahlander/Dexie.js/builds/512355553?utm_source=github_status&utm_medium=notificatio

I wish I had time to look at it now but I hopefully on friday, I could get some time for it.

**Comment by oleersoy** [comment]
Sounds good - I'll add the commit and job logs to the question on Discourse.

**Comment by dfahlander** [comment]
Seems to be an issue with karma-browserstack-launcher. I've upgraded packages and all unit tests in master succeeds, but only when karma connections dont fail, which happens too often. I've merged in the upgraded packages and some karma config changes. Also limited number of concurrent jobs in travis in order to prohibit overloading browserstack. I've also posted a support ticket to browserstack.

For now, I need to monitor travis jobs and restart them until they succeed. But at least there is now a possibility to run the tests.

**Comment by dfahlander** [comment]
Configured travis to run one job at a time and Browserstack integration is fine again. So builds are much slower now, but may have to live with that as Browserstack will bail out on too many parallell jobs. Before it seemed to just accept it and queue them but not now. Have to live with slower builds for a while but at least, the CI jobs seems stable again.
