### ISSUE TITLE
Dexie Usage Questions

### ISSUE THREAD

**Issue by MVSICA-FICTA** [dfahlander/Dexie.js#822]
I've been taking a dive into the Dexie Docs this week and am delighted with the robustness of the API. Thanks for making IDB great to work with! Discovering Dexie is like finding a pot of gold at the end of a long rainbow and at this point I have a some questions related to using Dexie with my project. These questions are posted as a sequence of separate issues.

**Comment by dfahlander** [comment]
Ok, thanks! I've tried to answer some of the questions.
