### ISSUE TITLE
How is JSON data stored and handled?

### ISSUE THREAD

**Issue by MVSICA-FICTA** [dfahlander/Dexie.js#823]
My app is all about composing music and there are a significant number of models involved. For instance, a musical score is made up of relationships between a score and it's tracks and their phrases. All of these sections are individual JSON files that are then pinned together with IDs. These JSON documents would be worked with locally using Dexie and then synced to a optional server like FireStore.

What I am not yet clear about is how JSON is stored via Dexie. Is JSON text stored as a blob? Does a blob need to be converted on input/output and does Dexie handle that? Also, on second thought maybe it is better to just convert a nested JSON document to an object and then store and work with the object instead?

**Comment by dfahlander** [comment]
IndexedDB stores javascript objects. So if your documents are JSON docs, they can be perfectly stored as objects (such as the result from for example JSON.parse(json)). If you choose to store the JSON as text instead, that would work as well, but in case you like to index certain properties, you must store them as objects.

**Comment by dfahlander** [comment]
If you store large data, such as mp3, images or movies, they should be stored as a Blob instance within your object. That way you can retrieve the smaller part faster and only when you need to download the large content, you can read the blob. Example:

```js
const db = new Dexie('music-store');
db.version(1).stores({
  songs: 'id, title'
});

async function addSong(id, title, mp3Blob) {
  await db.songs.add({
    id,
    title,
    mp3Blob
  });
}

async function findSong(title, {exactMatch}) {
  query = exactMatch ?
    db.songs.where('title').equals(title) :
    db.songs.where('title').startsWithIgnoreCase(title);
  return await query.toArray();
}

playAround().catch(error => console.error (error));

```

To query a song, call findSong() something like this:
```js
findSong("water", {exactMatch: false}).then(songs => {
  console.log(songs);
});

```
