### ISSUE TITLE
What is the preferred way of making relationship joins?

### ISSUE THREAD

**Issue by MVSICA-FICTA** [dfahlander/Dexie.js#824]
I'm storing different model sections in separate stores. The sections have IDs or pins that can be changed to produce a different score layout/arrangement. Some sections could be hidden or be made visible again and they can also be added or removed. This means that IDs or pins or properties would be changed at runtime.

There is a dexie-relationships addon which might be helpful? What is a best way produce a score made up of sections that continually evolve as changes are made to models that are hierarchical and contained in separate stores?

**Comment by dfahlander** [comment]
You can use dexie-relationships if you like, or you can lookup related entities manually. Just make sure to index the properties that acts as foreign keys.

If you need many2many relations, there's an exampe in issue #815

**Comment by MVSICA-FICTA** [comment]
Being able to dynamically update the foreign keys and react to the new relationships is perfect 💯
