### ISSUE TITLE
Is it also possible to store functions in IDB?

### ISSUE THREAD

**Issue by MVSICA-FICTA** [dfahlander/Dexie.js#825]
I'm using a FRP approach in my project so it would be great to be able to store RxJS related functions and also lit-html template functions. Being able to store these aspects and then compose them would open up a wonderful vista!

I'm choosing to implement a reactive data and logic first approach, essentially opposite of the common frameworks. Instead of components being the main way to think about app structure, I'm "thinking outside the box" here and handling components more like DOM decorating side-effects.

**Comment by dfahlander** [comment]
You cannot store functions in IDB, but if you declare a set of functions within your app, your objects can contain a named function so that you can invoke it when you render it.

**Comment by MVSICA-FICTA** [comment]
Yes, that will work well 👍 

I'm interested in the possibility of storing lit-html template strings and injecting / composing them to produce UI sections, will continue to explore.
