### ISSUE TITLE
Is mapToClass what I'm thinking it is?

### ISSUE THREAD

**Issue by MVSICA-FICTA** [dfahlander/Dexie.js#826]
One of the most enthralling things that I discovered when reading the Dexie Docs is the mapToClass functionality. I'm now wondering if it could accommodate some special use cases as well as play a significate role in sorting out where the functional business logic of my project can be placed.

A special use case would be storing XState Statecharts in a store and then mapping queried Statecharts to a class that would represent a XState Machine. So in my mind the end class instance would contain the given cloned Statechart and it's last state as properties. Then it would also have a const for a new Machine that would use the statechart and startup using it's saved last state. Then there would be functions in the class to start and stop the Machine instance as well as other related functions. XState is a new and great way to manage states in an app, please see more info here: https://xstate.js.org/docs

Is this the type of use case that mapToClass can be used for? If so then this pattern can be used for other types of object stores my app requires as well. Another use case would be to map a score object to a class that would have a specific RxJS processor that would then digest the data and be subscribed to by observers that then render the final result. In my app data is central and it does seem that this type of coupling between a type of store object and it's handler class is powerful and also a great way to arrange business logic.

Recently, I had noticed in the two different versions of a new TypeScript Dexie demo that related logic functions were inside the mapped to class on the initial demo and then taken out and placed in a utilities module on the 2nd version. Is the class mapped to suppose to remain a pure data object or is it okay to place both data and behavior into these classes? I think that having the ability to have both data and behavior mapped to the same handler is a good thing. There is more on data versus behavior objects being discussed here: https://medium.freecodecamp.org/how-to-build-reliable-objects-with-factory-functions-in-javascript-9ec1c089ea6f

**Comment by dfahlander** [comment]
See #827
