### ISSUE TITLE
Instead of mapToClass can I also use mapToFunction?

### ISSUE THREAD

**Issue by MVSICA-FICTA** [dfahlander/Dexie.js#827]
Is it also possible to map to functions that have closures and avoid the use of 'this'? Not sure if the intention of mapToClass was just to map to framework related components, which are for the most part classes. It would be great to allow mapping to both classes and functions. Not sure if this is directly supported by Dexie?

**Comment by dfahlander** [comment]
mapToClass will only do one simple thing: Set the prototype of returned objects. So if you've mapped the **friends** table to a function or class **Friend**, returned instances (like from db.friends.get(1) or db.friends.toArray()) will have their prototype set to Friend.prototype. The use case is that you can call methods on instances, such as friend.like() if you have defined **like** in the prototype of **Friend**.

**Comment by MVSICA-FICTA** [comment]
This clarifies the role of mapToClass, which is useful for some cases but to generic for others. By generic I mean that the DB objects returned are unique and they all get mapped to the same prototype, which means that what is mapped to defeats the uniqueness of the returned object and the intended usage of it.

Instead, I'd be better off to create my own function or ES6 class for each DB object returned and then simply place the object returned from the DB query into one of it's properties, because the returned object is only meant be a config that is referenced by another function within my custom function/class. 

Then I'd also be free to add additional properties that are not part of the returned config object, as well as any supporting functions my/class requires and create a robust handler for the objects the DB returns.

Just tell me I'm right :-)

**Comment by dfahlander** [comment]
Yes, you can use [hook('reading')](https://dexie.org/docs/Table/Table.hook(%27reading%27)) for that. That is where mapToClass() changes the prototype.

**Comment by MVSICA-FICTA** [comment]
Great! Hooks make almost anything possible 💯
