### ISSUE TITLE
What are the best options for user collaboration?

### ISSUE THREAD

**Issue by MVSICA-FICTA** [dfahlander/Dexie.js#828]
After much deliberation about FireStore and consideration of the realtime requirements of my app I finally discovered IDB and Dexie. This means I'm free to sync to any backend server and each user can have the best experience using IDB locally.

The Dexie.Syncable feature looks like a great way to keep local and remote stores in sync. However, I do not want to pay for incremental changes to a remote option like FireStore. Is there a way to only flush changes periodically or on demand?

Ideally, I'd also like P2P collaboration to only be a selective feature of the app. Maybe this would call for a separate DB that the score to be collaborated on can be placed into? So collaboration is only enabled when a group of users wants to collaborate.

The next option is then to consider WebSockets as an alternative to FireStore. Does Dexie have any options for working with dynamically created WebSockets to allow changes on a store to be propagated to selective peers?

**Comment by dfahlander** [comment]
Dexie.syncable does sync on every change (with a short debounce of some 100 milliseconds). It is currently not configurable.

You might implement sync manually based also. There are two API:s available for this:

* CRUD hooks (legacy)
* Middlewares (3.x alpha only)

The middlewares API is to prefer as it is simpler and yet more complete and flexible. The downside is that the API may change as this is alpha only and it is not documented. You would need to look at the sample posted on the release notes of [Dexie v.3.0.0-alpha.5](https://github.com/dfahlander/Dexie.js/releases/tag/v3.0.0-alpha.5) and find your way by trial and error and inspecting the dexie source code. DexieSyncable is based on CRUD hooks which are documented here: [creating](https://dexie.org/docs/Table/Table.hook(%27creating%27)), [updating](https://dexie.org/docs/Table/Table.hook(%27updating%27)) and [deleting](https://dexie.org/docs/Table/Table.hook(%27deleting%27)). These are the three hooks needed to implement sync in a similar fashion as done by dexie-observable / dexie-syncable.

**Comment by MVSICA-FICTA** [comment]
The middleware sounds interesting, I'll look into these options 💯
