### ISSUE TITLE
Collection.reverse() documentation needs better example.

### ISSUE THREAD

**Issue by gochinj** [dfahlander/Dexie.js#83]
Documentation should mention that you must call reverse() prior to calling a method like sortBy. This seems counter intuitive when wanting to writing an expression like the following.

   >myCollection.sortBy("property1").reverse().then(doSomething);  //Wrong, does not work.

as opposed to the correct syntax as follows:

   >myCollection.reverse().sortBy("property2").then(doSomething); //Correct, this does work.

So using the correct syntax you are basically configuring the next operation, which in this case is sortBy().  SortBy then returns a promise to return an array of objects, which when prefixed with the call to reverse(), returns the array in descending order.  If you pay attention to the return value of any given method you can figure it out. In this example reverse() returns a Collection, and sortBy() returns a Promise.

**Comment by dfahlander** [comment]
Wiki updated: https://github.com/dfahlander/Dexie.js/wiki/Collection.sortBy().
Thanks for pointing out.
