### ISSUE TITLE
Bulk get by keys

### ISSUE THREAD

**Issue by VladyslavGoloshchapov** [dfahlander/Dexie.js#833]
Hi,

How can I get docs if I have ids (primary index) with one request?

Could not find this in docs.

Thank you

**Comment by VladyslavGoloshchapov** [comment]
somethink like bulkGet

**Comment by VladyslavGoloshchapov** [comment]
does this cover this question ?

https://dexie.org/docs/WhereClause/WhereClause.anyOf()

if so, I would still recommend to add bulkGet method as a shortcut

**Comment by dfahlander** [comment]
anyOf() is conceptually a bulkGet, but can be done more efficiently. It's prepared in DBCore, that already have that capability, so it would be easy to extend the Table class to use it.

Marking this issue with the backlog label as it is in the plan.

**Comment by VladyslavGoloshchapov** [comment]
ok, will wait for more efficient solution

thanks

**Comment by dfahlander** [comment]
It's implemented and documented: https://dexie.org/docs/Table/Table.bulkGet()

CI tests are running still.

The feature will be part of 3.0.0-alpha.8 to be released within some days I hope.

**Comment by MisterY** [comment]
Ah, this explains it. The docs already list this method but the 2.0.4, which is installed by default, does not contain this method.
Adding v next (3.0.0-alpha.8) works. Thanks a lot for this fantastic library.
