### ISSUE TITLE
table.put ignores changed date values

### ISSUE THREAD

**Issue by stenet** [dfahlander/Dexie.js#841]
Hi,

when using table.put to update an existing object, date properties are ignored, if their value is changed (old + new have a value).
I.e. person with a birthdate and you would like to change the value from one value to another.

As far as I can see the reason for this is "getObjectDiff" doesn't handle dates correctly.

**Comment by dfahlander** [comment]
I tried to repro this, see https://github.com/dfahlander/Dexie.js/commit/fdf9193cbcb13d854655e967f35eaa1029b557b5 but the test pass. Could you try to do a repro of this similar to mine. Even better if you could clone my branch for this issue (issue-841-table-put-ignores-dates) and do a PR that updates the unit test to trigger the issue?

**Comment by dfahlander** [comment]
What version of Dexie are you using?

**Comment by stenet** [comment]
I'm using 2.0.4, but the problem exists also in the current alpha of version 3.
When creating the test I saw, that the cause is a bit more complicated than I wrote (sorry for that). The put works as excepted, the problem is the hook("updating"). The "modifications" parameter misses all date value changes.

Please see committed PR.

off-topic: would you already recommend using the current alpha for production?

**Comment by dfahlander** [comment]
Thanks for the explanation and the PR! Yes, I would recommend current alpha for production, actually. The issue is mainly only backward compability for typescript users.
