### ISSUE TITLE
TransactionInactiveError even though I am not explicitly using transactions

### ISSUE THREAD

**Issue by VladyslavGoloshchapov** [dfahlander/Dexie.js#844]
I am receiving TransactionInactiveError from time to time when performing toArray method on a table.

1) I am not using transactions directly
2) I am not performing async APIs in a transaction since I don`t use them
3) no typescript

How is this even possible?

Most of the time error is reproducible when same request to DB is performed few times in a row.

Thanks

**Comment by dfahlander** [comment]
I haven't heard of that behaviour before. Are you using a Promise polyfill of some kind? Are you using Zonejs?

**Comment by dfahlander** [comment]
It would also be nice to see some code where this happens.

**Comment by VladyslavGoloshchapov** [comment]
1. I don`t use any Promise polyfill
2. no Zonejs

I am not able to give code samples as they are commercial project unfortunately.
However there is nothing specific about that code. And that code is split in layers of app, so it would not mean anything to you.

I actually tried to reproduce the issue with different code samples, but it was unsuccessful.

**Comment by VladyslavGoloshchapov** [comment]
very strange issue

**Comment by dfahlander** [comment]
Are you doing an operation from the callback of Collection.each() or Collection.modify()? If so, your code would execute within the internal transaction. To make sure you are not executing from within a parent transaction, wrap your DB call through [Dexie.ignoreTransaction()](https://dexie.org/docs/Dexie/Dexie.ignoreTransaction()). See if it helps.

One theory would be if a callback from each() would launch a Promise of some kind, and then from the callback of that operation, you would start a new DB operation.

Another question: Are you using async/await? If so, are you transpiling it or executing it as is?

**Comment by VladyslavGoloshchapov** [comment]
I do not use Collection.each() or Collection.modify().
the only Dexie API I am using is:
new Dexie
hook
offset
limit
filter
toArray
where
startsWith
anyOf
sortBy
get
add
bulkAdd
bulkPut
put
delete
bulkDelete
getDatabaseNames
count

In the specific case where I am getting transactionInactive error I am using only toArray

I was using async/await without transpiling in 1 part of the app and I removed it for testing, but it didn`t help.

**Comment by VladyslavGoloshchapov** [comment]
more investigation

Added some logging and  Dexie.currentTransaction is always an object, when I see TransactionInactiveError.

Does this mean that I am trying to execute a request while another part of my code is already finishing a request ?

Another clarification about my use case, which I forgot to mention. My app can make requests to DB from different code parts simultaneously. Do I need to set some guards then ? Do I need to implement a queue ?

Wrapping that part of code in Dexie.ignoreTransaction resulted in the following error - "TypeError: Cannot read property 'global' of undefined". This error comes from the following code : 
var targetEnv = targetZone.env;

targetZone is undefined.

Do I need to include some library to handle zones ?

**Comment by VladyslavGoloshchapov** [comment]
OK, I RESOLVED THE ISSUE!

Maybe you will want to include this into your best practices section.

Problem was the following - I used hooks! This is another way to access the transaction.
I wasn`t doing that though - I only used another requests (toArray) inside the hook callback.
That`s why I saw this issue only sometimes (in hook callbacks).

I resolved it by wrapping my notify function into setTimeout(, 0).:

`
    function notifyListeners(dbName, change) {
        window.setTimeout(() => {
            let dbListeners = listeners[dbName];
            if (Type.isUndefined(dbListeners)) {
                return;
            }
            dbListeners.forEach((dbListener) => dbListener(change));
        }, 0);
    }

...

db.getDB().data.hook('creating', (ignoredPK, change) => notifyListeners(dbName, change));

`

hope this helps someone

**Comment by dfahlander** [comment]
Thanks, @VladyslavGoloshchapov for getting to the bottom with this! Indeed hooks execute within a transaction. If any of your dbListeners throws, the transaction will abort and become inactive. Wrapping it through setTimeout() is one solution. You could also wrap it with try...catch and call the listeners using Dexie.ignoreTransaction().

```js
function notifyListeners(dbName, change) {
  Dexie.ignoreTransaction(()=>dbListeners.forEach(dbListener => {
    try {
      dbListener(change);
    } catch (error) {
      // ...handle if nescessary...
    }
  ));
}
```

But maybe setTimeout() is easier.
