### ISSUE TITLE
Search over multiple attribute ranges for compound index

### ISSUE THREAD

**Issue by hybridcore8** [dfahlander/Dexie.js#845]
Would anybody happen to know what I should do in the following situation?

I'm recording browsing history and my query is trying to get all events for a certain website that overlap with today, that is events for a certain website whose beginning time is before the end of today AND whose ending time is after the beginning of today. It's filtering by the first two attributes (`url` which is fixed and `begin` which varies) but ignoring the third (`end`, also varies). As a result, I'll get all intervals where `begin` lands before the end of today but which may not have `end` land after the beginning of today (i.e. events that started and ended in the past).

```javascript
const db = new Dexie("database");

db.version(1).stores({
	history: "[url+begin+end]"
});

// Beginning and end of today.
let today_begin = new Date();
today_begin.setHours(0);
today_begin.setMinutes(0);
today_begin.setSeconds(0);
today_begin.setMilliseconds(0);
let today_end = new Date(today_begin);
today_end.setHours(23);
today_end.setMinutes(59);
today_end.setSeconds(59);
today_end.setMilliseconds(999);

// Get all of the events for github.com that overlap with today, that is events which have a beginning or ending time some time today.
db.history
		.where("[url+begin+end]")
		
		.between(
			["github.com", -Infinity, today_begin],
			["github.com", today_end, Infinity],
			true,
			true
		)
		.toArray(array => {...});
```

Originally I was using Table.filter(), but it was giving relatively poor performance of T(R) due to it having to scan through all tuples/objects in a table so I was trying to reduce it to B(index(R)) by indexing it so Dexie could just do a B+Tree index range scan.

I have read [issue 599](https://github.com/dfahlander/Dexie.js/issues/599) but I'm not sure if the solution there would give a consistent performance benefit. Since I'm looking at dates both near the beginning and end of the recorded browsing history (compared to just today in the example above), indexing just `begin`, doing `where("begin").belowOrEqual(arbitrary_date_end)`, and then doing `Collection.filter()` or the opposite with `end` and `greaterOrEqual(arbitrary_date_start)` doesn't yield much of a performance benefit when scanning the extremes of the browsing history. Choosing to index by `begin` heavily favors searching for events on days near the beginning of the browsing history and choosing to index by `end` heavily favors searching for events on days near the end of the browsing history.

Is there a way I can use compound indexes to do this or can I only use Table.filter() to get the result I want? Or am I better off trying something like PouchDB, Minimongo, ZangoDB, or JsStore instead for range queries over multiple attributes?

As far as the possibility of this on the implementation side, based on the way compound indexes are ordered on disk (group and sort by keys from left to right, basically lexicographically like words in a dictionary but each letter being a key) it seems like two things can be done:

1. If my compound index is `[url+begin+end]`, look for the leaf in the B+Tree index with the largest allowable value of `begin` (i.e. <= today_end) and then keep doing getPrevious() to get the previous item, checking if that previous item's `end` >= today_begin.

2. If my compound index is `[url+end+begin]`, look for the leaf in the B+Tree index with the smallest allowable value of `end` (i.e. >= today_begin) and then keep doing getNext() to get the next item, checking if that next item's `begin` <= today_end.

This is a bit of a narrow case since my data is guaranteed such that you can never have overlapping intervals and ordering by the beginning also orders by end as well due to each interval being sequential and mutually exclusive.

If it's an unclustered index, we're still going to get worst case T(R) but we no longer have to process every tuple when only looking for small subsets, giving a large performance boost.

**Comment by dfahlander** [comment]
This is a type of query that a btree cannot solve easily, no matter if it is IndexedDB or an SQL database. Some databases have Range indexes that specifically solves it (Postgres and mongo has it).

But good news is that you can solve it on top of a btree. I had the exact same need in my app where I want to list events that overlaps with a certain day.

Initially I modelled events with a start and end time, just as in your case. But I figured out there is a better appoach: Instead of storing begin and end, store **begin** and **duration**.

Then, assume that most events have a duration less than, say 24 hours. The longer ones are exceptions.

Your query could then be done like the following:

```js

const db = new Dexie("database");
db.version(x).stores({
  history: 'id, url, begin, duration'
});

const TYPICAL_MAX_DURATION = 24 * 60 * 60 * 1000;

async function findOverlaps(start, stop) {
  const [normalEvents, longEvents] = await Promise.all([
    db.history.where('start').between(start - TYPICAL_MAX_DURATION, stop).toArray(),
    db.history.where('duration').aboveOrEqual(TYPICAL_MAX_DURATION).toArray()
  ]);
  const events = [...normalEvents, ...longEvent].filter(event => {
    const eventEnd = event.begin + event.duration;
    return event.begin < stop && eventEnd >= start;
  });
  return events;
}

```

**Comment by dfahlander** [comment]
I was assuming you were storing numbers, but I notice now you are storing Date objects. The principle is the same, but you would need to adjust my code for converting the Dates to numbers of course.

If your code depends on the begin and end properties, you can make this change backward compatible:

```js
class HistoryEvent {
  get end() { return new Date(this.begin.getTime() + this.duration); }
  set end(value) { this.duration = value.getTime() - this.begin.getTime(); }
}
db.history.mapToClass(HistoryEvent);

```

**Comment by hybridcore8** [comment]
Will definitely give this a try. Thank you so much!
