### ISSUE TITLE
Safari 12: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

### ISSUE THREAD

**Issue by mrusme** [dfahlander/Dexie.js#846]
I'm having an issue where `dexie@next` in Safari 12.1 (with [indexedDBShim](https://github.com/axemclion/IndexedDBShim) included) doesn't seem to be working at all. Opening the database seems to succeed, however every action on a specific table fails with this error:

```
Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```

<img width="1077" alt="Screenshot 2019-05-10 at 8 44 22 PM" src="https://user-images.githubusercontent.com/151967/57549907-156f0800-7365-11e9-8af9-4cc8a47b8554.png">

Not using any transactions, the code is basically just a `put` followed by `.toArray()`. However, the identical code runs perfectly fine in Chrome 74 and in Firefox 66.

Any suggestions on how to debug this?
Thanks in advance!

**Comment by mrusme** [comment]
Info: Clearing the cache/cookies/localstorage seems to have done the trick. It's working in Safari now. However, it's weird that this was actually a caching issue. Will keep an eye open during development, whether this will reoccur and check the cached data for what could cause it.

**Comment by dfahlander** [comment]
Nice to hear you got it solved. Curious though why you use indexedDBshim on Safari 12? I'd it due to any issue with it's native indexedDB support?

**Comment by mrusme** [comment]
@dfahlander well, I'm trying to support more browsers than just Safari 12. Also, its documentation said it's not a bad idea to use the shim in general:

> Even if a browser natively supports IndexedDB, you may still want to use this shim. Some native IndexedDB implementations are very buggy.

What's your experience with Safari 12 and latest browsers in general?

**Comment by laukaichung** [comment]
My user got the same error today after upgrading the database.

NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found

I guess that's caused because the user has a very old db version that is no longer supported.

Is it possible to find out the name of the object store that was not found?

**Comment by dfahlander** [comment]
> My user got the same error today after upgrading the database.
> 
> NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found
> 
> I guess that's caused because the user has a very old db version that is no longer supported.
> 
> Is it possible to find out the name of the object store that was not found?

The error comes from native IndexedDB. If using dexie@4.1 or later, this should not happen since it will verify that the declared schema is in sync with the installed schema no matter if version is bumped or not.

**Comment by laukaichung** [comment]
Thanks for your response. I asked you about clearing all data if the version is too old in this thread: https://github.com/dexie/Dexie.js/discussions/2214

Another user has a more specific error "NotFoundError Table newTableX not part of transaction". Do you think the `clear()` code in the older version may somehow trigger the error?


````
db.version(93).stores({
    newTableX: "++id,",
})

db.version(91).stores({
    otherTable: "++id"
})

db.version(90).upgrade(tx => {
    for (const table of tx.storeNames) {
        tx.table(table).clear();
    }
});
````
