### ISSUE TITLE
Some documentation returning 404

### ISSUE THREAD

**Issue by kkeith-adg** [dfahlander/Dexie.js#849]
Some pages are returning a 404. Examples are below:

https://dexie.org/docs/API-Reference/
https://dexie.org/docs/Tutorial/Consuming-dexie-as-a-module/

**Comment by dfahlander** [comment]
The links you listed have slash at end and returns 404.
But searching through the source I cannot find any page that links to API-Reference/ or Consuming-dexie-as-a-module/ with slashes applied.

Could you provide the URL of a page that was linking to these links?

**Comment by kkeith-adg** [comment]
It was from the main docs page: https://dexie.org/docs/

The links look to be working now. Unsure why it would be temporary, but glad it's accessible for me again.
