### ISSUE TITLE
Table.clear() performance issues (except first time)

### ISSUE THREAD

**Issue by xVinCe** [dfahlander/Dexie.js#851]
Hi,

Developing an app with Angular that has an offline capability, with Dexie+relationships.
```
    "@angular/core": "6.1.10",
    "dexie": "^2.0.4",
    "dexie-relationships": "^1.2.10",
```

We're doing a manual sync with the server (not using Syncable).

For some tables, we erase and replace the full table. This is done once a month but for testing purposes I'm doing it several times in a row. Those tables have a few hundred rows to ~25.000 rows for the biggest.

Here is a code extract (it's inside a transaction)

```
            console.debug('Clearing table item', moment().toISOString());
            await this.db.item.clear();
            console.debug('Clearing table mission', moment().toISOString());
            await this.db.mission.clear();
            console.debug('Clearing table project', moment().toISOString());
            await this.db.project.clear();
(...)
            console.log('BulkAdd in table item', moment().toISOString());
            await this.db.item.bulkAdd(data.t_Item);
            console.log('BulkAdd in table mission', moment().toISOString());
            await this.db.mission.bulkAdd(data.t_Mission);
            console.log('BulkAdd in table project', moment().toISOString());
            await this.db.project.bulkAdd(data.t_Project);
```

The first sync takes ~35 seconds.
The second after more than 45 minutes was stuck on the clear() of the biggest table, and other tables were also much slower than the first time. Example for clearing a table with ~150 rows: 
- 120ms the first time
- 3500ms the second time

The tables initially have the same size before the first and 2nd run.

Similar results on Firefox and Chrome.

I have tried removing the transaction, same result.

I have tried using a new instance of Dexie each time, same result.

I'm not sure if it's Dexie or IndexedDb related, or anything else. We don't really have a problem in production because this sync is triggered only once a month at app startup, but I'm curious. Do you have any idea what might cause the issue?

Not related, but on my other findings, it's about 1.5 to 2 times faster to clear tables sequentially with `await db.myTable.clear()` than in parallel with `await Promise.all(clearPromisesArray)`

**Comment by dfahlander** [comment]
If you are subscribing to delete hook? Or are you using Dexie.Observable that does this? If so, dexie cannot use IDBObjectStore.clear() to clear a table. Instead it needs to query each row in the table prior to deleting the items, in order to trigger the hook subscriber with info about what is being deleted.

**Comment by dfahlander** [comment]
Also, Angular's Zone.js will generally make many calls to IndexedDB as it intercepts every row response event and tests whether the view has changed or not.

**Comment by xVinCe** [comment]
Ah, yes I'm subscribing to the delete hook!
If I remove it there is a drastic performance increase.

I didn't know it changed the behavior of clear(). I think it would be a good idea to add a remark about this on https://dexie.org/docs/Table/Table.clear().

It doesn't explain the huge difference between first and second call when there is the hook though, I guess it has to do with Zone.js.

Anyway, thank you!

**Comment by ZiyunHe** [comment]
btw. i'm experiencing the same issue. I'm using react. 
i did: await db.tablename.clear();

after first time, the promise takes forever to return back.
can someone help? thank you.

**Comment by ZiyunHe** [comment]
sorry im a newbie..what is a delete hook?

**Comment by dfahlander** [comment]
Dexie hooks enables getting notified about db calls. Delete hook is explained here: https://dexie.org/docs/Table/Table.hook('deleting')
