### ISSUE TITLE
dexie-export-import: JSON formatting is invalid in exports

### ISSUE THREAD

**Issue by travddm** [dfahlander/Dexie.js#854]
Dexie.js version 2.0.4
dexie-export-import version 1.0.0-alpha.10
-> Using all default options

While exporting and importing a large database (>600 MB), the JSON generated by the export was invalid.

After parsing the file with jsonlint, the problem seemed to be that there were missing commas between objects in large arrays. (expected between objects: "},{" vs found between objects: "}{") Throughout the whole file, I only found about 30 instances of these missing commas.

After replacing each "}{" with "},{", the database imported properly without any problems.

I suspect this issue may only be apparent in larger sets of data, and I also suspect it has something to do with objects being separated right on the start/end of each streaming chunk.

**Comment by dfahlander** [comment]
Thanks. I'll try to find a way to trigger this in a unit test and fix. Feel free to help me with the unit test if you'd have the time to make a PR

**Comment by dfahlander** [comment]
I found the issue and it should be fixed now. Try with the latest release on npm (1.0.0-beta.11)
