### ISSUE TITLE
Dexie not working with TypeScript

### ISSUE THREAD

**Issue by leoc5** [dfahlander/Dexie.js#856]
Hi!
I am trying to use Dexie for a web application, which uses TypeScript for backend and JS for front end. I installed it using "npm install dexie" and now I have the 'dexie' module inside node_modules folder.  
One of the simplest versions I tried (from the Internet) so far to create a database and open it is like: 

       export class DbConnection extends Dexie {
        constructor() {
        super("MyAppFirstDb");

        this.version(1).stores({
            friends: 'name, age'
        });
    }
}
and then try to use this class as: 

        var db:DbConnection = new DbConnection();
        db.table("friends").add({name: "Josephine", age: 21}).then(()=>{
            return db.table("friends").where("age").below(25).toArray();
        }).then(youngFriends => {
            console.log("My young friends: " + JSON.stringify(youngFriends));
        }).catch(e => {
            console.log("error: " + e.stack || e);
        });
but every time I get this error:
_MissingAPIError: indexedDB API not found. If using IE10+, make sure to run your code on a server URL (not locally). If using old Safari versions, make sure to include indexedDB polyfill._

Can you please help me?

**Comment by dfahlander** [comment]
That error usually happens when not running in a web browser, such as in nodejs for example.

**Comment by dfahlander** [comment]
Dexie is a wrapper for indexedDB but indexedDB is a part of the W3C Dom, so you need to run Dexie in an environment that supports indexedDB.

**Comment by leoc5** [comment]
So, is there a way I can use Dexie with TypeScript, in this situation?

**Comment by leoc5** [comment]
So, is there a way I can use Dexie with TypeScript, in this situation?

**Comment by dfahlander** [comment]
This is not a Typescript issue. Your code compiles, right? But you get an exception when you run it. 

Are you running this on Node or in  a browser?

**Comment by leoc5** [comment]
You are right, the title may not be the proper one, I'm sorry. The code compiles, indeed. It is a Node project, but I'm using _express_, in order to run it in browser.

**Comment by leoc5** [comment]
Do you think it is a Node related issue, or?

**Comment by remusao** [comment]
@leoc5 to use Dexie.js in Node.js environment you need a shim for IndexedDB. There are a few available like [fake-indexeddb](https://github.com/dumbmatter/fakeIndexedDB) or [IndexedDBShim](https://github.com/axemclion/IndexedDBShim). With `fake-indexeddb` it could look somewhat like:

```typescript
import Dexie from 'dexie';
import IDBKeyRange from 'fake-indexeddb/lib/FDBKeyRange';
import indexedDB from 'fake-indexeddb';

class DexieForNode extends Dexie {
  constructor(name) {
    super(name, {
      indexedDB,
      IDBKeyRange,
    });
  }
}
```

This will keep all the data in memory only but there are options to have a shim which persists data in sqlite on disk for example.
