### ISSUE TITLE
Electron crash when using DexieCollection `toArray()` api

### ISSUE THREAD

**Issue by kasnihuang** [dfahlander/Dexie.js#859]
When I using collection toArray() api in Electron, the electron exit immediately. Could you help to take a look.

`Application Specific Information:
Fatal Error: EXC_BREAKPOINT / EXC_I386_BPT

Thread 2328252 Crashed:
0   Electron Framework              0x111389f67         <unknown>
1   Electron Framework              0x11138e116         <unknown>
2   Electron Framework              0x11138e5c7         <unknown>
3   Electron Framework              0x113d1018b         <unknown>
4   Electron Framework              0x113d10000         <unknown>
5   Electron Framework              0x11138ce31         <unknown>
6   Electron Framework              0x111388584         <unknown>
7   Electron Framework              0x11137e2ef         <unknown>
8   Electron Framework              0x112586203         <unknown>
9   Electron Framework              0x11099eea5         <unknown>
10  Electron Framework              0x110fee3a0         <unknown>
11  Electron Framework              0x11102d222         <unknown>
12  Electron Framework              0x11259c933         <unknown>
13  Electron Framework              0x1125b73af         <unknown>
14  Electron Framework              0x1125b7913         <unknown>
15  Electron Framework              0x112657c24         <unknown>
16  Electron Framework              0x1125d62d8         <unknown>
17  Electron Framework              0x110e31c24         <unknown>
18  Electron Framework              0x11261b3ca         <unknown>
19  Electron Framework              0x112658047         <unknown>
20  libsystem_pthread.dylib         0x7fff7f064661      <unknown>
21  libsystem_pthread.dylib         0x7fff7f06450d      <unknown>
22  libsystem_pthread.dylib         0x7fff7f063bf9      <unknown>

Thread 2328175
0   libsystem_kernel.dylib          0x7fff7ee9320a      <unknown>
1   CoreFoundation                  0x7fff56e3d785      <unknown>
2   CoreFoundation                  0x7fff56e3cad7      <unknown>
3   CoreFoundation                  0x7fff56e3c153      <unknown>
4   HIToolbox                       0x7fff56126d96      <unknown>
5   HIToolbox                       0x7fff56126b06      <unknown>
6   HIToolbox                       0x7fff56126884      <unknown>
7   AppKit                          0x7fff543d7a73      <unknown>
8   AppKit                          0x7fff54b6de34      <unknown>
9   AppKit                          0x7fff543cc885      <unknown>
10  Electron Framework              0x11265e97c         <unknown>
11  Electron Framework              0x11265d4bf         <unknown>
12  Electron Framework              0x1125d62d8         <unknown>
13  Electron Framework              0x110e2a1f3         <unknown>
14  Electron Framework              0x110e2a030         <unknown>
15  Electron Framework              0x110e2c052         <unknown>
16  Electron Framework              0x110e26f04         <unknown>
17  Electron Framework              0x1121eb51e         <unknown>
18  Electron Framework              0x1121eb191         <unknown>
19  Electron Framework              0x113d9524f         <unknown>
20  Electron Framework              0x1121ea5e4         <unknown>
21  Electron Framework              0x1102d2513         AtomMain
23  libdyld.dylib                   0x7fff7ed4c015      [inlined] <unknown>
24  libdyld.dylib                   0x7fff7ed4c015      <unknown>

Thread 2328207
0   libsystem_kernel.dylib          0x7fff7ee9d28a      <unknown>
1   libsystem_pthread.dylib         0x7fff7f063be9      <unknown>
2   libdispatch.dylib               0x7fff7ed146f0      <unknown>

Thread 2328236
0   libsystem_kernel.dylib          0x7fff7ee9d28a      <unknown>
1   libsystem_pthread.dylib         0x7fff7f063be9      <unknown>

Thread 2328237
0   libsystem_kernel.dylib          0x7fff7ee9d28a      <unknown>
1   libsystem_pthread.dylib         0x7fff7f063be9      <unknown>
2   libsystem_malloc.dylib          0x7fff7eef6c7c      <unknown>
3   libdispatch.dylib               0x7fff7ed302de      <unknown>
4   libobjc.A.dylib                 0x7fff7e13b653      <unknown>
5   libsystem_platform.dylib        0x7fff7f05d7ad      <unknown>
6   libsystem_malloc.dylib          0x7fff7eef6679      <unknown>
7   libdispatch.dylib               0x7fff7ed13d3c      <unknown>
8   libdispatch.dylib               0x7fff7ed15aea      <unknown>
9   QuartzCore                      0x7fff621be361      <unknown>
10  libdispatch.dylib               0x7fff7ed12db8      <unknown>
11  libdispatch.dylib               0x7fff7ed1fcc5      <unknown>
12  libdispatch.dylib               0x7fff7ed224d1      <unknown>
13  libdispatch.dylib               0x7fff7ed14cc2      <unknown>
14  libdispatch.dylib               0x7fff7ed14755      <unknown>
15  libsystem_pthread.dylib         0x7fff7f06420e      <unknown>
16  libsystem_pthread.dylib         0x7fff7f063be9      <unknown>
17  libdispatch.dylib               0x7fff7ed2b9b1      <unknown>

Thread 2328247
0   libsystem_kernel.dylib          0x7fff7ee9dbea      <unknown>
1   Electron Framework              0x11266203d         <unknown>
2   Electron Framework              0x112657cde         <unknown>
3   Electron Framework              0x1125d62d8         <unknown>
4   Electron Framework              0x11260acd7         <unknown>
5   Electron Framework              0x11261b3ca         <unknown>
6   Electron Framework              0x112658047         <unknown>
7   libsystem_pthread.dylib         0x7fff7f064661      <unknown>
8   libsystem_pthread.dylib         0x7fff7f06450d      <unknown>
9   libsystem_pthread.dylib         0x7fff7f063bf9      <unknown>

Thread 2328248
0   libsystem_kernel.dylib          0x7fff7ee9320a      <unknown>
1   Electron Framework              0x1125eada0         <unknown>
2   Electron Framework              0x1125eaeb1         <unknown>
3   Electron Framework              0x1126067d8         <unknown>
4   Electron Framework              0x112606b42         <unknown>
5   Electron Framework              0x112606a54         <unknown>
6   Electron Framework              0x112658047         <unknown>
7   libsystem_pthread.dylib         0x7fff7f064661      <unknown>
8   libsystem_pthread.dylib         0x7fff7f06450d      <unknown>
9   libsystem_pthread.dylib         0x7fff7f063bf9      <unknown>

Thread 2328253
0   libsystem_kernel.dylib          0x7fff7ee9dbea      <unknown>
1   Electron Framework              0x1158e6560         uv_run
2   Electron Framework              0x115864536         <unknown>
3   libsystem_pthread.dylib         0x7fff7f064661      <unknown>
4   libsystem_pthread.dylib         0x7fff7f06450d      <unknown>
5   libsystem_pthread.dylib         0x7fff7f063bf9      <unknown>

Thread 2328255
0   libsystem_kernel.dylib          0x7fff7ee9ca16      <unknown>
1   Electron Framework              0x1158f1778         uv_cond_wait
2   Electron Framework              0x115864638         <unknown>
3   Electron Framework              0x1158623b8         <unknown>
4   libsystem_pthread.dylib         0x7fff7f064661      <unknown>
5   libsystem_pthread.dylib         0x7fff7f06450d      <unknown>
6   libsystem_pthread.dylib         0x7fff7f063bf9      <unknown>

Thread 2328257
0   libsystem_kernel.dylib          0x7fff7ee93246      <unknown>
1   Electron Framework              0x1158accf1         node::inspector::Agent::GetWorkerManager
2   libsystem_pthread.dylib         0x7fff7f064661      <unknown>
3   libsystem_pthread.dylib         0x7fff7f06450d      <unknown>
4   libsystem_pthread.dylib         0x7fff7f063bf9      <unknown>
5   Electron Framework              0x1158accdf         node::inspector::Agent::GetWorkerManager`

**Comment by dfahlander** [comment]
Sorry, I cannot debug that. Seems to be an electron-related issue. Database file that chromium uses might be corrupt or you are running several processes in parallell. This seems to be an Electron-related issue that I cannot answer.
