### ISSUE TITLE
Query multiEntry index using equals

### ISSUE THREAD

**Issue by tp** [dfahlander/Dexie.js#86]
Given the following schema:
```
db.version(2)
      .stores({
        friends: 'id,*parent.id'
      });
```

And adding objects to it like this:
```
db.friends
          .add({
            id: new Date().toJSON(),
            name: 'Camilla',
            age: 27,
            parent: [{
              id: 'xxx'
            }]
          })
```

I was wondering why this query does not return any results:
```
console.log('xxx children:')
            this.db.friends
              .where('parent.id')
              .equals('xxx')
              .each(function(friend) {
                console.log(friend.id, friend.name);
              })
```

Sorry for the quick and dirty code, but I assume I have an error in understanding. If you think this might be a bug in Dexie, I will provide a real test case.

**Comment by tp** [comment]
Ahh, I see that the index work for `parent`s holding mutiple ids, but not for multiple `parent`s each having just one id.

If I insert like this I get results with the above query, but that's not what I want to do in practice:
```
db.friends
          .add({
            id: new Date().toJSON(),
            name: 'Camilla',
            age: 27,
            parent: {
              id: ['xxx']
            }
          })
```

Is there another way to specify the index to support the scenario above?

I have this a lot in real apps where references are saved as array of objects like this: `{ type: 'objType', id: 1 }`.

**Comment by dfahlander** [comment]
I understand the need you request. It is a common scenario and cannot be resolved using multiEntry indexes.

Instead, you can have another table for parents as you would do in an SQL database.

```js
db.version(3)
    .stores({
        friends: 'id',
        parents: 'id,friendId'
    });
```

There's a newly added sample under samples/requirejs where I do a similar thing that you could look at. In particular, you need to query parents table separately to resolve the parents of a particular friend:

```js
function getParents(friend) {
    return db.parents.where('friendId').equals(friend.id).toArray();
}
```

And to put it together:
```js

var db = new Dexie('friendsParentsDb');
db.version(4)
    .stores({
        friends: 'id,name',
        parents: 'id,friendId'
    });
db.open();

function getParents(friend) {
    return db.parents.where('friendId').equals(friend.id).toArray();
}

function findFriends (nameHint) {
    return db.friends.where('name').startsWithIgnoreCase(nameHint).toArray()
        .then(function (friends) {
            return Dexie.Promise.all(
                friends.map(function (friend) { return getParents(friend); })
            ).then (function (parentses) {
                for (var i=0; i<friends.length; ++i) {
                    friends[i].parents = parentses[i];
                }
                return friends;
            });
        });
}

db.transaction ('rw', 'friends', 'parents', function () {
    // Store a friend with some parents:
    db.friends.put({id: 18, name: 'Camilla'});
    db.parents.put({id: 29, friendId: 18, type: 'mother', name: 'Gunilla' });
    db.parents.put({id: 30, friendId: 18, type: 'father', name: 'Bengt' });

    // Query
    findFriends ('C').then (function (friends) {
        alert ("Found friends: " + JSON.stringify (friends, null, 4));
    });
});
```

**Comment by tp** [comment]
Thanks for the elaborate response!

It seems clear to me now, that I have to change my schema. Though I think I will create a special lookup/index table and keep the objects as I get them from the server without changes. The lookup table will be updated every time a "normal" object changes.

For future reference: I have found a thread regarding this same issue on [Microsoft's forums](https://social.msdn.microsoft.com/Forums/en-US/dbf2fd2d-a8ca-4228-8a49-3948d44f7e26/indexeddb-and-complex-keypaths-for-index).

**Comment by tp** [comment]
Since progress needs to be made with the IndexedDB spec for this to ever improve, I filed a bug with the WG: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28456
