### ISSUE TITLE
dexie-export-import: Invalid JSON formatting in filtered exports

### ISSUE THREAD

**Issue by travddm** [dfahlander/Dexie.js#862]
Dexie.js version 2.0.4
dexie-export-import version 1.0.0-beta.11
-> Using default options except for filter

Similar to #854 

With large databases, filtering out large sets of data can result in "ghost commas".

For example, if I apply the following option to my export:
`let exportBlob = await db.export({
    filter: () => false
});`
And if I have a large enough set of data to require a significant amount of chunks, I will find output similar to this for each of my larger tables:
`{"tableName":"testTable1","inbound":true,"rows":[,,,,,,]}`

If I have time to do so (probably not for another day or so), I will submit a PR.

**Comment by dfahlander** [comment]
Ok thanks, you're very welcome to send a PR

**Comment by dfahlander** [comment]
The fix is now published on npm as 1.0.0-beta.12.
