### ISSUE TITLE
DB size increases and compactions seem not working

### ISSUE THREAD

**Issue by giddens9527** [dfahlander/Dexie.js#866]
I'm not 100% sure if this issue is caused by Dexie or IndexedDB. 
What happened to my electron app (sticky note app) is every time a user writes something, it would save the whole content as a JSON blob to one IndexedDB table via Dexie. Some users (roughly 1% - 2%) encountered the IndexedDB folder would increase several mb every time it saves on even pure text inputs. What I found was there were lots of .ldb files created; the MANIFEST file became several GB during few save to table operations; Some old .ldb files didn't get removed by compaction.

**Comment by dfahlander** [comment]
If you are using Dexie without any addons, it could not be an issue with Dexie as it does not store any extra data. I suppose the .ldb files refers to leveldb files and that you are experiencing this on chromium? How do you trigger a compaction in chromium? (this is over my knowledge)

**Comment by giddens9527** [comment]
Thank you! It was on chromium (electron) and I just read some docs related to leveldb and it mentioned that leveldb would do compaction automatically when the size of two level n-1 .ldb file reaches the limit and they would combined as a level n .ldb file. So probably this is more related to leveldb side.

**Comment by dfahlander** [comment]
Aha, thanks. There's a similar issue #641. Still no clear answer there either though...
