### ISSUE TITLE
Dexie.getDatabaseNames returns empty array(dump-databases.html)

### ISSUE THREAD

**Issue by remisteen** [dfahlander/Dexie.js#870]
Hi! 
I am new to Dexie. But i would like to migrate my existing idb wrapped in pouchdb to dexie.

My application is an Angular 5 app.

When i try to run the code from the dump-databases.html in my app.component.ts it returns:
"There are no databases at current origin. Try loading another sample and then go back to this page."

I know for sure there are data in indexeddb. 

Do you have som ideas on how to address this issue?

**Comment by dfahlander** [comment]
Either the databases where not created using dexie, or the databases are located on another URL than the one you are visiting.

**Comment by remisteen** [comment]
Its correct that they are not created by Dexie. They were created with pouchdb. 
According to the migration documentation it should be possible even if the db has been created with another wrapper : "Dexie can open any indexedDB database, no matter if you’ve created it via raw indexedDB or another indexedDB wrapper."

I am 100 % certain that the databases are on the sameurl.. In this case: localhost

Is the documentation wrong, or am I misunderstanding something?

**Comment by dfahlander** [comment]
You can open it but not enumerate databases

**Comment by dfahlander** [comment]
Db enumeration is a proprietary feature. At the time it was implemented this was also possible natively in some browsers but that api has become obsolete

**Comment by remisteen** [comment]
Ok. So i will not be able to query a pouch database with dexie?

Pouch is incredibly slow when using queries. But very good when it comes to syncing with database serverside.

The goal was to use dexie just to do queryes and pouch for syncing. The best of two worlds 😉

**Comment by dfahlander** [comment]
Yes, you just need to know the database name

**Comment by remisteen** [comment]
I am not in the office right now. Replying from my phone.
So this will work:
var db = new Dexie("my-pouch-db")
db.where()....... and so on

Or do I have to do this aswell?

db.version(1).stores({
    friends: `name, age`
}); 

If so. I basically have to do the same that dump-databases.html would do, but all manual.

Thanks for your replies. Much appreciated.

**Comment by dfahlander** [comment]
You can open the db without specifying version ().stores(). It will adapt to the current version and, stores and indexes.

**Comment by dfahlander** [comment]
’’’js
let db = await new Dexie("name-of-pouch-db").open();
console.log("Version", db.verno);
console.log("Tables", db.tables.map(({name, schema}) => ({
  name,
  schema
}));
’’’

**Comment by dfahlander** [comment]
Though, object stores must be accessed via the `table()` method (they are not put as direct properties on the db instance)

```js
db.table('objectStoreName').where('index')...
```

**Comment by remisteen** [comment]
Thanks for good feedback. I will try it out as soon as i get back to my office. Its very much appreciated.

**Comment by remisteen** [comment]
I was not able to combine dexie and pouchDb. Closing this question

**Comment by justinr1234** [comment]
@dfahlander The issue I run into is that the database gets corrupted when specifying things with Dexie and is not longer openable by PouchDB.

What I'd really like to do is just add a specific index to a specific table as the secondary index searches in Pouch are abysmally slow. I've been combing the code and it looks a bit complicated to do that.

Is this possible?

**Comment by dfahlander** [comment]
I know too little about how pouchdb stores it's data to give an answer. Sorry!

**Comment by justinr1234** [comment]
@remisteen It looks like it might work if you use the `pouchdb-adapter-indexeddb` instead of the default `idb` one. The problem is that the default `idb` adapter for pouchdb hardcodes the version number at 5 so it tries to open only that version, preventing any schema upgrades from Dexie. I managed to get a version working, but I'm still working out the order of upgrades between pouchdb's init and Dexie.
