### ISSUE TITLE
Querying Data from an Array with WhereClause.equals() 

### ISSUE THREAD

**Issue by jwlms** [dfahlander/Dexie.js#871]
After reading the documentation and starting to write queries with Dexie, I've run into an issue for querying data stored as an Array. I'm not sure if it's a limitation of the library, or my misuse of it.

I'm trying to retrieve records if they match one or more elements I provide in the equals clause, for example I would like to write a query that would retrieve all records that include "Google" as a member of the array. 

**The table:**

<img width="744" alt="Screen Shot 2019-07-15 at 4 48 38 PM" src="https://user-images.githubusercontent.com/955224/61256182-97dac600-a720-11e9-813b-a89fdf944e9f.png">

**Example query:**
```javaScript
db.table_name.where('search_engines').equals(["Google"]).toArray()}).then((data)=> {
// use data
});
```

This returns records that only have the value of `["Google"]`. However, it doesn't return records with more than one item in the Array, (e.g., `["Google", "Bing"]`). I would assume that the `anyOf` method would be useful here, but using this returns no records. Is a query like this possible with Dexie or is it only possible to check that the Array matches exactly?

**Comment by dfahlander** [comment]
For that, use [MultiEntry index](https://dexie.org/docs/MultiEntry-Index).

```js
const db = new Dexie('yourDbName');
db.version(1).stores({
  tableName: '++id, *search_engines'
});

// Add entries:
await db.tableName.bulkAdd([{
  name: "all",
  search_engines: ["Google", "Yahoo", "Bing"]
}, {
  name: "some",
  search_engines: ["Bing"]
}]);

// Query
const googles = await db.tableName.where('search_engines').equals("Google").toArray();
// Gives googles = [{id: 1, name: "all", search_engines: ["Google", "Yahoo", "bing"]}]
const bings = await db.tableName.where({search_engines: "Bing"}).toArray();
// Gives bings = [{
//    id: 1, name: "all", search_engines: ["Google", "Yahoo", "bing"]
//  }, {
//    id: 2, name: "some", search_engines: ["Bing"]
//  }]

```

**Comment by jwlms** [comment]
Thanks for the response and detailed example! 

As you pointed out you have already covered this in the docs, but obviously I had some difficulty in discovering it — at any rate it's a pretty killer library.

I ended up putting in a work around for my specific issue, but will revisit to use the MultiEntry.
