### ISSUE TITLE
How to delete a non indexed binary data in the collection

### ISSUE THREAD

**Issue by ShivamJoker** [dfahlander/Dexie.js#881]
Hey I am not able to find any example of deleting a binary data which is not indexed
This is how my collection looks and videoId is the primary key
![image](https://user-images.githubusercontent.com/23727670/62048302-27589c80-b22a-11e9-9482-d90fc676c21d.png)
I just want to remove the blob audio key
Thanks

**Comment by dfahlander** [comment]
Update the entry and set the property to null, undefined or delete the property.

```ts
db.table('tableName').update(videoId, {audio: undefined});

```

**Comment by ShivamJoker** [comment]
I thought of updating with undefined but can you please tell how can we delete it

**Comment by dfahlander** [comment]
This deletes the blob. Do you want to delete the whole row? Use db.table.delete(videoId)

**Comment by ShivamJoker** [comment]
No I mean to say using delete function to delete the whole audio key updating will just updated it's value to undefined

**Comment by dfahlander** [comment]
To delete the property, do:

```js
db.table.where({videoId: theVideoId}).modify(x => { delete x.audio})
```

**Comment by ShivamJoker** [comment]
Hey really thanks for that
