### ISSUE TITLE
WriteableTable.update() return values

### ISSUE THREAD

**Issue by AnimaLupi** [dfahlander/Dexie.js#89]
Hello, thank you for your work.

I'm having an issue with WriteableTable.update(). From the docs, it reads:

> Promise with value 1 (= key was found and object updated) or 0 (key was not found and nothing was updated)

Which I interpreted (note: maybe I'm wrong here!) basically as getting 0 on key not found and 1 on key being found.

I'm wondering though if it should be changed to "... or 0 (key was not found **or** nothing was updated)", as that's what I'm experiencing right now. Basically, I'm using update on an object I *do* have in my DB but I'm getting a return value of 0 as I'm updating it with same values as before.

Is this the correct interpretation? And in this case, any chance the return value could include a value for the specific case of "record found, but nothing changed"? This could probably be useful (well, at least it would be to me ;-) . Or is it possible to get the info about this particular case by using hooks?

**Comment by dfahlander** [comment]
Thanks.

Yes it's true that you will get 0 if the provided changes didnt affect the data. I've updated the documentation according to that.

What you could do in your case is:
```js
function updateAndReturnIfExisted(table, key, changes) {
    var existed = false;
    table.where(':id').equals(key).and(function(obj){
        return (existed = true);
    }).modify(changes).then(function() {
        return existed;
    });
}
```
Then, to use your function:
```js

updateAndReturnIfExisted(db.myTable, myKey, {keyPath1: "change1", keyPath2: "change2"})
.then(function (updated) {
    if (updated) console.log("Item existed");
    else console.log("Item didn't exist");
});

```

**Comment by AnimaLupi** [comment]
Thanks a lot for answering so quickly!
I'll go chaining the calls as you suggest then.
