### ISSUE TITLE
Update hard-codes "id" as the primary key

### ISSUE THREAD

**Issue by edelhart-voicebase** [dfahlander/Dexie.js#894]
it looks like the update key presumes your PK is named 'ID'. You should be able to use any key you want not just id.

**Comment by dfahlander** [comment]
No, the primary key can be named anything. In my samples, I often use "id" but that are just examples. If you've found a bug that this is not the case, please provide an example of what does not work as expected.

**Comment by dfahlander** [comment]
Can I close this?
