### ISSUE TITLE
Filtering a collection by Multi-valued indexes

### ISSUE THREAD

**Issue by joehackzero** [dfahlander/Dexie.js#895]
Hi, i'm trying to filter out a collection by Multi-valued indexes. Below is my database structure.
```
        db = new Dexie("Jobs");
        //
        db.version(1).stores({
            RXPersoDirectives: "&directiveID, directiveName, parameters",
            Lens: "++id, ProductCode, ProductName, ProductCategory, ProductNameAndCode, SellingPrice, Index, Material, Chroma, Color, Design, Sided, *ProductNameWords",
            LensAttribute: "++id, ProductCode, DIA, SPHFrom, SPHTo, SPHStep, CYLFrom, CYLTo, CYLStep, ADDFrom, ADDTo, ADDStep",
            ValueAdded: "++id, LensProductCode, ProductCode, ProductName, VAType"
        });
        // Add hooks that will index "ProductName" for full-text search:
        db.Lens.hook("creating", function (primKey, obj, trans) {
            if (typeof obj.ProductName == 'string') obj.ProductNameWords = getAllWords(obj.ProductName);
        });
        function getAllWords(text) {
            var allWordsIncludingDups = text.split(' ');
            var wordSet = allWordsIncludingDups.reduce(function (prev, current) {
                prev[current] = true;
                return prev;
            }, {});
            return Object.keys(wordSet);
        }
```

to fetch data, i use

```var result = db.Lens.where('ProductNameWords').startsWithIgnoreCase(searchText);```

what i would like to do is to filter this result based on ProductNameWords in order to further filtering down the result. for example: 

1. Fetch records where ProductNameWords startsWithIgnoreCase "Nikon"
2. From the 1st result, then filter where ProductNameWords startsWithIgnoreCase "1.65"

for other column filter i dont have any issue as i just do it like this:
```
if (lensTypeFilter.val() !== null && lensTypeFilter.val() !== '') {
            LensType = lensTypeFilter.val();
            result = result.filter(function (lens) {
                return lens.Design === LensType;
            });
        }
```

Maybe i did it the wrong way? any help is really appreciated.

**Comment by dfahlander** [comment]
When you've done the 1st step using the index, you will retrieve an array of items, the same way you got with lensTypeFilter, but now with productName filter. You could use a similar approach to filter further using plain javascript. The ProductNameWords array property will contain all the words from the product name, so you'd just have to do the further filtering something like this:

```js
const filterLower = filterInputString.toLowerCase();
result = result.filter(lens =>
  lens.ProductNameWords.some(word =>
    word.toLowerCase().startsWith(filterLower))
```

*HINT: You'd get improved performance if you'd store the ProductNameWords in lowercase from start, and replace startsWithIgnoreCase() with just startsWith(str.toLowerCase()). This will allow Dexie to utilize IDBIndex.getAll() which is much faster than IDBCursor queries.*

If you'd store the ProductNameWords in lowercase, you also wouldn't have to call .toLowerCase() on each word in the further filtering.

**Comment by joehackzero** [comment]
Thank you @dfahlander  for your advice and suggestion. I can see a great performance improvement now. Sadly. the filter does not seems to work as what i intended. Here are my updated codes:

````
for (var k = 0; k < searchTextArray.length; k++) {
            searchValue = searchTextArray[k].toString();
            searchValueLower = searchValue.toLowerCase()
            if (k == 0) {
                result = db.Lens.where('ProductNameWords').startsWith(searchValueLower);
            } else {
                result = result.filter(function (lens) {
                    return lens.ProductNameWords.some(function (word) {
                        return word.startsWith(searchValueLower);
                    });
                });
            }
        }
````
and below are screenshots on the actual result.

[
![Capture](https://user-images.githubusercontent.com/13724170/64220118-c8f29e00-cefa-11e9-85f0-e8f347295134.PNG)
](url)

it seems to be working correctly only up until the 2nd word. When i added "Air", the 1st item would still be there.

Sorry, i'm not very fluent with javascript as its not my main programming language.

**Comment by dfahlander** [comment]
Good luck with the debugging. I'm sure you'll find the bug.
