### ISSUE TITLE
Updating nested array using table.update

### ISSUE THREAD

**Issue by bwk1224** [dfahlander/Dexie.js#913]
I would like to know if something like below is possible.

```js
db.transaction('rw', db.TableSample, () => {
            let objectToUpdate = 'Data.Component.' + componentIndex + '.Section.' + sectionIndex + '.Card.' + focussedcardIndex + '.' + saveKey + '';

            db.TableSample.update("Template_1", { objectToUpdate : updatedValue });

        }).catch(function (e) {
            console.error(e);
        });
```

Basically I'm trying to update objectToUpdate variable dynamically through JS function, but I've had 0 luck with the above code. Dexie ends up with creating a new object called "objectToUpdate" instead.

Here's what I try to achieve.
db.TableSample.update("Template_1", { "Data.Component.0.Section.2.Card.0.CardType" : updatedValue });

I found a similar question was asked before, but the poster ended up using if/else statements, which is not possible in my case.

Any help would be appreciated.

**Comment by dfahlander** [comment]
Yes,

```js
db.TableSample.update("Template_1", { [objectToUpdate] : updatedValue });
```

**Comment by bwk1224** [comment]
Works great! Thanks!
