### ISSUE TITLE
Is CommonJS module loading supported for addons?

### ISSUE THREAD

**Issue by jmorton** [dfahlander/Dexie.js#92]
Is this the correct way to require addons when using the CommonJS approach?

```
var Dexie = require("dexie");
var DexieObservable = require("dexie/addons/Dexie.Observable/Dexie.Observable");
var DexieSyncable = require("dexie/addons/Dexie.Syncable/Dexie.Syncable");
```
I'm currently using browserify, and get an error when loading the .js it generates.

```Uncaught Error: Cannot find module 'Dexie'```

It looks like it's properly detecting that it should use the CommonJS path, but I think the dependency names aren't being resolved.  Hopefully the fix is obvious, I'm just getting my feet wet with this stuff and I've been trying to figure it out pretty much all day.

Keep up the good work!

**Comment by dfahlander** [comment]
Do you still have the problem in version 1.1? Might be issues with the dots in the file name. I'll spend some time with this later on to see what might be the error.

**Comment by lixiaoyan** [comment]
+1 for same question, directory "addons" was added in ".npmignore" so all addon files are not included in npm package.

**Comment by dfahlander** [comment]
Thanks for the pullrequest!
Need to make a new release in order to publish to npm though. Hopefully tomorrow.
