### ISSUE TITLE
Dexie-export-import in web worker

### ISSUE THREAD

**Issue by KurkoNorbert** [dfahlander/Dexie.js#922]
Hi dfahlander,
I tried to import dexie-export-import script in web worker and got the error:
 "Uncaught ReferenceError: window is not defined"

Here is a reference to **window**:
```javascript
if(typeof process === 'object' && process.env) env = process.env; 
else env = window;
```
I see that you have already checked  if window exists in case of commonjsGlobal declaration:
```javascript
var commonjsGlobal = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};
```
I think this check solves this issue too.

**Comment by dfahlander** [comment]
Hm. Seems this is done in a dependency: clarinet.

I've created a PR in clarinet: https://github.com/dscape/clarinet/pull/65

**Comment by dfahlander** [comment]
PR was merged and I've released a new version of dexie-export-import that has the newer version of clarinet bundled.

```
npm i dexie-export-import@1.0.0-beta.14
```

@KurkoNorbert Please verify it fixes it.

**Comment by KurkoNorbert** [comment]
Hi,
Tested. It is fixed.
Thanks @dfahlander
