### ISSUE TITLE
Dexie 3 rc1: PrematureCommitError only on Firefox for Android 68

### ISSUE THREAD

**Issue by yennor** [dfahlander/Dexie.js#928]
I've got some code in typescript:

```
await this.db.transaction('rw',
          this.db.device,
          this.db.option,
          this.db.deployment,
          this.db.protocol,
          this.db.trial, async () => {
            await this.db.device.clear();
            await this.db.device.bulkAdd(devices);
            await this.db.option.clear();
            await this.db.option.bulkAdd(options);
            await this.db.protocol.clear();
            await this.db.protocol.bulkAdd(protocols);
            await this.db.trial.clear();
            await this.db.trial.bulkAdd(trials);
            await this.db.deployment.clear();
            await this.db.deployment.bulkAdd(deployments);
});
```
It works on all desktop browsers I've tested (firefox, chromium, safari) and also on safari for iphone and chrome for android. BUT not on the actual Firefox for Android 68, there I get a PrematureCommitError error. I really can't see why? I only call dexie async functions which according to https://dexie.org/docs/DexieErrors/Dexie.PrematureCommitError.html is allowed.
Or did I understand something completely wrong?

**Comment by dfahlander** [comment]
Thanks! Could you test your code with dexie@3.0.0-alpha.8 or dexie@2.0.4 to see if the problem is there too, or if it's related to the changes in dexie@3.0.0-beta.1?

**Comment by dfahlander** [comment]
Can I access your project on GitHub or is it private source? I'm looking for a way to reproduce your error. Are your seeing it in a test or in a certain view? Was it easy to reproduce?

If you have any change, could you try to back to the configuration where you see the error and just downgrade dexie to 2.0.4, leaving the other libs as they are - just to verify you see the same error in 2.0.4?

**Comment by yennor** [comment]
I've downstripped the project from everything unnecessary, especially the rest calls ;-).
you can get it here
`git clone git@github.com:yennor/dexietest.git`

To start it up run
```
npm install
npm run serve

```
Then you should be able to connect to it using firefox on android. Connect a debugger console to it, and you should be able to see the error (The browser will only show a white page).
The error is in src/assets/data.ts

I've downgraded to dexie 2.0.4 and can tell you, dexie 3 is not the problem! I'm not even sure anymore if dexie is even the problem at all.
I get a LOOT of error messages but also only in firefox for android.
I haven't got  a single idea what the problem is. 
```
Unhandled promise rejection TypeError: "targetZone is undefined"
    switchToZone dexie.es.js:1284
    zoneLeaveEcho dexie.es.js:1265
    node_modules es.promise.js:110
    node_modules microtask.js:26
host-report-errors.js:6
Unhandled promise rejection TypeError: "currentZone is undefined"
    switchToZone dexie.es.js:1289
    nativeAwaitCompatibleWrap dexie.es.js:1336
    node_modules es.promise.js:110
    node_modules microtask.js:26
host-report-errors.js:6
Unhandled promise rejection TypeError: "currentZone is undefined"
    switchToZone dexie.es.js:1289
    nativeAwaitCompatibleWrap dexie.es.js:1341
    node_modules es.promise.js:110
    node_modules microtask.js:26
host-report-errors.js:6
Unhandled promise rejection TypeError: "currentZone is undefined"
    switchToZone dexie.es.js:1289
    nativeAwaitCompatibleWrap dexie.es.js:1341
    node_modules es.promise.js:110
    node_modules microtask.js:26
host-report-errors.js:6
Object { _e: Error, name: "TransactionInactiveError", message: "Transaction has already completed or failed", inner: null, stack: "" }
Data.ts:403
[Vue warn]: Error in created hook (Promise/async): "TransactionInactiveError: Transaction has already completed or failed"

found in

---> <IndexComponent> at src/views/Index.vue
       <IndexComponent> at src/App.vue
         <Root> vue.runtime.esm.js:619
Object { _e: Error, name: "TransactionInactiveError", message: "Transaction has already completed or failed", inner: null, stack: "" }
vue.runtime.esm.js:1888
Unhandled promise rejection 
Object { _e: Error, name: "TransactionInactiveError", message: "Transaction has already completed or failed", inner: null, stack: "" }
host-report-errors.js:6
    exports host-report-errors.js:6
    dispatchEvent es.promise.js:143
    result es.promise.js:155
    exports perform.js:3
    onUnhandled es.promise.js:152
    <anonymous> task.js:52
    run task.js:25
    listener task.js:36

```

**Comment by dfahlander** [comment]
Thanks a lot! No matter the reason it fails, I think this repro will help me make the dexie code handle situations where the js environment is not what it expects.

**Comment by yennor** [comment]
I've found out what line causes the problem. But I still don't know why????
In the repo in the file "data.ts" in the function cacheAllData()
replace the line
```
 } catch (error) {
      console.error(error);
 }
```
with
`} catch {}`

and it works!

**Comment by yennor** [comment]
argh. Sorry. I was tired. Ignore my last comment. I've tried for a few hours to find out where the problem was, and by removing that console.log obviously I just didn't see the error anymore....

**Comment by yennor** [comment]
Anyway, what I've found out, if it interests you:
If there is only one single write inside the transaction, it works.
If I don't use any transaction at all it also works. Right now I'm using that solution (The way the application is used, that should be alright in 99.9% of the cases). Every other transaction in the code seems to work, even when there are more than two writes inside it.

**Comment by dfahlander** [comment]
Thanks @yennor! I will defenitely have a look at your repo as soon as I can get some time and figure out the problem happening. Are you still seeing it on Firefox for Android 68 only?

**Comment by dfahlander** [comment]
@yennor I was unable to find a way to debug firefox on android. However, could I kindly ask you to yet again verify that this bug was not introduced in Dexie 3.0.0-beta.1? The reason I ask is because that 3.0.0-beta.1 did resolve #722, which included changes in those parts of the code that were being logged in your sample (switchToZone, zoneLeaveEcho etc).
