### ISSUE TITLE
Wich way is right? 

### ISSUE THREAD

**Issue by userbq201** [dfahlander/Dexie.js#929]
I have many features and ech featute has db store with created dexie object. Is it normal? Or bettet use one dexie object with all stores?

**Comment by dfahlander** [comment]
That's really up to you. Unless you need to do an atomic transaction across more than one of them, you are fine with one dexie per store

**Comment by dfahlander** [comment]
However, there have been bugs in prior versions of Firefox triggered when multiple indexeddb databases are opened simultaneously. So for that reason, maybe better to put all in one db.

**Comment by userbq201** [comment]
Ok, if it happen i try it
