### ISSUE TITLE
Searching from multiple indexes with one query [FEATURE]

### ISSUE THREAD

**Issue by cosecantt** [dfahlander/Dexie.js#93]
Hi there David,
I really love your code and style and using on my projects.
I came up with one feature. Is it missing or am I lazy to search indeed did a little search but could not find. I am building a web POS using your script. I have a name, short_name, barcode, sku indexes in my db. I need to search from multiple indexes with one query and get the all unique matches (duplicate is not allowed, in the beginning you can ignore this). Following is an example:
```javascript
db.Products.where('["name", "short_name", "barcode", "sku"]')
  .equalsIgnoreCase(posInput)
  .toArray (function (items) {
      console.log(JSON.stringify(items));
});
```
Any way to do this type of search with the current version?
Thank you very much.

**Comment by dfahlander** [comment]
Yes. First you have to define compound indexes. See Sample below.

```js
db.version(x).stores({
    Products: 'id,[short_name+barcode+sku]'
});

// Query
db.Products.where('[short_name+barcode+sku]').equals(x)

```

**Comment by dfahlander** [comment]
https://github.com/dfahlander/Dexie.js/wiki/Version.stores%28%29

**Comment by cosecantt** [comment]
I used latest dexie version and defined the indexes as follows
```javascript
db.version(1).stores({
   Products: 
        'sku, 
        barcode, 
        short_name, 
        name, 
        product_code, 
        [sku+barcode+short_name+name+product_code]'
});

db.Products
  .where('[sku+barcode+short_name+name+product_code]')
  .equalsIgnoreCase(posInput)
  .toArray (function (items) {
      console.log(JSON.stringify(items));
});
```
always returns [];
Anything I did wrong? Sorry David for this question.
As it said IE does not support compound indexes I ended up doing as follows:

```javascript
db.Products.where('sku')
 .equalsIgnoreCase(posInput)
 .or("barcode")
 .equals(posInput)
 .or("short_name")
 .equalsIgnoreCase(posInput)
 .or("name")
 .equalsIgnoreCase(posInput)
 .or("product_code")
 .equals(posInput)
 .toArray (function (items) {
	console.log(JSON.stringify(items));
});
```
returns the desired value.
Which one is performance efficient?

**Comment by dfahlander** [comment]
Ok, I misunderstood your goal. Thought you wanted to match all values
("and" btwn them). In your case, you could use "or" method as you
suggested. It's quite performant since it executes parallell index
searches.
Den 6 maj 2015 06:56 skrev "cosecantt" <notifications@github.com>:

**Comment by dfahlander** [comment]
It also removes duplicates

**Comment by cosecantt** [comment]
Ok I see. Thank you very much.
