### ISSUE TITLE
How to apply modification in updating hook ?

### ISSUE THREAD

**Issue by userbq201** [dfahlander/Dexie.js#930]
A have hook and i cant apply nested modifications. How do it? Dexie return string like  `'foo.bar'`

**Comment by userbq201** [comment]
i use set method from lodash, is it good idea ?

**Comment by dfahlander** [comment]
It's in the docs: 

For updating-hook, use a return value:

https://dexie.org/docs/Table/Table.hook('updating')#return-value

For creating-hook, modify given object:

https://dexie.org/docs/Table/Table.hook('creating')

**Comment by userbq201** [comment]
no, not it

I want listen changes, not modify

i want to have updated obj if i subscribe to updating hook

**Comment by userbq201** [comment]
this.value in updating hook

**Comment by userbq201** [comment]
and can i cancel update operation in updating hook ?
