### ISSUE TITLE
Search: Nested Property of Array ?

### ISSUE THREAD

**Issue by pbachman** [dfahlander/Dexie.js#933]
Hi

first of all dexie is great. Can I search for nested properties that are of type array?

Example. I have the following model definition:

```
export interface Customer {
  number: string;
  name: string;
  street: string;
  postalcode: string;
  city: string;
  country: string;
  recipient: DeliveryAddress[];
}

export interface DeliveryAddress {
  name: string;
  street: string;
  postalcode: string;
  city: string;
}
```

How can i search for the property recipient.name ? It doesn't work like this:

```
   this.version(1).stores({
      customer: '++number, name, street, city, recipient.name'
    });
```

**Comment by dfahlander** [comment]
@pbachman Did you find an answer to this question?

**Comment by pbachman** [comment]
@dfahlander I think I can solve it with the library [dexie-relationships](https://github.com/ignasbernotas/dexie-relationships) or am i wrong ?

**Comment by dfahlander** [comment]
@pbachman Yes with or without dexie-relationships you can link from one object to another to effectively get a relational model. The addon assists in querying related objects. Another option is described here: https://stackoverflow.com/questions/57154499/search-dexie-table-for-a-key-in-an-array .

**Comment by pbachman** [comment]
@dfahlander ok thanks, but how can i implement a searchmethod only with indexes ? i currently have implemented the method with "filter" to be able to search within a nested children array (recipient):
  ```
 searchCustomers(searchstring: string): Observable<Customer[]> {
    return from(this.table<Customer>('customer')
      .filter(x =>
        x.name.toLowerCase().includes(searchstring.toLowerCase()) ||
        x.street.toLowerCase().includes(searchstring.toLowerCase()) ||
        x.city.toLowerCase().includes(searchstring.toLowerCase()) ||
        x.recipient.some(d => d.number.toString().includes(searchstring) ||
          d.name.toLowerCase().includes(searchstring.toLowerCase()) || d.street.toLowerCase().includes(searchstring.toLowerCase()) ||
          d.postalcode.toLowerCase().startsWith(searchstring.toLowerCase()) || d.city.toLowerCase().includes(searchstring.toLowerCase()))
      .or('customerNr').startsWithAnyOfIgnoreCase(searchstring)
      .or('postalcode').startsWithAnyOfIgnoreCase(searchstring)
      .limit(20)
      .toArray());
  }
```
it works, but it's slow.
