### ISSUE TITLE
Database changes and transaction source

### ISSUE THREAD

**Issue by MacRdy** [dfahlander/Dexie.js#935]
Hi, Im looking for a way to set transaction 'source' prop.

As described here
https://dexie.org/docs/Observable/Dexie.Observable.DatabaseChange

I can set 'source' to ignore some changes, etc.
But I cant find a way how to do it.

Please help.

**Comment by rtibbles** [comment]
You should be able to set it by using a transaction and then inside the transaction you can write:
`Dexie.currentTransaction.source = '<your_id>'`
