### ISSUE TITLE
Import declaration conflict with TypeScript 3.7

### ISSUE THREAD

**Issue by mloffer** [dfahlander/Dexie.js#944]
```
ERROR in ../node_modules/dexie-syncable/api.d.ts:31:9 - error TS2440: Import declaration conflicts with local declaration of 'IDatabaseChange'.
31 import {IDatabaseChange} from 'dexie-observable/api';
```

Seems TypeScript made a potentially (in this case definitely) breaking change in 3.7:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict

**Comment by dfahlander** [comment]
Thanks! If someone would find a solution, PR would be very welcome. Otherwise, I'd try fixing it when there is time.
