### ISSUE TITLE
a lot of imports supported, but what about simple plain JS import ?

### ISSUE THREAD

**Issue by mnts** [dfahlander/Dexie.js#945]
I want this kind of import also to work
import dexie from './node_modules/dexie/dist/dexie.min.js';
 what is the point to support all artificial ways, and not ordinarry JS import?

**Comment by dfahlander** [comment]
The ES module version is at "./node_modules/dexie/dist/dexie.mjs".

**Comment by dfahlander** [comment]
But you have to npm install dexie@^3.0.0-rc.1.
