### ISSUE TITLE
Collection.modify uses incorrect iteration method

### ISSUE THREAD

**Issue by anlumo** [dfahlander/Dexie.js#947]
In the line

https://github.com/dfahlander/Dexie.js/blob/4d44e73c88e828cc6b8521ce93a5adaf9ede7f38/src/classes/collection/collection.ts#L499

for…in is used to iterate over an array, which is not how you're supposed to iterate over object keys in JavaScript.

I'm using a framework (ember.js) that injects extra keys into the Object prototype. Using the correct `Object.getOwnPropertyNames(failures)`, this isn't an issue, since it's not part of the `failures` object itself. However, with the code shown above, it iterates over the index “_super” and inserts it into the totalFailures array, even though there are actually no failures.

**Comment by anlumo** [comment]
![image](https://user-images.githubusercontent.com/644763/69824977-e4c1c380-120d-11ea-8a7f-2a33c33b72d5.png)

here you can see how that looks in Chrome's devtools. Note how failures is empty and pos is `_super`.

**Comment by anlumo** [comment]
Digging deeper, the underlying issue seems to be that `failures` is an array at runtime, but TypeScript is told that it's an object containing number indices here:

https://github.com/dfahlander/Dexie.js/blob/4d44e73c88e828cc6b8521ce93a5adaf9ede7f38/src/public/types/dbcore.d.ts#L36

This causes TypeScript to generate the wrong JavaScript output (it just uses the same code verbatim instead of iterating over the indices instead).

**Comment by dfahlander** [comment]
Thanks! I suppose the immediate fix would be to change the code in collection.ts to do a for-of Object.keys() instead. Also, the failures object is instantiated as an array in dbcore-indexeddb.ts while it really should be an object representing map between numbers and errors.

**Comment by anlumo** [comment]
I have implemented a fix here: https://github.com/anlumo/Dexie.js/tree/issue-947-collection.modify

I don't know whether it's clean, but it works so far.
