### ISSUE TITLE
running Dexie in a chrome DevTools snippet: error

### ISSUE THREAD

**Issue by tomeraz** [dfahlander/Dexie.js#949]
Hi,

Firstly, Dexie is very valuable.The api is superb and I'm using it in production. Awesome work :pray: 

As I haven't found a better way to modify indexedDB DB directly, I'm trying to run Dexie inside a [Chrome DevTools snippet](https://developers.google.com/web/tools/chrome-devtools/javascript/snippets). Here's the snippet:
```
import('https://unpkg.com/dexie@latest/dist/dexie.js').then(m => console.log(m));
```

And here's the error received in the console:
```
dexie.js:17 Uncaught (in promise) TypeError: Cannot set property 'Dexie' of undefined
    at dexie.js:17
    at dexie.js:18
(anonymous) @ dexie.js:17
(anonymous) @ dexie.js:18
dexie.js:18 Uncaught (in promise) TypeError: Cannot set property 'Dexie' of undefined TypeError: Cannot set property 'Dexie' of undefined
    at dexie.js:17
    at dexie.js:18
```

Is there a way to properly import Dexie from CDN and run it in the snippet?

Thanks!

**Comment by dfahlander** [comment]
Try import('https://unpkg.com/dexie@next/dist/dexie.mjs').then(m => console.log(m))
