### ISSUE TITLE
Possible to add multiple records

### ISSUE THREAD

**Issue by philnickel** [dfahlander/Dexie.js#952]
Hey guys, 

i don't unterstand how I can add multiple records. I have the following query

db.stoptime.where({username: 'max.mater', stoptime:undefined}).each(function(update){
// can I add some records here? 
})

This gives me stoptimes which are undefined. How can I add some records inside this loop?

**Comment by dfahlander** [comment]
Try avoid using each() and use toArray() or modify() instead.

```js
async function doit() {
  var stoptimes = await db.stoptime.where({
    username: 'max.mater',
    stoptime: someValidKey // undefined is not a valid key though
  }).toArray();
  // At this point, you have the result and you can add
  await db.stoptime.bulkAdd([{username: "foo", stoptime: Date.now()}, {...}]);
}
```

**Comment by kamedan** [comment]
i prefer using bulkPut than bulkAdd.
