### ISSUE TITLE
db.on('ready', ...) not called if autoOpen: true

### ISSUE THREAD

**Issue by heavyk** [dfahlander/Dexie.js#956]
for dexie@2, the on ready event is fired just fine with autoOpen: true (and also with autoOpen: false + db.open())

however, for dexie@3.0.0-rc.1 the ready event is not fired with autoOpen: true.

the workaround is to set autoOpen: false, then call db.open(), and the event will fire correctly.

---

as a sidenote, dexie is super cool! I'm really liking the new 3.0 db.use() functionality. thanks so much for this library! it's really really awesome

**Comment by heavyk** [comment]
actually, that workaround doesn't seem to work now. I don't know why it stopped working either. it only works some times and I'm trying to isolate where it fails to give a small reproducible case.

I'm trying the db.use you posted in #836 and if I comment that out or the 'populate' event, then it loads up, but not with both.

**Comment by heavyk** [comment]
omg, I feel kind of silly, but in the process I learned a lot about dexie.

so, in the example code in #836, it should read:

```js
            return table.mutate(req).then((res) => {
              const queue = (tx['_myQueue'] = tx['_myQueue'] || [])
              queue.push({req, res})
              return {...res} // this line was missing!
            })
```
everything seems to be working. I'll reopen if there's a problem, but looks good so far :) !

**Comment by dfahlander** [comment]
Thanks @heavyk for correcting the sample in #836. My bad to forget returning the res. I will update #836 accordingly. Do I understand it right, that the issue with 'ready' event not firing was a result of the faulty middleware? So with a corrected middleware or no middleware at all, the ready event works as expected in Dexie@3.0.0-rc.1 ?

**Comment by heavyk** [comment]
correct, if the mutate function does not return, then the ready event will never fire if also the populate event also happens happening.. so...

db.on('populate', ...) + db.use({ ... }) without a return event from the mutate will cause the ready event never to fire.

the reason is, when the populate event is called, any modifications that are made inside the populate event will go through the mutate event, yet because the mutuate does not return the response, it'll wait forever before calling the ready event.

---

I think the solution to this problem is to check to see when calling the mutate function to ensure that something is returned. I couldn't figure out where this was getting lost in dexie when I looked into it yesterday. wherever this is, if the mutate event doesn't return a response, then the original res should be used (eg. `if ((res = this.mutate()) == null) res = originalRes`)

**Comment by dfahlander** [comment]
Looking at the code, it seems as, in the case a middleware does not return a response, res.numFailures will throw with `TypeError: Cannot read property 'numFailures' of undefined`, making the promise reject and the calling flow abort.

I don't think we could (or should) cover up in this scenario in case middleware returns undefined. We don't even have a default `res` to return, we only a `req` (request), which is of a different shape. The middlware stack is the sole source of a response, and the nature of a middleware is that it is free to do whatever it likes. It is expected though to return something that corresponds to the `MutateResponse` interface. To really check each middleware, it would be needed to put an additional sanity-checker middleware in front of each user-registered middleware, checking that the response is truthy and has the required properties numFailures, failures and lastResult. But I would not give that the highest prio right now. However very glad that you took the time to debug this and find the fix! Thanks again!
