### ISSUE TITLE
unexpected data loss

### ISSUE THREAD

**Issue by srijib** [dfahlander/Dexie.js#958]
i am storing data in android chrome using dexie js. I observed that data gets wiped off if the app is not used for some days at a stretch. If i use app regularly all works well. Is there any expiry date for the IndexedDB if not used for sometime ?

**Comment by dfahlander** [comment]
Normally data is not wiped away like that, but the user agent is free to do that when there is low hard disk space on the device. Apps can ask for permission to have their data persisted in these scenarios. This is accomplished using the DOM [StorageManager](https://dexie.org/docs/StorageManager) API.
