### ISSUE TITLE
Typing errors when transpiling to ES modules

### ISSUE THREAD

**Issue by ksnyde** [dfahlander/Dexie.js#963]
I created a library [**Firemodel**](https://firemodel.info/using/dexie) which provides a modeling, mocking and interaction library for Firebase but I've always meant to provide an integration to the **Dexie** API once I found out about it. I finally found the time to do it and early _units_ are passing but when I transpile I target both the **es** and **cjs** module systems. In both cases I'm just using the Typescript `tsc` compiler but when transpiling I get a bunch of typing errors from **Dexie**:

![image](https://user-images.githubusercontent.com/980757/71777224-d031c300-2f51-11ea-809b-410fa5290e08.png)

The `tsconfig.json` is unchanged from what had been working prior to importing **Dexie** (below is `es` tsconfig):

```json
{
  "compilerOptions": {
    "declaration": true,
    "module": "esnext",
    "target": "es2017",
    "lib": ["es2016", "es2017", "esnext.asynciterable", "es2015.reflect"],
    "moduleResolution": "node",
    "sourceMap": true,
    "noImplicitAny": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "outDir": "./dist/esnext",
    "removeComments": false,
    "typeRoots": ["./node_modules/@types"],
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules/**/*"]
}
```

**Comment by ksnyde** [comment]
I know that in most cases you'll want a clear way to reproduce and I don't have a clean way of doing this yet but based on the focus on Typescript in **Dexie** I thought you might have run into something like this before.

**Comment by ksnyde** [comment]
On the surface it would appear that when I import the default export and then use that to define another interface it runs into a situation where downstream symbols in Dexie aren't being exported. Is this possible?

``typescript
import Dexie from "dexie";

export interface IDexiePriorVersion {
  /**
   * The model definitions for the prior version
   */
  models: IDictionary<string>;
  /** If there is a schema change then  */
  upgrade?: (tx: Dexie.Transaction) => Dexie.Collection<any, any>;
}
```

**Comment by ksnyde** [comment]
Just as a simple test I figured I'd see if I could get the symbols via named export.

![image](https://user-images.githubusercontent.com/980757/71777363-b5604e00-2f53-11ea-924c-04c557b9fea6.png)

As you can see, the core `Dexie` export seems to be available as both default and named export but `IDBTransaction` (one of the symbols complained about during transpilation) is not available.

**Comment by dfahlander** [comment]
IDBTransaction etc are part of the standard DOM library. This library needs to be specified in the lib option in tsconfig.

**Comment by ksnyde** [comment]
Yes but considering my library is for both front and backend solutions I'm not sure I want to include the DOM libraries. Is there any way you know of to just import the typings for the DOM libraries?

**Comment by ksnyde** [comment]
I did add "DOM" to the `tsconfig` files and it does transpile now. I will close this and thanks for your help.

**Comment by dfahlander** [comment]
The lib option will only affect typings and will not add anything to the transpiled js.
