### ISSUE TITLE
ProductItem.where('ProductId').anyOf(ProductIdArray).offset(OffsetValue).limit(10).toArray().then(function (ProductItemsRecords)

### ISSUE THREAD

**Issue by zohaib766lumensoft** [dfahlander/Dexie.js#964]
i want sort this in that condition using dexie but when i use sortby or orderby it did not load product
any solution to sort this

**Comment by dfahlander** [comment]
orderBy() is only available on a [Table](https://dexie.org/docs/Table/Table). Once you use where(...).someOperation()... you get a [Collection](https://dexie.org/docs/Collection/Collection) back instead. Collection has sortBy() but sortBy() returns a Promise and is thus a replacement of toArray().

I also refer to: #652 and #797 for some tips on how to sort paged data with other key than the one being queried.

**Comment by zohaib766lumensoft** [comment]
Thank you @dfahlander i slove my Issue by changing toarray() to Sortby()
