### ISSUE TITLE
Could not delete database: ""Internal error opening backing store for indexedDB.deleteDatabase."

### ISSUE THREAD

**Issue by ermandemirel** [dfahlander/Dexie.js#965]
Hi folks,

I encountered this error message in the logs;

            "error": {
                "message": "Internal error opening backing store for indexedDB.deleteDatabase.",
                "name": "UnknownError"
            },

The device is Android 4.4.4. 

Noted Symptoms:

Error message being displayed “ Caution, App data is corrupted and app could not boot. All data will be wiped out in 30 seconds” with a proceed immediately click box.
Upon proceeding “Caution, there was an error during database reset. Please reset the device to factory settings”.
After performing a factory reset we are no longer able to access the SOC Android OS leaving the displays unusable.

**Comment by dfahlander** [comment]
This issue seems not to be related to dexie but rather to a hardware failure or similar. Dexie is a JS library and is not capable of anything else than proxying the IndexedDB API.

**Comment by ermandemirel** [comment]
Oh thanks brother. It seems so.
