### ISSUE TITLE
db.storeName is undefined

### ISSUE THREAD

**Issue by namnguyen2091** [dfahlander/Dexie.js#968]
I create my project by reactjs, in one component (on top level) I init database by call this function:
InitIDB
```
import Dexie from 'dexie';
const db = new Dexie("FrontEnd");

export function InitIDB() {
	db.version(1).stores({
		projects: '++id,row_id,name'
	});
	db.open();
}
```
I see it's appeared in storage. And in other component, I dont call InitIDB function but, ofcourse, I still import:
```
import Dexie from 'dexie';
const db = new Dexie("FrontEnd");
```
but why when I try **console.log(db.projects);**, I got undefined?

**Comment by dfahlander** [comment]
I would advice you to not put db.version() in a function. It's declarative part that should always be there no matter who uses it.

Instead, have a module that exports the initialized db. Also you don't have to call db.open() explicitely. It will open automatically on first use unless you explicitely disable that in the constructor options.

```js
// db.js
import Dexie from 'dexie';
const db = new Dexie("FrontEnd");
db.version(1).stores({
  projects: '++id,row_id,name'
});

export db;

```

Usage
```jsx
import { db } from './db';

function App() {
  const [prefix, setPrefix] = useState('');
  return <div>
    Search projects:
    <input type="text" value={prefix} onChange={ev => setPrefix(ev.target.value)} />
    <ProjectList projectQuery={db.projects.where('name').startsWith(prefix)} />
  </div>;
}

function ProjectList (props) {
  const [projects, setProjects] = useState([]);
  const [error, setError] = useState([]);
  useEffect(()=>{
    props.projectQuery.toArray().then(setProjects, setError);
  }, [props.projectsQuery]);
  return <div>
    {error && <p style={{color: 'red'}}>{''+error}</p>}
    <ul>{projects.map(project => <li key={project.id}>{project.name}</li>)}</ul>
  </div>;
}
```

**Comment by namnguyen2091** [comment]
thanks, I did it. I have also question, I see on your document but why I can not use await keyword?
```
const friendsContainingLetterA = await db.friends
    .filter(friend => /a/i.test(friend.name))
    .toArray();
```
### Can not use keyword 'await' outside an async function

**Comment by dfahlander** [comment]
Javascript currently does not allow top level await. I still use await in samples for it to be used from within an async function. A more covering example of the above would be:

```js
async getFriendsContainingLetterA() {
  const friendsContainingLetterA = await db.friends
    .filter(friend => /a/i.test(friend.name))
    .toArray();
}
getFriendsContainingLetterA().then(friends => {
  console.log(friends);
}).catch(error => {
  console.error(''+error);
});
```
