### ISSUE TITLE
notEqual / noneOf for WhereClause

### ISSUE THREAD

**Issue by YuriSolovyov** [dfahlander/Dexie.js#98]
Otherwise only possible way is to use `collection.and()`.
Not sure if it's possible to negate matches with indexeddb, but I'd be happy to be wrong :)

**Comment by dfahlander** [comment]
For notEqual() you could use where(x). below().or(x).above(). However,  you won't get matches on keys that are null, undefined or other non index-compatible type. Only strings, numbers, dates and Arrays of such.

**Comment by YuriSolovyov** [comment]
...aand `noneOf()` ?

**Comment by dfahlander** [comment]
Would be possible to implement as an algorithm similar to anyOf but the opposite. Still, wont match undefined etc

**Comment by YuriSolovyov** [comment]
I'm totally fine with that.

**Comment by dfahlander** [comment]
Implemented the two methods and added simple unit tests for them. 
Documentation on wiki will follow.

**Comment by YuriSolovyov** [comment]
Cool, thanks a lot.
