### ISSUE TITLE
Transaction in upgrade not typed

### ISSUE THREAD

**Issue by ImmortalDragonm** [dfahlander/Dexie.js#982]
Typescript
Subclass My class from Dexie.
When I want to upgrade my data and use code line this:

```
constructor () {
    this.version(1).stores({friends: "++id,name"});
    this.version(2).stores({friends: "++id,name,shoeSize"});
    this.version(3).stores({friends: "++id,shoeSize,firstName,lastName"}).upgrade(tx => {
        // An upgrade function for version 3 will upgrade data based on version 2.
        return tx.friends.toCollection().modify(friend => {
            // Modify each friend:
            friend.firstName = friend.name.split(' ')[0];
            friend.lastName = friend.name.split(' ')[1];
            delete friend.name;
        });
    });
}
```
I got ts error:
`Property 'friends' does not exist on type 'Transaction'.ts(2339)`
in return tx.friends.toCollection().modify

**Comment by dfahlander** [comment]
Upgrades work on a historical schemas. Your new version of an entity might not match the properties it had historically. Change tx.friends to tx.table("friends"). I now see that there has been error in the docs about this on https://dexie.org/docs/Tutorial/Design#database-versioning. I will update the docs asap.
