### ISSUE TITLE
importDB does not work - TypeError: r.eof is not a function

### ISSUE THREAD

**Issue by mpkelly** [dfahlander/Dexie.js#987]
Hi, thanks for the library which has been nice to work with so far. 

I am trying to use the addon to import a Dexie DB using `importDB`. This DB was exported using `exportDB`. In fact, I have tried to import two databases: one with records and one which is just the default containing only table definitions. I am not using any fancy data types, just numbers and strings. 

Here are the relevant code snippets which are based on the this [page](https://dexie.org/docs/ExportImport/dexie-export-import) and this [Pen](https://codepen.io/dfahlander/pen/RqwoaB/). I have browsed the source for this project and can't figure out what would produce this error. Am I missing a config option or something?

**Export**
```
    const blob  exportDB(db, { prettyJson: true });
    ...
    export const downloadBlob = (blob: Blob, fileName: string) => {
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      document.body.appendChild(link);
      link.style.display = "none";
      link.href = url;
      link.download = fileName;
      link.click();
      window.URL.revokeObjectURL(url);
   };

```

**Import** 
```
     //file is the JSON file produced by exportDB
     const handleImportFile = async (event: ChangeEvent<HTMLInputElement>) => {
      if (event.currentTarget.files) {
         const file = event.currentTarget.files[0];
         db.importDb(file);
       }
   };
   ...
   //Database.importDb()
    await db.delete();
    return importDB(db, file);
```

**Error**

```
index.js:396 Uncaught (in promise) TypeError: r.eof is not a function
    at index.js:396
    at index.js:396
    at Object.next (index.js:396)
    at index.js:396
    at new Promise (<anonymous>)
    at o (index.js:396)
    at N (index.js:396)
    at Module.<anonymous> (index.js:396)
    at index.js:396
    at Object.next (index.js:396)
```

**Version Info:**
**Deployment**: Chrome extension
**Browser**: Chome 80.0.3987.122
**Packages**: 
```
    "dexie": "^2.0.4",
    "dexie-export-import": "^1.0.0-rc.1",
```

**Comment by dfahlander** [comment]
Seems as given file (event.currentTarget.files[0]) might not be a true Blob for some reason.

**Comment by mpkelly** [comment]
Hi there @dfahlander, thanks for your reply. I still want to use this feature but I have went with an all-in-memory solution for the beta release of my [app](https://github.com/mpkelly/Journal), so it's less critical now.

I believe this is a valid Blob as [all Files are Blobs](https://developer.mozilla.org/en-US/docs/Web/API/File):
> A File object is a specific kind of a Blob, and can be used in any context that a Blob can

Unless this doesn't hold for Chrome extensions but I think it does. Note that I am doing doing any processing on the File object whatsoever and the value I get form the HTMLInputElement is being passed to `importDB`. 

I am also working on a Firefox extension so I will try Dexie there and see how it compares once I have time to work on the project again. It would helpful if you could include uniminfied source with your npm package to help debug the issue. 

Cheers
Mike

**Comment by mpkelly** [comment]
This is working for me now. I am using versions:

```JSON
    "dexie": "^3.0.1",
    "dexie-export-import": "^1.0.0-rc.2",
```

like so:

```TypeScript
import * as DexieBackup from "dexie-export-import";

  exportDb: async () => {
    return await DexieBackup.exportDB(db);
  },
  importDb: async (file: File) => {
    await db.delete();
    return DexieBackup.importDB(file);
  },

```
Just importing the library and calling `db.import()` did not work - I got a type error and looking at the Dexie instance it doesn't appear to have been extended as expected. Using the module directly and passing in the Dexie instance does work though and so glad to have a scalable backup solution for the relaunch of my app. 

Great work with Dexie, @dfahlander - thank you!
