### ISSUE TITLE
"TypeError \"then\" is read-only" on a Firefox extension

### ISSUE THREAD

**Issue by pboutin** [dfahlander/Dexie.js#999]
I'm trying to build a browser extension that injects scripts on an existing website, and I need Dexie to store some information. It works well on chrome and opera, but for some reason, I can't get it to work for Firefox.

Here's the error I'm getting:
![image](https://user-images.githubusercontent.com/4255460/77210188-b9bdf100-6ad6-11ea-9a3d-97e2f02787cf.png)

I checked in my vendor.js file and the line that breaks is this one:
https://github.com/dfahlander/Dexie.js/blob/master/src/helpers/promise.js#L782

Is it a known issue ?
It seems related to Promises polyfills, is there a way to disable that (I only target modern browsers).

Thanks in advance for your input ✌️

**Comment by dfahlander** [comment]
Which version of Dexie are you using?

**Comment by pboutin** [comment]
@dfahlander 2.0.4, I also tried the 3.0.0-rc.5

**Comment by dfahlander** [comment]
The promise polyfill being used seems to configure Promise.prototype.then using a readonly flag. Would it be possible to use another promise polyfill, like [this one](https://www.npmjs.com/package/promise-polyfill) or are you bound to using a specific one? If you target firefox browsers in general, you might not need a promise polyfill at all unless it should work with very old versions of firefox.

**Comment by pboutin** [comment]
I thought the polyfill came with Dexie, is there a way to use it without polyfills at all ? I'm only targetting modern browsers

**Comment by dfahlander** [comment]
Dexie patches Promise.prototype.then temporarily, to maintain it's transaction zone across native async/await calls but restores it when outside the zone. So It's not a polyfill. But it seems as you have included another library that has redefined Promise. It seems to be a Promise polyfill of some kind. Try if there is any included library that polyfills Promise. If this is hard to track down, you could insert a script at the very start of your application, before any other library scripts load, that tracks code that replaces window.Promise with something else. For example, use 

```js
(()=>{
  let Promise = window.Promise;
  Object.defineProperty(window, "Promise", {
    get: ()=>Promise,
    set: P => {
      debugger;
      Promise = P;
    }
  });
})();
```

Have devtools open and the breakpoint should reveal the polyfill. If will also break when dexie patches promise, but if you can ignore that and try to detect who the polyfill is. A polyfill you probably do not need.

**Comment by dfahlander** [comment]
Might also be the case that the other library uses Object.defineProperty() to define Promise or Promise.prototype.then. This is for example something that I just learned that Meteor does. The snippet I posted should also make you detect the any further code that tries to redefine window.Promise because this snippet defines it as non-configurable. You might need to enable break-on-exceptions to detect when another piece of code does that.

**Comment by pboutin** [comment]
I tried to pin-point it, but can't find anything. As I said initially, I'm working on a browser extension that gets injected into a website. I think the faulty lib might be on the host site, which I have no control on. I think my next step here is to try to make it work using the native IDB API 😞

**Comment by dfahlander** [comment]
I get it. You might still appreciate the [IDB](https://www.npmjs.com/package/idb) library over raw IDB API. It will take you one step closer to the native IDB API but still be using promises to make it usable. It also does not patch the Promise as it does not use any concept of transaction zones. Transactions are more explicit instead.

**Comment by pboutin** [comment]
Thanks for trying to help, the Dexie API is really fun to work with. I will close the issue since it really is an edge case.
